[ 사다리타기 ] 2단계 - 사다리(생성)
next-step/java-ladder pull request #1027
Opened 2021-08-16 17:29 UTC by YooInKeun

안녕하세요 요한님!
시간 되실 때, 2단계 미션 리뷰 부탁 드립니다~ :bowing_man: 
좋은 하루 되세요! :fire:

2021-08-17 14:50 UTC, bass84 requested changes
인근님 안녕하세요~! 
1단계 넘어간지 얼마 안됐는데 바로 구현해서 올려주셨네요!
만드시느라 고생 많으셨습니다.^^

한 구간은 가로 라인이 만들어지지 않는 경우가 발생하는 것 제외하고는 대부분 소소한 내용으로 피드백 드렸는데요, 제가 드린 질문들이 있으니 한번 고민해보시고 인근님의 생각을 말씀해주시면 좋을 것 같습니다.^^

궁금한 점 있으면 언제든지 문의 주세요!
화이팅입니다! 🔥 🔥 🔥

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/LadderGame.java
> +public class LadderGame {
한 구간은 가로 라인이 만들어지지 않는 경우가 발생합니다. 해당 원인을 찾아서 수정해보시면 좋을 것 같습니다.^^

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/model/Ladder.java
> +        this.lines = generateLines(ladderHeight, playerCount - 1);
-1을 매직넘버로 사용하시기 보다는 의미있는 변수를 만들어보시면 어떨까요?^^ 네이밍 하는 게 쉽지는 않지만요.^^;

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/model/LadderLine.java
> +    private static List<Boolean> generatePoints(int pointCount) {
생성하는 방식은 좋습니다. 다만 코드를 조금 더 간소화 해보시면 좋을 것 같아요.^^

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/model/Players.java
> +public class Players {
일급객체에 걸맞는 기능들을 잘 만들어주셨네요! 👏

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/model/PlayerName.java
> +    private void validateMaxLength(String name) {
만약 `name`이 null 이라면 NPE가 발생할 것입니다. 인근님은 `validateNotEmpty()` 실행 후에 이 메서드를 호출한다는 가정을 하고 만드신 것이지만, 후에 다른 사람이 유지보수를 위해 이 코드를 만지다가 `validateMaxLength()` 메서드를 먼저 호출하는 것으로 변경했다고 해볼게요. 그럴 경우에는 NPE에서 자유로울 순 없겠죠. 메서드 분리가 꼭 좋은 것은 아닐 수 있어요.^^

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/view/InputView.java
> +public class InputView {
이 클래스가 인스턴스 생성이 필요한 클래스일까요? 제 생각을 말씀 드리자면 인스턴스 생성은 필요 없는 클래스라고 생각하는데요, 인근님은 왜 인스턴스를 생성하셨는지 궁금합니다.^^

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/view/ResultView.java
> +public class ResultView {
InputView 클래스와 마찬가지로 이 클래스가 인스턴스로 생성되어야 할 이유가 있으시다면 들어보고 싶습니다.^^

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/view/ResultView.java
> +    public void printResult(List<String> names, List<LadderLine> lines) {
StringBuilder를 사용하는 이유를 들어보고 싶습니다.^^

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/view/ResultView.java
> +            int blankSpaceLength = LADDER_WIDTH - name.length();
blankSpaceLength 값을 for 루프가 도는 횟수만큼 새로 생성해줄 필요는 없는 것 같아요. for 밖에서 선언하는 게 더 좋지 않을까요?^^

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/view/ResultView.java
> +    private String getNameResult(List<String> names) {
get~ 보다는 generate~ 같은 네이밍이 좀 더 어울려 보여요. get~으로 만든 메서드는 getter의 의미로 보는 게 좋습니다. 단순히 어떤 값을 조회하는 용도의 관용어 같은 것이라고 보시면 될 것 같아요.

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/LadderGame.java
> +        inputView.printLadderHeightInputMessage();
이 두개의 inpuview.printNewLine(), inputView.printLadderHeightInputMessage()를 분리해서 호출하는 것보다 하나의 메서드로 만들어서 호출하는 건 어떨까요?

2021-08-17 14:50 UTC, bass84 commented on src/main/java/ladder/LadderGame.java
> +        resultView.printResult(players.getNames(), ladder.getLines());
마찬가지로 resultView.printResultMessage(), resultView.printNewLine(), resultView.printResult() 를 하나의 메서드로 만들어서 호출하는 건 어떨까요?

2021-08-18 09:03 UTC, YooInKeun commented on src/main/java/ladder/model/LadderLine.java
> +    private static List<Boolean> generatePoints(int pointCount) {
감사합니다. Point를 생성하는 부분을 메소드로 분리해서 간소화하는 게 좋을 거 같네요!

2021-08-18 09:20 UTC, YooInKeun commented on src/main/java/ladder/model/PlayerName.java
> +    private void validateMaxLength(String name) {
좋은 지적 감사합니다. 개인적으로 요한님의 코멘트가 충분히 설득력 있다고 생각합니다!
이를 해소하기 위해 유효성 검사 메소드를 general 하게 하나로 만들 수 있을 것 같아요.

이때 마찬가지로 `LadderLine.class` 생성자에 있는 유효성 검사 메소드 역시 2개로 분리되어 있고, 메소드의 순서를 바꿔버리면 이 또한 NPE에서 자유로울 수 없을 거 같은데요. 하지만 이 경우에는 general 하게 하나의 메소드로 묶었을 때 메소드 코드가 긴 편이라 가독성이 조금은 떨어질 것 같다는 생각이 듭니다!

저의 종합적인 생각은 메소드를 분리하는 경우에 대한 장단점이 있어서, 요한님이 코멘트 주신 부분처럼 메소드를 통합했을 때 가독성 저하가 우려되지 않은 상황에서는 general 하게 통합하는 것도 좋을 거 같아요. :+1:

2021-08-18 09:21 UTC, YooInKeun commented on src/main/java/ladder/model/Ladder.java
> +        this.lines = generateLines(ladderHeight, playerCount - 1);
상수 추출 도전해보겠습니다!

2021-08-18 09:31 UTC, YooInKeun commented on src/main/java/ladder/view/InputView.java
> +public class InputView {
인스턴스 생성이 굳이 필요 없을 거 같아요! 
view 관련 클래스에 대해서는 큰 고민 없이 가볍게 진행했는데 생각지 못한 부분을 알려주셔서 감사합니다. 
static 하게 메소드를 변경해보겠습니다.

2021-08-18 09:47 UTC, YooInKeun commented on src/main/java/ladder/view/ResultView.java
> +    public void printResult(List<String> names, List<LadderLine> lines) {
우선 결과를 한 줄씩 출력하는 것보다, 결과에 해당하는 모든 문자열을 모아서 한 번만 출력하는 방법이 코드 상으로 깔끔할 거 같다고 생각했습니다.
그리고 문자열을 이어붙이는 연산이 자주 필요해서 문자열 연산에 효율적인 StringBuilder를 사용했습니다.
혹시 요한님이 생각하시는 문제나 다른 방법이 있을까요?

2021-08-18 09:49 UTC, YooInKeun commented on src/main/java/ladder/view/ResultView.java
> +            int blankSpaceLength = LADDER_WIDTH - name.length();
오 그러네요. 디테일한 피드백 감사합니다 :+1: :+1:

2021-08-18 09:52 UTC, YooInKeun commented on src/main/java/ladder/view/ResultView.java
> +    private String getNameResult(List<String> names) {
getter가 아닌데 get으로 네이밍 한 메소드는 모두 수정하는 게 좋겠네요! 감사합니다.

2021-08-18 10:19 UTC, YooInKeun commented on src/main/java/ladder/LadderGame.java
> +        resultView.printResult(players.getNames(), ladder.getLines());
printResult()로 통합하는 게 좋겠네요!

2021-08-18 11:54 UTC, YooInKeun commented on src/main/java/ladder/LadderGame.java
> +public class LadderGame {
실례지만 요한님께서 말씀하신 경우가 요구사항에도 포함이 되나요? :thinking: 
요구사항에 포함 되지 않더라도 고민해보려고 하는데, 당장 구현 방법이 떠오르지가 조금 슬프네요.. :cry:

2021-08-18 16:51 UTC, bass84 approved these changes
인근님 수고하셨습니다~!

짧은 시간 안에 잘 구현해서 반영해주셨네요. 👍 
이제 3단계 진행해주시면 되겠습니다!
계속 화이팅해요! 🔥 🔥 🔥

2021-08-18 16:51 UTC, bass84 commented on src/main/java/ladder/LadderGame.java
> +public class LadderGame {
요구사항에는 없어요. 그런데 한번 해보시면 좋겠다는 의미에서 권해봤습니다.

2021-08-18 16:51 UTC, bass84 commented on src/main/java/ladder/model/LadderLine.java
> +    private static List<Boolean> generatePoints(int pointCount) {
이 메서드 구현을 좋게 보는 이유중 하나가 각각의 변수에 의미를 잘 부여해주셨다는 점 때문입니다. 덕분에 한줄한줄 구현의 내용을 파악하기가 더 쉬웠습니다. 👍

2021-08-18 16:51 UTC, bass84 commented on src/main/java/ladder/model/LadderLine.java
> +        IntStream.range(SECOND_INDEX, pointCount)
메서드를 분리하는 것으로도 꽤 깔끔한 코드로 보이네요.^^

2021-08-18 16:51 UTC, bass84 commented on src/main/java/ladder/view/InputView.java
> +public class InputView {
잘 구현해주셨습니다.^^
저는 상태값을 가지지 않는 클래스에서는 인스턴스 생성이 필요 없다고 생각하거든요. 대표적으로 Util 클래스가 그렇습니다.(Util이라는 클래스를 만드는 게 좋은지는 번외로 하고요^^) 이 클래스도 그런 클래스라고 보여져요.

2021-08-18 16:51 UTC, bass84 commented on src/main/java/ladder/view/ResultView.java
> +public class ResultView {
제가 이 클래스에서 `StringBuilder` 에 대한 질문을 드렸던 이유는, 예전의 Java 버전에서는 메모리 이슈 때문에 문자열 합치는 로직에서는 String을 안 썼지만 1.5 버전 이후부터는 그게 조금 달라지긴 했어요. 물론 그래도 `StringBuilder` 를 쓰는 게 가장 최적화되기 때문에 좋기는 합니다. 참고하시라고 말씀드려봅니다.ㅎ

2021-08-18 16:51 UTC, merged