Step3
next-step/java-ladder pull request #1068
Opened 2021-08-23 08:55 UTC by superkkj

이번부분도 많이어려워서 오래걸렸습니다 ㅠㅠ 잘부탁드려요

2021-08-23 23:45 UTC, neojjc2 commented
#tag @neojjc2

2021-08-24 00:27 UTC, neojjc2 requested changes
안녕하세요 기준님 😄 

3단계 구현 잘해주셨습니다 💯 
여기저기 많이 고민의 흔적이 보이네요 😭 

소소한 의견 몇 가지 드렸습니다 😄 
한번 확인해주시고 개선 검토 해주시면 감사하겠습니다 

아! 그리고 요구사항도 조금 잘못 구현된 부분이 있어서
의견 드렸습니다 그 부분도 확인해주시면 감사하겠습니다 🙇 

그럼 재 리뷰 요청 기다리고 있겠습니다 🙇

2021-08-24 00:27 UTC, neojjc2 commented on src/main/java/nextstep/ladder/Ladder.java
> +    public int movePoint(int startPoint) {
사다리 게임 규칙 잘 반영해주셨네요 👍 💯

2021-08-24 00:27 UTC, neojjc2 commented on src/main/java/nextstep/ladder/Ladder.java
> +    private Boolean leftCheck(int startPoint) {
단순 `boolean`이라면 굳이 `Boolean`인 `wrapper` 클래스를 사용할 필요는 없어 보입니다 😄 

이 부분도 한번 정리하고 가시면 좋을 것 같습니다
도움 되실만한 내용 공유 드립니다 🙇 
> https://coding-factory.tistory.com/547

2021-08-24 00:27 UTC, neojjc2 commented on src/main/java/nextstep/ladder/LadderGame.java
> +        IntStream.range(NUMBER_ONE, ladders.size())
`stream` 사용은 좋습니다 만 과도한 `stream` 사용은 오히려 코드 가독성도 떨어뜨리고 불필요한 낭비를 줄 수도 있습니다 😄 
이쯤에서 한번 환기가 필요할 것 같습니다 🙇 
도움 되실 만한 내용 공유 드립니다 😄 

* Stream의 foreach 와 for-loop는 다르다
> https://woowacourse.github.io/tecoble/post/2020-05-14-foreach-vs-forloop/

2021-08-24 00:27 UTC, neojjc2 commented on src/main/java/nextstep/ladder/Reward.java
> +    private List rewardList = Arrays.asList(new String[]{FIRST_REWARD, SECOND_REWARD});
엇 이 부분은 요구사항을 다시한번 확인해주셔야 할 것 같습니다 😄 
실행 결과가 정해져 있는게 아니라 사용자로부터 실행 결과도 받은 다음 
사다리 게임을 실행결과를 보는게 요구사항 입니다 😅 
> 실행 결과를 입력하세요. (결과는 쉼표(,)로 구분하세요)
꽝,5000,꽝,3000

이 부분 다시한번 확인해주시면 감사하겠습니다 🙇

2021-08-24 00:27 UTC, neojjc2 commented on src/main/java/nextstep/view/ResultView.java
> +        IntStream.range(NUMBER_ZERO, executeLadderGames.getladders().size())
위에서도 의견 드렸지만 `stream` 보다는 `for-loop`가 좀 더 가독성 개선에 도움을 줄 수 있습니다 😄

2021-08-24 00:27 UTC, neojjc2 commented on src/main/java/nextstep/view/ResultView.java
> +                IntStream.range(NUMBER_ZERO, executeLadderGames.getPlayers().size()).forEach(idx
이 부분에 대해서 좀 더 정리가 필요할 것 같습니다 😄 
많이 고민하신 흔적이 보이네요 😭 

사다리 게임 결과를 담당하는 객체, 그리고 `Ladder`를 가진 일급컬렉션, 
그리고 출력하기 편한 최소정보를 `ResultView`에 전달 되도록 하면 
많이 구조적으로 정리가 될 것 같습니다 😄 
이 부분도 개선검토 해주시면 감사하겠습니다 🙇 

이미 아실 수도 있는데 😅 
도움되실만한 내용들 공유 드립니다 🙇 

* 디미터 법칙
> https://dundung.tistory.com/203

* 일급컬렉션
> https://jojoldu.tistory.com/412

* 도메인 모델 데이터 뷰에 노출하는 방법에 관하여
> https://javacan.tistory.com/entry/methods-about-exporting-domain-object-to-view

2021-08-24 00:27 UTC, neojjc2 commented on src/test/java/nextstep/ladder/LadderGameTest.java
> +    void 사다리게임플레이어시작포인트를벗어나면예외처리를한다() {
한글 `method` 명도 좋은데 `@DisplayName`이라는 어노테이션도 한번 활용해보시는걸 추천 드립니다 😄

2021-08-24 04:18 UTC, superkkj commented on src/test/java/nextstep/ladder/LadderGameTest.java
> +    void 사다리게임플레이어시작포인트를벗어나면예외처리를한다() {
앗.. 소스고치다 또습관이 바로수정하겠습니다 :)

2021-08-24 04:19 UTC, superkkj commented on src/main/java/nextstep/view/ResultView.java
> +        IntStream.range(NUMBER_ZERO, executeLadderGames.getladders().size())
괜히 스트림만고집했나보군요 감사합니다 )

2021-08-24 04:19 UTC, superkkj commented on src/main/java/nextstep/ladder/Reward.java
> +    private List rewardList = Arrays.asList(new String[]{FIRST_REWARD, SECOND_REWARD});
ㅠㅠㅠ 제가 요구사항을잘못봣군요 ㅅ ㅜ정하겠습니다

2021-08-24 04:19 UTC, superkkj commented on src/main/java/nextstep/ladder/LadderGame.java
> +        IntStream.range(NUMBER_ONE, ladders.size())
과도한 stream 사용해서 좀 고민했엇는대 좋은 정보 감사합니다

2021-08-24 04:20 UTC, superkkj commented on src/main/java/nextstep/ladder/Ladder.java
> +    private Boolean leftCheck(int startPoint) {
나름대로 분리하려했는대 과도했나보군요 ㅠㅠ 공유해주신 자료 감사합니다 다시읽고고치겠습니다

2021-08-24 04:20 UTC, superkkj commented on src/main/java/nextstep/ladder/Ladder.java
> +    public int movePoint(int startPoint) {
감사합니다 :)

2021-08-24 16:04 UTC, superkkj commented on src/main/java/nextstep/view/ResultView.java
> +                IntStream.range(NUMBER_ZERO, executeLadderGames.getPlayers().size()).forEach(idx
아는내용이긴한대 적용시키는게 참어렵군요.. 고민하고 좀더 개선해보겠습니다 좋은피드백 너무감사합니다 ^^

2021-08-25 00:14 UTC, neojjc2 approved these changes
안녕하세요 기준님 😄 

요청 사항 반영 잘 해주셨습니다 👍 
현재 구조에서 최선을 다 해주신 것 같아요 😭 
정말 수고 많으셨습니다 🙇 

마지막 단계는 
기능 요구사항은 동일하지만 추가로 제공되는 객체 설계 힌트를 참고해서
재 구현 해보는 미션 입니다 😄 

기준님이 잡으신 구조와 비교해 가시면서 진행해보시면
아마 많은 부분 정리가 되실 것 같습니다 😄 

조금만 더 힘내 주세요 🔥 🔋

2021-08-25 00:14 UTC, neojjc2 commented on src/main/java/nextstep/ladder/LadderGame.java
> +        for (int index = 0; index < players.size(); index++) {
이런 부분들은 `Players`라는 일급컬렉션이 생성 되고 그 객체로 위임 되면 더 좋을 것 같습니다 😄

2021-08-25 00:14 UTC, neojjc2 commented on src/main/java/nextstep/ladder/Reward.java
> +    private void checkVaild(String[] rewards, int playerCount) {
검증 좋습니다 💯 👍

2021-08-25 00:14 UTC, merged