🚀 3단계 - 사다리(게임 실행)
next-step/java-ladder pull request #1121
Opened 2021-08-31 02:35 UTC by hae-gun

미션 시작

2021-09-06 01:56 UTC, hae-gun commented on src/main/java/nextstep/ladder/Ladder.java
>      }
해당 메서드를 스트림 처리하고싶은데 아이디어가 나오질 않네요...
조언 부탁드릴수 있을까요 ㅎㅎ

2021-09-06 01:57 UTC, hae-gun commented on src/main/java/nextstep/ladder/Ladder.java
>      }
해당 메서드를 스트림 처리하고싶은데 아이디어가 나오질 않네요...
조언 부탁드릴수 있을까요 ㅎㅎ

2021-09-07 00:47 UTC, JunilHwang requested changes
안녕하세요 해근님! 질문 주신 내용에 대해 답변 드렸습니다. 이 외에도 if/else를 사용한 부분이나 while/if를 사용한 부분이 있는데 전부 개선해주세요!
멤버변수도 최대 2개 이하로 유지할 수 있도록 해주세요 ㅎㅎ
즉, 객체를 작은 단위로 유지해야한답니다!

2021-09-07 00:47 UTC, JunilHwang commented on src/main/java/nextstep/ladder/Ladder.java
> +//        }
reduce를 사용해보면 어떨까 싶어요!
![image](https://user-images.githubusercontent.com/18749057/132268587-3b05e546-6772-4903-a97d-c370b72f8213.png)
제가 미션 수행할 땐 이런 식으로 작성했었습니다 ㅎㅎ

2021-09-07 00:47 UTC, JunilHwang commented on src/main/java/nextstep/ladder/Ladder.java
> +    private List<Result> results;
멤버변수는 최대 2개로 유지해주세요!
그러기 위해선 Ladder의 역할이 아닌 것들은 분리할 필요가 있겠죠?

2021-09-07 00:47 UTC, JunilHwang commented on src/main/java/nextstep/ladder/Line.java
> +       }
else, else if 등은 사용하지 않도록 해주세요!
다른 영역에서도 동일합니다.

2021-09-07 00:47 UTC, JunilHwang commented on src/main/java/nextstep/ladder/view/LadderApp.java
> +        }
while/if가 중첩된 상태네요. 이 부분도 개선해주세요!

2021-09-10 07:26 UTC, hae-gun commented
로직 수정이 어렵다 생각하여 그냥 처음부터 다시 만들었습니다... 
1184fb0부터 새로 만든 코드입니다.

2021-09-11 01:22 UTC, JunilHwang requested changes
안녕하세요 해근님! 아예 처음부터 다시 만들어주셨네요 😭
아직 개선할 부분이 많이 있는 것 같아요. 피드백 확인 후 다시 리뷰 요청 부탁드려요!

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/App.java
> +    }
지금 main method 하나가 하는 일이 무척 많은 것 같아요!
메소드를 분할해서 관리해주면 어떨까요?

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/App.java
> +        }
사용성을 생각해서 이렇게 만들어주신 것 같아요 ㅋㅋ
다만 이렇게 main 내부에서 반복을 하기 보단 차라리 메소드 단위로 분리해주면 좋지 않을까 싶습니다.

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/ladder/Ladder.java
> +
Stream 관련 미션인 만큼 이 부분은 stream으로 표현해주면 어까요?

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/ladder/MakeRealLine.java
> +    }
전략 객체가 아예 List<Boolean>을 반환하고 있네요. boolean 한 개만 반환할 수 있도록 구성해주면 어떨까요?

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/ladder/MakeRealLine.java
> +        }
무엇보다 이렇게 for/if가 중첩되지 않도록 신경써주세요!

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/player/Direction.java
> +    }
개행이 필요할 것 같아요!

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/player/Player.java
> +    }
`5`는 상수로 표현해주면 어떨까요?
그리고 CustomException을 만들어서 관리해주면 더 좋을 것 같아요!

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/player/Players.java
> +        return group;
forEach로 add를 하기 보단 아예 map을 써서 바로 반환 할 수 있는 코드로 구성해주면 어떨까요?

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/player/Players.java
> +    }
여기도 개행이 필요할 것 같아요!

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/player/Players.java
> +    private List<Player> makeGroup(String[] names) {
메소드 순서도 코드 흐름에 맞게 재구성 해주면 어떨까요?
```suggestion
    private Players(List<Player> players) {
        this.players = players;
    }

    public static Players of(List<Player> players)) {
        return new Players(players);
    }

    public static Players of(String s) {
        return of(makeGroup(s.split(",")));
    }

    private List<Player> makeGroup(String[] names) {
```
그리고 makeGroup도 아예 of로 표현해주면 더 좋지 않을까 싶네요 ㅎㅎ

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/player/Players.java
> +    }
this는 생략해도 좋을 것 같아요!

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/player/Players.java
> +                });
```suggestion
        directions .forEach(dir -> players.get(index.getAndIncrement()).move(dir));
```
List는 바로 forEach를 사용해줘도 된답니다!

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/point/LadderPoint.java
> +        }
```suggestion
        if(left() != Point.INVALID_POINT && ladderLine.get(left().index())){
            return Direction.LEFT;
        }
        if(right() != Point.INVALID_POINT && ladderLine.get(right().index())){
            return Direction.RIGHT;
        }
```
else도 사용하지 않도록 해주세요!

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/point/Point.java
> +    private final int MIN_INDEX = 0;
상수가 아니기 때문에 `camelCase`로 표현해주면 어떨까요?

2021-09-11 01:22 UTC, JunilHwang commented on src/main/java/nextstep/ladder2/point/Point.java
> +    }
여기도 this는 생략해도 무방할 것 같습니다.

2022-04-04 06:09 UTC, closed without merging