Step2 사다리 생성
next-step/java-ladder pull request #1122
Opened 2021-08-31 12:24 UTC by yongsoo-kim

안녕하세요 유라님!
저번에 알려주신 팁을 바탕으로 사다리타기 생성을 구현해보았습니다.
시간이 너무 오래걸렸고(1주일정도)그리고 너무 만족스럽지 못했습니다. 이유는 다음과 같습니다.

1. 사다리생성을 하고난뒤, 사다리타기게임을 할수 있는 이미지가 현 코드에서 전혀 떠오르지 않습니다. 단순히 true일때는 가로라인이 존재하고, false일때는 가로라인이 없는 로직뿐이기에, 정말 게임이 이코드를 베이스로 플레이가능할까를 떠올리면서 몇번이나 수정헀으나, 이이상 시간을 끄는것은 좋지 않을것 같았습니다.
2. 이전단계에서 활용한 함수형 프로그래밍(Predicate등등)을 별로 활용하지 못하고 있는 느낌입니다.
3. 사다리생성의 로직이 마음에 들지않습니다. 랜덤으로 생성하도록 구현했지만, 이게 옳았을지...

좋은 어드바이스 주시면 대단히 감사하겠습니다!

2021-09-01 05:02 UTC, dbeod2 requested changes
안녕하세요! 용수님

사다리 생성 미션 잘 진행해주셨습니다.
고민을 많이 하신 부분들이 소스에서 많이 보입니다 🙏
너무 고생많으셨어요! 

몇가지 코멘트 남긴 부분이 있는데 확인해주시고 리뷰 재요청주세요! 
궁금하신점이나 의견나누고싶으신 부분있으시면 DM꼭 남겨주세요 
최대한 빠르게 답변해보는거로 하겠습니다 🙇🏻‍♀️

2021-09-01 05:02 UTC, dbeod2 commented on src/main/java/nextstep/ladder/domain/LadderRow.java
> +        addLastColumn();
라인 생성 잘해주신 것 같습니다 🙏

2021-09-01 21:28 UTC, yongsoo-kim commented on src/main/java/nextstep/ladder/README.md
> +## TODO
답변감사합니다. 예를 들면 어떤 이름이 명확할까요?
2중 배열을 의식해 이름을 지어봤는데, rows와 columns가 수학적으로 맞고, 명확한 이름인것 같습니다.

혹시 생각하시는 좋은 이름이 있으신가요?

https://www.google.com/url?sa=i&url=https%3A%2F%2Fblog.finxter.com%2Fhow-to-calculate-simple-average-of-numpy-array%2F&psig=AOvVaw1uZ9Ki3xgT95wm4ziRkFoN&ust=1630617976758000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCKiHi73b3vICFQAAAAAdAAAAABAD

2021-09-02 13:10 UTC, yongsoo-kim commented on src/main/java/nextstep/ladder/LadderGameConsole.java
> +        final LadderGameSettings settings = LadderGameSettings.of(ladderSize, new RandomDrawLineStrategy());
답변 감사합니다.
다만, 랜덤코드에 대한 테스트를 할수 있다는것이 어떤 의미인가요?
말그대로 랜덤이라, 테스트를 작성해도 그 값이 무작위로 나올것 같은데요. 이런경우 단위테스트가 가능한가요?

2021-09-02 13:11 UTC, yongsoo-kim commented on src/main/java/nextstep/ladder/domain/Player.java
> +                String.format("플레이어 이름이 최대 길이를 초과했습니다. [최대길이: %d자] [입력한 이름: %s]", MAX_NAME_LENGTH, name));
답변 감사드립니다.  이렇게 수정했습니다.

1. 입력후 잘못된 점이 있으면 바로 예외를 던지도록 수정.
2. 최소 2명이상이 사다리 게임을 할수 있도록 수정.

2021-09-02 13:11 UTC, yongsoo-kim commented on src/main/java/nextstep/ladder/domain/LadderRow.java
> +        }
알려주셔서 감사합니다. 수정했습니다.

2021-09-02 13:15 UTC, yongsoo-kim commented on src/main/java/nextstep/ladder/domain/LadderRow.java
> +        addNoVerticalLineColumn();
답변감사합니다. 확실히 과한것 같기는한데... 이렇게 하지 않으면 마지막 세로줄에서 뭘하는지 알기 어려울것 같아서 이렇게 해보았습니다.  지금으로서는 최선이라고 생각해서 이렇게 했는데...좋은 방법이 있을까요?

2021-09-02 13:20 UTC, yongsoo-kim commented on src/main/java/nextstep/ladder/domain/LadderRow.java
> +    private int getMiddleSize(LadderGameSettings settings) {
마지막 라인때문이 아닙니다. 이미 첫번쨰 플레이어의 라인이 19번째 줄에서 정해졌기 때문에, 중간줄수는 총 플레이어 수에서  첫번째 플레이어와 마지막 플레이어의 수를 합한 2를 빼야만 정확하게 나오기 때문입니다.

2021-09-02 13:23 UTC, yongsoo-kim commented on src/main/java/nextstep/ladder/domain/LadderRow.java
> +        addLastColumn();
답변 감사합니다!
다만 저는 정말 이번 미션에대해 감이 오질 않습니다. 많은 지도 부탁드립니다.

2021-09-03 00:54 UTC, dbeod2 commented on src/main/java/nextstep/ladder/LadderGameConsole.java
> +        final LadderGameSettings settings = LadderGameSettings.of(ladderSize, new RandomDrawLineStrategy());
랜덤코드의 테스트는 자유지만
저 같은 경우는 random에 대해서 테스트 코드를 작성했던 경험이 있었어서 말씀드렸구요! ㅎㅎ 
외부에서 주입받는 경우 테스트가 가능합니다

2021-09-03 00:57 UTC, dbeod2 commented on src/main/java/nextstep/ladder/README.md
> +## TODO
아하 그래서 네이밍을 columns, rows였군요 ㅎㅎ
2중 배열을 의식해서 이름을 짤 필요가 없다고 생각이 드는데요!

용수님은 구현해주셨어서 해당이름이 와닿을 수 있지만 다른사람들이 만약봤을때 한눈에 보기엔 조금 헷갈릴 수 있는 부분 같아요! 
LadderRow는 Ladder 라는 이름도 사용해도 될 것 같구요 보니까 LadderRow에서는 LadderColumns를 리스트로 감싸주고 계신데 그부분은 Ladders라는 이름도 괜찮을 것 같습니다.

2021-09-03 00:58 UTC, dbeod2 commented on src/main/java/nextstep/ladder/domain/LadderRow.java
> +        addNoVerticalLineColumn();
메서드를 그냥 감싸지 않고 사용해주셔도 될 것  같다고 판단이 듭니다!

2021-09-03 05:29 UTC, dbeod2 approved these changes
안녕하세요 용수님! 

사다리 2단계 미션 수행해주신다고 고생하셨습니다.
피드백 잘 반영해주셔서 일단 2단계 미션은 머지하겠습니다.

추가로 아침에 DM으로 설명 드린 부분이랑 네이밍 수정까지 다음미션에서 같이 진행해주셔도 될 것 같아요! 
궁금하신점 생기시면 DM주세요! 

다음미션을 진행해주세요!

2021-09-03 05:29 UTC, merged