step3 - 사다리(게임 실행)
next-step/java-ladder pull request #1129
Opened 2021-09-01 07:05 UTC by jaeyoungjang2

안녕하세요 리뷰어님!

이번 스텝에서는 사다리 타기 게임 로직을 구현하였습니다.
최대한 작게 나눠서 구현하려고 노력하였습니다!

부족하지만 이번에도 잘 부탁드립니다!
감사합니다!

2021-09-02 08:49 UTC, bass84 requested changes
재영님 안녕하세요!!

피드백 내용들이 조금 많긴 합니다.
고민해야 할 부분들이 좀 있으실 거예요.
한번 고민 해보시고 반영해주시길 부탁드립니다^^
화이팅이에요!! 🔥 🔥 🔥

2021-09-02 08:49 UTC, bass84 commented on src/main/java/step2/domain/LadderGameManager.java
> +public class LadderGameManager {
이 클래스는 게임 결과을 실행시켜 결과를 만드는 클래스인데 결과에 대한 값까지 같이 가지고 있네요. 이 두 개는 분리시키는 게 맞지 않을까 싶어요. 특히 이 클래스에서 ladderGameColumns는 약간 요주의 인물같은 느낌이에요.^^ 계속 참조하는 변수가 바뀌고, 참조하는 변수(List 타입) 안에 있는 원소들도 계속 바뀌는데 결국 하는 것은 결과의 마지막 값만 들고 있거든요.

2021-09-02 08:49 UTC, bass84 commented on src/main/java/step2/domain/LadderGameManager.java
> +    public List<LadderGameColumn> getLadderGames() {
getLadderGames의 의미를 해석하면 `사다리게임들을 가져온다`인데 처음 이 코드를 본 사람이 이 의미를 파악하기 매우 어려워 보입니다.

2021-09-02 08:49 UTC, bass84 commented on src/main/java/step2/domain/LadderGameManager.java
> +    public void runGame(int value, Ladder ladder) {
이것은 public 메서드이기 때문에 외부의 다른 클라이언트에게 공개되는 메서드인데 클라이언트가 이 스펙을 봤을 때 value의 의미를 알 수 있을까요?

2021-09-02 08:49 UTC, bass84 commented on src/main/java/step2/domain/LadderGameManager.java
> +            List<LadderGameColumn> collect = ladderGameColumns.stream()
collect 같은 것은 의미 없는 네이밍 같아요. 쉽지는 않지만 고민해서 만들어주시면 좋을 것 같습니다.

2021-09-02 08:49 UTC, bass84 commented on src/main/java/step2/domain/LadderGameManager.java
> +            ladderGameColumns = collect;
루프 돌 때마다 ladderGameColumns가 collect를 참조하도록 할 이유가 있을까요? 지금 코드 봐서는 마지막에 한번만 하면 될 것 같아서요.

2021-09-02 08:49 UTC, bass84 commented on src/main/java/step2/domain/LadderGameManager.java
> +    private LadderGameColumn moveStrategy(int index, Line line, LadderGameColumn ladderGameColumn) {
1. 여기에 있는 if 내용들은 저렇게 있으면 무엇 하는지 추측하기가 쉽지 않습니다. 대부분 경우 내 코드 조차도 나중에 봤을 때 왜 저렇게 했는지 해석하기 어려울 때가 많습니다. 특히 이런 경우에는 더욱 그래요. 그래서 유지보수에 있어서 매우 어렵게 되죠. 최소한 if의 내용들을 각각의 메서드로 분리만 하더라도 어떤 걸 하는지 이해하기 쉬울 거예요.
2. 여기 역시 메서드명을 봐서는 무엇을 하는 것인지 이해하기가 어렵습니다.
3. 이 메서드를 호출할 때마다 LadderGameColumn가 새로 생성되는데 낭비인 것 같습니다. 위의 runGame에서 루프로 돌며 결국 가장 마지막에 호출되어 생성되는 LadderGameColumn 인스턴스만 사용되는데 이렇게 할 이유가 있을까요? 지금이야 어플리케이션의 크기가 작기 때문에 아무리 생성해도 메모리 이슈가 거의 없겠지만 실제 어플리케이션에서 이렇게 만들 경우 꽤 큰 메모리 낭비를 유발할 것 같습니다.

2021-09-02 08:49 UTC, bass84 commented on src/main/java/step2/domain/LadderGameManager.java
> +    public void calResult(Result results) {
1. cal의 의미는 calculate인가요? 네이밍을 줄여서 하는 것은 지양해주세요.
2. 여기에서도 결국 ladderGameColumns 안에 참조 값들이 또 바뀌네요.

2021-09-02 08:49 UTC, bass84 commented on src/main/java/step2/domain/Result.java
> +    private static final String delimiter = ",";
private static final로 만들어진 인스턴스의 변수명은 `대문자 + "_"`가 컨벤션이에요.

2021-09-02 13:24 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameManager.java
> +            ladderGameColumns = collect;
마지막에 한번만 하면 된다는 부분을 이해하지 못하였습니다.
```
public void runGame(int height, Ladder ladder) {
    for (int i = 0; i < height; i++) {
        Line line = ladder.getLines().get(i);
        ladderGameColumns = runGameByFloor(line);
    }
}

private List<LadderGameColumn> runGameByFloor(Line line) {
    return ladderGameColumns.stream()
            .map(ladderGameColumn -> gameByHeight(line, ladderGameColumn))
            .collect(Collectors.toList());
}
```
위와 같이 메서드를 분리하였습니다.
한결 보기는 좋아진 것 같지만, 리뷰어님의 의도를 반영한 건 아닌것 같습니다ㅜㅜ.

2021-09-02 13:26 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameManager.java
> +            List<LadderGameColumn> collect = ladderGameColumns.stream()
무의미한 변수였던 collect를 제거하였습니다.
```
public void runGame(int height, Ladder ladder) {
    for (int i = 0; i < height; i++) {
        Line line = ladder.getLines().get(i);
        ladderGameColumns = runGameByFloor(line);
    }
}

private List<LadderGameColumn> runGameByFloor(Line line) {
    return ladderGameColumns.stream()
            .map(ladderGameColumn -> gameByHeight(line, ladderGameColumn))
            .collect(Collectors.toList());
}
```

2021-09-02 13:37 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/Result.java
> +    private static final String delimiter = ",";
ㅜㅜ 죄송합니다!! 수정하였습니다!! 
알고 있었는데 또 습관이 그대로 나와버렸네요.
항상 생각하면서 코드를 작성하도록 하겠습니다!

2021-09-02 14:16 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameManager.java
> +    private LadderGameColumn gameByHeight(Line line, LadderGameColumn ladderGameColumn) {
의미없는 메서드 였던 moveStrategy를 제거하였습니다

2021-09-02 14:16 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameManager.java
> +        return moveStrategy(ladderGameColumn.getPosition(), line, ladderGameColumn);
moveStrategy를 제거하였습니다.

2021-09-02 14:42 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/Result.java
> +    private final List<String> strings;
결과 항목이라는 의미로 strings -> items 로 변경하였습니다!

2021-09-02 14:43 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameManager.java
> +    public void calResult(Result results) {
넵 calculate 였습니다. 
사다리 타기 게임이 도착지점에 도달 하였을 때 결과값을 적어주는 기능을 담당하고 있습니다.
이것도 동일하게 불변객체 사용을 위함이었습니다.

2021-09-03 02:58 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameManager.java
> +public class LadderGameManager {
LadderGameColumns를 클래스로 분리를 해보았습니다!

2021-09-03 03:00 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameManager.java
> +    public List<LadderGameColumn> getLadderGames() {
getLadderResults 로 메서드명 변경을 했는데, 조금은 명확해 졌을까요??

2021-09-03 03:03 UTC, jaeyoungjang2 commented
불변 객체를 사용하는 것을 시도하였는데,
이번에는 다시 객체의 내용을 바꾸는 방법으로 수정하였습니다.

한가지 걱정되는 부분은 
LadderGameColumns 클래스 -> addResultInToLadderGameColumns 메서드에서
ladderGameColumn.setResult 메서드를 사용하고 있는데, 
이것이 적절한 방법인지 
아니면 시작값과 결과값을 연결해주는 map type을 새로 만들어서 사용하는 것이 더 적절한 방법인지 고민이 됩니다.

2021-09-03 03:04 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameManager.java
> +    public void runGame(int value, Ladder ladder) {
value -> height 로 변경하였습니다.

2021-09-04 04:29 UTC, bass84 requested changes
재형님 구현하시느라 수고하셨습니다!
어려운 내용들을 요청드렸는데 잘 수정해주셨어요!! 👍 
한번 생각해보셨으면 하는 걸 피드백 드렸어요.
고민해보시고 반영해주시면 좋을 것 같습니다!!
완료되시면 다시 PR주세요!

2021-09-04 04:29 UTC, bass84 commented on src/main/java/step2/domain/LadderGameColumns.java
> +    }
이 부분 설명이 짧아서 이해하기 어려우셨던 것 같아요.
runLadder 메서드 구현 내용을 보면 루프를 돌며 ladderGameColumns의 참조를 바꿔주고 있어요.
그럼 height가 3번이면 3번 참조를 바꿔주고 5번이면 5번 참조를 바꿔주게 됩니다.
그런데 실제로 필요한 ladderGameColumns 값은 루프에서 마지막으로 참조해주는 참조값이 되어요.
그렇다면 이렇게 구현할 필요가 있을까 의문이 든다는 것이었습니다.
설명이 되었을까요??^^

2021-09-04 04:29 UTC, bass84 commented on src/main/java/step2/domain/LadderGameColumns.java
> +        // 현재 포지션에서 왼쪽에 사다리가 존재하면서, 연결 라인이 있을 때, 왼쪽으로 위치 이동
필요할 땐 이렇게 주석을 남기는 것이 좋습니다! 그런데 이 if의 내용을 따로 메서드로 분리하면 더 좋겠다는 게 저의 의견이었습니다.^^ 이거 메서드명 만드는 게 쉽진 않지만 한번 해보시길 바라요!

2021-09-04 04:29 UTC, bass84 commented on src/main/java/step2/view/ResultView.java
> +    public static void printResultOfTarget(String target, List<LadderGameColumn> ladderGameColumns) {
오 좋습니다!! 잘 분리해주셨네요!! 👍

2021-09-06 08:25 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameColumns.java
> +        // 현재 포지션에서 왼쪽에 사다리가 존재하면서, 연결 라인이 있을 때, 왼쪽으로 위치 이동
if 문을 메서드로 분리하였습니다.
성능상에는 차이가 없지만 메서드명을 통해 무엇을 위한 if 문인지 의미를 더 명확하기 위함이라고 판단해도 될까요??

인터페이스로 분리해서 기능을 구현하는 것은 어떨까요?
인터페이스로 분리하게 되면 3개의 인자를 받는 형태로 만들어 지던데,
이럴떄는 인터페이스로 구현하는 것 보다는 메서드로 분리하는 것이 더 옳은 판단일까요??

인터페이스 분리해서 구현하느냐, 메서드로 분리해서 구현하느냐
둘은 매개변수가 얼마나 들어가는지를 기준으로 판단하면 될까요??

2021-09-06 08:26 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameColumns.java
> +    }
넵 확인하였습니다.
수정 완료하였습니다!

2021-09-07 06:57 UTC, bass84 requested changes
재영님 반영하시느라 수고 많으셨습니다!
대부분 잘 반영해주셨는데 몇몇 부분 조금 더 수정이 되었으면 하는 부분들이 있어서 피드백을 드렸습니다.
확인해주시고 다시 한번 PR 주세요!
화이팅입니다!!

2021-09-07 06:57 UTC, bass84 commented on src/main/java/step2/domain/LadderGameColumn.java
> +    private String result;
Result에서 결과값을 가지고 있는데 여기에서도 가지고 있을 필요가 있을까요? 더군다나 이것 때문에 setter가 추가되기도 하구요.

2021-09-07 06:57 UTC, bass84 commented on src/main/java/step2/domain/LadderGameColumns.java
> +        // 현재 포지션에서 왼쪽에 사다리가 존재하면서, 연결 라인이 있을 때, 왼쪽으로 위치 이동
`성능상에는 차이가 없지만 메서드명을 통해 무엇을 위한 if 문인지 의미를 더 명확하기 위함이라고 판단해도 될까요??`
-> 맞습니다. 추후 유지보수를 위해서 그렇게 하는 것이 좋습니다.

`인터페이스로 분리해서 기능을 구현하는 것은 어떨까요?`
이런 것이야 말로 질문해주신 것처럼 인터페이스로 구현하기 가장 적합한 부분이죠.^^

`인터페이스 분리해서 구현하느냐, 메서드로 분리해서 구현하느냐 둘은 매개변수가 얼마나 들어가는지를 기준으로 판단하면 될까요??`
-> 매개변수가 얼마나 들어가는지 여부는 중요하지 않습니다. 만약 매개변수 수가 많아진다면 매개변수들을 모아서 하나의 Object로 구성하면 되니까요. 인터페이스 구현 여부는 추상화를 먼저 고민해봐야 할 것 같습니다. 어떤 행위가 하나의 공통성을 가지는지를 판단하시면 됩니다. 예를 들어, `축구게임을 하다, 야구게임을 하다` 두 가지의 행위가 있을 때 이 행위는 `스포츠 게임을 한다`는 공통성을 가집니다. 그럼 이 경우에는 `게임하다`라는 행위를 인터페이스화 해서 실제 구현은 두 가지를 만드는 것이죠.

2021-09-07 06:57 UTC, bass84 commented on src/main/java/step2/domain/LadderGameColumns.java
> +    public void calculateResult(Result results) {
1. 이 부분은 collect()를 수행하면서 새로운 리스트를 생성하는데 그럴 필요는 없어 보여요. ladderGameColumn가 참조변수이기 때문에 addResultInToLadderGameColumns 메서드를 통해 수행된 내용은 그대로 저장이 되니까요.
2. 타입은 Result인데 변수명은 results네요. 아래 메서드에서 그렇구요.

2021-09-07 06:57 UTC, bass84 commented on src/main/java/step2/domain/LadderGameColumns.java
> +        String result = results.getItems().get(position);
여기는 results.getResultByPosition() 같은 방식으로 만들면 더 좋겠네요.
디미터법칙 또는 데메테르 법칙이라는 것이 있습니다. 한번 검색해보시고 참고해보시면 좋을 것 같습니다.

2021-09-08 07:41 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameColumns.java
> +        String result = results.getItems().get(position);
다른 객체가 어떠한 자료를 갖고 있는지 속사정을 몰라야 한다는 것
포비님이 강조하신 "객체에게 메세지를 보내라" 라는 것과 일치하는 것이군요.

아.. 많이 들었는데 구현에만 집중하다 보니 이런일이 발생해 버렸네요ㅜㅜ
수정 하였습니다.

2021-09-08 07:43 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameColumns.java
> +    public void calculateResult(Result results) {
```
이 부분 설명이 짧아서 이해하기 어려우셨던 것 같아요.
runLadder 메서드 구현 내용을 보면 루프를 돌며 ladderGameColumns의 참조를 바꿔주고 있어요.
그럼 height가 3번이면 3번 참조를 바꿔주고 5번이면 5번 참조를 바꿔주게 됩니다.
그런데 실제로 필요한 ladderGameColumns 값은 루프에서 마지막으로 참조해주는 참조값이 되어요.
그렇다면 이렇게 구현할 필요가 있을까 의문이 든다는 것이었습니다.
설명이 되었을까요??^^
```
위 피드백을 구현하면서 이번에 주신 1번 피드백에 대한 내용을 이해하였는데,
해당 코드는 수정을 못하였네요 ㅜㅜ
수정하였습니다!!
감사합니다!

2. 변수명도 수정 완료하였습니다. (클래스 명 수정으로 적용)

2021-09-08 07:43 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/LadderGameColumn.java
> +    private String result;
제거하였습니다!!

2021-09-08 07:44 UTC, jaeyoungjang2 commented
리뷰어님 ㅜㅜ 
너무 코드가 조잡하게 짜여저서 읽기 힘드실텐데 
좋은 피드백을 주셔서 너무 감사합니다.

말씀해 주신 피드백은 모두 적용하였습니다.
감사합니다!

2021-09-09 04:39 UTC, bass84 approved these changes
재영님~ 반영하시느라 수고 많으셨어요!
잘 반영해주셨습니다.
이제 마지막 단계를 앞두고 있네요.
지금까지 열심히 하셨던 것처럼 마지막 단계에서도 화이팅해요!! 🔥

2021-09-09 04:39 UTC, bass84 commented on src/main/java/step2/domain/LadderGameColumns.java
> +        String result = results.resultOfPosition(position);
result는 사용을 안 하네요. 지워주세요~!

2021-09-09 04:39 UTC, merged