Lambda ex
next-step/java-ladder pull request #1139
Opened 2021-09-02 17:17 UTC by testminseok

안녕하세요 ! 
사다리 타기 1단계를 진행했습니다.
피드백 부탁드립니다.

3단계 사다리 타기 잘부탁드립니다. !!!

2021-09-03 13:10 UTC, seok-2-o requested changes
안녕하세요. 사다리 미션을 함께 하게 된 이재석입니다. ✋ 

이번 과정도 이전 과정에서 지켜주신 규칙들을 준수할 수 있도록 해주면 좋을 것 같아요.
매직넘버를 이용한 부분이나 들여쓰기가 중첩되어 있는 부분들을 개선해서 다시 PR 요청주세요.

함께 할 수 있게 되어 무척 기쁜 마음입니다. :)
모쪼록 다음 PR 기대하고 있을게요. 🙇

2021-09-03 13:10 UTC, seok-2-o commented on src/main/java/nextstep/fp/Lambda.java
>          }
이번 과정은 람다와 스트림을 연습하는 과정입니다 람다를 이용해서 리펙토링 할 수 있으면 좋을 것 같아요

추가로 이번 과정에서 들여쓰기는 1번으로 제한하고 있으니 해당 부분도 개선 하면 좋을 것 같아요.

2021-09-03 13:10 UTC, seok-2-o commented on src/main/java/nextstep/fp/Lambda.java
>              if (number % 2 == 0) {
매직넘버는 상수로 분리하면 좋을 것 같아요.

2021-09-03 15:40 UTC, testminseok commented on src/main/java/nextstep/fp/Lambda.java
>          }
해당 문제에서 인터페이스를 추출하여 테스트 코드에서 람다를 파라미터로 넘기는걸로 이해했는데 그게 아닌가요 !?
피드백 주신대로 람다 스트림으로 변경하여 커밋했습니다 !
피드백 감사드립니다.

2021-09-04 12:39 UTC, seok-2-o approved these changes
피드백 반영 잘 해주셨네요.
스트림에서 중복코드를 제거 할 수있는 소소한팁을 남겨두었으니 확인 부탁드려요.
본격적으로 사다리 미션 진행하시죠 🏃

2021-09-04 12:39 UTC, seok-2-o commented on src/main/java/nextstep/fp/Lambda.java
> +                .reduce(INIT_TOTAL_VALUE, Integer::sum);
중복되는 코드를 아래와같이 추출 할 수 있을 것 같아요.

```JAVA
    public int sumAll(List<Integer> numbers) {
        return sum(numbers, it -> true);
    }

    public int sumAllEven(List<Integer> numbers) {
        return sum(numbers, it -> it % 2 == 0);
    }

    private int sum(List<Integer> numbers , Predicate<Integer> predicate) {
        return numbers.stream()
                .filter(predicate)
                .mapToInt(i -> i)
                .sum();
    }

2021-09-04 12:40 UTC, merged