Step2 사다리 생성
next-step/java-ladder pull request #1178
Opened 2021-09-11 13:57 UTC by snh15978

안녕하세요 재연님.

사다리 생성 미션입니다.

밀린업무가 많아 미션진행을 못했는데 남은기간동안 빠르고 꼼꼼하게 해보겠습니다!

좋은 리뷰 부탁드려요!

2021-09-12 11:48 UTC, jaeyeonling requested changes
사다리 생성을 잘 구현해주셨습니다 👍 
코멘트 남겨두었으니 확인 부탁드려요 😄

2021-09-12 11:48 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/LadderGame.java
> +        Ladder ladder = new Ladder(new AutoLadderGenerator().generate(ladderHeight, players.numberOfPlayers()));
LadderGenerator로 인터페이스를 분리하는 이유에 대해 고민해보시고, 도메인 외부에서 사용할 경우 인터페이스의 어떠한 장점을 얻을 수 있을지 고민해보아요!

2021-09-12 11:48 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/domain/AutoLadderGenerator.java
> +    private static boolean postLine = false;
해당 값이 static으로 존재하게 된다면 해당 클래스를 여러 스레드에서 사용할 때 어떠한 문제가 발생할 수 있을까요?

2021-09-12 11:48 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +public class Ladder {
해당 클래스를 보았을 때 단순 getter만 가지고 있는 빈약한 객체의 상태를 가지고 있습니다
해당 객체가 어떠한 역할과 책임을 가지고 있는지 고민해보고 역할과 책임을 부여해보아요 

다른 클래스들도 같이 확인해주세요!!

2021-09-12 11:48 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/domain/Players.java
> +                .map(name -> playerList.add(new Player(name.trim()))).collect(Collectors.toList());
스트림에서 map 연산자와 collect 연산자의 역할에 대해 공부해보면 좋을 것 같습니다!
지금 구현의 문제는 map에서 collect를 초기화한다는 점과, collect에서 최종적으로 만들어진 컬렉션을 사용하지 않는다는 문제가 있네요!

2021-09-12 11:48 UTC, jaeyeonling commented on src/test/java/nextstep/ladder/PlayerTest.java
> +class PlayerTest {
도메인 구현에 비해 테스트가 많이 부족하네요 ㅎㅎ
시간이 부족한 만큼 모든 부분에 테스트를 작성하는 것은 힘드셔도 핵심 로직에는 테스트 코드를 추가해보아요 :)

2021-09-13 14:48 UTC, snh15978 commented on src/test/java/nextstep/ladder/PlayerTest.java
> +class PlayerTest {
테스트 코드 추가 완료!

2021-09-13 14:48 UTC, snh15978 commented on src/main/java/nextstep/ladder/domain/Players.java
> +                .map(name -> playerList.add(new Player(name.trim()))).collect(Collectors.toList());
정신없이 하다보니 collect가 붙어있는 것을 놓쳤습니다 ㅠㅠㅠ

2021-09-13 14:49 UTC, snh15978 commented on src/main/java/nextstep/ladder/domain/AutoLadderGenerator.java
> +    private static boolean postLine = false;
값이 공유되기때문에 true - true 되는 경우가 발생할 수 있겠네요. 변경 완료하였습니다!

2021-09-13 14:51 UTC, snh15978 commented on src/main/java/nextstep/ladder/LadderGame.java
> +        Ladder ladder = new Ladder(new AutoLadderGenerator().generate(ladderHeight, players.numberOfPlayers()));
인터페이스를 만들어놓고 활용하지 않았네요..
사다리 생성 팩토리를 만들고 Ladder안에서 찾아 사다리를 생성하도록 변경하였는데 좋은 방법일까요..? 검색해보고 처음 적용해보는거라 어색하네요 😅

2021-09-14 10:22 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨습니다 👍 
질문의 답변과 추가적인 코멘트 남겨두었으니 확인 부탁드리고 다음 단계에 반영해주세요 :)

2021-09-14 10:22 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +        lines = ladderLinesGenerator.generate(ladderHeight, playerCount);
Q. 인터페이스를 만들어놓고 활용하지 않았네요..
사다리 생성 팩토리를 만들고 Ladder안에서 찾아 사다리를 생성하도록 변경하였는데 좋은 방법일까요..? 검색해보고 처음 적용해보는거라 어색하네요 😅

A. 생성자 내부에 존재하게 된다면 LadderGenerateFactory를 수정할 수 없는데요!
생성자의 파라미터로 LadderGenerator를 받는다면 SRP를 지킬 수 있을 것 같습니다 ㅎㅎ

2021-09-14 10:22 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/domain/Players.java
> +            throw new IllegalArgumentException("플레이어는 최소 2명 이상 이어야 합니다.");
```suggestion
            throw new IllegalArgumentException("플레이어는 최소 " +MIN_PLAYER_COUNT + "명 이상 이어야 합니다.");
```

와 같이 작성한다면 조건이 변경 됐을 때 메시지를 신경쓰지 않아도 되겠네요 ㅎㅎ

2021-09-14 10:22 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/domain/Players.java
> +                .forEach(name -> playerList.add(new Player(name)));
forEach에서 add를 해주는 것 보다 마무리 연산자 collect를 활용해보면 좋겠습니다 ㅎㅎ

2021-09-14 10:22 UTC, merged