ladder Step2
next-step/java-ladder pull request #1181
Opened 2021-09-12 07:45 UTC by minyul

안녕하세요! 리뷰어님! 

아직 완성을 못했음에도 리뷰요청을 하는 이유는 ..
구현을 함에 있어서 모르는 부분에 있어서 억지로 console에 나타냄을 위해 시간을 버리는 것이 너무 답답함이 있어서 입니다.

궁금한 것이 있습니다.

1. 일급컬렉션, 일급객체 ( User , Name, Users ) 와 같이 계속 쪼갰을 때 ! equals 와 hasCode를 전부 오버라이딩을 해야하는 것일까요? 찾아보니 전부 오버라이딩이라기 보다는 new Number(3) 와 new Number(3) 같은 경우 오버라이딩을 안해줄 경우 '다르다' 가 나오기 때문에 오버라이딩을 해줘야한다고 알고 있습니다. 그럼 이렇게 Name 또는 일급컬렉션인 Users 도 오버라이딩을 해줘야할까요?

2. 구현하다가 문제가 생기는 곳이 항상 같습니다. 일급컬렉션 ( Users -> List<User> ) 가 있을 경우 Controller 에서 반복문을 돌때, users.size() 를 구해야하는데 이렇게 일급컬렉션인 Users 로 구현하였을 경우 users.size() 라는 메세지를 보내서 크기를 받아도 되는것일까요? 

현재 가장 답답한 부분이 2번입니다 ㅠ-ㅠ ... 일급컬렉션, 일급 객체 처럼 감쌌을 때, 그 안에 있는 크기(?) 를 구하지 못한다는게 어렵습니다. 

감사합니다.

2021-09-13 01:27 UTC, dbeod2 requested changes
안녕하세요 민율님! 
미션 진행 빠르게 해주셨네요 👍🏻

상황에 대한 예외도 잘해주셨고, 커밋로그도 잘 작성해 주셔서 빠르게 확인 했던 것 같아요! 

질문에 대한 답변 드릴게요! 
Q1. 필수는 아닙니다! 민율님도 궁금해서 찾아보셨겠지만 잘 이해하셨습니다! 
Q2.넵 메시지를 보내서 크기를 받아도 됩니다:-) 

코멘트 확인해보시고 리뷰 재요청 주세요!

2021-09-13 01:27 UTC, dbeod2 commented on src/main/java/domain/Line.java
> +	private List<Boolean> points = new ArrayList<>();
전체적으로 박싱된 타입(Boolean)을 사용하신 이유는 무엇일까용?🤔

2021-09-13 01:27 UTC, dbeod2 commented on src/main/java/domain/Ladder.java
> +	IS_WIDTH("-----");
ui코드로만 사용하실 예정이신걸까요오?

2021-09-13 01:27 UTC, dbeod2 commented on src/main/java/domain/Name.java
> +	public Name(String name) {
예외처리 👍🏻

2021-09-13 01:27 UTC, dbeod2 commented on src/main/java/domain/Users.java
> +	public String toString() {
ui로직은 프러덕트 코드와 분리 시켜주세요! 🙏

2021-09-13 01:27 UTC, dbeod2 commented on src/main/java/utils/Result.java
> +	private String viewLine(Line line) {
사다리가 4일때 다리가 3개만 표시되고 있습니다! 확인 부탁드릴게용

2021-09-13 12:23 UTC, minyul commented on src/main/java/domain/Ladder.java
> +	IS_WIDTH("-----");
넹

2021-09-13 12:42 UTC, minyul commented on src/main/java/domain/Users.java
> +	public String toString() {
음.............. 의도에 맞게 고친건.. 모르겠는데 ㅠ-ㅠ 우선 고쳤습니다. toString이 왜 ui 로직인지 모르겠습니당.

2021-09-13 13:05 UTC, minyul commented on src/main/java/domain/Line.java
> +	private List<Boolean> points = new ArrayList<>();
음... 우선은 박싱된 타입을 쓰게 된 이유는 ResponseDto에서 프리미티브 타입으로 받았을 때 nullPointException이 나서 항상 박싱된 타입을 쓰게됐고.... Boolean을 쓴 이유는 그 점에 가로 사다리가 있는지 여부를 확인하기 위해 플래그 형태로 표현하기위해 Boolean을 썼습니다! 

그리고 이번 리팩토링때는 Point 라는 것을 써서 구현해보겠습니다.

2021-09-13 13:40 UTC, dbeod2 commented on src/main/java/domain/Users.java
> +	public String toString() {
제가 설명을 따로 못드렸네욥 
toString이 ui로직이 아니라 toString을 이용해서 ui코드에서만 사용되고 있어서 제가 판단하기엔 ui로직으로 사용되는 것같아서 말씀드린 부분이었습니다.
혼돈 드려 죄송해요!

2021-09-14 02:59 UTC, dbeod2 approved these changes
안녕하세요! 민율님 

사다리 2단계 미션 피드백 잘 반영해주셨네요! 커밋 로그도 잘 써주셔서 좋네요👍🏻
따로 이견드릴게 없어서 바로 머지하겠습니다.🙏

다음미션 진행해주세요!

2021-09-14 02:59 UTC, dbeod2 commented on src/test/java/nextstep/domain/UsersTest.java
> +public class UsersTest {
users도메인 테스트 👍🏻

2021-09-14 02:59 UTC, dbeod2 commented on src/test/java/nextstep/domain/LineTest.java
> +public class LineTest {
테스트가 조금 부족한 것 같습니다 🥲

2021-09-14 03:00 UTC, merged

2021-09-14 11:46 UTC, minyul commented on src/test/java/nextstep/domain/LineTest.java
> +public class LineTest {
넹