[사다리타기] 4단계 - 사다리(리팩토링)
next-step/java-ladder pull request #1209
Opened 2021-11-22 12:07 UTC by csh0034

안녕하세요.

4단계 - 사다리(리팩토링) 제출합니다.

---
Point 의 경우 index 를 보관하며 상태를 변경시키는 방법이 필요하지 않다고 생각하여 제외하였습니다.
Direction 의 경우 enum 을 적용하며 이동해야하는 값을 관리하여 move 처리를 하였습니다.
- 생성자에서 if 문으로 하는 방법이 좋아 보이진 않다고 생각됩니다만 Generator 에서 생성된 랜덤값을 어디선가 분기 처리를 해야할것 같은데
더 좋은 위치 또는 다른 처리 방법이 있는지 질문드립니다. 😃

2021-11-22 12:46 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
구조변경을 간단하게 제안 드렸는데 제안은 간단하지만 변경은 간단치 않을 것 같습니다;
한번 검토 부탁 드리겠습니다.

2021-11-22 12:46 UTC, wheejuni commented on src/main/java/nextstep/ladder/generator/Generator.java
> +	boolean generate();
리턴타입이 `boolean` 말고 다른 타입이면 되지 않으려나요? 제가 보기에도 다른 쪽에서 분기처리를 하는 것은 이상합니다.
`DirectionGenerator` 와 같이 행동이 구체화된 타입이면 좋지 않을까요? 한번 고민 부탁 드리겠습니다.

2021-11-22 12:46 UTC, wheejuni commented on src/test/java/nextstep/ladder/domain/LadderTest.java
> +	 */
👍

2021-11-22 12:46 UTC, wheejuni commented on src/test/java/nextstep/ladder/generator/FixedFalseGenerator.java
> +public class FixedFalseGenerator implements Generator {
👍

2021-11-23 12:41 UTC, csh0034 commented
안녕하세요.
말씀해주신 행동이 구체화된 타입을 리턴하는 DirectionGenerator 적용 관련해서 검토해보았습니다.

현재 Ladder -> Line -> Point -> Direction 으로 설계가 되어있으며
사다리를 그리기위해선 Line 에서 첫번째 포인트는 반드시 RIGHT or HOLD Direction 을 가져야하며
Line의 마지막 포인트는 LEFT or HOLD Direction 을 가져야합니다. 따라서 이러한 규칙을 적용하기위해선 
사다리 가로 넓이의 인덱스의 따라서 Line 이 생성될때 적용 가능하기 때문에 LineGenerator 로 구현해야 한다고 판단했습니다.

LineGenerator 를 구현할 경우 랜덤으로 생성된 boolean 값을 if 문으로 비교하여 Line -> Point -> Direction 까지 전달해야하며
각 라인마다 첫번째 포인트, 마지막 포인트를 조건문으로 체크하면서 random boolean 값까지 체크하는것보다
Direction 생성시에 한번만 체크하는것이 낫다고 생각하여 기존 구조 유지하였습니다.

2021-11-24 03:16 UTC, wheejuni commented
네 수고하셨습니다

2021-11-24 03:16 UTC, merged