Step2
next-step/java-ladder pull request #1228
Opened 2021-12-02 16:44 UTC by hiro032

안녕하세요 리뷰어님 오랜만에 PR드립니다 ㅎㅎ

미션구현을 완료했지만 기능적인 부분은 크게 없는 미션이라 테스트 코드를 작성할 부분이 많지 않았던것 같습니다.
이번 미션을 구현하면서 전략패턴을 적용해보기위해 LinesGenerator를 구현해 봤는데요, 

이 부분에 대한 피드백이 듣고 싶습니다.  특히 lineGenerate 부분이 조금 이상한것같아 궁금합니다...😓

그럼 피드백 부탁 드리겠습니다!! 감사합니다 ㅎㅎ😇

2021-12-03 00:57 UTC, testrace requested changes
안녕하세요 😀

사다리 생성 기능 잘 구현해 주셨네요!
코드를 깔끔하게 작성해 주셔서 보기 좋았습니다! 👍

몇 가지 의견 남겼으니 확인해 주시고 리뷰 요청 부탁드려요.

2021-12-03 00:57 UTC, testrace commented on docs/🚀 2단계 - 사다리(생성) 요구사항.md
> +- |-----|-----| 모양과 같이 가로 라인이 겹치는 경우 어느 방향으로 이동할지 결정할 수 없다.
기능 요구 사항 👍

2021-12-03 00:57 UTC, testrace commented on src/main/java/nextstep/ladder/Application.java
> +            return getPlayers();
재입력을 해야하는 이유를 알려주면서 입력을 받으면 좋을 것 같아요.

2021-12-03 00:57 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +        validateLines(lines);
유효성 검증에 대한 테스트 코드도 추가할 수 있을 것 같아요.

2021-12-03 00:57 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Line.java
> +        return line;
컬렉션을 그대로 반환하면 변조를 할 수 있어 일급 컬렉션의 의미가 없어지는 것 같아요.
내부 요소를 수정하지 못하는 컬렉션을 반환하면 어떨까요?
```suggestion
        return Collections.unmodifiableList(line);
```

2021-12-03 00:57 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Player.java
> +            throw new IllegalArgumentException(name);
커스텀 예외를 활용해 제약 사항(제한 길이)의 예외 메시지를 제공한다면 어떨까요?
이펙티브 자바의 아이템 75번을 참고해보시면 좋을 것 같아요!

2021-12-03 00:57 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Players.java
> +    }
사다리 게임의 최소 인원수가 2명이어야 할 것 같아요!

![image](https://user-images.githubusercontent.com/8064743/144509834-5bc6a708-2ebf-44f5-a7ac-8bbc6a14116d.png)

2021-12-03 00:57 UTC, testrace commented on src/main/java/nextstep/ladder/domain/RandomLinesGenerator.java
> +    }
피드백 요청하신 부분이네요.
작성하신 코드도 충분히 좋은데요! 👍
다만 메소드를 분리해서 내부 코드를 간소화하면 가독성도 좋아지고 유지보수에도 좋을 것 같아요.

추가 의견으로 Point.next()에 의존하지 않고 `이어진다, 이어지지 않는다`에 대한 책임을 직접 수행하는 전략도 있으면 어떨까 싶습니다.

2021-12-03 00:57 UTC, testrace commented on src/main/java/nextstep/ladder/domain/RandomLinesGenerator.java
> +    }
사다리 높이에 대한 유효성 검증도 추가되면 좋을 것 같아요.

2021-12-03 00:57 UTC, testrace commented on src/main/java/nextstep/ladder/utils/StringUtils.java
> +    }
private으로 생성자를 통한 인스턴스화를 막아주셨네요 👍
내부에서도 생성하지 못하도록 예외를 던져보면 어떨까요?
이펙티브 자바의 아이템 4번을 참고해보시면 좋을 것 같아요!
```suggestion
    private StringUtils() {
        throw new AssertionError();
    }
```

2021-12-03 00:57 UTC, testrace commented on src/main/java/nextstep/ladder/view/InputView.java
> +    private static final String askLadderHeight = "최대 사다리 높이는 몇개 인가요?";
상수명 자바 컨벤션을 확인해 주세요.
참고링크
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2021-12-03 00:57 UTC, testrace commented on src/main/java/nextstep/ladder/view/OutputView.java
> +        System.out.println();
```
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.
규칙 2: else 예약어를 쓰지 않는다.
```
도메인 객체가 아니더라도 규칙을 지키면서 구현해 보시면 좋을 것 같아요!


플레이어 수와 사다리의 세로 선의 수가 일치하지 않아요. 확인 부탁드려요.
![image](https://user-images.githubusercontent.com/8064743/144510061-9b90d510-57e7-43f7-9ac1-fbb0e303c030.png)

2021-12-03 00:57 UTC, testrace commented on src/test/java/nextstep/ladder/domain/LineTest.java
> +class LineTest {
요구사항
`사다리 타기가 정상적으로 동작하려면 라인이 겹치지 않도록 해야 한다`에 만족하기 위해서
연속된 Point로 Line을 생성 예외에 대한 테스트도 있으면 좋을 것 같아요

```java
Arrays.asList(Point.from(Boolean.TRUE), Point.from(Boolean.TRUE), Point.from(Boolean.TRUE))
```

2021-12-03 01:49 UTC, hiro032 commented on src/main/java/nextstep/ladder/domain/RandomLinesGenerator.java
> +    }
추가 했습니다!

2021-12-03 01:49 UTC, hiro032 commented on src/main/java/nextstep/ladder/domain/Players.java
> +    }
수정 완료 했습니다

2021-12-03 01:52 UTC, hiro032 commented on src/main/java/nextstep/ladder/domain/Player.java
> +            throw new IllegalArgumentException(name);
적용해 봤습니다

2021-12-03 01:53 UTC, hiro032 commented on src/main/java/nextstep/ladder/domain/RandomLinesGenerator.java
> +    }
>  추가 의견이 잘 이해가 가지 않는데 혹시 예시로 들어주실만한 코드가 있을까요 ?ㅜㅜ

2021-12-03 01:54 UTC, hiro032 commented on src/main/java/nextstep/ladder/utils/StringUtils.java
> +    }
이런 방법은 모르고있었네요 ㅎㅎ 이펙티브 자바읽어보도록 해야할것 같아요

2021-12-03 04:01 UTC, hiro032 commented on src/main/java/nextstep/ladder/view/OutputView.java
> +        System.out.println();
메서드 추출 했습니다

2021-12-03 14:12 UTC, hiro032 commented on src/test/java/nextstep/ladder/domain/LineTest.java
> +class LineTest {
Point에 메서드를 만들어서 확인할수 있도록 했습니다

2021-12-04 09:14 UTC, testrace approved these changes
안녕하세요 😀
피드백 빠르게 반영해 주셨네요. 👍

몇 가지 코멘트 남겨두었으나 다음 단계 진행하시면서 반영해 주시면 될 것 같아요!

다음 단계 진행 부탁드립니다!

2021-12-04 09:14 UTC, testrace commented on src/main/java/nextstep/ladder/domain/ContinuousRowException.java
> +package nextstep.ladder.domain;
```suggestion
package nextstep.ladder.exception;
```

2021-12-04 09:14 UTC, testrace commented on src/main/java/nextstep/ladder/domain/ContinuousRowException.java
> +public class ContinuousRowException extends RuntimeException {
커스텀 예외 👍

2021-12-04 09:14 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Line.java
> +    private static int FIRST_INDEX = 0;
재할당을 하지 않는다면 final 키워도 붙여 주세요 😀

2021-12-04 09:14 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Line.java
> +        }
메서드로 분리하면 좋을 것 같아요.

2021-12-04 09:14 UTC, testrace commented on src/test/java/nextstep/ladder/domain/PlayerTest.java
> +        assertThatThrownBy(() -> Player.from(name)).isInstanceOf(PlayerNameException.class);
테스트가 실패하고 있어요 😢

2021-12-04 09:14 UTC, testrace commented on src/test/java/nextstep/ladder/domain/PlayersTest.java
> +                        Players.from(new String[] {"hi"}), 1
테스트가 실패하고 있어요 😢

2021-12-04 09:15 UTC, merged

2021-12-06 06:49 UTC, hiro032 commented on src/test/java/nextstep/ladder/domain/PlayerTest.java
> +        assertThatThrownBy(() -> Player.from(name)).isInstanceOf(PlayerNameException.class);
수정 했습니다!

2021-12-06 06:49 UTC, hiro032 commented on src/test/java/nextstep/ladder/domain/PlayersTest.java
> +                        Players.from(new String[] {"hi"}), 1
수정 했습니다!

2021-12-08 02:25 UTC, testrace commented on src/main/java/nextstep/ladder/domain/RandomLinesGenerator.java
> +    }
Point의 next 메서드를 RandomLinesGenerator 내부로 옮기면 어떨까 싶어 의견 드렸었습니다 😀

```java
    private Line lineGenerate(int rowCount) {
        List<Point> points = new ArrayList<>();

        Point point = Point.from(RANDOM.nextBoolean());
        points.add(point);

        for (int i = 0; i < rowCount - 1; i++) {
            boolean next = next(points.get(points.size() - 1).isTrue());
            points.add(Point.from(next));
        }

        return Line.from(points);
    }

    private boolean next(boolean point) {
        if (point) {
            return false;
        }
        return RANDOM.nextBoolean();
    }
```

랜덤이 아닌 `true, false, true, false` 패턴의 사다리를 만들어야 한다면
Point에 nextTrueFalse() 같은 메서드가 추가 되어야 할 것 같았어요.

사실 RandomLinesGenerator 은 전략패턴과 조금 거리감이 있어 보이는데요,
전략 패턴은 특정 행위에 대해서 추상화를 하고 추상화된 행위를 구체화 하여 주입 받아 유연성을 보장하는 것이 특징이라고 생각합니다.

```java
class Point {
    ...
    public Point next(PointStrategy strategy) {
        return new Point(strategy.next());
    }
}
```

```java
Point next = point.next(new ContinousStrategy());
```