Step2 - 사다리(생성)
next-step/java-ladder pull request #1231
Opened 2021-12-04 01:20 UTC by kth4878

2단계 사다리 생성 입니다.

2021-12-04 15:02 UTC, parkeeseul requested changes
2단계 미션 잘 진행해주셨네요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다! 😄 
즐거운 주말 보내세요! 🔥

2021-12-04 22:22 UTC, kth4878 commented on src/main/java/ladder/domain/Line.java
> +    }
특별한 이유는 없습니다.

처음에는 if를 사용했지만 삼항 연산자를 사용해도 될거같아서 사용했습니다.

2021-12-05 14:46 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
한 가지 소소한 코멘트 남겨두었으니 확인 부탁드릴게요! 😄 
다음 단계 진행해주세요! 화이팅 입니다! 🔥

2021-12-05 14:46 UTC, parkeeseul commented on src/main/java/ladder/domain/Height.java
> +    private final int height;
개인적으로는 상수와 일반 변수는 개행을 통해 구분해주면 좀 더 가독성이 좋다고 생각합니다 😄 
```suggestion
public class Height {
    private static final String HEIGHT_ERROR_MESSAGE = "error : 높이는 최소%d, 최대%d 까지 가능합니다.";
    private static final int MIN = 2;
    private static final int MAX = 10;
    
    private final int height;
```

2021-12-05 14:46 UTC, merged