🚀 2단계 - 사다리(생성)
next-step/java-ladder pull request #1238
Opened 2021-12-05 17:19 UTC by giyeon95

안녕하세요 리뷰어님!

2단계 리뷰 구현 후 리뷰 요청 드립니다.

감사합니다~!

2021-12-06 10:39 UTC, SSONG22 requested changes
안녕하세요, 기연님:) 2단계 구현 잘해주셨어요 👍 
몇가지 코멘트를 남겼는데 확인 후에 리뷰 재요청 주세요 😊

2021-12-06 10:39 UTC, SSONG22 commented on src/main/java/nextstep/ladder/Line.java
> +            .forEach(i -> points.add(isNotDrawnBeforePoint(i) && pickAtRandom(random)));
0은 의미가 있어보이는 숫자네요 👀
i 보다는 밑에서 썼던 index로 바꾸는 건 어떨까요?

2021-12-06 10:39 UTC, SSONG22 commented on src/test/java/nextstep/ladder/LadderTest.java
> +    private List<Line> getLinesByReflection(Ladder ladder)
`getLines()`가 있는데 리플렉션을 쓰면서 테스트한 이유가 궁금해요:)

2021-12-06 10:39 UTC, SSONG22 commented on src/test/java/nextstep/ladder/LineTest.java
> +    private Random drawLineRandomMock() {
`nextBoolean()` 를 재정의 해서 테스트 하셨네요! 👍

2021-12-06 10:39 UTC, SSONG22 commented on src/test/java/nextstep/ladder/ParticipantTest.java
> +    private String getNameByReflection(Participant participant)
커밋 로그 보니 getter 생성 전에 테스트 코드를 만드셔서 리플렉션을 쓰셨군요 👍 
getter를 안쓰려고 리플렉션을 쓰신건지 궁금해요! 테스트 코드에서는 주로 private 메서드를 테스트할 때 리플렉션을 쓰는 걸로 알고 있는데 기연님 생각은 어떠신가요?

2021-12-06 11:27 UTC, giyeon95 commented on src/main/java/nextstep/ladder/Ladder.java
> +    public static Ladder create(int height, int participantsCount) {
리펙토링을 하다가 놓친 부분이 있었네요, 😂 꼼꼼한 리뷰 감사합니다!

2021-12-06 12:04 UTC, giyeon95 commented on src/test/java/nextstep/ladder/LadderTest.java
> +    private List<Line> getLinesByReflection(Ladder ladder)
안녕하세요 리뷰어님!
테스트 코드를 작성하는 시점에는, `게터` 메소드가 필요가 사실 없는 상황이었는데요~
나중에 `게터` 메소드가 추가되면서, 말씀 주신것처럼 리플렉션이 필요 없는 상황이 되었네요!

2021-12-06 12:09 UTC, giyeon95 commented on src/test/java/nextstep/ladder/ParticipantTest.java
> +    private String getNameByReflection(Participant participant)
로그까지 꼼꼼히 봐주셔서 감사합니다 👏👏

말씀주신 것처럼, 테스트 코드 작성 시점에서는 `게터`를 최대한 지양하고자, 리플렉션을 사용했습니다.
사용할지 모르는 `게터`를 테스트를 위해 먼저 추가하는건 아니지 않을까? 라는 생각이 들었어요!

private 메소드를 테스트 할때도 사용할 수 있지만 저는 반드시 private 에서만 사용해야 한다고는 생각하지는 않습니다.
해당 기술이 필요와 용도에 따라 사용된다면 하나의 방법이 될 수 있지 않을까요? 😊😊

2021-12-06 12:12 UTC, giyeon95 commented on src/main/java/nextstep/ladder/Ladder.java
> +    public Ladder(int height, int participantsCount) {
랜덤값을 계속 생성하면 불필요한 객체 생성으로 성능이 저하될 수 있다고 생각됩니다,

다만, static 으로 지정후 사용한다면, 테스트가 가능한 구조일까 고민이 들었고, 객체를 외부에서 주입받는 방식으로 변경하게 되었습니다.

```
    private Random drawLineRandomMock() {
```

혹시 제가 잘못 생각하는 부분이 있거나,, 다른 좋은 방법이 있을까요.? 😂😂

2021-12-06 13:02 UTC, SSONG22 commented on src/main/java/nextstep/ladder/Ladder.java
> +    public Ladder(int height, int participantsCount) {
테스트 하기 쉬운 구조로 만들때는 클래스를 나누는 것이 좋다고 생각되는데요, 전략패턴을 쓰는건 어떨까요? 👀

2021-12-06 14:04 UTC, SSONG22 requested changes
빠르게 피드백 반영해주셨네요! 👍 
리팩토링 잘 해주셨는데요, 한가지 더 수정할 사항이 보여서 🥲 
확인 후 한번 더 리뷰 재요청 해주세요 🙇🏻‍♀️

2021-12-07 03:42 UTC, SSONG22 approved these changes
피드백 바로 적용해주셨네요 👏👏👏
바로 머지하겠습니다! 다음 단계 진행해주세요 🔥

2021-12-07 03:42 UTC, merged