🚀 2단계 - 사다리(생성)
next-step/java-ladder pull request #1245
Opened 2021-12-07 07:39 UTC by soosue

첫 번째 단계로부터 너무 오랜 시간이 걸렸네요😢
사다리 만드는 게 너무 생소했었습니다. 잘 만들었는지도 모르겠네요..

리뷰 부탁 드립니다. 좋은 하루 보내세요😄!!

2021-12-08 10:28 UTC, catsbi requested changes
안녕하세요. 윤수님 슬랙 메세지를 제대로 못봐서 리뷰가 너무늦어졌네요 죄송합니다 😢 🙏 
미션으로 넘어와서, 사다리 2단계 코드 잘 작성해주셨습니다. 
피드백 적용도 잘 해주셨고, 전체적으로 코드가 깔끔하고 클린코드 규약에서 벗어난것도 많지 않아서 좋았습니다.  몇가지 피드백이 필요한 부분에 대해서 코멘트를 드렸으니, 리팩토링을 조금만 더 진행하면 더 좋은 코드가 될 것 같습니다. 

리팩토링 후 다시 리뷰요청 해주세요! 👍

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/domain/LadderPartFactory.java
> +public class LadderPartFactory {
유틸리티 클래스는 생성자 제한을 통해 예기치못한 인스턴스 생성을 막아주는게 좋습니다 ㅎ

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/domain/LadderPartFactory.java
> +        return Rung.rung(false);
isRunSet의 논리값 분기에 따라 다른 `Rung`을 만들고 랜덤 논리값을 반환하는 로직을 여기서 하기보다는 Rung 객체에 정적 팩토리 메서드로 isRungSet 값과 RandomBoolean 에 대해서 전략패턴을 적용해서 전달해보는건 어떨까요? 
여기선 랜덤으로 사다리의 `Rung`을 만들지만 좀 더 유연하게 적용해보는 것이죠. 자동차 경주때의 전진전략처럼요 ㅎ

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/domain/Line.java
> +    private static final Predicate<Integer> widthCondition = width -> width % 2 == 0;
```suggestion
    private static final IntPredicate widthCondition = width -> width % 2 == 0;
```

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/domain/Line.java
> +        if (widthCondition.test(width)) {
다른 객체도 그렇지만 람다식을 사용하는 이유가 명확하지 않습니다.
람다식으로 함수라는 `행위`를 변수로 만드는 것의 특장점은 행위 자체를 다른 도메인 혹은 계층으로 전달할 수 있다는 것인데, 여기서는 그저 내부에서 해당 일급 함수를 사용할 뿐입니다.  그럼 이런 일급 함수를 만들 이유가 있을까요?

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/domain/Line.java
> +        }
Stream API를 사용할수 있을 것 같습니다. 
그리고  `previousRung` 이라는 객체는 굳이 사용하지 않고 Rung만으로도 충분하거나 혹은 Rung도 필요 없을 것 같은데 해보시겠어요?

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/domain/Name.java
> +        if (o == null || getClass() != o.getClass()) return false;
`{}` 블럭은 한 줄 짜리이거나 IDE에서 자동생성된 코드라도 생략은 지양해주세요 ㅎ

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/domain/Name.java
> +        Assert.notNull(value, MAX_NAME_MESSAGE);
String API에서 제공하는 isEmpty혹은 Objects의 nonNull로도 충분히 대응이 가능할 것 같습니다.

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/domain/Names.java
> +    private final List<Name> names;
멤버 필드의 이름을 클래스명과 동일하게 하지 말아주세요 getter 사용시나 기타 코드에서 혼동될 수 있습니다 ㅎ

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/domain/Rung.java
> +    public static Rung rung(boolean on) {
정적팩토리 메서드의 단점은 프로그래머가 찾기 힘들다는데 있죠. 그렇기에 이 문제를 해결하기 위해 관례를 따르는 네이밍으로 정적 팩토리 메서드임을 알리곤합니다. 
이펙티브 자바의 아이템 1에서 이를 언급하고 있으니 참고해보시겠어요? [아이템1](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#f955301e-6ea2-4f7a-a4c0-f8346c47f61c)

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/ui/InputView.java
> +public class InputView {
생성자 제한 혹은 싱글톤 패턴을 통해 객체를 핸들링해보는건 어떨까요?

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/ui/OutputView.java
> +        StringBuilder sb = new StringBuilder();
StringBuilder를 멤버 필드 혹은 정적 멤버필드로 빼서 재활용이 가능할 것 같습니다. 
해당 객체는 유틸리티 클래스로 공유가 될 가능성이 있는데, 메서드가 호출될 경우마다 새로 생성하는건 비용이 아깝네요!

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/ui/OutputView.java
> +        if (sb.length() % 2 == 0) {
length가 짝수인지 판단하는 이 로직은 어디선가 이미 봤던거같지 않나요?

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/ui/OutputView.java
> +        if (sb.length() % 2 == 0) {
그리고 매직넘버와 매직리터럴이 보이는군요!

2021-12-08 10:28 UTC, catsbi commented on src/main/java/ladder/ui/OutputView.java
> +        System.out.println(sb.toString());
toString() 을 생략해도 도리 것 같습니다 ㅎ

2021-12-09 09:07 UTC, soosue commented on src/main/java/ladder/domain/Ladder.java
> +        }
~~~java
IntStream.range(0, height)
        .forEach(idx -> lines.add(new Line(width)));
~~~
이렇게일까요??

2021-12-09 09:10 UTC, soosue commented on src/main/java/ladder/domain/LadderPartFactory.java
> +        return new Random().nextBoolean();
RandomUtil.randomBoolean()처럼 유틸성 클래스로 빼는게 좋을까요?
아니면 private final static 변수로 빼는게 좋을까요?? 저는 내부 변수쪽으로 좀 더 기우는데요.

항상 이런 부분에서 고민이 됩니다! 유틸성 클래스로 빼게 되면, 아무래도 의존성이 생기게 되고, 내부 변수로 빼자니 해당 객체가 가지고 있어야하는 변수인가 하는 생각이 들어서요. 의견 주실 수 있을까요?

2021-12-09 09:12 UTC, soosue commented on src/main/java/ladder/domain/Names.java
> +    private final List<Name> names;
value나 nameList를 생각했는데, 그 중 value가 나아보이는데 어떻게 생각하시나요??

2021-12-09 09:14 UTC, soosue commented on src/main/java/ladder/domain/Rung.java
> +    public static Rung rung(boolean on) {
from 괜찮을까요!

2021-12-09 09:23 UTC, soosue commented on src/main/java/ladder/ui/OutputView.java
> +        StringBuilder sb = new StringBuilder();
동시성 상황을 한 번 생각 해보고 정적변수로 안 뺐던건데요. 현재 프로젝트가 멀티스레드 환경이 아니니 굳이 고려하지 않아도 됐을까요??

2021-12-09 11:02 UTC, catsbi commented on src/main/java/ladder/domain/LadderPartFactory.java
> +        return new Random().nextBoolean();
xxxUtil은 반 필연적으로 SRP 정책을 위반하게 되기에 조심스럽죠. 
여기서 중요한건 RandomUtil이라는 유틸리티 클래스에서 SRP를 위배할까 아닐까에 대한 고민이라고 생각해요. 
해당 팩토리에서만 Random을 사용할 것 같다면 클래스 내 상수로 빼도 될 것 같습니다. ㅎ

2021-12-09 11:04 UTC, catsbi commented on src/main/java/ladder/domain/Names.java
> +    private final List<Name> names;
value도 충분해보이긴하네요 ㅎ List라는 단어는 조심해서 사용해야해요 클린코드 책에서는 해당 네이밍에 대해 이렇게 언급하고 있어요. 

> 그릇된 정보를 피하라 여러 계정을 그룹으로 묶을 때, 실제 List가 아니라면, accountList라 명명하지 않는다. 프로그래머에게 List라는 단어는 특수한 의미다. 계정을 담는 컨테이너가 실제 List가 아니라면 프로그래머에게 그릇된 정보를 제공하는 셈이다. (주석1 - 나중에 살펴보겠지만, 실제 컨테이너가 List인 경우라도 컨테이너 유형을 이름에 넣지 않는 편이 바람직하다.) 그러므로 accountGroup, bunchOfAccounts, 아니면 단순히 Accounts라 명명한다.

2021-12-09 11:05 UTC, catsbi commented on src/main/java/ladder/ui/OutputView.java
> +        StringBuilder sb = new StringBuilder();
volatile 혹은 synchronized 키워드를 통해서 충분히 제어가 가능합니다 ㅎ

2021-12-09 11:44 UTC, soosue commented on src/main/java/ladder/domain/Line.java
> +        if (widthCondition.test(width)) {
1단계에서의 방식으로 람다식을 사용해야한다라는 의미는 알 것 같습니다! 제가 일급함수로 만든 이유는 매직리터럴과 같은 의미에서의 사용이였어요. 해당 람다식에 의미를 부여할 수 있다는?

굳이 그렇게까지 할 필요는 없을까요?

2021-12-10 04:11 UTC, soosue commented on src/main/java/ladder/ui/OutputView.java
> +        if (sb.length() % 2 == 0) {
재사용할 수 있게 공통으로 빼보라는 말씀이실까요?!

2021-12-10 04:17 UTC, soosue commented
리뷰 반영해서 푸시해보았습니다!

전략패턴(?)으로 만드는 부분과 PreviousRung을 제거하는 부분 고민을 많이 하고 구현해봤는데,
이게 생각하시는 방법이 맞는지는 잘 모르겠네요😂

부족한 부분이 있다면 알려주시면 감사하겠습니다!
아 그리고 IntStream.range(0, xxx)에서 0도 매직넘버일까요??

2021-12-10 05:35 UTC, catsbi commented on src/main/java/ladder/ui/OutputView.java
> +        if (sb.length() % 2 == 0) {
네 맞습니다 ㅎㅎ

2021-12-10 05:36 UTC, catsbi commented on src/main/java/ladder/domain/Line.java
> +        if (widthCondition.test(width)) {
네, 계층전달의 목적혹은 전략패턴의 사용이 아니라면 메서드로 정의해도 상관없을 것 같네요 ㅎㅎ

2021-12-10 06:11 UTC, catsbi requested changes
윤수님 피드백 적용 빠르게 해주셨네요 👍 
람다식과 인터페이스를 활용하려고 노력하셔서 아주 좋습니다. 
그대로 넘어가기엔 조금 아쉽기에 몇가지 피드백을 남겼으니 한 번만 더 리팩토링 해봅시다 
리뷰 확인후 다시 요청해주세요!

2021-12-10 06:11 UTC, catsbi commented on src/main/java/ladder/domain/LadderPartFactory.java
> +    }
전략패턴을 쓰려고 하는 시도는 좋지만, 코드의 가독성은 떨어지고 생성 로직중 이전LadderPart의 논리값 분기는 하지만 랜덤으로 값을 만든다는건 팩토리클래스에서 그냥 정의하고있습니다. 
완전히 유연한 전략패턴이 아니죠. 

```suggestion
    public static LadderPart ladderPart(int idx, MakeRungStrategy strategy) {
        if (Function.EVEN_NUMBER.test(idx)) {
            return Rail.instance();
        }

        if (isPreviousRungSet) {
            changeIsPreviousRungSet(false);
            return Rung.from(isPreviousRungSet);
        }
        
        return Rung.from(strategy.test());
    }
```
저라면 이런식으로 생각해볼수도 있다고 생각해요 ㅎ 

그리고 MakeRungStrategy 인터페이스의 구현체로 랜덤 발판 생성기를 하나 만드는거죠 ㅎ

```java
public class RandomRungSupplier implements MakeRungStrategy{
    private static final Random RANDOM = new Random();
    
    @Override
    public boolean test() {
        return RANDOM.nextBoolean();
    }
}
```

2021-12-10 06:13 UTC, catsbi commented
> 아 그리고 IntStream.range(0, xxx)에서 0도 매직넘버일까요??
네, ㅎㅎ 저는 이왕 학습하는것이니 다 빼는것도 좋다고 생각해요. 

그리고, Rail, Rung이 제가 볼 때는 Enum 열거타입으로 정리가 될 것 같다는 생각이드는데 어떻게 생각하시나요? 
이 부분은 해보실 수 있으면 해볼만하다고 생각합니다 ㅎㅎ

그리고 각각의 객체에서 출력될 결과 문자열 값(ex: `-----`)을 알고있지만, 이건 View Layer에서 알아야 할 값이지 도메인에서는 어떻게 출력될지는 알 필요가 없다고 생각해요 ㅎㅎ

2021-12-10 07:48 UTC, soosue commented on src/main/java/ladder/domain/Ladder.java
> +    private static final ToIntFunction<Names> NAMES_TO_WIDTH = names -> names.count() * 2 - 1;
아.. 너무 한 쪽으로만 쏠린 생각을 하고 있었네요 ㅠㅠ

2021-12-10 07:51 UTC, soosue commented on src/main/java/ladder/util/function/Function.java
> +public class Function {
하하하.. 마지막에 공통화 해놓고 빼먹었네요 🤪

2021-12-10 07:52 UTC, soosue commented on src/main/java/ladder/util/function/Function.java
> +public class Function {
MathFunction...?! or NumberFunction..?

2021-12-10 07:53 UTC, soosue commented on src/main/java/ladder/ui/OutputView.java
> +            append(STRING_BUILDER);
아뇨아뇨!! 절대 없죠!!!

2021-12-10 08:32 UTC, soosue commented on src/main/java/ladder/domain/LadderPartFactory.java
> +    }
아 Rung에게 MakeRungStrategy를 주입하라고 말씀하신 줄 알았었어요. 그래서 Rung이 해당 strategy를 알 필요가 있나? 하는 생각에 LadderPartFactory에다가 놔야겠다고 생각하고 구현하다보니 이렇게 나왔는데, 그게 아니었군요!

제가 import에 대해서 뭔가 잘못된 생각을 가지고 있는 것 같은데요. Line에서 LadderPartFactory.ladderPart(index, new RandomRungSupplier())를 호출하니깐 import xxx.xxx.RandomRungSupplier;가 생기게 되는데, 이렇게 import를 하게 되는 것에 대해 거부감이 생기더라구요. RandomRungSupplier가 없게 되면 Line에서 에러가 나게 되니깐요.
제가 어떤 식으로 생각을 바꿔야할까요?? 아니면 추천해주실만한 서적이나 자료 같은게 있을까요?

2021-12-10 09:46 UTC, catsbi commented on src/main/java/ladder/domain/LadderPartFactory.java
> +    }
@soosue 

 이건 이펙티브자바의 [아이템 5](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#99fc646f-2f60-43d4-9418-07544af02d43)를 참고해보시면 좋을 것 같아요.

구현체를 어디서 주입해줄지에 대해서에 대한 고민이신것 같은데, 그 선은 윤수님이 잘 정해주셔야 할 것 같네요.
개인적으로는 서비스레이어에서 하거나 아예 DI만 전담할 설정영역을 만드는것도 방법이겠죠. 
결국 `SOLID`에 대해 고민하면서 나올만한 주제인데, 현재 해당 사다리 프로젝트는 적절한 서비스계층이 존재하지 않다보니 이 RandomRungSupplier라는 인터페이스가 아닌 구현체를 어디서 의존할지에 대한 고민을 하게되는 것 같아요 ㅎㅎ

개인적으로는 LadderPartFactory에서 해당 구현체에 대한 의존성을 가져도 될 것 같긴하네요. 
그렇다면 이렇게 코드를 작성할 수 있겠죠
```java
public class LadderPartFactory {
    
    private boolean isPreviousRungSet;
    private final MakeRungStrategy makeRungStrategy;

    public LadderPartFactory(MakeRungStrategy makeRungStrategy) {
        this.isPreviousRungSet = false;
        this.makeRungStrategy = makeRungStrategy;
    }

    public LadderPart ladderPart(int idx) {
        if (Function.EVEN_NUMBER.test(idx)) {
            return Rail.instance();
        }
        if (isPreviousRungSet) {
            changeIsPreviousRungSet(false);
            return Rung.from(isPreviousRungSet);
        }

        return Rung.from(makeRungStrategy.test());
    }
    //logic...
}
```

2021-12-10 16:39 UTC, soosue commented
다시 리뷰 요청드립니다!

2021-12-11 13:50 UTC, catsbi approved these changes
윤수님 피드백 빠르게 적용해주셨네요 👍 
동일한 실수를 반복안하고, 피드백도 고민해서 잘 적용하셨네요. 
2단계는 여기서 merge하도록 하겠습니다. 이제 3단계로 넘어가시죠 😃

2021-12-11 13:50 UTC, catsbi commented on src/main/java/ladder/domain/Line.java
> +                .mapToObj(index -> LadderPartFactory.ladderPart(index, new RandomRungSupplier()))
RandomRungSupplier에 대해서도 외부에서 주입(`DI`)되면 좋을 것 같네요. 
Line이라는 도메인보다는 LadderPartFactory나 기타 서비스레이어 혹은 설정영역 등 하나의 도메인이 아닌 애플리케이션, 설정 계층에서 구현체를 주입하고 이를 사용하는게 더 나을 것 같아요 ㅎㅎ

2021-12-11 13:50 UTC, catsbi commented on src/main/java/ladder/ui/OutputView.java
> +                    return EMPTY_RUNG_VALUE;
method로 분리해서 Method Reference를 사용해보는것도 좋을 것 같네요 ㅎㅎ

2021-12-11 13:50 UTC, merged