Step4 - 사다리(리팩토링)
next-step/java-ladder pull request #1253
Opened 2021-12-08 10:32 UTC by mizm

안녕하세요 리뷰어님!

힌트에 나온 것들을 적용하기 보다 제 생각에는 제가 한 방식도 나쁘지 않다고 생각해서

getter를 쓴 부분을 최대한 삭제하고 메시지 전달로 변경해보려고 리팩토링 해보았습니다 :)

2021-12-08 14:38 UTC, parkeeseul requested changes
4단계 잘 진행해주셨네요! 👍 
한 가지 소소한 코멘트 남겨두었으니 확인 부탁드릴게요! 😄 
화이팅 입니다! 🔥

2021-12-08 14:38 UTC, parkeeseul commented on src/main/java/nextstep/step2/domain/Line.java
> +    }
코드는 위에서 아래로 자연스럽게 읽히도록 하는 것이 가독성이 좋은데요
메서드의 순서를 move -> findBridge 순서로 개선해보면 어떨까요? 😄 

또한 매개변수의 네이밍을 before 라고 작성해주신 이유가 있을까요? 🤔

2021-12-09 10:15 UTC, mizm commented on src/main/java/nextstep/step2/domain/Line.java
> +    }
클릭해서 들어가다보니 생각못했던 부분이네요 좋은 리뷰 감사합니다.
이동하기 전 위치 -> 이동 후 위치로 말을 적으려다 보니까 before이라고 했는데 코드내에서 뭔가 애매하네요,,
차라리 point라는 명칭이 더 좋은거 같아요 !

2021-12-09 15:19 UTC, parkeeseul approved these changes
소소한 마지막 피드백 잘 반영해주셨네요! 👍 
이만 머지하도록 하겠습니다!
그동안 많은 피드백 반영해주시느라 정말 고생 많으셨어요! 🙏 
남은 미션들도 꼭 완주하셔서 많은 인사이트 얻어가시길 바라요! 
앞으로도 화이팅 입니다 🔥

2021-12-09 15:19 UTC, merged