[Step2] 사다리(생성)
next-step/java-ladder pull request #1259
Opened 2021-12-09 15:17 UTC by sUpniverse

안녕하세요 리뷰어님,,

2단계 처음으로 리뷰 요청합니다.

생각보다 사다리를 이름에 맞추어 그리는데 시간을 많이 허비했네요.

잘부탁드리겠습니다!! 🙇🏻‍♂️

2021-12-10 04:46 UTC, yongdae requested changes
안녕하세요. 문섭님 ~ :)

사다리 미션 2단계를 열심히 진행해주셨네요. 👍 
진행해주신 미션 내용에 대해 리뷰를 진행하였습니다.

확인하시고 다시 리뷰 요청 부탁드릴께요~ 🔥

2021-12-10 04:46 UTC, yongdae commented on src/main/java/nextstep/ladder/LadderApplication.java
> +  public static void main(String[] args) {
<img width="1039" alt="스크린샷 2021-12-10 오후 1 01 06" src="https://user-images.githubusercontent.com/4317804/145515159-524991fb-00a7-485b-a929-2fe685b87051.png">

지금은 사다리의 간격이 좊아보이는데,
기능 요구사항에 따라 사다리 간격을 넓혀보면 좋을 것 같아요. :)

2021-12-10 04:46 UTC, yongdae commented on src/test/java/nextstep/ladder/NameTest.java
> +  void createMoreThan5(String inputName) {
사람 이름 5글자 제한에 대한 테스트를 잘 만들어주셨네요. :)

2021-12-10 04:46 UTC, yongdae commented on src/test/java/nextstep/ladder/PointTest.java
> +class PointTest {
Point를 이용해서 `사다리 타기가 정상적으로 동작하려면 라인이 겹치지 않도록 해야 한다`
이 요구 사항에 대한 테스트를 해볼 수는 없을까요? 🤔

2021-12-10 04:46 UTC, yongdae commented on src/main/java/nextstep/ladder/domain/entity/LadderHeight.java
> +  private static final int ONE = 1;
ONE 대신 MIN_HEIGHT나 MIN_VALUE 같은 이름은 어떤가요?
변수명이 변수 값 자체를 표현하기보다는 어떤 값을 가지고 있는지를 표현하는게 더 좋을 것 같아요

2021-12-10 04:46 UTC, yongdae commented on src/main/java/nextstep/ladder/domain/entity/Line.java
> +  private static final Boolean FALSE = false;
여기에서 사용된 상수의 변수명도 바꿔보면 좋을 것 같아요.

2021-12-10 04:46 UTC, yongdae commented on src/main/java/nextstep/ladder/view/ViewImpl.java
> +  private String printLadder(Names names, Ladder ladder) {
<img width="489" alt="스크린샷 2021-12-10 오후 1 33 10" src="https://user-images.githubusercontent.com/4317804/145517757-74b40823-7f28-45fc-b684-dffc4738c3d0.png">

사다리 게임에 참가한 사람들을 출력하는 부분에 문제가 있는 것 같아요.
main()에서 드린 출력 관련 내용과 연관성을 가지고 있는 부분이네요.

2021-12-10 04:46 UTC, yongdae commented on src/main/java/nextstep/ladder/view/ViewImpl.java
> +    return Symbol.VERTICAL_LINE.getValue().concat(collectPoint).concat(Symbol.VERTICAL_LINE.getValue());
`규칙 4: 한 줄에 점을 하나만 찍는다.`
이 규칙을 적용해보면 좋을것 같아요. :)

2021-12-10 04:46 UTC, yongdae commented on README.md
> +
<img width="787" alt="스크린샷 2021-12-10 오후 1 44 35" src="https://user-images.githubusercontent.com/4317804/145518574-4699b9bd-1f37-4638-98e5-310791eaba38.png">

사다리 미션의 기능 목록을 정리해보면 어떨까요? 🤔

2021-12-10 04:52 UTC, sUpniverse commented on src/test/java/nextstep/ladder/PointTest.java
> +class PointTest {
이부분이 조금 저도 애매한 부분인데 사실 makePointRandomly()이 부분이 private 접근 제한자로 되어있어서 어떻게 테스트를 할 수 있을지가 조금 고민했었는데 차라리 리뷰를 받고 의견을 물어보면 좋을거 같아서 일단 pr을 올렸네요~! 이부분을 public으로 변경하여서 테스트해도 괜찮을까요?

2021-12-10 05:01 UTC, sUpniverse commented on src/main/java/nextstep/ladder/view/ViewImpl.java
> +  private String printLadder(Names names, Ladder ladder) {
이 부분도 현재의 코드에서는 사람의 이름에따라 사다리의 `사람 이름을 5자 기준으로 출력하기 때문에 사다리 폭도 넓어져야 한다.`를 근거로 기준해서 만들고 사실 사다리가 변하기보단 사람의 이름의 간격이 변하는게 구현에 더 적합하다고 생각이 들긴하는데 일단 다시 변경을 해보겠습니다.

2021-12-10 07:54 UTC, sUpniverse commented
리뷰를 반영하여서 수정하였습니다.

car의 movable 구현 때를 다시 생각해보고 길을 만드는 책임을  각 좌표에게 주어 테스트도 가능하도록 했습니다. 리뷰부탁드립니다!!

2021-12-10 14:07 UTC, yongdae requested changes
피드백을 빠르게 반영해주셨네요. 👍 
의견을 주신 내용에 대해 답변을 드렸습니다.

아직은 `라인이 겹치지 않도록 해야 한다.`라는 부분에 대한 검증이 필요해보여요.
그럼 확인하시고 다시 리뷰 요청 부탁드릴께요. :)

2021-12-10 14:07 UTC, yongdae commented on src/test/java/nextstep/ladder/PointTest.java
> +class PointTest {
makePointRandomly는 Line 객체가 가지고 있는 기능이에요.

그리고 makePointRandomly()의 역할은 전략을 전달받아 다음 Point를 만드는 부분이 라고 생각되요.
정말 makePointRandomly()은 `라인이 겹치는 유무를 판별`을 하기에 적합한 기능인가요?

이 의견을 드렸던 이유는 Line보다는 Point를 이용해서
`사다리 타기가 정상적으로 동작하려면 라인이 겹치지 않도록 해야 한다`를 검증해보는 방법에대해 고민해보실 원해서
의견을 드린 부분이였어요.

2021-12-10 14:07 UTC, yongdae commented on src/main/java/nextstep/ladder/domain/entity/Line.java
> +  private void makePointRandomly(int now, BuildStrategy buildStrategy) {
Line을 만드는 부분은 외부로 분리해보면 어떨까요?
Line 생성에 대한 책임을 Line이 가지지 않아도 되고, BuildStrategy과 같은 전략에 대한 의존성도 지울수 있어요. :)

2021-12-10 15:57 UTC, sUpniverse commented
리뷰 다시 반영했습니다.

생성의 책임을 service로 분리하였고

그 중 point만드는 부분에 이전 point를 이용해 `라인이 겹치지 않도록 해야 한다.` 라는 검증을 Point에서 하던것도 
servcie로 분리하였습니다.

2021-12-11 02:16 UTC, yongdae approved these changes
새벽에도 쉼 없이 피드백을 반영해주셨네요. 👍 
그럼 2단계는 여기서 마무리짓고 다음 단계로 넘어가도록 하겠습니다.

진행해주신 내용에 다시 의견을 드린 부분이 있으니
다음 단계에서 같이 반영 부탁드릴께요. 🙇 

수고하셨습니다!

2021-12-11 02:16 UTC, yongdae commented on src/test/java/nextstep/ladder/PointTest.java
> +class PointTest {
Point next(boolean next) {
        if (way && next) {
          throw new IllegalArgumentException();
        }
        return new Point(next);
    }

이런 생성자를 Point 객체에 추가한다면 어떨까요?
Point가 자신의 역할에 더 충실 할 뿐만아리라 `라인이 겹치는 유무를 판별`까지 판별 할 수 있어요.

현재 설계하신 내용은 라인이 겹치지 않기 위한 비지니스를 LadderService가 제공하지만,
LadderService가 없다면 연속으로 라인이 생성 될 수 있어요.

2021-12-11 02:16 UTC, yongdae commented on src/main/java/nextstep/ladder/domain/service/LadderService.java
> +public class LadderService {
사다리 생성에 대한 책임을 분리해주셨네요. 👍

2021-12-11 02:16 UTC, merged

2021-12-13 09:41 UTC, sUpniverse commented on src/main/java/nextstep/ladder/domain/service/LadderService.java
> +public class LadderService {
src/main/java/nextstep/ladder/domain/entity/Point.java

이전 리뷰때 Point에 현재 service에서 진행하는 부분들을 구현했었는데 주신 리뷰를 통해 잘못구현이 된것 같다고 제가 알아듣고 service로의 로직을 외부로 가져왔던건데 다시 구현해 보도록 하겠습니다.