Step4
next-step/java-ladder pull request #1297
Opened 2021-12-21 03:04 UTC by monkeyDugi

질문1
스프링 컨트롤러와 비슷하게 MVC 구조를 대략 만들어 보고 싶어서 Controller에 파라미터가 3개입니다.
그래서 Dto도 만들어 봤습니다.
이 부분은 어떻게 생각 하시나요?

질문2
LadderContext클래스는 클라이언트에서 해당 클래스 외에 다른 클래스는 최대한 인터페이스 하지 않도록 하기 위해 이렇게 하였습니다.
물론 하위 단의 기능을 계속 가져오는 방식이라서 상세 내용은 복잡하지만 사용자 입장에서는 더 편하고, 변경에도 유리하다고 생각이 들어서
해봤습니다.

2021-12-22 23:40 UTC, javajigi requested changes
전체적인 객체 설계와 구현 좋네요. 👍 
특별히 피드백할 내용이 없네요.
바로 merge하려다 아쉬울 것 같아 소소한 피드백 남겨 봅니다.

1. 인자수가 많을 경우 DTO 추가해서 구현한 점 좋다고 생각해요.
2. LadderContext의 경우 모든 메시지를 Ladder에게 위임하고 있어 굳이 필요 없을 수도 있다 생각해요.

2021-12-22 23:40 UTC, javajigi commented on src/main/java/ladder/domain/ladder/Controller.java
> +public class Controller {
이 클래스 이름이 Controller인 이유가 있나?

2021-12-22 23:40 UTC, javajigi commented on src/main/java/ladder/domain/ladder/LadderResult.java
> +    private final Map<String, String> results = new LinkedHashMap<>();
Name 클래스를 추가했는데 `Map<Name, String>`로 구현해 보는 것은 어떨까?

2021-12-23 11:47 UTC, lkimilhol commented on src/main/java/ladder/domain/ladder/Direction.java
> +    int move() {
디폴트로 구성하신 이유가있겠죠?

2021-12-23 11:47 UTC, lkimilhol commented on src/main/java/ladder/domain/ladder/Point.java
> +        return new Point(index + 1, direction.next(current));
이 코드 좋네요 ㅎㅎ

2021-12-23 11:47 UTC, lkimilhol commented on src/test/java/ladder/domain/user/NameTest.java
> +                .hasMessage("이름은 1자 이상 5자 이하로 입력 해주세요");
테스트케이스 라지만 같은 메시지는 String으로 선언하면 어떨까요? ㅎㅎ

2021-12-23 14:51 UTC, bbbnam reviewed
지나가다가 소소하게 남겨봅니다-!

코드가 많이 개선된 거 같아요~!
앞으로도 화이팅입니닷+_+b

2021-12-23 14:51 UTC, bbbnam commented on src/main/java/ladder/domain/ladder/Controller.java
> +    public static ResponseDto readyLadderGame(String participantNames, String inputLadderResult, int ladderHeight) {
아래쪽의 Dto로 파라미터 수를 줄인것처럼 여기도 적용해보는 건 어떨까요?

2021-12-23 14:51 UTC, bbbnam commented on src/main/java/ladder/domain/ladder/Height.java
> +        if (height > MAXIMUM_HEIGHT || height < MINIMUM_HEIGHT) {
if문 안의 조건식을 의미있는 표현으로 나타내 보는 건 어떨까요?

2021-12-23 14:51 UTC, bbbnam commented on src/main/java/ladder/domain/user/Name.java
> +        if (name == null || name.trim().length() < 1 || name.trim().length() > 5) {
이 부분도 조건들이 한눈에 보기 어려우니 의미있는 표현으로 변경해보면 어떨까요?

2021-12-26 01:15 UTC, monkeyDugi commented on src/main/java/ladder/domain/ladder/Direction.java
> +    int move() {
넥텝 과정 피드백 영상에서 최대한 접근 제어자를 닫아두고 필요할 때 열으라는 피드백을 봤어요
장점은 연관없는 패키지에서 남용할 가능성을 줄여 의도치 않은 예외도 줄일 수 있고, 의존성도 줄일 수 있다고 생각해요
실제 실무에서도 전혀 무관한 패키지인데 막 땡겨와서 쓰는 경우가 많았거든요. 그래서 의존성이 엄청났었어요 😁
그래서 이렇게 해봤습니당.

2021-12-26 01:34 UTC, monkeyDugi commented on src/main/java/ladder/domain/ladder/Point.java
> +        return new Point(index + 1, direction.next(current));
넘 어려워서 포비님 코드 뜯어 가면서 봤네요
아마 안봤으면 getIndex()를 사용했을 수도 있을 것 같은데 그랬으면 SRP 위반하면서 클라이언트 마다 다음 포인트를 생성할 때
다른 로직을 가질 위험이 열려있었을 것 같아요. 메시지로 협력하는게 아주 잘된 것 같아요😁

2021-12-26 02:09 UTC, monkeyDugi commented on src/main/java/ladder/domain/ladder/Controller.java
> +public class Controller {
UI에서 파라미터를 받고 Dto도 반환해주기 때문입니다.
스프링에서도 Controller에 파라미터 받고 처리한 값을 반환하는 형식을 생각 했어요🥲

2021-12-27 09:42 UTC, javajigi approved these changes
피드백 반영 잘했네요. 💯 
지금까지 사다리 미션 진행하느라 수고했어요.

2021-12-27 09:42 UTC, merged