2단계 - 사다리(생성)
next-step/java-ladder pull request #1302
Opened 2021-12-22 11:18 UTC by gyuyeol

커밋을 몰아서 하게 되는데 어떻게 하면 좋을까요?

Player를 만들고 커밋 하고 Players를 만들다 보면 Player에 수정이 발생해서 커밋메시지가 제 역할을 못하고 있는게 아닌가 하는 생각이 듭니다.

리뷰어님의 커밋 방식이 궁금합니다~

2021-12-23 00:45 UTC, sah3122 commented
안녕하세요 😄 
저는 클래스 단위로 커밋을 나누기 보다는 기능단위로 커밋을 남기는 편이에요. 
예를 들면 사다리 연결 로직을 하나의 커밋으로 남기고, 사다리 한줄 구현을 하나의 커밋으로 남기곤 합니다 😄

2021-12-23 00:46 UTC, sah3122 requested changes
사다리 생성 미션 잘 구현해주셨네요 👍 
몇가지 생각거리를 남겨두었으니 확인 부탁드려요 !

2021-12-23 00:46 UTC, sah3122 commented on src/main/java/rick/domain/Ladder.java
> +            .forEach(lines::add);
forEach를 활용하기 보다는, collect 메소드를 활용하여 초기화 하는건 어떨까요 ?

2021-12-23 00:46 UTC, sah3122 commented on src/main/java/rick/domain/Line.java
> +    public Line(List<Boolean> points) {
테스트 작성을 위한 프로덕션 코드는 지양하지 않습니다 ㅎㅎ

2021-12-23 00:46 UTC, sah3122 commented on src/main/java/rick/domain/Line.java
> +        }
Point 객체를 만들어 사다리간 연결에 대한 책임을 맡을수 있도록 변경해보는건 어떨까요 ㅎㅎ

2021-12-23 00:46 UTC, sah3122 commented on src/main/java/rick/view/InputView.java
> +}
클래스의 마지막은 new line으로 끝내는것을 권장 드려요.
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2021-12-23 00:46 UTC, sah3122 commented on src/main/java/rick/view/ResultView.java
> +    //    public void drawResult(int playerCount, int ladderHeight, LadderLines ladderLines) {
현시점에서 사용하지 않는 코드는 과감하게 삭제해보세요 😄

2021-12-23 00:46 UTC, sah3122 commented on src/main/java/rick/view/ResultView.java
> +    }
이번 과정을 진행하면서 메소드의 depth는 2까지만 허용하고 그 이상이 필요한 경우 메소드를 분리해보세요. 
추가로 if - else 의 사용은 금지입니다 😄

2021-12-23 00:46 UTC, sah3122 commented on src/main/java/rick/domain/Ladder.java
> +public class Ladder {
테스트 코드가 필요해보여요 !

2021-12-23 12:44 UTC, gyuyeol commented on src/main/java/rick/view/ResultView.java
> +    }
리팩토링 하면서 바꿔야지 했다가 안바꿨네요 수정하였습니다~

2021-12-23 12:45 UTC, gyuyeol commented on src/main/java/rick/domain/Ladder.java
> +public class Ladder {
테스트 코드를 같이 커밋 하지 않았네요; 코드리뷰 반영하면서 수정하여 커밋하였습니다.

2021-12-23 12:47 UTC, gyuyeol commented on src/main/java/rick/domain/Line.java
> +        }
Point 객체를 만들었습니다.

한 라인에서 연속되는 이동 가능한 Point 확인에 대한 책임은  Line에 생성 시 검사 하도록 하였고
PointCreationStragey를 LineCreationStragey롤 바꿔 이 안에서 연속되는 이동가능한 포인트가 없는 배열을 반환하도록 수정하였습니다.

2021-12-23 12:49 UTC, gyuyeol commented
코드 리뷰 사항을 반영하였습니다.

Point 객체를 추가하였습니다.
PointCreationStrategy를 LineCreationStrategy로 변경하고 이동가능한 포인트가 연속되지 않는 리스트를 반환하도록 리팩토링 하였습니다.

2021-12-24 15:33 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
간단한 생각거리 하나 남겨드렸는데 다음 미션을 진행하기전에 확인 부탁드려요 🙏

2021-12-24 15:33 UTC, sah3122 commented on src/main/java/rick/domain/Line.java
> +    }
마찬가지로 들여쓰기는 2까지만 허용해주세요 !

2021-12-24 15:33 UTC, sah3122 commented on src/main/java/rick/domain/Point.java
> +public class Point {
Point객체 도출 👍

2021-12-24 15:33 UTC, sah3122 commented on src/main/java/rick/strategy/RandomLineCreationStrategy.java
> +public class RandomLineCreationStrategy implements LineCreationStrategy {
반드시 필요한 클래스 도출인지 고민해보시면 좋을것 같아요. 
해당 클래스에서 제공하는 기능들이 Line의 역할이 되어야 한다면 클래스 분리 보다는 메소드로 나타내는것이 직관적이며 복잡도를 낮출수 있을것 같습니다 😄

2021-12-24 15:34 UTC, merged

2021-12-25 05:31 UTC, gyuyeol commented on src/main/java/rick/strategy/RandomLineCreationStrategy.java
> +public class RandomLineCreationStrategy implements LineCreationStrategy {
이전 Point의 값에 따라 다음 Point의 값이 제약되기 때문에 (true 다음 연속해서 true 일 수 없음) 규칙을 지켜서 라인을 생성하는 Point를 한 번에 만들 주는 클래스를 분리하기로 하였습니다. 이후 단계 진행에 막히는 부분이 없다면 이대로 진행하고 변경이 필요하다면 수정하겠습니다 감사합니다~!