[Min-92] Step3 구현, 코드리뷰 반영
next-step/java-ladder pull request #1378
Opened 2022-05-15 17:52 UTC by Min-92

### Step 3 구현 내용
- Step -> Point 변경
  - 사다리 따라 이동하기 편한 구조로 변경
- 불필요한 일급컬렉션(Rows) 제거
- reward 추가
- 사다리 타기 기능 구현
- 결과 출력 추가

### 코드리뷰 반영
- 테스트에서만 사용되는 메소드 삭제
- 메소드 명 변경
- 결과 출력 toString 활용

2022-05-16 10:53 UTC, yongdae requested changes
민재님! 이전 단계 피드백을 포함해서 3단계 미션을 멋지게 잘 수행해주셨네요. 
큰 틀에서는 의견 드릴 부분이 없이 멋지게 만들어주셨다고 생각해요!! 💯

소소하지만 몇 가지 의견을 남겨놓았습니다.
확인하시고 다시 리뷰 요청 부탁드릴께요. 🙇 

수고하셨습니다!!! 🔥

2022-05-16 10:53 UTC, yongdae commented on src/main/java/ladder/app/LadderGame.java
> +    private Ladder ladder;
`규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.`
이 규칙을 적용해 볼 수 있을 것 같아요. :)

2022-05-16 10:53 UTC, yongdae commented on src/main/java/ladder/domain/ladder/Row.java
> +public class Row {
Line과 같은 이름을 써보는 것도 괜찮지 않을까요? 🤔

2022-05-16 10:53 UTC, yongdae commented on src/main/java/ladder/domain/ladder/Row.java
> +    }
사다리를 만드는 책임을 별도의 객체로 만들어서 분리시켜보면 어떨까요? 🤔

2022-05-16 10:53 UTC, yongdae commented on src/main/java/ladder/domain/point/Point.java
> +    public Point next() {
next() 메서드를 통해 `다음`지점을 잘 만들어 주셨네요. 👍

2022-05-16 10:53 UTC, yongdae commented on src/main/java/ladder/domain/point/Point.java
> +    public boolean isRight() {
isRight도 접근제한자를 private으로 바꾸어보면 어떨까요?

2022-05-18 14:54 UTC, Min-92 commented on src/main/java/ladder/domain/point/Position.java
> +    private final int position;
요거는 바꿀만한 부분을 잘 못찾았네요ㅠ 어딜 어떻게 바꾸면 좋을지 알 수 있을까요

2022-05-18 19:32 UTC, Min-92 commented on src/main/java/ladder/domain/ladder/Row.java
> +    }
생성하는 책임은 클래스 자신이 가지고 있는게 맞다고 생각해서 설계를 했습니다.
다른 좋은 방법이 있을까요?

2022-05-19 08:16 UTC, yongdae approved these changes
의견 드렸던 부분들을 많이 고민해서 반영해주셨네요. 💯 
그럼 이번 스텝은 여기서 마무리 짓고 다음 단계로 넘어가도록 하겠습니다!

진행해주신 내용에 대해서는 몇 가지 의견을 추가로 드렸습니다.
이 부분은 다음 단계에서 같이 반영 부탁드릴께요!! 😄 

수고 많으셨습니다. 🙇

2022-05-19 08:16 UTC, yongdae commented on src/main/java/ladder/domain/ladder/Line.java
> +    public int width() {
접근제한자를 private으로 바꾸면 좋을 것 같아요.

2022-05-19 08:16 UTC, yongdae commented on src/test/java/ladder/domain/ladder/LadderTest.java
> +    void trace는_position을_사다리를_따라서_이동된_위치를_반환한다() {
테스트 코드가 이전보다 깔끔해졌다고 생각해요.
이제는 쉽게 사다리의 결과를 알 수 있어요. 😄

2022-05-19 08:16 UTC, yongdae commented on src/main/java/ladder/domain/ladder/LadderGame.java
> +        return rewards.findByPosition(
사다리의 게임의 결과를 `Map<Position: 시작, Position: 끝>`로 만들어두었다가
보상(Reward)을 꺼내어 보면 어떨까요?

2022-05-19 08:16 UTC, merged

2022-05-21 07:37 UTC, Min-92 commented on src/main/java/ladder/domain/ladder/LadderGame.java
> +        return rewards.findByPosition(
Map을 구현하는 의도는 성능을 위한 걸까요?

이전 미션 진행하면서 결과 도출 과정에서 성능을 위한 코드를 만들어야 하는가에 대해서 포비한테 질문드린적이 있습니다.
성능에 큰 영향을 끼치는 부분이 아니라면 굳이 성능을 따지지 않아도 좋다는 답변을 받았고,
저 또한 강의 주제(클린코드)에 맞는 코드를 추구하는게 좋을것 같다는 생각이 들어서 map대신 stream처럼 간결한 코드를 사용한 부분입니다 :)

2022-05-29 13:56 UTC, yongdae commented on src/main/java/ladder/domain/ladder/LadderGame.java
> +        return rewards.findByPosition(
의견을 드렸던 부분은 성능과는 상관없이
play(게임 실행)와 게임 결과 반환을 분리해보는 것을 목표로 이야기 드렸던 부분이에요 ~ :)