Step2 - PR
next-step/java-ladder pull request #1409
Opened 2022-05-23 04:25 UTC by hahoho87

안녕하세요! 백경윤입니다!
사다리미션 step2 PR 입니다

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/2f78169f-13c3-41b8-80ca-2fc971d1c019/Untitled.png)

구현하고 몇 번 돌려보니, 이런식으로 가로 라인이 없는 사다리가 종종 만들어지는데, 
사다리가 이렇게 만들어져도 되는건지 잘 모르겠네요ㅠㅠ

따끔한 피드백 부탁드리겠습니다!

2022-05-23 15:05 UTC, yongdae requested changes
안녕하세요. 경윤님!!
사다리 미션 2단계를 잘 진행해주셨네요. 👍 

이전 단계 피드백을 포함해서 사다리 게임 설계를 깔끔하게 잘 만들어주셨네요.

진행해주신 부분에 대해 소소하게 몇 가지 의견을 드렸습니다.
확인하시고 다시 리뷰 요청 부탁드릴께요. 😄

2022-05-23 23:56 UTC, hahoho87 commented on src/main/java/ladder/domain/Ladder.java
> +        return lines;
![image](https://imgur.com/AObkuNx)

찾아보니 UnmodifiableList 라는 읽기만 가능한 불변 리스트 객체가 있었네요!
덕분에 처음 알게 되었습니다.

말씀하신대로 Line 과 Participant 는 생성 후 변경되면 안되기 때문에
생성할 때 불변 리스트로 만들어주는게 맞다고 보입니다!👍

2022-05-26 03:06 UTC, hahoho87 commented on src/main/java/ladder/domain/Line.java
> +    public Integer numberOfPoints() {
테스트코드에서 
```java
assertThat(line.getPoints.size()).isEqualTo(width);
```
로 작성해놓고 디미터 법칙에 위배되는거 같아 한 번 감쌌는데,
테스트 코드에서만 사용되는지 체크를 못했네요:joy:
이렇게 테스트 코드에서만 검증을 위해 쓰인 경우는 그냥 위 코드처럼 작성해도 괜찮을까요??

2022-05-26 03:08 UTC, hahoho87 commented on src/test/java/ladder/domain/DirectionTest.java
> +class DirectionTest {
`PointTest` 클래스에서 이전 point 와 연결되지 않는 부분만 검증을 해서 이전 point 로부터 연결되는 선이 생기는 부분에 대해서도 테스트 추가했습니다!

2022-05-26 03:14 UTC, hahoho87 commented on src/main/java/ladder/domain/Participant.java
> +    }
테스트에서만 검증을 위해 사용되고 있고, participant 를 출력하기 위해 toString 을 재정의 했기 때문에 `getName()` 을 없애고 테스트에서도 `toString()` 을 사용하도록 변경해봤습니다!

2022-05-26 05:02 UTC, hahoho87 commented
안녕하세요! 리뷰 반영해봤습니다.
사다리의 생성과 활용의 분리 측면에서 `LadderGenerator` 클래스를 생성했는데, 
그리고 나니 `Ladder` 클래스의 활용이 애매해진 것 같습니다.
물론 추후에 사다리 게임을 진행한다는 걸 알고 있으니 해당 클래스를 활용할 수 있겠지만, 현재는 상태와 getter 만 가진 클래스가 된 것 같아서 이렇게 나누는게 맞는지 잘 모르겠습니다ㅠㅠ

그리고 객체지향적인 측면에서 getter 을 통해 가져오지 말고 메시지를 던져야 한다는 걸 알고는 있는데, 익숙치 않다보니 많이 어렵네요ㅠㅠ..

그럼 아낌없는 피드백 부탁드리겠습니다!

2022-05-26 08:47 UTC, yongdae approved these changes
의견 드린 부분을 열심히 반영해주셨네요. 👍 

이번 단계는 여기서 마무리하도록 하겠습니다.
리뷰 드린 내용은 다음 단계에서 같이 반영부탁드릴께요~ 🔥 

추가로 작업하신 일을 하나의 단위로 커밋하는 연습을 해보신다면 더 좋을 것 같아요!

수고하셨습니다. 🙇

2022-05-26 08:47 UTC, yongdae commented on src/main/java/ladder/domain/Ladder.java
> +public class Ladder {
<img width="478" alt="스크린샷 2022-05-26 오후 5 26 32" src="https://user-images.githubusercontent.com/4317804/170449659-fba05d47-b8a4-480a-9d37-835ed9f2120c.png">

사다리 게임 진행 때문에 의견을 드렸던 부분은 아니에요. :)

이야기 주신 것처럼 Ladder가 애매해질 수도 있지만
클래스 이름만으로 어떤 역할 하는지 혹은 설계 의도를 알려 줄 수 있다고 생각하면 어떨까요?

2022-05-26 08:47 UTC, yongdae commented on src/main/java/ladder/domain/Line.java
> +    public Integer numberOfPoints() {
네 지금 단계에서는 괜찮다고 생각합니다.

2022-05-26 08:47 UTC, yongdae commented on src/main/java/ladder/domain/Point.java
> +    }
static이 나쁜건 아니지만 유지 보수 측면에서 [유리하지 않은 코드](https://kellis.tistory.com/127)를 양산합니다.
이 부분에 대해서는 어떻게 생각하시나요? 🤔

2022-05-26 08:47 UTC, yongdae commented on src/main/java/ladder/domain/Direction.java
> +    public Direction(boolean isLeft, boolean isRight) {
isLeft와 isRight가 false인 경우 예외를 발생하게 해본다면 어떨까요?
Direction만으로 `라인은 겹칠 수 없다`라고 테스트로 검증 해 볼 수 있어요.

그리고 Point에서 값을 판별해서 Direction을 만든다면
Point의 비지니스에 따라 선이 겹칠 수 있는 문제가 생기지 않을까요?

2022-05-26 08:47 UTC, yongdae commented on src/main/java/ladder/domain/Direction.java
> +    private final boolean isRight;
변수의 이름에 is를 사용해야 하는 이유가 있나요?

2022-05-26 08:47 UTC, yongdae commented on src/main/java/ladder/domain/LadderGenerator.java
> +                .collect(Collectors.collectingAndThen(Collectors.toList(), lines -> new Ladder(lines, participants)));
👍

2022-05-26 08:47 UTC, yongdae commented on src/main/java/ladder/domain/LadderGenerator.java
> +    public Ladder createLadder(Participants participants, int height) {
Participants를 받지 않고 width를 처음부터 받는다면 Participants에 대한 의존성을 줄일 수 있을 것 같아요. :)

2022-05-26 08:47 UTC, merged