Step2 사다리(생성)
next-step/java-ladder pull request #1465
Opened 2022-10-08 18:35 UTC by Wordbe

리뷰 부탁드립니다 :)

간단하게 도메인 로직을 정리하면 아래와 같습니다.
- 사다리 사이에 가로로 난 길을 horizontalWay 이라고 정의했습니다.
- 사다리를 한 라인 기준으로 가로로 순회면서 
  - 이전에 horizontalWay가 있으면 다음은 horizontalWay 가 만들어지지 못합니다.
  - 없다면 50% 확률로 으로 생성됩니다.
- Ladder 는 height 개의 Line 들의 집합입니다.

2022-10-09 07:57 UTC, seokhongkim requested changes
성호님, 사다리 게임 2단계 미션 잘 구현해주셨습니다. 👍 

도메인이 UI에 의존하지 않도록 구현해주신 점과 클래스 분리를 통해 책임을 나눠서 구현하신 점이 좋았습니다. 코멘트로 간단히 설명해주셔서 코드를 이해하기도 쉬웠네요.

조금 더 고민해보시면 좋을 것 같은 부분이 있어 코멘트 남겼습니다.
도메인에 필요한 값 객체 추가, 테스트 코드 작성과 관련된 부분입니다. :) 코멘트 확인 부탁드립니다. 🙏 

코멘트 보시고 궁금한 점이나, 함께 이야기 해보면 좋을 내용이 있다면 깃헙 코멘트 또는 슬랙 DM으로 편하게 말씀 부탁드립니다. 😀

2022-10-09 07:57 UTC, seokhongkim commented on README.md
> +## Step2 사다리(생성)
기능 요구사항 잘 정리해주셨네요! 👍 
마크다운 문법 중 체크리스트를 사용하여 구현이 완료되었음을 나타내보면 어떨까요?

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/Main.java
> +    public static void main(String[] args) {
도메인이 UI에 의존하지 않도록 잘 분리해주셨습니다. :)

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/view/InputView.java
> +    private static final String NAMES_QUESTION = "참여할 사람 이름을 입력하세요. (이름은 쉼표(,)로 구분하세요)";
적절한 상수 사용 좋습니다. 👍

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/view/InputView.java
> +    private static String validateName(String name) {
`name` 에 대한 규칙을 관리하는 값 객체를 만들어보는 건 어떨까요?

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/view/InputView.java
> +                .map(InputView::validateName)
값을 검증하기 위해 `map` 함수를 사용하는 것은 동작은 기대한 방식으로 동작하지만, 적절한 사용은 아니라고 생각됩니다.

`map` 함수는 스트림을 다른 스트림으로 변경(`map`)하기 위한 목적인데 메소드 호출을 위해 오용되고 있는 것은 아닐까요? 이를 위해 `validateName` 이라는 메소드도 밸리데이션만 하는 것이 아닌, 값을 반환하는 형태로 구현된 것은 아닐까요?

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/view/InputView.java
> +        Scanner scanner = new Scanner(System.in);
`Scanner` 리소스가 계속 생성되고 사용을 마친 이후에도 종료되지 않을 것 같아요.
try with resources 문법을 사용해보면 어떨까요?

이름을 가져오는 부분과 높이를 가져오는 부분이 나뉘어 있어서 `System.in` 리소스 종료 시 문제가 발생할 여지가 있는데, 이런 부분을 고려하여 리소스를 닫지 않으신 것인지 궁금합니다. :)

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/view/ResultView.java
> +                    .collect(joining(BAR, " ".repeat(FIXED_NAME_LENGTH - 1) + BAR, BAR));
`" ".repeat(FIXED_NAME_LENGTH - 1) + BAR` 부분이 사다리의 시작점이고, 매번 같은 값이 사용되니 상수로 분리해보면 더 코드를 이해하기 쉬울 것 같아요!

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/view/ResultView.java
> +        return " ".repeat(FIXED_NAME_LENGTH);
`HORIZONTAL_WAY` 는 `FIXED_NAME_LENGTH` 만큼 `-` 가 생성되어야 할 것 같고, 빈 구간인 경우 ` `(공백)이 `FIXED_NAME_LENGTH` 만큼 생겨야겠네요.
공백과 `HORIZONTAL_WAY` 모두 `FIXED_NAME_LENGTH` 에 의존성이 있으니, 이를 이용해서 미리 만들어놓으면 어떨까요?

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/view/ResultView.java
> +    private static String fixedName(String name) {
`String.format` 함수를 사용해보면 어떨까요?
> https://stackoverflow.com/questions/13475388/generate-fixed-length-strings-filled-with-whitespaces

2022-10-09 07:57 UTC, seokhongkim commented on src/test/java/ladder/domain/LadderTest.java
> +}
파일 마지막에 `newline` 이 없다고 또 경고를 띄워주네요 😢 
설정을 통해 파일 마지막의 `newline` 을 강제해보면 어떨까요?

2022-10-09 07:57 UTC, seokhongkim commented on src/test/java/ladder/domain/RandomLineFactoryTest.java
> +class RandomLineFactoryTest {
`horizontalWays` 에 아무런 값도 저장하지 않아도 테스트가 성공할 것 같아요.
즉, `[false, false, false, false, ..., false]` 인 경우에도 성공할 것 같습니다.
난수에 의해 적절하게 사다리가 만들어지는지 테스트해보려면 어떻게 하면 좋을까요?

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/domain/RandomLineFactory.java
> +public class RandomLineFactory implements LineFactory {
인터페이스를 분리하고 구현체를 추가해서 테스트하기 수월한 구조를 만드신 것 같아요.
사다리가 잘 만들어지는지 테스트를 추가해보면 어떨까요?

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/domain/RandomLineFactory.java
> +    private Boolean nextLane(List<Boolean> newLanes, int i) {
이전 라인에 `horizontalWays` 가 있는지 여부만 전달하면, 메소드의 인자 개수를 줄일 수 있지 않을까요?
이 메소드는 이전 가로줄의 존재 여부에 따라, 다음 가로줄에 대한 생성 여부만 반환해주면 될 것 같아서요. :)

2022-10-09 07:57 UTC, seokhongkim commented on src/main/java/ladder/view/InputView.java
> +        if (name.length() > 5) {
`5` 도 의미를 가진 상수로 보여요. 상수로 관리해보면 어떨까요?
그리고 이 값이 변경되면 `ResultView` 에서 관리하는 값과 함께 변경되어야 할 것 같네요!

2022-10-09 10:39 UTC, Wordbe commented on src/test/java/ladder/domain/LadderTest.java
> +}
![스크린샷 2022-10-09 19 39 01](https://user-images.githubusercontent.com/40506736/194752138-b0573098-0ae0-4c97-a4f3-8bb8875f3b55.png)

설정 저장했습니다 :)

2022-10-09 11:17 UTC, Wordbe commented on src/main/java/ladder/view/InputView.java
> +                .map(InputView::validateName)
위에서 말씀하신 값객체를 만드는 것으로 해결이 되네요. 이 부분 수정했습니다 감사합니다

2022-10-09 12:20 UTC, Wordbe commented on src/main/java/ladder/view/InputView.java
> +        Scanner scanner = new Scanner(System.in);
리소스 해제를 고려하지 못했습니다.
try with resource 구문 사용해서 다시 만들어보았습니다.

2022-10-09 12:38 UTC, Wordbe commented on src/main/java/ladder/view/ResultView.java
> +        return " ".repeat(FIXED_NAME_LENGTH);
반영했습니다 :)

2022-10-09 12:49 UTC, Wordbe commented on src/main/java/ladder/domain/RandomLineFactory.java
> +    private Boolean nextLane(List<Boolean> newLanes, int i) {
코드가 심플해지고 좋네요 감사합니다 !!

2022-10-09 13:46 UTC, Wordbe commented on src/test/java/ladder/domain/RandomLineFactoryTest.java
> +class RandomLineFactoryTest {
RandomFactory 생성해서 수정해보았습니다 :)

2022-10-09 13:47 UTC, Wordbe commented on src/main/java/ladder/domain/RandomLineFactory.java
> +public class RandomLineFactory implements LineFactory {
사다리가 잘 만들어지고 있는지는 LadderTest 에 구현했었습니다!

2022-10-10 06:08 UTC, seokhongkim approved these changes
성호님, 2단계 미션 피드백 잘 반영해주셨습니다. 💯 

2단계 PR은 이만 머지하도록 하겠습니다.
코멘트 조금 남긴 부분은 3단계 미션 진행하실 때 참고 부탁드립니다. 🙏 

3단계 미션에서 뵙겠습니다. 😀

2022-10-10 06:08 UTC, seokhongkim commented on src/main/java/ladder/domain/LineFactory.java
> +    Line create(Integer personCount);
`Integer` wrapper type 을 사용하신 이유가 있을까요? personCount 가 nullable 한 값은 아닐 것 같은데, wrapper type 을 사용하신 이유가 있는지 궁금합니다.

2022-10-10 06:08 UTC, seokhongkim commented on src/main/java/ladder/domain/RandomLineFactory.java
> +    private Boolean nextBridges(Boolean existsPreviousBridge) {
`Boolean` 도 wrapper type 을 사용하신 이유가 있는지 궁금합니다. :)

2022-10-10 06:08 UTC, seokhongkim commented on src/main/java/ladder/view/InputView.java
> +    public InputView() {
`InputView` 에서 값을 읽은 후 바로 반환하는 형태로 구현해보면 어떨까요?
`names`, `height` 를 이용하여 `InputView` 가 수행하는 로직은 없는데, 값만 가지고 있는 것으로 보입니다.
두 값을 반환하기 위해 DTO를 사용해봐도 좋겠네요!

2022-10-10 06:08 UTC, seokhongkim commented on src/main/java/ladder/view/ResultView.java
> +        return String.format("%s%s ", " ".repeat(Name.MAX_LENGTH - 1 - nameLength), name.name());
`String.format("%5s")` 를 학습하고 적용해보면 어떨까요? :)
위의 분기를 포함해 모두 처리할 수 있을 것으로 보입니다.

hint: 5라는 숫자는 해당 문자열의 minimal width 입니다.
> https://stackoverflow.com/questions/13475388/generate-fixed-length-strings-filled-with-whitespaces

2022-10-10 06:08 UTC, seokhongkim commented on src/test/java/ladder/domain/LadderTest.java
> +        assertThat(ladder).isEqualTo(new Ladder(List.of(line, line)));
사다리 생성 테스트 좋습니다. 👍

2022-10-10 06:08 UTC, merged

2022-10-10 07:33 UTC, Wordbe commented on src/main/java/ladder/domain/LineFactory.java
> +    Line create(Integer personCount);
통일하기 위해서 될수있으면 wrapper 타입 사용했었습니다.
말씀하신 부분이 일리가 있어서 primitive 타입으로 수정하겠습니다. :)

2022-10-10 07:33 UTC, Wordbe commented on src/main/java/ladder/domain/RandomLineFactory.java
> +    private Boolean nextBridges(Boolean existsPreviousBridge) {
이 부분도 수정하겠습니다 :)

2022-10-10 08:57 UTC, Wordbe commented on src/main/java/ladder/view/ResultView.java
> +        return String.format("%s%s ", " ".repeat(Name.MAX_LENGTH - 1 - nameLength), name.name());
제안해주신대로라면, 아래와 같이 고칠 수 있을 것 같은데요
```java
private static String formattedName(Name name) {
        return String.format("%" + Name.MAX_LENGTH + "s", name.name());
```

문제에서 제시된 포맷에 대해 의아한점이 있습니다.
```
pobi  honux crong   jk // (1) 문제에서 이렇게 나와있음
 pobi honux crong    jk // (2) 위와 같이 코드 실행 후 결과. (이대로 사용하는게 더 규칙적이고, 보기도 좋음)
```

제 질문은 (1) 처럼 문제에 나와있는 요구사항 대로 하려면 분기로직이 필요할 것 같은데,
말씀해주신대로 String.format 으로 분기를 모두 포함해 처리할 수 있을까요?

2022-10-11 01:14 UTC, seokhongkim commented on src/main/java/ladder/view/ResultView.java
> +        return String.format("%s%s ", " ".repeat(Name.MAX_LENGTH - 1 - nameLength), name.name());
말씀해주신대로 `String.format` 만 사용하면 포맷이 문제에 나와 있는 것과 정확히 일치하지 않네요!
길이가 5인 경우와 그렇지 않은 경우(`"%4s "`)를 나눠서 처리해야 요구사항을 정확히 만족할 수 있겠네요. 😢

2022-10-11 12:28 UTC, Wordbe commented on src/main/java/ladder/view/ResultView.java
> +        return String.format("%s%s ", " ".repeat(Name.MAX_LENGTH - 1 - nameLength), name.name());
이 부분은 `"%5s"` 로 통일하는게 실제로 출력할 때 보기좋아보이네요. 실제코드에서는 기획을 조금 바꿔서 `%5s` 로 반영해보겠습니다.