Step2 : 2단계 - 사다리(생성)
next-step/java-ladder pull request #1471
Opened 2022-10-10 15:08 UTC by codeleesh

안녕하세요 리뷰어님,

강아지 좋아하시나요?ㅎㅎ 감사합니다.

2단계 - 사다리(생성) 리뷰 요청드립니다.

개인적으로 레이싱카, 로또 보다도 어려운 미션이였습니다.
아쉬운 부분은 enum 활용을 통해 `Direction`과 `Movement` 객체가 하나로 합쳐질 수 있을것 같은데 진행하지 못하였습니다.
리뷰를 받고 개선해볼 예정입니다.

그럼, 소중한 리뷰 부탁드립니다.

감사합니다.

2022-10-11 13:03 UTC, vagabond95 requested changes
사다리게임이 확실히 난이도가 높은 편이죠 😭 

Ladder - Line - Point 순으로 각 계층간 구분, 스스로 해야할 역할을 잘 구분지어 주신 것 같아요!
그외 구현해주신 내용에 대해 코멘트 남겼는데, 확인 후 리뷰요청 부탁드리겠습니다 :)

2022-10-11 13:03 UTC, vagabond95 commented on src/main/java/nextstep/ladder/domain/Direction.java
> +    RIGHT, DOWN, LEFT
좌,우   와  아래의 방향성은 같은 방향이지만 다른 성질을 가지고 있으므로 (좌/우는 제약 존재, 아래는 제약 존재하지 않음) 같은 enum 으로 묶는 것이 적절한지 고민해보시면 좋을 것 같아요!

2022-10-16 06:50 UTC, codeleesh commented on src/main/java/nextstep/ladder/domain/LadderCreator.java
> +    public Ladder start() {
네 사다리 생성의 시작이라는 느낌을 주려고 했는데 명확하지 않는것 같습니다.

사다리의 라인 생성을 요청하여서 사다리 생성을 진행하니 `create` 로 변경해보도록 하겠습니다!

2022-10-16 06:52 UTC, codeleesh commented on src/main/java/nextstep/ladder/domain/ParticipationName.java
> +        return Arrays.stream(name.split(REGEX_COMMA))
입력값의 대한 처리 부분이 사실 고민이 되긴 했었는데요, 컨트롤러까지 필요한 어플리케이션이 아니다보니 
입력값의 대한 익셉션 처리 부분은 각 객체에서 책임을 갖도록 진행하였습니다.

그래서 이 부분도 View의 역할보다는 객체에서 처리하는 것이 맞다고 생각을 하게 되었습니다.

2022-10-16 07:49 UTC, codeleesh commented on src/main/java/nextstep/ladder/domain/LineCreator.java
> +        final Point point = Point.first(Movement.first(generate()));
네 장점으로는 하나의 Point에서 역할을 수행하기 때문에 로직 관리가 한곳에서 이루어지게 됩니다.
단점으로는 Point의 많은 책임이 느껴지게 되는것 같습니다.

단점으로 인하여 Point의 많은 책임이 생겨나게 될것 같아서 Movement로 분리를 하게 되었습니다.

한번 합쳐보도록 하겠습니다!

2022-10-16 14:36 UTC, codeleesh commented
안녕하세요 리뷰어님
리뷰 주신 내용 반영하여서 요청드렸습니다. 
소중한 코드 리뷰 부탁드립니다.

감사합니다.

2022-10-17 08:11 UTC, vagabond95 approved these changes
리뷰 드렸던 사항을 꼼꼼히 반영해주셨네요!

리뷰 내용에 대한 생각을 남겨주신 부분도 좋았습니다 :) 얘기 주신 부분에 대해 크게 이견은 없습니다!
2단계는 추가로 리뷰드릴 사항이 보이지 않아 머지하도록 하겠습니다~!

2022-10-17 08:11 UTC, merged