Step3 : 3단계 - 사다리(게임 실행)
next-step/java-ladder pull request #1503
Opened 2022-10-18 15:27 UTC by codeleesh

안녕하세요, 리뷰어님

3단계 미션으로 찾아뵙게 되었습니다.

3단계 미션을 진행하면서 2단계때 진행한 사다리 라인 그리는 부분에 버그가 있어서 관련 부분도 같이 수정하였습니다.

사다리 순수 결과(번호)과 최종 결과(참가자에 해당하는 상품)를 나누어서 처리하는 것에 대해서 고민을 하였는데,

DTO로 분리하여서 화면에서 사용할 수 있도록 처리하였습니다.

그럼, 소중한 리뷰 부탁드립니다.

감사합니다.

2022-10-19 10:54 UTC, vagabond95 requested changes
3단계 마무리 하시느라 고생 많으셨습니다!

구현해주신 내용에 대해 몇가지 리뷰 남겼는데, 확인 부탁드릴게요!

2022-10-19 10:54 UTC, vagabond95 commented on src/main/java/nextstep/ladder/domain/LadderWinningResult.java
> +    private static void process(final Map<Integer, Integer> ladderResult, final Line line, final int row) {
메소드 이름이 너무 모호한것 같아요. process 라는 이름은 어떠한 로직이 들어가도 대부분 그럴듯하기 때문에 2개이상의 역할을 하는 메소드가 될 확률이 높아지지 않을까요?

2022-10-19 10:54 UTC, vagabond95 commented on src/main/java/nextstep/ladder/domain/LadderWinningResult.java
> +    private static void process(final Map<Integer, Integer> ladderResult, final Line line, final int row) {
또한 process 를 비롯하여 이를 구성하는 로직들이 LadderWinningResult 클래스에 위치하는게 적절한지도 고민해보면 좋을 것 같아요.

결과로 LadderWinningResult 를 만들긴하지만, LadderWinningResult 클래스의 상태를 직접 이용한다기보다 필요한 도메인 모델들을 적절히 명령하고 조합하는 과정이 진행되므로 Controller 의 역할에 가깝지 않을까요?

2022-10-19 10:54 UTC, vagabond95 commented on src/main/java/nextstep/ladder/view/ResultView.java
> +        if ("all".equals(name)) {
"all" 값이 여러부분에서 사용되는 것 같은데, 상수로 선언하여 관리해보는 것은 어떨까요?

2022-10-19 10:54 UTC, vagabond95 commented on src/main/java/nextstep/ladder/dto/LadderWinningResultDto.java
> +public class LadderWinningResultDto {
Dto 클래스를 잘활용해주신 것 같아요 👍

2022-10-19 14:02 UTC, codeleesh commented on src/main/java/nextstep/ladder/view/ResultView.java
> +        if ("all".equals(name)) {
네 상수로 뺴서 관리해보겠습니다!

2022-10-19 14:41 UTC, codeleesh commented on src/main/java/nextstep/ladder/domain/LadderWinningResult.java
> +    private static void process(final Map<Integer, Integer> ladderResult, final Line line, final int row) {
네 맞습니다. 그래서 DTO로 분리를 하긴 했는데, 어쩔수 없이 `LadderWinningResult` 에서 convert가 필요하였어요..

해당 결과를 알맞게 사용하기 위해서 관련 책임을 DTO로 분리한다면 좋을것 같습니다.

2022-10-19 14:45 UTC, codeleesh commented
안녕하세요 리뷰어님,

리뷰 주신 내용 수정하여서 다시 요청드립니다.

`LadderWinningResult` 를 사용하지 않고 DTO에서 변환 및 화면에서 사용할 수 있도록 제공하는 것이 좋을것 같아서 그렇게 변경하였습니다.

그럼, 소중한 리뷰 부탁드립니다.

감사합니다.

2022-10-25 08:00 UTC, vagabond95 requested changes
일주일이나 경과되어 많이 기다리셨을 것 같습니다 😭 

DTO 와 관련하여 같이 생각해보고 싶은 부분이 있어서 코멘트 남겼는데 확인 부탁드려요!

2022-10-25 08:00 UTC, vagabond95 commented on src/main/java/nextstep/ladder/dto/LadderWinningResultDto.java
> +    private static void verify(final Map<Integer, Integer> ladderResult, final Line line, final int row) {
LadderWinningResult 가 제거됨으로써 좀 더 각 클래스의 역할이 명확해진 것 같아요!

다만, 한가지 추가로 고민해보면 좋을 점은 DTO 클래스는 의미 그대로 계층간 데이터 전달을 위한 역할을 가지고 있는데요.
이러한 역할에 빗대어 봤을 때 저는 DTO 클래스에서 getter 외의 로직은 최대한 지양해야한다는 생각을 가지고 있습니다.

현재는 verify 일 뿐이지만, 이러한 코드가 씨앗이 되어 다른 비즈니스 로직이 추가되기 싶고 그렇게 될 경우 해당 클래스는 DTO 보다는 또다른 도메인 클래스에 가까워지는 것 같아서요 ㅎㅎ

이 부분에 대해서 어떻게 생각하실지 의견 들어보고 싶습니다!

2022-10-25 16:55 UTC, codeleesh commented on src/main/java/nextstep/ladder/dto/LadderWinningResultDto.java
> +    private static void verify(final Map<Integer, Integer> ladderResult, final Line line, final int row) {
네 사실 이 부분에 대한 고민이 참 많았는데요, 

저는 화면에 노출되는 부분은 변경사항이 일어날 수 있기 때문에 비즈니스 로직과 같이 있게 된다면 잦은 수정 사항이 발생할 수 있다고 생각하고 있습니다.

그렇기에, 사다리의 최종 결과는 화면에 노출시키기 위한 영역이라서 현재 출력을 담당하는 `ResultView` 에 위치해야 한다는 생각이었지만 DTO를 통해서 해당 부분을 처리하는 것이 자연스럽다고 느껴졌습니다.

물론, 관련 로직이 늘어날 수 있는 여지도 충분히 있겠지만 출력용으로 한정지어서 사용한다면 가능할것으로 보여집니다.

혹시 리뷰어님의 생각은 어떠신가요?

2022-10-27 23:30 UTC, codeleesh commented
안녕하세요 리뷰어님
문의주신 내용에 답변 추가하였습니다.
추가로 리뷰어님 의견도 듣고 싶습니다!

2022-10-30 07:29 UTC, vagabond95 commented on src/main/java/nextstep/ladder/dto/LadderWinningResultDto.java
> +    private static void verify(final Map<Integer, Integer> ladderResult, final Line line, final int row) {
현재는 출력용으로 만들어졌더라도, 추후에 발생할 변경의 방향성에 대해 강제를 시키기는 어려우므로 저는 비즈니스로직을 모두 빼는 것이 맞다는 의견입니다!

2022-10-30 07:31 UTC, vagabond95 approved these changes
제가 독감이 걸려 리뷰가 많이 딜레이되어 죄송합니다 ㅜㅜ

DTO 에 대한 저의 생각을 추가로 남겼고, 해당 단계에서 중요한 문제는 아니라고 생각되어 머지 진행하도록 하겠습니다!

2022-10-30 07:31 UTC, merged