Step03 사다리(게임 실행)
next-step/java-ladder pull request #1506
Opened 2022-10-19 16:46 UTC by hiblue02

리뷰 요청드립니다 : )

2022-10-24 17:15 UTC, lxxjn0 requested changes
혜영님, 리뷰가 늦어져서 죄송합니다 ㅠㅠ

전체적으로 코드를 짜임새있게 잘 짜주셔서 간단한 부분에 대해서 피드백 남겨두었습니다!! 한번 확인해보고 피드백 반영 부탁드릴게요 :)

2022-10-24 17:15 UTC, lxxjn0 commented on src/main/java/laddergame/domain/Ladder.java
> +    }
저는 보통 필드와 동일한 타입을 파라미터로 받을 경우에는 생성자를, 다른 타입을 받아서 내부적으로 로직을 가지면서 가공을 거쳐서 생성을 하는 경우에는 정적 팩토리 메서드를 사용합니다. 팩토리 메서드라는 네이밍 자체가 무언가를 가공해서 생성하는 역할을 가지고 있는 것으로 느껴져서요!!

이렇게 생성하는 로직 내부에서 특정한 가공이 일어나냐/아니냐에 따라서 사용하는 생성 메서드를 다르게 가져가면 전체적인 코드를 작성하고 유지할 때 도움이 되더라구요. 이 부분은 한번 참고해보시면 좋을 것 같아서 피드백 남겨두었습니다!!

2022-10-24 17:15 UTC, lxxjn0 commented on src/main/java/laddergame/domain/Ladder.java
> +    public int getResultIndex(int index) {
이 부분도 저 같은 경우에는 getter에만 get 네이밍을, 그 외에는 find와 같은 다른 용어를 사용하곤 합니다!!

2022-10-24 17:15 UTC, lxxjn0 commented on src/main/java/laddergame/domain/Line.java
> +        if (Boolean.TRUE.equals(values.get(0))) {
기존 코드도 충분히 이해하기 쉬웠던 것 같은데 이렇게 수정한 이유가 있을까요?

2022-10-24 17:15 UTC, lxxjn0 commented on src/main/java/laddergame/domain/Rewards.java
> +    }
Reward는 보상을 입력한 값들을 관리하는 객체로 보여지는데 People 객체를 받아서 유효성을 관리하는 부분이 조금 어색한 것 같아요!! 해당 유효성 검증이 꼭 Rewards에서 일어나야만 하는건지, Rewards라는 객체의 비즈니스 유효성 검증 로직이 맞는지 한 번 더 고민해보면 좋을 것 같아요!!

제가 생각하기엔 단지 입력을 받아온 시점에서 검증해야 하는 부분이 아닐까 싶기도 하네요.

2022-10-24 17:15 UTC, lxxjn0 commented on src/main/java/laddergame/domain/service/LadderGame.java
> +        result.put(personName, rewards.getReward(ladder.getResultIndex(people.getIndex(personName))));
메서드 내부에 너무 여러개의 메서드가 중복되어서 호출되니 오히려 가독성을 해치고 있어요. 적절하게 변수로 추출한다면 가독성을 높일 수 있습니다.

2022-10-24 17:15 UTC, lxxjn0 commented on src/main/java/laddergame/view/OutputView.java
> +        rewards.getRewards().forEach(n -> stringBuilder.append(lpad(n.toString())));
해당 부분도 변수로 추출해서 가독성을 개선하면 좋을 것 같아요!!

2022-10-24 17:15 UTC, lxxjn0 commented on src/main/java/laddergame/controller/LadderGameController.java
> +        OutputView.printResult(ladderGame.getResult(new PersonName(wantResult)));
지금의 로직도 예제처럼 결과를 출력하고 싶은 사람을 여러번 입력받을 수 있나요?

2022-10-24 17:15 UTC, lxxjn0 commented on src/main/java/laddergame/domain/Ladder.java
> +    }
유효성 검증이 들어간다면 모든 line의 사이즈가 동일한지에 대해서 생성 후 유효성 검증을 하는 것도 좋을 것 같아요!! 이런 부분은 도메인의 특성 상 꼭 확인이 되어야 하는 부분이라는 생각도 드네요!! 👍🏼

2022-10-25 13:27 UTC, hiblue02 commented on src/main/java/laddergame/domain/Ladder.java
> +    }
👍

2022-10-25 13:28 UTC, hiblue02 commented on src/main/java/laddergame/domain/Ladder.java
> +    public int getResultIndex(int index) {
👍

2022-10-25 13:57 UTC, hiblue02 commented on src/main/java/laddergame/domain/Line.java
> +        if (Boolean.TRUE.equals(values.get(0))) {
아.. 인텔리제이에서 경고 메세지가 뜨길래 맞춰서 수정해봤습니다.. ㅎㅎㅎ ;;;;

2022-10-25 14:08 UTC, hiblue02 commented on src/main/java/laddergame/domain/Rewards.java
> +    }
네! 검증 로직을 어디에 넣을까 고민하다가... 로직 흐름 상에 맞춰 집어넣었는데요. 조언데로 수정했습니다. 감사합니다! : )

2022-10-25 15:02 UTC, hiblue02 commented on src/main/java/laddergame/controller/LadderGameController.java
> +        OutputView.printResult(ladderGame.getResult(new PersonName(wantResult)));
여러 번 입력할 수 있도록 수정했습니다!

2022-10-27 10:56 UTC, lxxjn0 approved these changes
혜영님, 피드백 반영하시느라 수고 많으셨습니다!! 👍🏼 

앞서 코드 구조를 예쁘게 잘 짜두셔서 리팩토링도 수월하게 잘 진행된 것 같아요!! 따로 피드백 드릴만한 부분이 없는 것 같아서 이번 단계는 여기서 마무리하도록 할게요!! 다음 단계 진행해주세요 :)

2022-10-27 10:56 UTC, lxxjn0 commented on src/main/java/laddergame/domain/Line.java
>      }
이 부분은 개인적인 의견인데 파라미터로 받는 두 값으로 얻는 values를 통해 Line을 생성을 한다면 굳이 정적 팩토리 메서드로 만들지 않고 Line 생성자의 파라미터로 `painter.draw(numberOfPerson)`을 넘겨줘도 괜찮을 것 같아요!!

2022-10-27 10:56 UTC, merged