Step2 - 사다리(생성)
next-step/java-ladder pull request #1517
Opened 2022-10-22 17:30 UTC by snt2525

안녕하세요!
2단계 사다리 생성 리뷰도 잘 부탁드립니다.
감사합니다 😊

2022-10-28 17:01 UTC, lxxjn0 requested changes
남희님, 미션 구현하시느라 수고 많으셨습니다!! 👍🏼 

아직은 사다리를 그리기만 하는 미션이라 간단하게 몇 가지만 피드백 남겨두었는데 한 번 확인해보시고 반영해주세요 :)

추가로 리뷰어 페이지에 문제가 있었던건지 남희님 리뷰가 어제까진 안보였는데 오늘 갑자기 생겼네요 ㅠㅠ 리뷰가 조금 늦어진 것 같아 죄송합니다 🙇🏼‍♂️

2022-10-31 01:13 UTC, snt2525 commented on src/main/java/ladder/model/Player.java
> +        this.name = Optional.of(name)
찾아보니 반환 타입으로의 사용을 권장하는군요.. 해당 로직 수정해두겠습니다~!

2022-10-31 01:16 UTC, snt2525 commented on src/main/java/ladder/model/Direction.java
> +    private final boolean left;
지금 현재는 사용되지 않지만.. 다음 레벨에서의 사용 가능성으로 미리 만들어 둔 값입니다. 다음 레벨에서도 사용되지 않게 되면 제거하겠습니다^^;

2022-10-31 01:17 UTC, snt2525 commented on src/main/java/ladder/model/LadderLine.java
> +    private List<Point> pointList;
아하 points로 명 수정해 두었습니다:)

2022-10-31 01:31 UTC, snt2525 commented on src/main/java/ladder/model/LadderLine.java
> +    }
생성된 point 값들은 리턴해주고 create메소드에서 add를 해주는 것이 더 깔끔해보이는군요. 수정해두겠습니다:)

2022-11-01 18:26 UTC, lxxjn0 approved these changes
남희님, 피드백 반영하시느라 수고 많으셨습니다!!

추가로 코드 수정할 부분이 없어보여요!! 다음 단계 진행하시면 될 것 같습니다!! 👍🏼

2022-11-01 18:27 UTC, merged