1단계 - 자바8 스트림, 람다, Optional
next-step/java-ladder pull request #1524
Opened 2022-10-24 13:14 UTC by Yunsik-Choi

안녕하세요 리뷰어님 사다리타기 미션 동안 잘 부탁드립니다 🙇‍♂️

## 람다
- [x] CarTest의 MoveStrategy에 대한 람다를 적용
- [x] Lambda의 sumAll, sumAllEven method 람다를 활용해 중복 제거

## 스트림
- [x] StreamStudyTest 클래스의 sumOverThreeAndDouble() 테스트를 pass해야 한다.
- [x] StreamStudy 클래스의 printLongestWordTop100() 메서드를 구현한다.

## Optional
- [x] Optional을 활용해 ageIsInRange2() 메소드에 구현
- [x] Users의 getUser() 메소드를 자바 8의 stream과 Optional을 활용해 구현
- [x] ExpressionTest의 테스트가 통과하도록 Expression의 of 메소드를 구현

## 추가
- [x] ComputerStore 클래스의 getVersionOptional 메소드 구현

ps. 1단계 문서에 ComputerStore 내용이 빠진것 같아요!

2022-10-24 23:34 UTC, seokhongkim requested changes
윤식님 안녕하세요!
사다리타기 미션을 함께 할 리뷰어 김석홍입니다. 만나서 반갑습니다. 😀 

먼저 제보해주신 `ComputerStore` 관련 내용은 전달했습니다. 제보해주셔서 감사합니다 🙇 

1단계 미션 잘 진행해주셨고, 요구사항도 PR에 정리해주셔서 이해하기 좋았습니다.
조금 더 고민해보시면 좋을 것 같은 부분을 코멘트로 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-10-24 23:34 UTC, seokhongkim commented on src/main/java/nextstep/fp/Conditional.java
> +@FunctionalInterface
`@FunctionalInterface` 를 이용하여 명시적인 함수형 인터페이스임을 작성해주신 것 좋습니다. 👍

2022-10-24 23:34 UTC, seokhongkim commented on src/main/java/nextstep/fp/Lambda.java
> +    public static int sumAll(List<Integer> numbers, Conditional c) {
lambda 로 변경하는 작업 잘 해주셨습니다. 👍 
`sumAll` 이 오버로딩 되는 형태로 구현되었는데, 메소드명은 한번 고민해보셔도 좋겠습니다. :)

2022-10-24 23:34 UTC, seokhongkim commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .distinct()
`distinct` 이후에 소문자로 변환되어 중복이 걸러지지 않는 상황이 있을 수 있겠네요.

2022-10-24 23:34 UTC, seokhongkim commented on src/main/java/nextstep/fp/StreamStudy.java
>          // TODO 이 부분에 구현한다.
주석은 삭제해주셔도 좋을 것 같습니다. :)

2022-10-24 23:34 UTC, seokhongkim commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .sorted(Comparator.comparingInt(word -> -word.length()))
긴 순서로 정렬해야 하니, 역순 정렬이 필요하지 않을까요?

2022-10-24 23:34 UTC, seokhongkim commented on src/main/java/nextstep/fp/StreamStudy.java
>  }
파일 마지막에 newline 이 없다고 경고를 띄워주네요.
파일 마지막의 newline 은 왜 필요할까요?

2022-10-24 23:34 UTC, seokhongkim commented on src/main/java/nextstep/optional/ComputerStore.java
> +                .map(c -> c.getSoundcard())
method reference 를 사용해보셔도 좋겠습니다. :)

2022-10-24 23:34 UTC, seokhongkim commented on src/main/java/nextstep/optional/Expression.java
> +//    static Expression of(String expression) {
사용하지 않는 코드는 주석 처리하지 말고 제거해보면 어떨까요?

2022-10-24 23:34 UTC, seokhongkim commented on src/main/java/nextstep/optional/User.java
> +                .map(u -> u.getAge())
여기도 method reference 로 변경해보시면 좋겠습니다!

2022-10-24 23:34 UTC, seokhongkim commented on src/main/java/nextstep/optional/Users.java
> +        return users.stream().filter(user -> user.matchName(name))
stream 메소드 체인을 사용할 때 한 줄에 메소드 호출을 작성하신 이유가 있을까요?

2022-10-25 01:28 UTC, Yunsik-Choi commented
안녕하세요 석홍님!
코멘트 달아주신 부분들 리팩토링 했습니다!
리뷰 부탁드립니다!

### 공통
- [x] 주석 제거
- [x] method reference 사용
### Lambda
- [x] Lamba sumAll 오버로딩 메서드명 변경
### Stream
- [x] StreamStudy printLongestWordTop100 소문자 변환 위치 변경
- [x] StreamStudy printLongestWordTop100 reversed() 적용
### war-and-peace.txt
- [x] 마지막 newline 제거

2022-10-25 01:29 UTC, Yunsik-Choi commented on src/main/java/nextstep/optional/Users.java
> +        return users.stream().filter(user -> user.matchName(name))
stream()이 간단한 역할이라 filter까지 한 줄로 읽는 것이 편하다고 생각했었는데 줄을 변경하는 것도 좋을 것 같네요!

2022-10-25 01:30 UTC, Yunsik-Choi commented on src/main/java/nextstep/fp/StreamStudy.java
>  }
실수로 추가된 것 같습니다 😅

2022-10-25 01:30 UTC, Yunsik-Choi commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .sorted(Comparator.comparingInt(word -> -word.length()))
문자열 길이를 음수로 변환하여 역순 정렬하였는데 가독성이 좋지 않은 것 같아 reversed()를 적용했습니다!

2022-10-25 09:25 UTC, seokhongkim commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .sorted(Comparator.comparingInt(word -> -word.length()))
음수로 변환해서 정렬을 하셨군요! 제가 잘못봤네요. 😅 
말씀하신 것처럼 `reversed` 를 사용하면 더 명시적으로 잘 보일 것 같습니다 👍

2022-10-25 09:29 UTC, seokhongkim approved these changes
윤식님, 1단계 미션 피드백 잘 반영해주셨습니다! 💯 

1단계 PR은 이만 머지하도록 하겠습니다.
파일 마지막의 newline 문자열에 대해서는 더 찾아보시면 좋을 것 같아 코멘트를 추가로 남겼습니다.

2단계 미션에서 뵙겠습니다. 😀

2022-10-25 09:29 UTC, seokhongkim commented on src/main/java/nextstep/fp/Lambda.java
> +    public static int sumAllByConditional(List<Integer> numbers) {
이 메소드의 이름도 함께 변경된 것 같습니다. :)

2022-10-25 09:29 UTC, seokhongkim commented on src/main/java/nextstep/fp/StreamStudy.java
>  }
이와 같은 내용을 참고해보시면 좋겠습니다. :)
> https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2022-10-25 09:29 UTC, merged