2단계 - 사다리(생성)
next-step/java-ladder pull request #1546
Opened 2022-10-30 10:18 UTC by yeonsuyang

@FunctionalInterface 에 대해 공부해보았습니다. 감사합니다!

2022-10-30 14:30 UTC, choihz requested changes
안녕하세요, 연수님!

구현해 주신 내용을 확인하고 몇 가지 코멘트를 남겨 두었습니다. 궁금한 점이나 의견이 있으실 땐 부담 없이 코멘트나 DM 주세요~

2022-10-30 14:30 UTC, choihz commented on src/main/java/step2/domain/Users.java
> +    public List<String> names;
`names` 값을 `public`으로 열어 `ResultView`에서 이를 직접 참조하고 있는데요, 이렇게 했을 때 발생할 수 있는 문제점에 대해 고민해 볼까요? 접근 제어자에 대해서도 함께 학습해 보시면 더욱 좋을 것 같고요.

2022-10-30 14:30 UTC, choihz commented on src/main/java/step2/domain/Line.java
> +    public final List<Boolean> isLine;
의미를 이해하기 몹시 어려운 이름으로 느껴집니다. `is`로 시작하는 네이밍은 주로 `boolean`을 리턴하는 **메서드**에서 사용돼요. [Bool 변수 이름 제대로 짓기 위한 최소한의 영어 문법](https://soojin.ro/blog/naming-boolean-variables)과 [자바에서의 필드 네이밍 규칙](https://google.github.io/styleguide/javaguide.html#s5.2.5-non-constant-field-names)을 참고해 보시면 좋을 것 같아요.

2022-10-30 14:30 UTC, choihz commented on src/main/java/step2/domain/Users.java
> +        if (name.length() > 5) {
여기서의 매직 넘버는 특정 의미를 담고 있기 때문에 상수로 추출해 주면 좋을 것 같아요.

2022-10-30 14:30 UTC, choihz commented on src/main/java/step2/domain/Users.java
> +                .forEach(name -> validateNames(name));
꼭 스트림을 사용해야 할까요? [Stream의 foreach 와 for-loop 는 다르다.](https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/)를 읽어 보아요.

2022-10-30 14:30 UTC, choihz commented on src/main/java/step2/domain/Ladder.java
> +    private int height;
변하지 않는 값이라면 `final` 키워드를 붙여도 좋겠네요.

2022-10-30 14:30 UTC, choihz commented on src/main/java/step2/view/InputView.java
> +    public static final String HEIGHT_INPUT_TEXT = "\n최대 사다리 높이는 몇 개인가요?";
`\n`은 항상 개행을 보장하지 않습니다. 관련하여 학습해 볼까요?

2022-10-30 14:30 UTC, choihz commented on src/main/java/step2/view/InputView.java
> +    }
숫자가 아닌 문자 또는 0과 음수 같이 사다리를 생성할 수 없는 숫자가 입력되면 어떻게 하고 있나요?

2022-10-30 14:30 UTC, choihz commented on src/main/java/step2/domain/Users.java
> +    }
<img width="378" alt="스크린샷 2022-10-30 오후 11 25 20" src="https://user-images.githubusercontent.com/18049492/198883866-44c6c374-d482-4a3b-9754-35b104e4c2da.png">

5자를 넘지만 않으면 되나요?

2022-10-30 14:30 UTC, choihz commented on src/main/java/step2/domain/Ladder.java
> +    }
<img width="201" alt="스크린샷 2022-10-30 오후 11 26 55" src="https://user-images.githubusercontent.com/18049492/198883967-a67ea1a6-cf2e-4503-8012-85342a86e7b1.png">

이렇게 양쪽으로 연결된 사다리가 존재해도 되나요?

2022-10-30 14:30 UTC, choihz commented on src/main/java/step2/domain/Ladder.java
> +    public void createLadderGame(int userCounts) {
사다리 "게임"을 생성하고 있나요?

2022-10-30 14:30 UTC, choihz commented on src/test/java/step2/domain/LadderTest.java
> +}
<img width="163" alt="스크린샷 2022-10-30 오후 11 29 05" src="https://user-images.githubusercontent.com/18049492/198884067-8615aa02-f170-4d7c-aa67-a455ab4b164f.png">

GitHub에서 이런 경고를 띄우는 이유와 이를 해결할 방법을 찾아 볼까요?

2022-10-31 14:45 UTC, yeonsuyang commented on src/main/java/step2/domain/Ladder.java
> +    }
앗 요구사항을 잘못 읽었네요 반영하였습니다.

2022-10-31 14:46 UTC, yeonsuyang commented on src/main/java/step2/domain/Line.java
> +    public final List<Boolean> isLine;
해당 칸이 라인을 가지고 있는지를 보관한다는 의미로 hasLine으로 변경하였습니다.

2022-10-31 14:46 UTC, yeonsuyang commented on src/main/java/step2/domain/Users.java
> +    public List<String> names;
final을 빼먹었네요, final을 붙혀 외부에서 수정할 수 없도록 변경하겠습니다.

2022-11-01 11:49 UTC, choihz approved these changes
안녕하세요, 연수님!

수정해 주신 내용을 확인하고 몇 가지 코멘트를 더 남겨 두었습니다. 다음 단계를 진행하며 함께 확인해 주세요~

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/domain/Line.java
> +    public final List<Boolean> hasLine;
사실 `is`나 `has`나 동사이긴 마찬가지이지요. 제가 첨부해 드렸던 링크를 보면 필드 이름에 대해 아래와 같이 설명하고 있습니다. (보통 명사 또는 형용사 등을 사용해요)

> These names are typically nouns or noun phrases. For example, `computedValues` or `index`.

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/domain/Line.java
> +    public final List<Boolean> hasLine;
또한 인스턴스 변수를 `public`으로 열어 테스트 코드와 `ResultView`에서 직접 참조하고 있는데요, 혹시 접근 제어자의 개념, 그리고 캡슐화에 대해 학습해 보셨을까요?

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/domain/Users.java
> +    }
사소하긴 하지만, "이름들"을 검증하고 있는 것은 아니네요 🙂

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/view/InputView.java
> +    public static final String HEIGHT_INPUT_TEXT = System.lineSeparator()+"최대 사다리 높이는 몇 개인가요?";
```suggestion
    public static final String HEIGHT_INPUT_TEXT = System.lineSeparator() + "최대 사다리 높이는 몇 개인가요?";
```

컨벤션에 항상 신경 써 주세요!

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/view/InputView.java
> +    public static final String NAME_SEPARATOR = ",";
여기서도 전체적으로 접근 제어자 확인해 주세요~

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/view/ResultView.java
> +    public static final int REPEAT_COUNT = 5;
여기서도 역시, 상수의 이름과 접근 제어자, 그리고 컨벤션 확인 부탁드려요.

2022-11-01 11:49 UTC, choihz commented on src/test/java/step2/domain/LadderTest.java
> +    void 사다리_사이즈가_맞게_생성되었는지_라인수는_사람수_마이너스1() {
테스트 이름도 조금 더 읽기 쉽게, 맥락을 파악하기 쉽게 작성해 주시면 좋을 것 같아요.

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/domain/Ladder.java
> +    public static final String HEIGTH_EXCEPTION = "사다리의 높이는 1이상이어야 합니다.";
이름에 오타가 있네요.

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/domain/Ladder.java
> +    public final List<Line> lines;
```suggestion
    public static final String HEIGTH_EXCEPTION = "사다리의 높이는 1이상이어야 합니다.";

    private final int height;
    public final List<Line> lines;
```

상수와 인스턴스 변수 사이에는 한 줄을 띄워 주는 것이 좋습니다.

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/LadderGameMain.java
> +        ladder.createLadder(users.getUserCounts());
`Ladder` 객체를 생성한 후 `createLadder()` 메서드를 호출해야만 사다리가 완성되는 구조인데요, 만약 객체 생성 후 해당 메서드 호출을 잊어버리면 어떻게 될까요? 또는 이미 호출한 것을 잊고 다시 호출하게 되면요?

이렇듯 실수를 유발하기 쉬운 구조는 최대한 막는 것이 좋겠죠. 어떻게 개선할 수 있을까요?

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/view/ResultView.java
> +    public static void printLadderGame(Users users, Ladder ladder) {
사다리 "게임"을 출력하고 있나요?

2022-11-01 11:49 UTC, choihz commented on src/main/java/step2/view/InputView.java
> +    }
<img width="382" alt="스크린샷 2022-11-01 오후 8 41 01" src="https://user-images.githubusercontent.com/18049492/199225005-302b6697-e22a-4a7a-90ed-126e39c5aee7.png">

😱

2022-11-01 11:49 UTC, choihz commented on README.md
> +# step2 요구사항
수정해 주신 내용을 f6bd1b2e 와 같이 단 하나의 커밋으로 반영해 주셨는데, 이렇게 하면 나중에 변경 이력을 확인하고 이해하기가 몹시 어려워져요. 어색하시더라도 각 변경을 따로 커밋하며 적절한 메시지를 작성하는 연습을 해 보시는 것을 추천해 드리고 싶어요.

2022-11-01 11:51 UTC, merged

2022-11-02 09:29 UTC, yeonsuyang commented on src/main/java/step2/domain/Line.java
> +    public final List<Boolean> hasLine;
안녕하세요 같이 첨부해주신 [[Bool 변수 이름 제대로 짓기 위한 최소한의 영어 문법]((https://soojin.ro/blog/naming-boolean-variables) https://soojin.ro/blog/naming-boolean-variables)] 을 참고하였는데요. bool변수도 These names are typically nouns or noun phrases. For example, computedValues or index. 해당 문구를 따른다면, 위 링크의 bool 변수 이름 추천에 대한 내용을 모두 비추천 하신다는 뜻인가요?

2022-11-02 09:37 UTC, yeonsuyang commented on src/main/java/step2/domain/Line.java
> +    public final List<Boolean> hasLine;
객체 final키워드를 사용하거나 privated으로 수정해서 getter사용 추천한다고 강의를 들었는데요~ resultView에서 출력해야 하는 경우 private + getter를 사용하기를 더 추천하시는건가요?

2022-11-02 09:50 UTC, yeonsuyang commented on src/main/java/step2/domain/Ladder.java
> +    public static final String HEIGTH_EXCEPTION = "사다리의 높이는 1이상이어야 합니다.";
![image](https://user-images.githubusercontent.com/46802360/199458483-a27c1c88-ccdc-48ce-8b61-3da3189d0aa5.png)

어떤 오타인지 이해를 하지 못하였습니다!

2022-11-02 09:57 UTC, yeonsuyang commented on src/main/java/step2/view/ResultView.java
> +    public static void printLadderGame(Users users, Ladder ladder) {
이름과 , 사다리를 통틀어 사다리게임이지 않을까요? 결과는 사다리게임의결과이고 그렇게 생각하였습니다.

2022-11-02 18:21 UTC, yeonsuyang commented on src/main/java/step2/domain/Line.java
> +    public final List<Boolean> hasLine;
List는 final로 해도 add를 할 수 있기때문에 제대로된 캡슐화가 되지않음을 이해하였습니다~

2022-11-03 03:14 UTC, yeonsuyang commented on src/main/java/step2/domain/Line.java
> +    public final List<Boolean> hasLine;
list들은 final,private만으로는 캡슐화가 되지않음을 이해하였습니다. 해당내용은 반영하겠습니다. 숫자나 텍스트타입의 경우의견이 궁금합니다.