🚀 Step3  - 사다리(게임 실행)
next-step/java-ladder pull request #1548
Opened 2022-10-30 14:08 UTC by o3ozzvb

안녕하세요. 리뷰어님.
2단계 피드백 반영 및 3단계 사다리 게임 실행 구현하였습니다.

피드백 부탁드립니다.
감사합니다!

2022-10-31 10:04 UTC, csh0034 requested changes
3단계 각 클래스를 역할에 맞게 잘 분리해주셨네요 👍

다만 아쉬운점은 이전단계 첫 리뷰요청때와 같이 컴파일 에러가 
발생하는점과 도메인이 ui 에 의존하고 있는부분이 있습니다. 😭 
commit 전에 확인해주시면 좋을것 같아요.

추가로 몇가지 코멘트 남겨두었는데 확인후에 다시 리뷰요청
부탁드려요!

2022-10-31 12:10 UTC, o3ozzvb commented
실행까지 하고 커밋을 하였는데 컴파일 오류가 있네요 ㅠㅠ 앞으로 잘 확인하여 커밋하도록 하겠습니다..!
코멘트 다시 읽어보고 피드백 반영하였습니다. 

질문 1 ) Random 객체를 매번 생성하지 않을 수 있는 방법이 어떤 게 있을까요?..

질문 2 ) 도메인이 ui 에 의존하고 있는 부분이 있다고 하셨는데... 어디일까요?..

2022-10-31 16:28 UTC, csh0034 approved these changes
코멘트 잘 반영해주셨네요 👍 

몇가지 코멘트만 남겨드리고 이번 단계는
머지하도록 하겠습니다. 

마지막 단계도 화이팅입니다 😄

2022-10-31 16:28 UTC, csh0034 commented on src/main/java/ladder/domain/Ladder.java
> +        List<Line> lines = new ArrayList<>();
스트림을 사용하여 하단과 같이 표현해볼수도 있겠네요!

```java
return Stream.generate(() -> Line.of(width - 1))
    .limit(height)
    .collect(Collectors.collectingAndThen(Collectors.toList(), Ladder::new));
```

2022-10-31 16:28 UTC, csh0034 commented on src/main/java/ladder/domain/Ladder.java
> +    private final List<Line> lines;
클래스 구성요소 순서에 맞게 배치해보면 좋을것 같습니다.

1. 상수(클래스 변수)
2. 인스턴스 변수
3. 생성자
4. 정적팩토리 메서드
5. 인스턴스 메서드

2022-10-31 16:28 UTC, csh0034 commented on src/main/java/ladder/domain/Ladder.java
>          return lines;
반환덴 컬렉션에 대해 수정을 할 수 없도록 Unmodifiable Collection 를 적용해보면 좋을것 같습니다.

[방어적복사 vs Unmodifiable Collection](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/)

2022-10-31 16:28 UTC, csh0034 commented on src/test/java/ladder/utils/LadderUtils.java
> +public class LadderUtils {
이러한 테스트를 위해 세팅된 데이터를 `Test fixture` 라고 합니다.

따라서 저는 fixture 를 세팅해두는 클래스를 Fixtures 라고 명명하여 사용하고 있습니다.

2022-10-31 16:28 UTC, csh0034 commented on src/main/java/ladder/domain/Ladder.java
> +        List<Point> points = lines.get(row).getPoints();
객체를 꺼내와서 비교하기보다 Line 에게 메세지를 보내서 처리하도록 하면 좋을것 같습니다.

2022-10-31 16:28 UTC, csh0034 commented on src/main/java/ladder/LadderApplication.java
>      public static void main(String[] args) {
과정을 진행할땐 이전 미션에서의 프로그래밍 요구사항들도 적용이 필요합니다.

하단의 요구사항을 지켜보면 좋을것 같아요!
`함수(또는 메소드)의 길이가 15라인을 넘어가지 않도록 구현한다.`

2022-10-31 16:29 UTC, merged

2022-11-01 14:23 UTC, o3ozzvb commented on src/main/java/ladder/domain/LadderGame.java
> +    public LadderGame() {
final 원소를 갖는 클래스의 기본 생성자는 어떻게 선언할 수 있을까요?

2022-11-01 15:14 UTC, csh0034 commented on src/main/java/ladder/domain/LadderGame.java
> +    public LadderGame() {
물론 필드가 final 이기 때문에 기본생성자를 추가하려면 null 또는 값을 반드시 세팅해야합니다.

제 질문의 의도는 LadderGame 을 생성할때 Names 와 Results 가 null 이라면 완전하지 않은 상태인데
이러한 완전하지 않은 상태의 객체를 기본 생성자를 추가하여 만들어야 하는 이유가 있는지 여쭤보는거였습니다 😄