2단계 - 사다리(생성)
next-step/java-ladder pull request #1557
Opened 2022-11-01 02:03 UTC by nhs219

안녕하세요.
2단계 리뷰 부탁드립니다.
팩토리 패턴을 처음 써봐서 많이 부족합니다 😭😭
지적 많이 해주세요 ㅎㅎ
감사합니다😊😊

2022-11-01 11:21 UTC, pkch93 requested changes
안녕하세요 희선님 ㅎㅎ
2단계 잘 구현해주셨네요 ㅎㅎ 몇가지 피드백 드렸는데 한번 확인부탁드릴께요.
궁금하신 점 있으시면 DM이나 코멘트 남겨주세요!

2022-11-01 11:21 UTC, pkch93 commented on src/main/java/nextstep/ladder/OutputView.java
> +                .forEach(p -> System.out.print(p + TAB));
```suggestion
person.getPerson()
                .forEach(p -> System.out.print(p + TAB));
```
List를 forEach 하는 경우는 stream 없이 가능해요~

2022-11-01 11:21 UTC, pkch93 commented on src/main/java/nextstep/ladder/RandomLadderFactory.java
> +        if (point > 0 && points.get(point - 1)) {
이부분이 처음 봤을때 이해하기 어려웠는데요. if문 내에 조건에 이름을 붙여주면 어떨까요?

2022-11-01 11:21 UTC, pkch93 commented on src/main/java/nextstep/ladder/Person.java
> +    List<String> person = new ArrayList<>();
person 변수는 Person 클래스 내부에서만 사용하는데 package 레벨로 열어두신 이유가 있을까요?

2022-11-01 11:21 UTC, pkch93 commented on src/main/java/nextstep/ladder/Person.java
> +    List<String> person = new ArrayList<>();
그리고 List로 정의하신만큼 복수형으로 변수명을 표현하면 어떨까요?

2022-11-01 11:21 UTC, pkch93 commented on src/main/java/nextstep/ladder/Person.java
> +public class Person {
`사다리 게임에 참여하는 사람에 이름을 최대5글자까지 부여할 수 있다.` 라는 요구사항이 있는데요. 체크하는 로직이 보이지 않는데 혹시 누락일까요? 테스트에서도 체크되지 않는걸로 봐서는 누락으로 보이네요.

2022-11-02 01:54 UTC, nhs219 commented on src/main/java/nextstep/ladder/LadderFactory.java
> +public abstract class LadderFactory {
factory 패턴이 제대로 머릿속에서 정리되지 않은 상태에서 개발하다보니, 패턴 이해를 잘 못했습니다. interface로 수정하였습니다.😂

2022-11-02 01:55 UTC, nhs219 commented
리팩토링 하면서 패키지 분리를 해보았는데, 맞게 한 건지 잘 모르겠습니다.😭 좋은 패키지 구조가 있다면 가이드 부탁드립니다!

2022-11-03 10:00 UTC, pkch93 approved these changes
희선님~ 피드백 반영 잘 해주셨네요 감사합니다 😄 
이번 단계는 여기서 마무리해도 될 거 같아요. 하나 질문 남긴게 있는데 한번 확인해주시면 좋겠어요.

그리고 패키지 관련해서 질문 남겨주셨는데 희선님께서 왜 지금과 같이 패키지를 나누셨는지도 함께 알려주시면 의견 나누는데 좀 더 도움이 될거 같습니다 :)

2단계는 머지할께요 ㅎㅎ

2022-11-03 10:00 UTC, pkch93 commented on src/main/java/nextstep/ladder/domain/Person.java
> +public class Person {
Person 안에서는 여러 참가자들을 다루는걸로 보이네요 ㅋㅋ 좀 더 적절하게 클래스 네이밍이 되면 어떨까요?

2022-11-03 10:00 UTC, pkch93 commented on src/main/java/nextstep/ladder/factory/LadderFactory.java
> +public interface LadderFactory {
인터페이스로 수정해주셨네요. 😃 다만 지금 LadderFactory를 추상화할 필요가 있을지에 대해 의문이 들었었는데요. 혹시 추상화를 하신 이유가 있을까요?

2022-11-03 10:00 UTC, merged