2단계 - 사다리(생성)
next-step/java-ladder pull request #1560
Opened 2022-11-01 09:22 UTC by jwoo-o

2단계 작성이 오래 걸린거 같네요
리뷰 잘 부탁드리겠습니다!

2022-11-04 19:02 UTC, lxxjn0 approved these changes
진우님, 미션 진행하시느라 수고하셨습니다!!

간단한 피드백만 남겨봤는데 한 번 확인해보시고 피드백 반영 부탁드릴게요 :)

2022-11-04 19:03 UTC, lxxjn0 requested changes
실수로 approve를 눌러서 다시 request changes로 변경하였습니다!! ㅠㅠㅠ

2022-11-08 01:12 UTC, jwoo-o commented on src/main/java/ladder/domain/User.java
> +    public boolean equals(Object o) {
이름이 동일하다고 해서 동일한 사람으로 보장하기는 힘들겠네요

2022-11-10 07:07 UTC, lxxjn0 requested changes
진우님, 피드백 반영하시느라 수고하셨습니다!

크게 피드백 더 드릴만한 부분은 없을 것 같아서 다음 단계로 진행해주시면 될 것 같습니다 :)

2022-11-10 07:07 UTC, lxxjn0 commented on src/main/java/ladder/domain/Line.java
> +    private boolean addPoint(int index) {
해당 로직과 같은 경우 early return을 활용하면 코드를 더 간결하게 작성할 수 있어요!!

```java
private boolean addPoint(int index) {
    if (index > 0) {
        return validPoint(point, points.get(index - 1));	           
    }
    return RANDOM.nextBoolean();
}
```

2022-11-10 07:07 UTC, lxxjn0 commented on src/main/java/ladder/domain/Users.java
> +            .collect(Collectors.toUnmodifiableList());
getter를 사용할 때도 안전하게 사용할 수 있도록 작업해주셨네요!! 👍🏼

2022-11-10 10:13 UTC, jwoo-o commented
다음 단계로 넘어가라고 하신거 같은데 merge가 안된거 같습니다 ㅠㅠ

2022-11-10 10:14 UTC, jwoo-o commented on src/main/java/ladder/domain/Line.java
> +    private boolean addPoint(int index) {
이부분은 현재 나온 random boolean값과 이전에 나온 boolean 값을 비교해야되서 
early return을 사용하지 못합니다

2022-11-10 10:41 UTC, merged