🚀 Step4 - 사다리(리팩토링)
next-step/java-ladder pull request #1570
Opened 2022-11-02 13:20 UTC by o3ozzvb

안녕하세요. 
Step3 피드백 반영 과 Step4 리팩토링 과정 진행하였습니다.
3단계 피드백 반영했는데, 4단계에서 대부분의 코드가 대체되어서 조금 아쉬운 마음도 드네요..ㅎㅎ

피드백 부탁드립니다!
감사합니다 :)

2022-11-03 03:26 UTC, csh0034 requested changes
Line 과 LineTest 에 컴파일 에러가 발생하네요 😭 
수정후에 다시 리뷰요청 부탁드려요!

2022-11-03 09:55 UTC, o3ozzvb commented
ㅠㅠ 백업 파일들은 커밋안했더니 컴파일 오류 발생했나 보네요... 다시 커밋하였습니다..

2022-11-03 15:11 UTC, csh0034 requested changes
4단계 힌트 참고하여 잘 구현 해주셨네요 👍 

현재 사용하고 있지 않거나 주석처리된 코드들
정리 해주시면 좋을것 같습니다!

추가로 코멘트 몇개 남겨두었는데 같이 확인해주시고
다시 리뷰요청 부탁드려요!

2022-11-03 15:11 UTC, csh0034 commented on src/test/java/ladder/domain/LineTest.java
>  class LineTest {
사용하지 않는 코드는 삭제해주세요!

2022-11-04 03:49 UTC, csh0034 approved these changes
안녕하세요. 은경님 😃

피드백 잘 반영 해주셨네요 💯
마지막 단계는 이만 머지하도록 하겠습니다.

이번 단계를 마지막으로 사다리미션도 마무리 되었네요.
그동안 사다리미션 진행하시느라 수고 많으셨고

마지막 볼링미션까지 완주하시길 응원하겠습니다 🎉🎉

2022-11-04 03:49 UTC, merged