step3 사다리 게임 실행 구현
next-step/java-ladder pull request #1581
Opened 2022-11-03 23:52 UTC by JopopScript

아직 모든 public 메소드에 대한 단위테스트를 작성하진 못하였습니다. 혹시 필요하다면 추후에 계속 추가하겠습니다.
개인적인 사정으로  step3단계가 늦어 졌네요 ㅠㅠ 잘부탁드리겠습니다!!

2022-11-05 05:37 UTC, ksy90101 requested changes
안녕하세요 :)
3단계도 너무 고생 많으셨습니다!!
간단한 피드백을 남겼으니, 한번 확인해주시면 감사하겠습니다.
궁금하신게 있다면 언제든 질문주세요~

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/domain/RandomLineGenerator.java
> +            boolean nextPoint = accumulatedLine.isLastTrue() ? false : getRandomBoolean();
3항 연산자는 안쓰는게 좋습니다.
아울러 
```suggestion
            boolean nextPoint = !accumulatedLine.isLastTrue() && getRandomBoolean();
```
이런식으로도 작성할수 있을듯 해요~

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/domain/Line.java
>          if (line.size() == 0) {
```suggestion
        if (line.isEmpty()) {
```

이런식으로 제공해주는 것을 사용하면, 더 깔끔해 보일수 있겠어요!

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/domain/Line.java
> +    public boolean isLastTrue() {
굳이 True라는 단어를 쓸 필요는 없어보여요.
isLastPoint / isLast와 같은 단어가 어떠신가요?

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/domain/Line.java
> +        return index > -1;
-1이라는 것에 의미를 알기가 조금 어렵습니다.
-1을 상수로 빼보면 어떨까요?

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/controller/GameRunner.java
> +        while(true) {
무한르프가 발생할듯 하네요.

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/domain/Ladder.java
> +    private final List<Line> ladder;
저는 개인적으로 lines라는 단어가 더 어울릴듯 해요.
사다리는 라인들을 상태로 가지고 있다고 생각이 드는거 같아요 ㅎㅎ
어떻게 생각하시나요?

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/domain/Ladder.java
> +        this.ladder = IntStream.range(0, height)
지금단계까지 오셨다면, 사실 Stream의 연습은 충분히 하셨다고 생각이 들어요.
그렇다면 우리는 좀더 고민해봐야 하는 사항이 있는거 같습니다.
바로, for문과 stream중에 각각 어떤 상황에 쓰는가 인데요.
지금과 같은 경우엔 IntStream을 단순히 순회하면서 돌기 때문에 의미있는 단어는 아닌거 같은데, 어떻게 생각하시나요?

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/domain/Ladder.java
> +    public List<Line> ladder() {
콘솔이기 때문에 getter는 별수 없을듯 해요.
그래서 굳이 이런식으로 이름을 변경할 필요가 있을까 합니다.
아울러 외부에서 해당 값을 참조할때, 혹시라도 잘못된 값을 변경할수도 있을듯 해요.
1. 불변으로 한다 / 2. 복사본을 내준다.
두가지 방법을 한번 고려보세요.

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/controller/GameRunner.java
>          int ladderHeight = inputView.enterLadderHeight();
실제 게임에 필요한 상태를 하나의 객체에서 상태로 가지고 있으면 좀더 깔끔해 질수 있을듯 해요.
그렇다면 각 게임에 상태를 차후에 저장할수 있지 않을까 합니다.
입력은 Runner에서 받고 입력된 것을 객체에 줄수도 있겠죠.

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/domain/Point.java
> +    private final int maxLocation;
이 부분을 객체로 관리해보면 어떨까요?
원시값을 포장해보는거죠!

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/domain/Points.java
> +                .orElseThrow(RuntimeException::new);
RuntimeException이 아닌 더 의미있는 예외를 사용해보시겠어요?

2022-11-05 05:37 UTC, ksy90101 commented on src/main/java/ladder/view/ResultView.java
> +                    System.out.printf("%s : %s\n", point.name(), winningPoint.name());
\n보단, System.lineSperator()를 한번 알아보시면 어떨까요?

2022-11-05 17:26 UTC, JopopScript commented on src/main/java/ladder/domain/RandomLineGenerator.java
> +            boolean nextPoint = accumulatedLine.isLastTrue() ? false : getRandomBoolean();
추천해주신것과 같이 intellij에서 변경하는것을 추천했었지만 저는 3항연산자가 조금더 일반적으로 다른사람이 이해하기 쉽지않을까 생각했습니다.
현업이나 이런곳에서는 추천해주신 방법이 조금더 많이쓰이면서 잘 읽히는 코드일까요??

2022-11-05 17:30 UTC, JopopScript commented on src/main/java/ladder/domain/Line.java
> +    public boolean isLastTrue() {
last로 바꿔봤는데요 괜찮은가요? ㅋㅋㅋ...

2022-11-05 17:36 UTC, JopopScript commented on src/main/java/ladder/controller/GameRunner.java
> +        while(true) {
<img width="247" alt="image" src="https://user-images.githubusercontent.com/72125027/200133490-b5d1b4ef-e421-40cc-a892-0ac624948021.png">
요구사항 화면에서 여러번 결과를 조회 가능하도록 되어 있는것 같아 의도적으로 무한루프로 작성하였습니다.
아니면 2번 이라던가 이렇게 결과 조회 횟수에 제한을 두거나 하는게 좋을까요?

2022-11-05 18:47 UTC, JopopScript commented on src/main/java/ladder/controller/GameRunner.java
>          int ladderHeight = inputView.enterLadderHeight();
- class LadderGame에서 ladder(**진행이력 데이터**), resultParticipants(**결과 데이터**) 두가지로 게임이 완료된 후 값을 가지고 있습니다.
- participants: resultParticipants과 중복된데이터(참여자의 이름, 최대 길이)가 있지만 위치정보(**초기 데이터**)는 게임진행을 파악하는데 의미를 가질것으로 생각됩니다. 이것을 기록형태로 저장하여 사용자에게 제공을 대비하는게 좋다는 의미가 맞을까요?
- winningItems: LadderGame에는 없는 **초기 데이터**로 별도의 관리가 필요해 보입니다. 이떄 초기에 생성된 participants와 같은 **초기 데이터**유형으로 둘을 같이 관리하는게 유용해보인다는 것이 맞을까요??

2022-11-05 20:13 UTC, JopopScript commented on src/main/java/ladder/domain/Point.java
> +    private final int maxLocation;
포장도 고려를 해봤으나 포장을 하게되면 Line과 Location(location과 maxLocation을 가진 객체)를 비교함에 어려움이 있었습니다.
ex) line의 왼쪽끝이나 오른쪽끝을 넘어가는 Location이 생성되었는지 체크하기 위해서는
둘중에 한곳에서는 getter를 통해서 위치정보를 꺼낸 후에 다른 객체에게 원시값을 argument로 전달하면서 메세지를 전달할 수 밖에 없었습니다.

2022-11-05 21:33 UTC, JopopScript commented on src/main/java/ladder/view/ResultView.java
> +                    System.out.printf("%s : %s\n", point.name(), winningPoint.name());
"%s : %s" + System.lineSperator() 의 형태가 가독성이나 조금 코드가 더러워지는것  같아서 "%s : %s%n"를 사용 했습니다.
%n도 System.lineSperator()와 마찬가지로 OS에 따라서 개행문자를 알아서 잘(\r\n 또는 \n) 추가해준다고 이걸 사용했는데요. 추천해주신 이유가 이게 맞을까요??

2022-11-06 23:34 UTC, ksy90101 commented on src/main/java/ladder/domain/RandomLineGenerator.java
> +            boolean nextPoint = accumulatedLine.isLastTrue() ? false : getRandomBoolean();
저는 BooleanExpression이 훨씬 잘 읽히는 코드라고 생각합니다.
명확하게 옆에서 옆으로 읽으면 어떤 느낌인지 알수 있는거 같아요.
사실 이런 코드를 많이봐서 익숙한거 같기도 하고요!

2022-11-06 23:34 UTC, ksy90101 commented on src/main/java/ladder/domain/Line.java
> +    public boolean isLastTrue() {
넵 충분히 의미전달이 가능하다고 생각합니다.

2022-11-06 23:34 UTC, ksy90101 commented on src/main/java/ladder/controller/GameRunner.java
> +        while(true) {
이건 선택의 문제인데, 저는 all이 들어온 경우 제한을 두었을거 같아요!

2022-11-06 23:35 UTC, ksy90101 commented on src/main/java/ladder/controller/GameRunner.java
>          int ladderHeight = inputView.enterLadderHeight();
네. 게임진행을 파악하기 위한 상태들은 객체로 추출해 관리하는게 더 좋을거 같아요.

2022-11-06 23:36 UTC, ksy90101 commented on src/main/java/ladder/domain/Point.java
> +    private final int maxLocation;
포장을 해서 Compare을 재정의하면 비교함이 쉽지 않을까요?
Location과 MaxLocation은 하나의 정의인듯 한데요. 하나의 객체로 둘다 관리해보는거죠!
https://st-lab.tistory.com/243
이글을 한번 읽어보세요!

2022-11-06 23:38 UTC, ksy90101 commented on src/main/java/ladder/view/ResultView.java
> +                    System.out.printf("%s : %s\n", point.name(), winningPoint.name());
네! %n도 좋습니다. 플랫폼 종속적인 구분자이기 때문에 충분한듯 합니다!

2022-11-06 23:51 UTC, ksy90101 requested changes
안녕하세요 :)
질문주신 사항에 대해서 답변을 남겨두었습니다.
참고해서 한번 더 수정해주시면 감사하겠습니다~
질문이 있다면 언제든 연락주세요!

2022-11-06 23:51 UTC, ksy90101 commented on src/main/java/ladder/view/ResultView.java
> +    private String lineConvertString(Line line, int nameMaxLength) {
이건 제 개인적인 스타일인데, 3항연산자를 쓰지 않고 아래와 같이 메서드를 추출하긴 합니다. ㅎㅎ

```
    private String lineConvertString(Line line, int nameMaxLength) {
        String lineString = line.line().stream()
                .map(point -> test(point, nameMaxLength))
                .collect(Collectors.joining(VERTICAL_ROAD));
        return VERTICAL_ROAD + lineString + VERTICAL_ROAD;
    }

    private String test(boolean point, int nameMaxLength) {
        if (Boolean.TRUE.equals(point)) {
            return HORIZONTAL_ROAD.repeat(nameMaxLength)
        }
        return EMPTY_HORIZONTAL_ROAD.repeat(nameMaxLength)
    }
```

참고만 해주세요~

2022-11-06 23:51 UTC, ksy90101 commented on src/main/java/ladder/domain/Location.java
> +public class Location {
답변을 남기긴 했지만, location, maxLocation을 하나의 객체에 상태를 가지고 잇는게 아니라 객체 하나가 각각 의미가 되도록 해보세요~
참고 링크드렸습니다!

2022-11-06 23:51 UTC, ksy90101 commented on src/main/java/ladder/domain/Point.java
> +        }
2개이긴 하지만, if문을 두번 쓰기 보단, 문자열 계산기때 했던 enum을 이용하면 전략패턴으로 관리할수 잇지 않을까요?

2022-11-07 01:31 UTC, JopopScript commented on src/main/java/ladder/view/ResultView.java
> +    private String lineConvertString(Line line, int nameMaxLength) {
혹시
if (point) 이렇게 사용하지 않고
if (Boolean.TRUE.equals(point)) 이렇게 쓰신 이유가 있을까요?

2022-11-08 00:13 UTC, ksy90101 commented on src/main/java/ladder/view/ResultView.java
> +    private String lineConvertString(Line line, int nameMaxLength) {
앗... 이걸 쓰려다가 여기에 안썻네요 😢 
Boolean과 같은 BoxedType은 Null이 될수도 있습니다.
따라서 NPE가 발생할 확률이 있는데요.
https://stackoverflow.com/questions/9479806/boolean-object-and-boolean-variable-issue-in-java
위 글을 참고해보시겠어요?

2022-11-08 19:35 UTC, JopopScript commented on src/main/java/ladder/domain/Point.java
> +    private final int maxLocation;
Comparable, Comparator 두개 모두 같은 자료형을 대상으로만 비교가 가능한것으로 봤습니다.
처음 리뷰해주신부분을 제대로 이해하지 못하여 방향을 잘못잡은것 같아 location, maxLocation은 분리하였습니다.

그러나 line와 point를 비교하는것이 어려운부분은 해결되지 못했습니다.
이 부분은 아래 리뷰에 전략패턴으로 해결하는것을 생각하시는게 맞을까요??

2022-11-08 19:36 UTC, JopopScript commented on src/main/java/ladder/domain/Point.java
> +        }
enum을 어떻게써야할지 감을 못잡아서 일단 전략패턴으로는 구현했습니다.
리뷰의도에 맞지않게 수정한건 아닌지 궁금합니다...??

MoveStrategy를 client인 GameRunner쪽으로 완전히 빼내진 못했습니다. 조금 더 고민해 보겠습니다....

2022-11-10 23:55 UTC, ksy90101 requested changes
안녕하세요 3단계까지 너무 고생 많으셨습니다 💯 
이만 3단계는 머지하고 마지막 4단계떄 전체적으로 한번 더 보고 리뷰 남기도록 하겠습니다!
4단계도 파이팅입니다!

2022-11-10 23:55 UTC, ksy90101 commented on src/main/java/ladder/domain/Location.java
> +    private final int location;
```suggestion
    public static final Location ZERO = new Location(0);
    
    private final int location;
```
상수와 필드는 새행으로 분리해두면 더 깔끔해 보입니다

2022-11-10 23:55 UTC, ksy90101 commented on src/main/java/ladder/domain/Location.java
> +public class Location implements Comparable<Location> {
👍

2022-11-10 23:56 UTC, ksy90101 approved these changes

2022-11-10 23:56 UTC, merged