🚀 2단계 - 사다리(생성)
next-step/java-ladder pull request #1634
Opened 2022-11-14 15:58 UTC by withbeth

잘 부탁드립니다 :)

2022-11-15 15:02 UTC, ddaaac requested changes
안녕하세요 종은님 👋 

이전 단계들에서 배운 내용들 토대로 너무 구현 잘 해주셨습니다 👍 

몇 가지 코멘트를 남겼으니 확인 부탁드려요!

2022-11-15 15:02 UTC, ddaaac commented on src/test/java/nextstep/ladder/domain/LadderLineTest.java
> +class LadderLineTest {
테스트 케이스 정말 꼼꼼하게 잘 작성해주셨습니다 💯

2022-11-16 08:36 UTC, withbeth commented on src/main/java/nextstep/ladder/domain/LadderCreator.java
> +    Ladder create(final PositiveNumber ladderHeight, final PositiveNumber ladderWidth);
피드백 감사합니다.
사다리, 사다리라인 객체 생성방식을 분리하기 위해 인터페이스로 분리하였구요.
테스트 작성시 편하게 람다 형식으로 작성키 위해 함수형 인터페이스로 정의했습니다 :)

다시보니, 조금 과하게 분리한 감이 없지 않은것같아서 삭제 하도록 하겠습니다!

2022-11-16 08:38 UTC, withbeth commented on src/main/java/nextstep/ladder/domain/PointType.java
> +    public abstract boolean isNode();
감사합니다 :)

2022-11-16 08:40 UTC, withbeth commented on src/main/java/nextstep/ladder/domain/RandomWrapper.java
> +        return random.nextBoolean();
지우지 못한 부분이 있었네요!
값 생성시마다 새로운 시드 생성은 아무 의미가 없어서, 시드 업데이트를 지우려고 했었습니다 :)
매의 눈으로 찾아주셔서 감사해요!

2022-11-16 08:54 UTC, withbeth commented on src/main/java/nextstep/ladder/domain/LadderCreator.java
> +    Ladder create(final PositiveNumber ladderHeight, final PositiveNumber ladderWidth);
사용치 않는 인터페이스로 분리하는 방법 삭제 완료했습니다.

2022-11-16 08:54 UTC, withbeth commented on src/main/java/nextstep/ladder/domain/PointType.java
> +    public abstract boolean isNode();
수정 완료 했습니다

2022-11-16 09:35 UTC, withbeth commented on src/main/java/nextstep/ladder/domain/LadderLine.java
> +        }
자세한 피드백 고마워요!
모던 자바인 액션책을 열심히 참조해보았지만, 연속값 validate는 stream만으로는 조금 부족해보이네요!
밑의 방식으로 수정했습니다.

```java
    private static void validateConnectedPoints(final List<Point> points) {
        IntStream.range(SECOND_INDEX, points.size())
            .forEach(i -> validateConnectedInRow(points.get(i - 1), points.get(i)));
    }

    private static void validateConnectedInRow(final Point prevPoint, final Point currPoint) {
        if (prevPoint.isConnectedInRow(currPoint))  {
            throw new IllegalArgumentException("Points can not be connected in a row");
        }
    }
```

2022-11-16 10:00 UTC, withbeth commented on src/main/java/nextstep/ladder/domain/LadderCreatorImpl.java
> +        return Collections.unmodifiableList(result);
단지 for문 돌려고 값 객체를 가독성해치면서까지 사용하는 부분이 저도 조금 마음에 걸렸었어요!
다음과 같이 가독성 좋게 개선하였습니다 :)

```
    private List<LadderLine> createLadderLines(
        final PositiveNumber ladderHeight,
        final PositiveNumber ladderWidth
    ) {
        return IntStream.range(FIRST, ladderHeight.intValue())
            .mapToObj(i -> ladderLineCreator.create(ladderWidth))
            .collect(Collectors.toUnmodifiableList());
    }
```

2022-11-16 10:02 UTC, withbeth commented on src/main/java/nextstep/ladder/domain/LadderLineCreatorImpl.java
> +        return Collections.unmodifiableList(result);
꼼꼼한 피드백 감사합니다 :) 다음과 같이 개선하였습니다.

```java
    private List<Boolean> generateRandomValues(final PositiveNumber pointsSize) {
        return Stream.iterate(randomValueGenerator.nextValue(), this::nextValue)
            .limit(pointsSize.intValue())
            .collect(Collectors.toUnmodifiableList());
    }
```

2022-11-16 12:32 UTC, ddaaac commented on src/main/java/nextstep/ladder/domain/RandomWrapper.java
> +        return random.nextBoolean();
링크가 빠졌군요... [여기](https://stackoverflow.com/a/17565472)였습니다 ㅠㅠ

2022-11-16 12:33 UTC, ddaaac commented on src/main/java/nextstep/ladder/domain/LadderLine.java
> +        }
꼭 stream으로 변경할 필요는 없었는데 잘 변경해주셨네요 💯

2022-11-16 12:34 UTC, ddaaac commented on src/main/java/nextstep/ladder/domain/LadderCreatorImpl.java
> +        return Collections.unmodifiableList(result);
자바가 연산자 오버로딩을 지원하지 않아서 이런 부분이 깔끔하게 작성하기가 어렵더라구요 😄

2022-11-16 12:53 UTC, ddaaac approved these changes
종은님 안녕하세요 👋 

리뷰 반영 너무 잘 해주셔서 크게 남길 코멘트가 없네요!

다음 단계 진행해주세요~

2022-11-16 12:53 UTC, merged