Step2
next-step/java-ladder pull request #1635
Opened 2022-11-14 21:38 UTC by hasunzo

안녕하세요 리뷰어님
사다리타기 2단계 리뷰 요청드립니다.
감사합니다

2022-11-15 03:42 UTC, testrace requested changes
안녕하세요 하선님 😃 
2단계 미션 잘 구현해 주셨네요 👍 
몇 가지 개선이 되었으면 하는 부분들이 있어서 코멘트 남겼습니다.
코멘트 확인해 주시고 리뷰 요청 부탁드려요!
궁금하신 내용이나 의견 있으시면 편하게 DM 주세요!

2022-11-15 03:42 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Line.java
> +            points.add(generator.generate());
들여쓰기를 최대 1까지만 유지해 보시면 어떨까요?

2022-11-15 03:42 UTC, testrace commented on src/main/java/nextstep/ladder/domain/LineGenerator.java
> +public interface LineGenerator {
FP interface임을 명시하게 위해 `@FuntionalInterface` 애너테이션을 적용해 보시면 어떨까요?

2022-11-15 03:42 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Line.java
> +    private Boolean prevIsTrue(int i) {
primitive type boolean 대신 wrapper type Boolean 을 사용하신 이유가 궁금합니다! 🤔

2022-11-15 03:42 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Lines.java
> +                .collect(Collectors.toList());
lines를 바로 리턴하면 어떨까요?

2022-11-15 03:42 UTC, testrace commented on src/main/java/nextstep/ladder/service/LadderService.java
> +    private final Ladder ladder;
클래스 변수와 인스턴스 변수 사이에 개행을 추가하면 가독성에 도움이 될 것 같아요 😃

2022-11-15 03:42 UTC, testrace commented on src/main/java/nextstep/ladder/service/LadderService.java
> +    }
일급 컬렉션 객체에게 바로 생성하도록 메시지를 보내 받으면 어떨까요?
Service에서 private 메서드를 제거할 수 있지 않을까요?

2022-11-15 03:42 UTC, testrace commented on src/main/java/nextstep/ladder/view/LadderResultView.java
> +        }
(optional)
ui 로직에서도 지금까지의 프로그래밍 요구사항을 적용해 보셔도 좋을 것 같아요 😃

2022-11-15 03:42 UTC, testrace commented on src/main/java/nextstep/ladder/view/LadderResultView.java
> +            nameString.append("  ");
사다리의 세로 선과 참가자의 이름 위치가 일치 하지 않아서 보기에 쉽지 않은 것 같아요 😢 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/8064743/201820720-1336afbb-fc51-4d68-9dc7-189929ce1fc2.png">

2022-11-15 03:42 UTC, testrace commented on src/main/java/nextstep/optional/User.java
> +    }
피드백 반영 👍 
학습 과정이니 조금 더 극단적으로 메서드를 분리해 보셔도 좋을 것 같아요!

2022-11-15 03:42 UTC, testrace commented on src/test/java/nextstep/ladder/domain/LineTest.java
> +    public static final Line LINE_TEST2 = new Line(List.of(true, false, true, false));
테스트에서도 변수 명을 의미 있게 부여하면 어떨까요?
변수명을 한글로 지어도 괜찮을 것 같아요!

2022-11-15 12:16 UTC, hasunzo commented on src/main/java/nextstep/ladder/domain/Line.java
> +    private Boolean prevIsTrue(int i) {
인스턴스 변수를 Boolean 타입의 리스트로 선언해서 별 생각없이 Boolean 으로 반환했었습니다 boolean 으로 바꾸는게 좋을 듯 하여 반영하도록 하겠습니다 :)

2022-11-15 13:32 UTC, hasunzo commented on src/main/java/nextstep/ladder/service/LadderService.java
> +    }
리뷰어님 말씀대로 일급 컬렉션 객체에게 생성하도록 하려고 했는데요!
하는 도중에 의문이 생겨서 질문드립니다.

해당 방식으로 개발 시 일급 컬렉션이 split을 하면서 Regex 를 알고 있어야하는데요,
일급 컬렉션은 리스트 외의 다른 멤버 변수를 가지면 안되지 않나 싶어서요..

그래서 일단은 string 값을 통해 split 을 하고 User 객체를 만들어 리스트로 반환해주는
유틸성 클래스 StringUserNamesToUsersGenerator 를 만들어 보았는데 
이런식으로 분리를 하는 방법에 대해서 어떻게 생각하시는지 답변 부탁드립니다..!

2022-11-15 13:44 UTC, hasunzo commented on src/test/java/nextstep/ladder/domain/LineTest.java
> +    public static final Line LINE_TEST2 = new Line(List.of(true, false, true, false));
도저히 의미있는 이름이 떠오르질 않는데 혹시 예시 하나만 들어주실 수 있으실까요..ㅠㅠㅠ

2022-11-16 23:29 UTC, testrace commented on src/main/java/nextstep/ladder/service/LadderService.java
> +    }
Util 클래스를 활용하는 방법도 괜찮은 것 같습니다 😃 

개인적으로 일급 컬렉션은 컬렉션 멤버 변수를 1개로 두고 
클래스 변수를 두는 것은 괜찮다고 생각합니다.

2022-11-16 23:33 UTC, testrace commented on src/test/java/nextstep/ladder/domain/LineTest.java
> +    public static final Line LINE_TEST2 = new Line(List.of(true, false, true, false));
테스트의 의도만 드러낼 수 있는 변수명이면 괜찮을 것 같아요!
생성과 관련된 테스트에서 사용되니 단순하게 `첫번째_줄`, `두번째_줄`과 같은 이름은 어떠실까요?
다음 단계에서는 해당 변수가 다른 용도로 활용될 수 있으니 그 때 이름에 대해서도 고민해 보시면 좋을 것 같아요 😃

2022-11-16 23:38 UTC, testrace approved these changes
안녕하세요 하선님 😃 
피드백 반영 멋지게 해주셔서 크게 피드백 드릴 내용이 없네요. 👍 👍 
바로 다음 단계 진행 부탁드려요!! 

질문에 대한 답변은 코멘트로 남겨두었으니 확인 부탁드립니다.
미션완료까지 화이팅입니다! 🔥

2022-11-16 23:38 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Line.java
> +            createPoint(generator, i);
메서드가 분리되어 가독성이 높아졌네요 👍

2022-11-16 23:38 UTC, testrace commented on src/main/java/nextstep/ladder/domain/Lines.java
> +        return Collections.unmodifiableList(lines);
`unmodifiableList` 👍

2022-11-16 23:38 UTC, testrace commented on src/main/java/nextstep/ladder/view/LadderResultView.java
> +    private static final String DIVISION_LINE = "|";
상수 치환 💯

2022-11-16 23:39 UTC, merged