Step2 사다리(생성) 미션 구현
next-step/java-ladder pull request #1669
Opened 2023-05-02 13:01 UTC by right1203

안녕하세요 리뷰어님
사다리 생성 미션 구현하였습니다.
최대한 요구사항을 지키면서 하려고 했는데 못 지킨 부분이나 개선할 수 있는 부분이 있으면 편하게 말씀 주세요!

그리고 Step1이 머지되기 전에 작업을 시작해서 현재 충돌이 일어나는데요.. ㅎㅎ 어떻게든 해결해보겠습니다.
감사합니다 :)

2023-05-03 15:31 UTC, testrace requested changes
안녕하세요 영훈님 😄 
2단계 미션 잘 구현해 주셨네요 👍 
작은 단위로 구현하고 커밋해 주신 부분들이 인상적이었습니다!
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요
궁금한점이나 의견 있으시면 편하게 DM 주세요

2023-05-03 15:31 UTC, testrace commented on src/test/java/ladder/domain/LadderGameTest.java
> +    }
이 테스트는 어떤 의도로 만들어 주신걸까요?
connectedCounts 메서드에 대해 설명 부탁드려요

2023-05-04 06:52 UTC, right1203 commented on src/test/java/ladder/domain/LadderGameTest.java
> +    }
connectedCounts는 없어도 되는 메서드입니다.
원래는 양쪽에 대한 연결 여부를 체크해야 한다고 생각을 했어서 만들었는데요, 작업하다보니 오른쪽에 대한 체크만 해도 충분할 것 같아 사용하지 않은 메서드네요.
관련 메서드는 모두 삭제하겠습니다~

2023-05-13 07:21 UTC, right1203 commented
안녕하세요 용주님~
다른 일로 바쁘다보니 놓쳐서 늦어졌습니다.
처음 구현할 때 빈 사다리를 만들어놓고 이후에 그리는 방법으로 구현을 하였는데요,
이렇게 했을 때 코드가 깔끔해지지 않는 것 같아서 구현 방식을 변경했습니다.

확인 부탁드립니다~!!

2023-05-14 05:50 UTC, testrace requested changes
안녕하세요 영훈님 😃 
재 구현해 주신 코드가 이전에 비해 훨씬 깔끔해졌네요 👍 
몇 가지만 다듬고 다음 단계 진행하면 좋을 것 같아서 코멘트 남겼는데 확인 부탁드려요
궁금한 점이나 의견 있으시면 편하게 DM 주세요

2023-05-14 05:50 UTC, testrace commented on src/main/java/ladder/domain/Direction.java
> +    RIGHT(true, false),
LEFT의 인스턴스 변수 left의 값이 false, right의 값이 true 라서 서로 반대가 된 것이 아닌가 싶어요
Direction 4개의 값이 LEFT, RIGHT, LEFT, RIGHT일 때 
출력에서 `|-----|     |-----|` 인데 의도하신게 맞으신지 궁금합니다 🤔

2023-05-14 05:50 UTC, testrace commented on src/main/java/ladder/domain/Ladder.java
> +        return ladderRows.get(0).width();
users를 활용해 가로 값을 반환해도 좋을 것 같아요 😃

2023-05-14 05:50 UTC, testrace commented on src/main/java/ladder/domain/Ladder.java
> +    }
참가자들의 이름에 대해 가장 잘 알고 있는 Users에게 위임하면 어떨까요?

2023-05-14 05:50 UTC, testrace commented on src/main/java/ladder/domain/Point.java
> +            return new Point(true, false);
고정된 값을 가진 객체는 상수로 만들어두고 재활용하면 어떨까요?

2023-05-14 05:50 UTC, testrace commented on src/test/java/ladder/domain/DirectionTest.java
> +    }
열거타입이니 직접 비교하면 어떨까요?
```suggestion
    @ParameterizedTest(name = "{0}, {1}")
    @CsvSource({
            "false, true, LEFT",
            "true, false, RIGHT",
            "false, false, NONE"
    })
    @DisplayName("방향 생성")
    void create(boolean left, boolean right, Direction expected) {
        // when
        Direction direction = Direction.of(left, right);

        // then
        assertThat(direction).isSameAs(expected);
    }
```

2023-05-14 05:50 UTC, testrace commented on src/main/java/ladder/domain/Point.java
> +    public Point next(boolean nextRight) {
전략 패턴을 사용하고 있으니 포인트를 생성할 때 전략을 주입받으면 어떨까요?
```suggestion
    public Point next(DrawStrategy drawStrategy) {
```

2023-05-14 10:51 UTC, right1203 commented on src/main/java/ladder/README.md
> +- [x] 개인별 이름을 입력하면 개인별 결과를 출력하고, "all"을 입력하면 전체 참여자의 실행 결과를 출력한다.
리뷰 기다리는 동안 다음 미션 진행하다가 섞였나보네요 ㅎㅎ

2023-05-14 11:00 UTC, right1203 commented on src/main/java/ladder/domain/Direction.java
> +    RIGHT(true, false),
아이구;; 수정하면서 제일 중요한 부분에서 실수가 생겼군요..
테스트 케이스도 더 잘 작성해야할 것 같습니다.
잘 챙겨주셔서 감사합니다 ㅎㅎ

2023-05-14 11:02 UTC, right1203 commented on src/main/java/ladder/domain/Ladder.java
> +        return ladderRows.get(0).width();
아 이건 바꿨는데 푸시를 안 했네용 ㅎㅎ

2023-05-14 11:06 UTC, right1203 commented on src/test/java/ladder/domain/DirectionTest.java
> +    }
오~ 감사합니다 ㅎㅎ

2023-05-14 11:19 UTC, right1203 commented
안녕하세요 용주님
피드백 주신 부분 반영했습니다.
제가 리뷰 대기 중에 3단계 진행하다가 조금 꼬여서 3단계 부분이 쪼끔 섞여있을 수 있는데 양해 부탁드립니다 ㅎㅎ

2023-05-14 14:43 UTC, testrace approved these changes
안녕하세요 영훈님 😃 
피드백 반영 잘해 주셨네요 👍 
소소하게 코멘트 남겼는데 확인해 주시고 다음 단계 진행해 주세요 🔥

2023-05-14 14:43 UTC, testrace commented on src/main/java/ladder/domain/Point.java
> +    private static final boolean NOT_CONNECTED = false;
Point 객체 자체를 상수로 만들어두는 방법도 고려해 보시면 좋을 것 같아요 😃 
```suggestion
    private static final Point LEFT_POINT = new Point(Direction.LEFT);
    private static final Point RIGHT_POINT = new Point(Direction.RIGHT);
```

2023-05-14 14:43 UTC, testrace commented on src/main/java/ladder/domain/Direction.java
> +    RIGHT(true, false),
단순 오타였군요 😃

2023-05-14 14:44 UTC, merged