Step2 - 사다리(생성)
next-step/java-ladder pull request #1715
Opened 2023-05-11 15:36 UTC by gurioh

2023-05-12 02:10 UTC, wooobo requested changes
안녕하세요!
2단계 잘 진행해주셨습니다~ 😄 

코멘트 확인 후 재요청 부탁드려요~!
좋은 하루 되세요!

2023-05-12 02:10 UTC, wooobo commented on src/main/java/ladder/util/StringParseUtil.java
> +public class StringParseUtil {
개인적으로는 미션진행시 `Util`,`Common` 클래스 개념을 사용하지 않는게 더 많은 부분을 습득할 수 있을거라고 생각해요.

미션 과정에서 훈련 할 수 있는 많은 부분중에 하나가 `책임과역할`이 분명한 객체를 만들고 그러한 객체에게 메시지를 전달하는 개발 패턴 학습에 있다고 생각해요.

원하고자 하는 도메인 객체를 만들어보면 어떨까요?
예를들어, `Player`같은 객체가 있을것 같기도하구요 참고해주세요~ 😄 
```
public class Player {

    String[] values;

    private Player(String[] values) {
        this.values = values;
    }

    public Player commaOf(String value) {
        String COMMA = ",";
        return new Player(value.split(COMMA));
    }
}
```

2023-05-14 09:04 UTC, gurioh commented on src/main/java/ladder/util/StringParseUtil.java
> +public class StringParseUtil {
아 뭔가 유틸을 만들어서 하는것이 습관이 되어있다보니 의도하고자하는 방향으로 학습을 못했던것 같습니다. 
좋은 지적 감사합니다 :)

2023-05-15 03:22 UTC, wooobo approved these changes
안녕하세요! 2단계 잘 진행해주셨습니다.

추가적으로 몇가지 관점 공유해보았습니다.
다음단계 진행시 참고 부탁드려요~

오늘 날씨 좋네요 ㅎ 좋은 하루 되세요~

2023-05-15 03:22 UTC, wooobo commented on src/test/java/ladder/service/LadderGameTest.java
> +                () ->  new Player("123456"))
`LadderGameTest` 보다는 `PlayerTest`로 분리해도 좋을것 같아요!

2023-05-15 03:22 UTC, merged