Step3 게임 실행 리뷰 요청 드립니다.
next-step/java-ladder pull request #1780
Opened 2023-05-17 16:06 UTC by wsdf25867

안녕하세요 3단계 게임 실행 리뷰 요청 드립니다.

피드백 반영 및 기능 구현 완료하여 리뷰 요청 드립니다.

리뷰에서 Line의 상태를 그냥 넘겨주고 있다고 하셨는데

getter 에서 unmodifiableList 로 주고 있어서 괜찮다고 생각했습니다!

그래서 이번에는 unmodifiableList 로 초기화 하도록 수정 했는데 이걸 원하셨던 건지 궁금합니다

2023-05-18 16:59 UTC, dave915 requested changes
지우님 안녕하세요! 이번에도 깔끔하게 잘 구현해주셨네요 💯 
Dto를 어떤 레이어에서 변환 할 것인가, 언제 변환할 것 인가에 대한 질문 남겨두었어요! 
코멘트나 DM을 통해 이야기 해보면 좋을 것 같습니다!

2023-05-18 16:59 UTC, dave915 commented on src/main/java/nextstep/ladder/domain/ExecutionResult.java
> +        List<GamerDto> gamers = climbedGamers.toDto().getGamers();
`ExecutionResult`는 도메인 객체인데, climbedGamers 상태를 dto로 변환해서 사용하고있네요 🤔
지우님은 언제 도메인에서 dto로 변환 되어야한다고 생각하시는지 궁금합니다 :)

2023-05-18 16:59 UTC, dave915 commented on src/main/java/nextstep/ladder/domain/Position.java
> +public class Position {
Position `VO` 👍

2023-05-18 16:59 UTC, dave915 commented on src/main/java/nextstep/ladder/domain/Position.java
> +            return new Position(value - 1);
왼쪽으로 이동하는 테스트가 없어보이는데.. 맞을까요? 🧐

2023-05-19 13:33 UTC, wsdf25867 commented
안녕하세요 다시 리뷰 요청드립니다!!

도메인 안에 `toDto`를 만들게 된 이유는 `getter` 의 사용을 피하려다 보니 도메인 안에 구현하게 되었습니다!

`ExecutionResult` 에서 dto를 사용해서 구현한 방법은 잘못된 방법 같습니다! 그래서 match 새로 메소드를 만들어서 로직을 수정했습니다

또 왼쪽으로 이동에 대한 테스트도 추가했습니다

2023-05-21 04:41 UTC, dave915 approved these changes
지우님 피드백 반영 확인했습니다! 💯 
다음 단계 진행 부탁드려요!

2023-05-21 04:41 UTC, dave915 commented on src/main/java/nextstep/ladder/domain/Gamer.java
> +    public Result match(List<String> executionResult) {
👍

2023-05-21 04:41 UTC, merged