Step2 - 사다리(생성)
next-step/java-ladder pull request #1786
Opened 2023-05-18 11:23 UTC by hoa0217

## 개요
사다리 생성 시 Point끼리 Line을 만들어주는 전략을 데코레이터 패턴으로 만들었습니다.
오버엔지니어링 아닌가  고민이 되었는데 혹 더 좋은 방법이 있다면 피드백 부탁드립니다~ 

## 작업사항
- Member 클래스 : 입력받은 이름을 갖는 클래스
- Members 클래스 : Member들을 갖는 일급 Collection 클래스 
- LadderInfo 클래스 : 입력받은 멤버들의 사이즈(width), 입력받은 높이(height)를 갖고 **Ladder를 생성하는 로직을 갖는 클래스**
- Ladder 클래스 : height 만큼 Row들을 갖는 일급 Collection 클래스 
- RowFactory 클래스 : Line생성전략을 주입받아 Row 생성 시 Point끼리 Line도 함께 만들어주는 클래스
- Row 클래스 : width 만큼 Point들을 갖는 일급 Collection 클래스
- Point 클래스  : 왼쪽, 오른쪽에 Line이 있는지 여부(`boolean`)를 갖는 Point 클래스

2023-05-19 16:21 UTC, lxxjn0 requested changes
정화님, 미션 구현하시느라 수고 많으셨습니다!! 👍🏼 

우선 코드 레벨에서 드릴 수 있는 피드백을 먼저 드렸는데 한번 확인해보시고 반영 부탁드릴게요!! 추가로 피드백을 보실 때 전체적인 코드에도 같이 반영해주세요! 동일한 피드백의 경우 추가로 남기지 않아서 전체 코드에 피드백 반영해주시면 좋을 것 같습니다 :)

2023-05-19 16:21 UTC, lxxjn0 commented on src/main/java/nextstep/laddergame/ui/InputView.java
> +public class InputView {
view의 메서드에서 도메인 생성까지 하고 있어요!! view의 역할에 맞게 로직을 명확히 나눠보면 어떨까요?

2023-05-19 16:21 UTC, lxxjn0 commented on src/main/java/nextstep/laddergame/README.md
> +- [x] Ladder 출력 시 사람 이름도 함께 출력한다.
구현할 기능 목록 작성 👍🏼

2023-05-19 16:21 UTC, lxxjn0 commented on src/main/java/nextstep/laddergame/ui/InputView.java
> +  private static final Scanner sc = new Scanner(System.in);
축약은 최대한 지양해주세요! 추가로 상수의 경우 상수명을 대문자로 작성해주세요

2023-05-19 16:21 UTC, lxxjn0 commented on src/main/java/nextstep/laddergame/factory/RowFactory.java
> +  static public Row createRow(int width, LineStrategy lineStrategy) {
키워드 순서가 잘못된 것 같아요!! public static 순서입니다!!

2023-05-19 16:21 UTC, lxxjn0 commented on src/main/java/nextstep/laddergame/domain/Members.java
> +public class Members {
일급 컬렉션으로 생성해주셨는데 일급 컬렉션을 둔 만큼의 역할이나 행위가 없는 것 같아요!! 일급컬렉션으로 만드신 이유가 무엇인가요?

2023-05-19 16:21 UTC, lxxjn0 commented on src/main/java/nextstep/laddergame/domain/strategy/LineStrategyNotTwoWay.java
> +  public boolean isCreateLine(Point leftPoint, Point rightPoint) {
이름이 조금 어색한 것 같아요!! canCreateLine 과 같은 이름도 좋을 것 같아요

2023-05-19 16:21 UTC, lxxjn0 commented on src/main/java/nextstep/laddergame/domain/strategy/decorator/LineStrategyDecorator.java
> +public class LineStrategyDecorator implements LineStrategy {
혹시 데코레이터 패턴을 사용하신 이유가 있을까요?

2023-05-19 16:21 UTC, lxxjn0 commented on src/main/java/nextstep/laddergame/ui/OutputView.java
> +    }
반복문과 조건문을 적절히 분리해서 리팩토링 해보는 것은 어떨까요? 지금의 코드는 너무 중첩이 심해서 가독성을 저해하는 것 같아요!!

2023-05-19 16:21 UTC, lxxjn0 commented on src/test/java/nextstep/laddergame/domain/LadderInfoTest.java
> +    assertThatThrownBy(() -> new LadderInfo(0, 0)).isInstanceOf(IllegalArgumentException.class);
여러 개의 assertion을 가질 때 assertAll 메서드를 주로 사용합니다!! 어떠한 차이가 있는지 한번 학습해보셔도 좋을 것 같아요!

2023-05-21 07:58 UTC, hoa0217 commented on src/main/java/nextstep/laddergame/factory/RowFactory.java
> +  static public Row createRow(int width, LineStrategy lineStrategy) {
이런 실수를... 감사합니다

2023-05-21 08:02 UTC, hoa0217 commented on src/main/java/nextstep/laddergame/domain/Members.java
> +public class Members {
불변객체로 만들기 위해 일급컬렉션으로 만들었습니다. 즉 `InputView.inputMembers()`를 제외하고는 코드 어디에서도 수정할 수 없도록 하기 위해서 입니다. 하지만 비즈니스적 역할 또는 행위가 없다면 일급컬렉션으로 굳이 만들 필요가 없나요?

2023-05-21 08:04 UTC, hoa0217 commented on src/main/java/nextstep/laddergame/ui/OutputView.java
> +    }
출력쪽 리팩토링하는걸 깜빡했습니다..! 넵 메서드 분리 및 스트림 사용해서 리팩토링 해보겠습니다.

2023-05-21 08:26 UTC, hoa0217 commented on src/main/java/nextstep/laddergame/domain/strategy/decorator/LineStrategyDecorator.java
> +public class LineStrategyDecorator implements LineStrategy {
`사다리 타기가 정상적으로 동작하려면 Line이 겹치지 않도록 해야 한다.`

라는 요구사항은 미션에 명시 되어있어 default로 지켜져야하는 부분이라고 생각했지만,

`각 Row 생성 시 랜덤하게 Point 사이를 이어주는 Line을 갖는다.`

라는 요구사항은 **제가 임의로 생각해서 만든 요구사항** 이기 때문에 언제든 변경될 수 있다 생각하였습니다.

그래서 `LineStrategyNotTwoWay`를 구현체로 만들고 `LineStrategyRandom`를 데코레이터로 만들어 언제든 조건을 추가하고 제거할 수 있도록 만들었습니다.

만약 랜덤하게 사이를 잇는게 아닌, 다른 요구사항이 생긴다면 그에 맞게 데코레이터를 구현해준 후 `LineStrategyNotTwoWay`를 감싸주면 됩니다.
`LineStrategy lineStrategy = new LineStrategyNewDecorator(new LineStrategyNotTwoWay());`

하지만 위에도 제가 질문드렸다시피 아직 다른 요구사항이 나온상황이 아닌터라,, 이게 오버엔지니어링이 아닐까? 라는 생각이 들어 질문드렸습니다.

2023-05-21 09:23 UTC, hoa0217 commented on src/test/java/nextstep/laddergame/domain/LadderInfoTest.java
> +    assertThatThrownBy(() -> new LadderInfo(0, 0)).isInstanceOf(IllegalArgumentException.class);
assertAll은 단언문들을 그룹화하여 순차적으로 실행할 수 있으며, 중간에 실패해도 나머지 단언문의 결과를 확인할 수 있다는 장점이 있네요..! 감사합니다.

2023-05-24 04:29 UTC, javajigi approved these changes
피드백 반영하느라 수고했어요. 👍 
객체를 작은 단위로 잘 분리했네요.
다음 단계가 사다리타기 미션의 핵심 미션인데요.
다음 단계 구현 기대할께요.

2023-05-24 04:29 UTC, merged