#  사다리게임 Step 4 미션 완료입니다.
next-step/java-ladder pull request #1815
Opened 2023-05-22 10:43 UTC by juno-junho

## 추후 수정 예정

2023-05-25 09:38 UTC, juno-junho commented on src/main/java/nextstep/ladder/controller/NextStepLadderGame.java
> +                break;
메서드 내에서 한 단계 들여쓰기만 하라고 객체 생활 체조 원칙에는 나와있는데,
depth가 2 에서 1로는 줄이기 힘들었습니다.

해결 할 수 있는 방법이 있을까요?

2023-05-25 16:09 UTC, csh0034 commented on src/main/java/nextstep/ladder/controller/LadderGame.java
> +/*
미사용 코드는 제거 또는 내부 코드르르 NextStepLadderGame 으로 변경해주시면 좋을것 같아요!

2023-05-25 16:14 UTC, csh0034 commented on src/test/java/nextstep/ladder/domain/nextstep/DirectionTest.java
> +class DirectionTest {
Direction 생성 및 움직임에 따른 단위테스트 추가 👍

2023-05-25 16:18 UTC, csh0034 commented on src/main/java/nextstep/ladder/domain/nextstep/NextStepLineCreator.java
> +        Direction first = Direction.first(strategy.makeBridge());
성능적으로는 크게 체감할만큼 이슈는 없을것 같아요.
다만, Line 에서 Point 수만큼 리스트를 가지고있기 때문에 Point 자체가 인덱스는 관리하지 않으며 
Direction 이 left, right 값을 관리하지 않고 단순히 어느 방향으로 움직여야하는지에 대해 enum 으로 나타낸다면
더 간결하게 표현할수도 있을것 같습니다.

2023-05-25 16:23 UTC, csh0034 commented on src/main/java/nextstep/ladder/controller/NextStepLadderGame.java
> +                break;
```java
  private void loopResult(Participants participants, Map<String, String> gameResult) {
    String input;
    while (!(Code.EXIT.equalsCode((input = getNameOrCodeForResult())))) {
      participants.validateResultInput(input);
      printResult(input, gameResult);
    }
  }
```

equalsCode 메서드를 추가한다면 depth 를 줄이기 위해 상단과 같이 처리해볼수도 있을것 같네요.
하지만 exit 에 대해선 요구사항에 있는 내용은 아니므로 기존방식 유지하셔도 될 것 같습니다 🙂

2023-05-25 16:42 UTC, csh0034 commented
질문 해주신 내용에 대해선 저도 크게 공감합니다.
TDD, in -> out 방식, 책임주도설계 에서 가장 중요한것은
요구사항으로부터 기능(역할)을 가진 도메인(객체)를 추출하고 설계하는 것입니다.

사실 이는 반복적인 학습과 경험을 토대로 점진적으로 발전한다고 생각해요.
다수의 여러 비슷한 경험을 했을때 요구사항으로 부터 책임을 가진 도메인을 더 상세하게
설계할수있으며 이에 대해 TDD 및 책임주도설계를 할수있다고 생각합니다.

물론 처음엔 어렵고 난해하다고 느껴질수 있기 때문에 연습과 실전을 경험하며
더 나은설계에 대한 고민을 계속해서 한다면 점차 체득하실수 있을거에요 🙂

2023-05-29 12:07 UTC, juno-junho commented on src/main/java/nextstep/ladder/controller/NextStepLadderGame.java
> +    public static final String DELIMITER = ",";
scanner를 통해서 입력을 받고 그것을 list로 controller에 넘겨 줄지, string으로 넘겨 줄 지 등, 입력에 대한 형식 처리는 inputview에서 처리하는것이 맞겠죠?

2023-05-29 12:18 UTC, juno-junho commented on src/main/java/nextstep/ladder/controller/NextStepLadderGame.java
> +                break;
> ```java
>   private void loopResult(Participants participants, Map<String, String> gameResult) {
>     String input;
>     while (!(Code.EXIT.equalsCode((input = getNameOrCodeForResult())))) {
>       participants.validateResultInput(input);
>       printResult(input, gameResult);
>     }
>   }
> ```
> 

이렇게 input을 메서드 안에서 정의해 줄 수 있다는 것을 처음 알았습니다..! 
자바를 잘 안다고 생각했는데 이렇게 사용할 수 있는 것은 처음 보네요

2023-05-29 12:40 UTC, juno-junho commented on src/main/java/nextstep/ladder/domain/nextstep/NextStepLineCreator.java
> +        Direction first = Direction.first(strategy.makeBridge());
이 방식에 대해서는 당연히 Point가 Boolean 값을 가지며, List의 Point의 index 값이 index를 대체할 수 있기 때문에 인스턴스 변수로 놔두는 것이 아니라, Direction을 enum으로 설정하여 LEFT, RIGHT, PASS로 설정하여 index 값을 조작하는 것이 옳은 방법이라고 생각합니다!
하지만, 제가 Point에서 index를 필드로 설정한 이유는, tdd 과정에 있어서 가장 작은것 (Point) 에서 큰것 (Ladder)로 점진적으로 확대하는 데 있어서, 바로 Line으로 시작을 하지 않는다면, tdd를 통해 Point를 먼저 생성함에 있어서 Point에서 index를 필드로 설정하여 테스트 작성하는 방법 (현재의 구조)가 나올 수 밖에 없는것 같습니다.

tdd로 기능이 잘 작동되도록 설정 한 후, 말씀하신 방식대로 Line의 List에서 index를 가지기에 Point의 index 상태값을 제거 할 수 있기에 리펙토링이 가능하지만 초기 방식에서는 Point를 건너 뛰고 Line부터 생성하지 않는 한 바로 적용하기는 힘들것 같은데 어떻게 생각하시나요?

2023-05-29 12:45 UTC, juno-junho commented
네 전체적인 말씀하신 부분을 바탕으로 리펙토링 해 보았습니다!
책임 주도 설계 강의를 보니 factory 패키지를 두어서 인터페이스와 구현 객체에 있어서 패키지내 순환 구조가 생기지 않도록 설정해 주더라고요. 
그런데 이 부분이 좀 이해가 안가는 것이, 현재 프로젝트가 작아서 그런지 순환구조가 생길것 같지 않아 보이고 `LadderFactoryBean`은 컨트롤러의 코드에서 Line을 생성하고 Ladder를 생성하는 것을 묶은 구조 밖에 되지 않아 보이는데 제가 이해하지 못하거나 놓치는 부분이 있을까요?

Point를 boolean값과 Direction을 필드로 가지고, Directiond은 방향을 나타내는 enum으로 refactoring하는 것은 메인 로직을 처음 부터 다시 tdd를 통해서 만들어야 할 것 같아 일단 리뷰 요청 후 시도해 보겠습니다!

2023-05-29 12:49 UTC, juno-junho commented
또한 테스트 작성하는데 있어서 미흡한 부분이 있는데, 현재 `LadderFactoryBean`나 `NextStepLadderCreator` 같은 부분은 어떻게 테스트 해야 할까요?
재성님은 sysout을 통해서 아래와 같이 값을 찍으시던데 이렇게 테스트 해도 되나요..?
```java
  @Test
    void create() {
        Line line = lineRepository.create(3);
        System.out.println(line);
    }
```

2023-05-30 09:38 UTC, csh0034 commented on src/main/java/nextstep/ladder/domain/nextstep/NextStepLineCreator.java
> +        Direction first = Direction.first(strategy.makeBridge());
Point 는 말그대로 사다리의 교차점이므로 어디로 움직일지에 대한 정보(Direction) 만 가지고있고 전달받은 위치값에 대해서 처리후 값을 반환한다면 테스트까지 가능하지 않을까요? 🤔
물론 지금처럼 인덱스를 가질수도 있지만 Point 는 Line 하위에서만 존재하는 개념이기 때문에 둘다 가능하다고 생각해요!

2023-05-30 09:43 UTC, csh0034 commented
우선 로그만 출력하는 테스트코드는 검증으로서 의미가 없기 때문에 꼭 필요해 보이진 않네요.
다만, `예외가 발생하지 않고 정상적으로 생성되었다.` 로도 볼수도있을것 같네요.

FactoryBean 과 Creator 의 경우엔 생성을 하는것 그자체가 존재 목적이기 때문에
테스트코드가 꼭 필요해보이진 않네요. 다만 위의 말씀드린 내용과 같이
`정상적으로 생성되었다.` 정도로만 두면 되지않을까 싶습니다.

2023-05-30 09:46 UTC, csh0034 requested changes
리팩토링 잘 진행 해주셨네요!
질문에 대한 답변 남겨 두었습니다.
지금 상태로 머지가능하지만 추가 리팩토링을 고민하시는
부분이 있는것 같아 request changes 로 두겠습니다.
만약 수정할 부분이 없다면 바로 리뷰 요청주시면 머지하도록할게요!

2023-05-31 13:23 UTC, juno-junho commented
수강신청 미션을 해야할것 같아 현재 상태로도 괜찮으면 바로 머지 부탁드립니다!
고생하셨습니다 :)

2023-05-31 14:02 UTC, csh0034 approved these changes
그동안 사다리 미션 진행하시느라
수고 많으셨습니다 😄

2023-05-31 14:02 UTC, merged