Step3
next-step/java-ladder pull request #1817
Opened 2023-05-22 14:48 UTC by JHyunJung

2023-05-23 07:03 UTC, testrace requested changes
안녕하세요 재현님 😃 
몇 가지 코멘트 남겼는데 확인해 주시고 다시 리뷰 요청해 주세요 
궁금한 점이나 의견 있으시면 편하게 DM 주세요

2023-05-23 07:03 UTC, testrace commented on src/main/java/nextstep/ladder/Line.java
> +    }
이 코드는 절차지향적 코드이고 테스트도 없네요 😢 
위치 이동과 관련된 객체를 도출하고 책임을 위임하면 어떨까요?

2023-05-23 07:03 UTC, testrace commented on src/main/java/nextstep/ladder/Ladder.java
> +    public Map<String, String> start(Participant participant, LadderResult ladderResult) {
이번 단계의 핵심 기능인데 테스트가 누락되었네요 😢 
모든 도메인 로직에 단위 테스트를 추가하면 좋을 것 같아요

2023-05-24 16:42 UTC, JHyunJung commented
코드 리뷰 반영 추가 하였습니다.

2023-05-24 16:42 UTC, JHyunJung commented on src/main/java/nextstep/ladder/Line.java
> +    }
해당 코드 같은 경우는 해당 메서드 관련하여 추가적인 객체가 필요할지 의문이고 어떤 객체를 만들어야 할지 생각이 나지 않네요.
테스트는 추가하였습니다.

2023-05-25 07:50 UTC, testrace commented on src/main/java/nextstep/ladder/Line.java
> +    }
라인이 가지고 있는 Boolean을 하나의 객체로 분리하고 메시지를 보낼 수 없는지 고려해 보시면 좋을 것 같아요
객체가 불필요하다고 판단되시면 메서드를 분리해서 indent라도 줄여보시면 좋을 것 같아요

2023-05-25 07:52 UTC, merged