🚀 1단계 - 스트림, 람다, Optional
next-step/java-ladder pull request #1906
Opened 2023-11-21 06:17 UTC by simbokyung98

안녕하세요 리뷰어님😆😆
1단계 구현 PR 요청드립니다!

사다리 미션 잘 부탁드립니다🐣

2023-11-21 13:20 UTC, seokhong requested changes
보경님 안녕하세요.
사다리타기 미션을 함께 할 리뷰어 김석홍입니다. 만나서 반갑습니다!

1단계 미션 잘 구현하셨습니다. 👍 
코드에 코멘트 조금 남겼습니다. 코멘트 확인 부탁드립니다. 🙂

2023-11-21 13:20 UTC, seokhong commented on src/main/java/nextstep/fp/Conditional.java
> +public interface Conditional {
함수형 인터페이스를 추가해서 사용하신 점 좋습니다. 👍 
`@FunctionalInterface` 어노테이션을 이용하여 명시적으로 함수형 인터페이스임을 표현해보면 어떨까요?

2023-11-21 13:20 UTC, seokhong commented on src/main/java/nextstep/fp/Lambda.java
> +    public static int sumAll(List<Integer> numbers, Conditional conditional) {
람다를 이용해 계산하도록 메서드 구현 잘 하셨고, 람다를 이용한 테스트도 좋습니다. 👍 

한편, 테스트 코드에서 람다를 정의하면, 프로덕션 코드에서 정의한 람다가 잘 동작하는지 테스트는 안 될 것으로 보여요.
프로덕션 코드에 있는 `sumAll`, `sumAllEven`, `sumAllOverThree` 코드에서 새로 만드신 `sumAll` 과 람다를 활용하도록 리팩터링하고, 기존에 있던 `LambdaTest` 코드를 통해 기존과 동일하게 동작하는지 검증해보는 건 어떨까요?

2023-11-21 13:20 UTC, seokhong commented on src/main/java/nextstep/fp/Lambda.java
> +            if(conditional.test(number)) {
`if` 키워드와 여는 소괄호(`(`) 사이에 공백이 누락됐네요.
IDE의 자동 줄맞춤 단축키를 사용하시거나, 파일을 저장할 때마다 자동으로 줄맞춤이 되도록 설정해보시면 좋겠습니다.

intellij를 사용하신다면 Preferences > Tools > Actions on Save 에서 자바 코드도 Reformat Code, Optimize Imports를 설정해서 수정하는 코드를 자동 줄맞춤, 임포트 최적화를 실행하도록 하실 수 있습니다. :)

2023-11-21 13:20 UTC, seokhong commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .sorted(Comparator.comparing(String::length))
긴 문자열을 출력해야 하니, 역순 정렬이 필요할 것으로 보이네요!
```suggestion
                .sorted(Comparator.comparing(String::length).reversed())
```

2023-11-21 13:20 UTC, seokhong commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .skip(100)
100개를 스킵하신 이유가 있을까요?

2023-11-21 13:20 UTC, seokhong commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .distinct()
`distinct()`를 먼저 호출한 후 `String::toLowerCase`를 호출하면 동일한 단어가 중복으로 나올 수 있지 않을까요?

2023-11-21 13:20 UTC, seokhong commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .collect(Collectors.toList());
최종적으로 `results.forEach`를 통해 출력만 하는 것이라면, `collect` 과정 없이 `forEach` 메서드 체이닝을 통해 출력하면 어떨까요?

2023-11-21 13:20 UTC, seokhong commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .filter(number->number>3)
여기도 띄어쓰기가 일부 누락됐네요. :)

2023-11-21 13:20 UTC, seokhong commented on src/main/java/nextstep/optional/User.java
> +        Optional<User> optionalUser = Optional.ofNullable(user);
`optionalUser`를 변수로 관리할 필요 없이, 바로 메서드 체이닝으로 이어가는 것은 어떨까요?

2023-11-22 01:01 UTC, simbokyung98 commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .skip(100)
앗 limit를 써야하는데 요구사항을 헷갈렸습니다! 수정하였습니다😲😲

2023-11-22 01:42 UTC, simbokyung98 commented
아직 람다와 스트림에 적응하고 있어서 자잘한 구현실수가 많네요😵😵
다음 단계에서도 계속 신경쓰면서 구현하겠습니다😢

2023-11-22 10:10 UTC, merged