3단계 - 사다리(게임 실행)
next-step/java-ladder pull request #2000
Opened 2023-12-06 06:52 UTC by sunggyupaik

# 사다리 게임

## 3단계 - 사다리(게임실행)

### 기능 요구사항
- 사다리 실행 결과를 출력해야 한다.
- 개인별 이름을 입력하면 개인별 결과를 출력하고, "all"을 입력하면 전체 참여자의 실행 결과를 출력한다.

### 프로그래밍 요구사항

- 자바 8의 스트림과 람다를 적용해 프로그래밍한다.
- 규칙 6: 모든 엔티티를 작게 유지한다.
- 규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

### 기능 목록 정리
- 결과 금액
  - [x] 결과 생성
- 게임
  - [x] 게임 실행
- 게임 결과
  - [x] 게임 결과 생성
- 화면
  - [x] 결과 금액 입력 받기
  - [x] 결과 금액 출력 하기
  - [x] 게임 결과 이름 입력 하기
  - [x] 참가자 게임 결과 출력 하기

2023-12-06 06:53 UTC, sunggyupaik commented
step3 완성했습니다 잘 부탁드립니다:)

2023-12-06 07:00 UTC, sunggyupaik commented
`Point`의 boolean 변수만 사용해서 사다리 게임을 진행하려니 너무 힘들었습니다. Point를 변수를 통해 계속 주고받는 과정에서 지저분해졌습니다.

따라서 Point를 왼쪽, 오른쪽으로 가지는 `Brace` 클래스를 하나 추가했습니다. 이 클래스를 통해 한번에 왼쪽과 오른쪽을 검사하여 쉽게 게임을 진행 할 수 있었습니다. 특히, 사다리의 index를 넣고 리턴하도록 하여 객체들은 index만 계산하도록 `move()` 메서드를 만들었습니다.

이번 과제의 흐름은 다음과 같습니다.

1. `Point`를 이용한 사다리 게임 구현
2. 게임 구현 코드 리팩토링
3. `Brace` 클래스를 추가하여 점진적으로 리팩토링 코드 작성
4. 신규 `Brace` 클래스로 완전 코드 대체
5. 게임 완성

2023-12-06 17:37 UTC, csh0034 requested changes
3단계 구현 잘해주셨네요 💯 
고민해주신 구조에 대해서 조금 더 
개선해보도록 몇가지 코멘트 남겨두었습니다.
확인후에 리뷰요청 부탁드려요!

2023-12-07 11:19 UTC, sunggyupaik commented on src/main/java/nextstep/ladder/LadderApplication.java
>  public class LadderApplication {
기본적인 순서가 지켜지지 않았네요 ㅠ
더불어 이번에도 뭔가 게임 진행이 제대로 안되는군요, `Brace`에서 나란히 가로줄이 있는 경우를 테스트했는데 사실 제가 만드는 방식으로 사다리 생성 예외가 발생 할 수 있네요, 이런 케이스들을 잘 고찰하고 테스트도 만들어야겠네요

2023-12-07 11:46 UTC, sunggyupaik commented on src/main/java/nextstep/ladder/domain/Point.java
>  public class Point {
저도 그 부분을 고민했었습니다. `Point`가 단지 getter로만 사용되는게 맞나 생각헀습니다.
말씀하신대로 `Brace`가 `Point`에 의존하되 `Point`가 left와 right를 관리하도록 개선했습니다!
따라서 좀 더 자신의 클래스에서 책임을 다할 수 있는 구조가 되었습니다.

2023-12-07 12:06 UTC, sunggyupaik commented on src/main/java/nextstep/ladder/LadderApplication.java
>  public class LadderApplication {
테스트 추가했습니다!

```java
private void checkBracesNotConnected(List<Brace> braces) {
        IntStream.range(0, braces.size())
                .filter(index -> notConnected(braces, index))
                .findFirst()
                .ifPresent(index -> {
                    throw new IllegalArgumentException("사다리가 정상적으로 이어져 있지 않습니다.");
                });
    }
```

2023-12-07 12:08 UTC, sunggyupaik commented on src/main/java/nextstep/ladder/domain/Brace.java
> +    private final Point leftPoint;
네 피드백에따라서 개선헀습니다~!

2023-12-09 08:20 UTC, csh0034 approved these changes
리뷰 반영 너무  잘해주셨네요 💯 
마지막단계에서 뵙겠습니다 😄

2023-12-09 08:20 UTC, csh0034 commented on src/test/java/nextstep/ladder/domain/BraceTest.java
> +public class BraceTest {
꼼꼼한 단위테스트 작성 너무 좋네요 💯

2023-12-09 08:20 UTC, csh0034 commented on src/test/java/nextstep/ladder/domain/LadderTest.java
> +    private static final Brace BRACE_LEFT = new Brace(true, false);
테스트를 위해 생성하는 대상을 테스트 픽스처 라고 합니다.
별도 fixtures 패키지를 만든후 하단과 같이 추가하여 공통적으로 호출하도록 해볼수도 있을것 같아요.

```java
public class BraceFixtures {
  public static Brace none() {
    return new Brace(false, false);
  }
  public static Brace left() {
    return new Brace(true, false);
  }
  public static Brace right() {
    return new Brace(false, true);
  }
}
```

2023-12-09 08:20 UTC, csh0034 commented on src/test/java/nextstep/ladder/domain/LadderGameTest.java
> +    void success() {
하단내용은 참고만 해주시면 됩니다.

주석이아닌 코드로서 구현 내용을 표현하는것이 가장 좋다고 생각합니다.
하지만 테스트 코드의 경우 어떤것을 테스트하고 표현하는지에 대한 
가독성이 중요하기 때문에 하단과 같이 주석을 추가해볼수도 있을것 같아요. 

```java
  /*  a   b   c   d
  *   | - |   |   |
  *   | - |   |   |
  *   |   | - |   |
  *   | - |   |   |
  *   1   2   3   4   
  */
```

2023-12-09 08:20 UTC, csh0034 commented on src/main/java/nextstep/ladder/domain/Line.java
> +    public int move(int index) {
brace 에게 한번더 메세지를 보내볼순 없을까요? 🤔
`return brace.move(...)`

2023-12-09 08:20 UTC, merged