🚀 3단계 - 사다리(게임 실행)
next-step/java-ladder pull request #2035
Opened 2023-12-19 13:40 UTC by hoon25

## 작업내용
- Step2 리뷰반영
- Step3 기능구현
- [Step2](https://github.com/next-step/java-ladder/pull/2028#pullrequestreview-1785131696)에 코멘트 달아주신 것 답변 달아두었습니다.!

리뷰 감사합니다🙇‍♂️🙇‍♂️

2023-12-19 22:10 UTC, javajigi requested changes
전체적인 객체 설계와 구현, 단위 테스트 코드 구현 💯 
현재 구조도 좋은데요.
좀 더 작은 단위의 객체를 추가함으로써 OOP의 잇점을 느껴보면 좋을 것 같아 피드백 남겨봤어요.

2023-12-19 22:10 UTC, javajigi commented on src/main/java/nextstep/ladder/domain/JoinMembers.java
> +    public JoinMembers(String names) {
👍

2023-12-19 22:10 UTC, javajigi commented on src/main/java/nextstep/ladder/domain/JoinMembers.java
> +    public static JoinMembers fromMemberNames(List<String> members) {
JoinMembers(String names) 생성자를 통해 같은 효과를 낼 수 있는데 굳이 이 메서드를 제공할 필요가 있을까?

2023-12-19 22:10 UTC, javajigi commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +    public Ladder(JoinMembers joinMembers, int height) {
```suggestion
    public Ladder(String names, int height) {
```

이 생성자도 부생성자로 추가하는 것은 어떨까?

2023-12-19 22:10 UTC, javajigi commented on src/main/java/nextstep/ladder/domain/Line.java
> +    public int move(int idx) {
이 메서드의 복잡도가 높으면서 가장 중요한 로직 구현을 담당하고 있다.
이 메서드 로직을 더 작은 단위의 객체를 추가함으로써 복잡도를 낮출 수 있는 방법은 없을까?

2023-12-19 22:10 UTC, javajigi commented on src/main/java/nextstep/ladder/domain/LineFactory.java
> +        List<Boolean> points = new ArrayList<>();
List가 가지고 있는 값이 Boolean이다.
원시값을 포장한다는 원칙을 적용해 Boolean을 객체로 분리할 경우 이 객체를 분리한 효과가 있을까?

2023-12-19 22:10 UTC, javajigi commented on src/test/java/nextstep/ladder/domain/LineTest.java
> +    void move() {
단위 테스트로 고려했을 때 한번에 너무 여러 가지 경우를 테스트하는 느낌이 든다.
한번에 값 5개로 검증하는 것이 아니라 값 2개씩 나눠 각 test case에 대한 로직을 검증하도록 개선해 보면 어떨까?

2023-12-20 23:06 UTC, hoon25 commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +    public Ladder(JoinMembers joinMembers, int height) {
그게 좋겠네요! 추가했습니다!

2023-12-20 23:07 UTC, hoon25 commented on src/main/java/nextstep/ladder/domain/JoinMembers.java
> +    public static JoinMembers fromMemberNames(List<String> members) {
삭제했습니다!

2023-12-21 10:30 UTC, hoon25 commented on src/main/java/nextstep/ladder/domain/Line.java
> +    public int move(int idx) {
LineDirection 클래스로 분할했습니다!

2023-12-21 10:32 UTC, hoon25 commented on src/main/java/nextstep/ladder/domain/LineFactory.java
> +        List<Boolean> points = new ArrayList<>();
생성에 대해서 일부 역할을 `LineDirection`으로 옮겼는데, 적절한지 고민이되네요..

2023-12-21 10:37 UTC, hoon25 commented on src/test/java/nextstep/ladder/domain/LineTest.java
> +    void move() {
넵 테스트를 분할했어요!

2023-12-22 01:48 UTC, javajigi approved these changes
피드백 반영 넘 잘 했네요. 💯 
LineDirection 추가하고 로직 분리하니 훨씬 더 깔끔해 졌네요.

마지막 4단계 리팩터링은 다음 피드백을 반영해 보거나, 인터페이스 기반으로 구현 도전해 보는 것은 어떨까요?

사다리 타기의 전체 흐름을 다음과 같은 구조로 구현해 보는 것은 어떨까?
main()은 MVC에서 Controller의 역할로 가능한 가볍게 구현해야 한다.
Controller 내에는 로직은 최대한 배제하고 Model과 View 사이의 연결 역할만 하도록 구현한다.

```java
public static void main(String[] args) throws Exception {
    Players players = InputView.createPlayers();
    Rewards rewards = InputView.createRewards();

    Ladder ladder = LadderFactory.createLadder(players.countOfPeople(), InputView.getHeight());
    OutputView.printLadder(players, ladder, rewards);

    MatchingResult matchingResult = ladder.play();
    LadderResult result = matchingResult.map(players, rewards);

    OutputView.printResult(result);
}
```

MatchingResult는 Map<Integer, Integer>에 대한 일급콜렉션 객체이다.
Map의 key는 시작 위치, values는 사다리를 실행한 결과 위치이다.

LadderResult는 위치 값만 가지고 있는 MatchingResult의 값을 이름과 결과로 매핑한 결과를 가지는 일급콜렉션 객체이다.

반드시 위와 같은 구조로 개발하지 않아도 된다.
단, 위 코드 힌트를 참고해 개선할 부분이 있으면 개선해 본다.

2023-12-22 01:48 UTC, javajigi commented on src/main/java/nextstep/ladder/domain/LineDirection.java
> +public enum LineDirection {
👍

2023-12-22 01:48 UTC, merged