사다리타기-1단계 리뷰 요청
next-step/java-ladder pull request #2053
Opened 2024-03-25 15:47 UTC by ljydapp214

사다리타기 1단계 구현 완료하여 리뷰 요청드립니다.

해당 단계는 간단한 구현이라 따로 질문 사항 없습니다. 

감사합니다.

2024-03-26 09:40 UTC, mskangg requested changes
안녕하세요
이번 미션 리뷰를 맡은 강민수입니다 🙇

1단계 구현 잘해주셨네요!
몇가지 피드백 남겨드렸으니, 확인부탁드립니다!

2024-03-26 09:40 UTC, mskangg commented on src/main/java/nextstep/fp/Conditional.java
> +    int getCondition(int total, int num);
```suggestion
    boolean getCondition(Integer number);
```

위와 같이 해야 간결하게 람다로 구현이 가능할것 같아요 🤔

2024-03-26 09:40 UTC, mskangg commented on src/main/java/nextstep/fp/Lambda.java
> +    public static int sumAll(List<Integer> numbers,Conditional conditional) {
하나의 메서드에서 인터페이스로 주는 조건을 활용해서 리턴하게 하는건 어떨까요?

```java
return numbers.stream()
                .filter(conditional::getCondition)
                .reduce(0, Integer::sum);
```

이렇게 구현한뒤 람다로 조건을 넣어주면 하나의 메서드로 가능할것 같습니다 😄

2024-03-26 09:40 UTC, mskangg commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .map(String::toLowerCase).forEach(System.out::println);
distinct 먼저한다면, toLowerCase 시 중복이 발생할수도 있을것 같아요 🤔
`aAa` `AaA`

2024-03-26 09:40 UTC, mskangg commented on src/main/java/nextstep/optional/User.java
> +                .filter(u -> u.getAge() != null)
map 으로 age 를 추출한뒤 filter를 걸어도 될것 같아요 😄

2024-03-26 12:53 UTC, ljydapp214 commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .map(String::toLowerCase).forEach(System.out::println);
제시해주신 예외가 존재했네요! 다시 반영해보겠습니다.

2024-03-26 12:56 UTC, ljydapp214 commented on src/main/java/nextstep/optional/User.java
> +                .filter(u -> u.getAge() != null)
꼼꼼함이 부족했던 것 같습니다. 좀 더 디테일을 챙겨야겠네요 ㅜㅜ

2024-03-26 13:00 UTC, ljydapp214 commented on src/main/java/nextstep/fp/Conditional.java
> +    int getCondition(int total, int num);
습관대로 진행하다보니 복잡한 형태로 람다를 구현하게 된 것 같습니다.
보통 람다는 최대한 간단하게 표현하는게 좋은 케이스일까요?

2024-03-27 06:42 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요! 👏 
그럼 다음 단계 진행해주세요
화이팅 🔥 🚀

2024-03-27 06:42 UTC, mskangg commented on src/main/java/nextstep/fp/Conditional.java
> +    boolean getCondition(int number);
👍 
https://github.com/next-step/java-ladder/pull/2053#discussion_r1539178362

간단하게 구현하는게 가독성 측면에도 좋죠 😄
재영님이 느끼기에 수정전과 지금의 차이를 느끼신대로 사용하시면 될것 같아요! 👍

2024-03-27 06:42 UTC, mskangg commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .distinct()
👍

2024-03-27 06:42 UTC, merged