3단계 - 사다리(게임 실행)
next-step/java-ladder pull request #2102
Opened 2024-04-03 12:51 UTC by oht1221

안녕하세요 한솔님 :) 3단계 리뷰 요청 드립니다!

2024-04-04 11:15 UTC, catsbi requested changes
안녕하세요 홍택님, 미션 진행 잘 해주셨어요 👏 
몇 가지 고민해보면 좋을 피드백 남겨드렸으니 확인해보시고
추가적으로, 현재 public한 함수에 대한 테스트 케이스가 좀 누락된 것 같아요. 
그리고 각 함수의 테스트 중 브랜치 커버리지(분기 검증)을 좀 더 채워보면 어떨까요?

피드백 확인 후 다시 리뷰요청 부탁드려요!

2024-04-04 11:15 UTC, catsbi commented on src/main/java/ladder/domain/Ladders.java
> +    return position;
개인적으로는 position의 좌표정보가 x값 뿐 아니라 y값도 있고 이를 관리하는 point가 있으면 어떨까 싶어요. 좀 더 정확한 위치정보를 파악하는 것이죠. 

그리고 이 경우 point를 Stack 자료구조로 관리하며 관리할수도 있어서 재밌을 것 같네요 ㅎㅎ 
해당 피드백이 흥미롭다면 한 번 해보셔도 좋을 것 같습니다.

2024-04-04 11:15 UTC, catsbi commented on src/main/java/ladder/domain/Prize.java
> +    }
정규표현식을 이용하면, 간결하게 해결될 수 있을 것 같네요 🤔

2024-04-04 11:15 UTC, catsbi commented on src/main/java/ladder/LadderGame.java
> +            .forEach(entry -> results.put(entry.getKey(), new PrizeDto(entry.getValue())));
```suggestion
    this.results.forEach(entry -> results.put(entry.getKey(), new PrizeDto(entry.getValue())));
```

stream()을 호출하지 않아도 상관 없을 것 같네요!

2024-04-04 11:15 UTC, catsbi commented on src/main/java/ladder/LadderGame.java
> +    final HashMap<String, PrizeDto> results = new HashMap<>();
참조타입은 최대한 추상화를 참조하도록 해주세요. 코드의 유연성을 떨어트릴 수 있습니다. 
```suggestion
    final Map<String, PrizeDto> results = new HashMap<>();
```

2024-04-04 11:15 UTC, catsbi commented on src/main/java/ladder/domain/Player.java
> +  private Prize prize;
사용하지 않는 변수로 보이네요!

2024-04-04 11:15 UTC, catsbi commented on src/main/java/ladder/rowgenerator/RowGeneratorRandom.java
>    private final int size;
사이즈는 인스턴스 변수가 아니라 매개변수로 받아서 필요한 만큼 만들어주도록 하는게 낫지 않을까요? 
stateful 하게 관리되지 않아도 될 객체로 보이네요!

2024-04-04 11:15 UTC, catsbi commented on src/main/java/ladder/domain/Row.java
> +      return values.get(cursor++);
next로 값을 꺼내기전에 hasNext()로 다음 값을 꺼낼 수 있는지 체크를 하는게 어떨까요?

2024-04-06 02:49 UTC, oht1221 commented on src/main/java/ladder/domain/Row.java
> +      return values.get(cursor++);
`hasNext()`를 구현해놓고 사용은 안했네요 😂 `hasNext()`로 다음 요소가 있는지 검사하도록 수정했습니다!

2024-04-06 03:45 UTC, oht1221 commented on src/main/java/ladder/LadderGame.java
> +            .forEach(entry -> results.put(entry.getKey(), new PrizeDto(entry.getValue())));
네 말씀해주신대로 `stream`호출 제거하였습니다! 감사합니다 :)

2024-04-06 03:46 UTC, oht1221 commented on src/main/java/ladder/LadderGame.java
> +    final HashMap<String, PrizeDto> results = new HashMap<>();
변수 자동완성을 사용하다 놓친 것 같네요 😂 `Map` 인터페이스로 수정하였습니다!

2024-04-06 03:46 UTC, oht1221 commented on src/main/java/ladder/domain/Player.java
> +  private Prize prize;
제거하였습니다!

2024-04-06 03:52 UTC, oht1221 commented on src/main/java/ladder/rowgenerator/RowGeneratorRandom.java
>    private final int size;
말씀해주신대로 굳이 객체에서 유지하고 있어야할 상태값이 아니네요 ㅎㅎ 실제 row 생성 메서드인 generate 메서드의 매개 변수로 수정하였습니다! 추가적으로, 입력된 size와 generator에 의해 생성된 Row의 크기가 다른 경우 예외처리를 추가하였습니다!

2024-04-06 04:02 UTC, oht1221 commented on src/main/java/ladder/domain/Ladders.java
>  public class Ladders implements Iterable<Row> {
아하, 첨에 여러 사용자별 사다리가 합쳐진 모양으로 생각으로 해서 `Ladders`로 명명했는데요, 다시 생각해보니 게임 내에서는 사다리 하나의 개념으로 보는게 더 맞을 것 같네요. 단수 형태로 수정하였습니다!

2024-04-06 04:43 UTC, oht1221 commented on src/main/java/ladder/domain/Ladders.java
> +    if (rows.size() == 0) {
객체에게 메세지를 보내는 방식! 아직 습관이 안돼서 신경쓰지 않으면 이런 코드가 자꾸 나오는 것 같네요 ㅠㅠ 수정하였습니다!

2024-04-06 04:47 UTC, oht1221 commented on src/main/java/ladder/LadderGame.java
> +            .split(","));
trim 사용하는 방식으로 수정하였습니다! :)

2024-04-06 05:04 UTC, oht1221 commented on src/main/java/ladder/domain/Ladders.java
>  public class Ladders implements Iterable<Row> {
아 처음에 사다리가 여러개 묶여있는 모습이라 생각해서 `Ladders`라고 네이밍했었는데, 다시 생각해보니 이 게임 상에서는 하나의 사다리로 보는게 맞을 것 같네요 :)  단수형으로 수정했습니다!

2024-04-06 05:30 UTC, oht1221 commented on src/main/java/ladder/domain/Prize.java
> +    }
input의 조건을 정규식으로 구성하여 validation 하도록 수정하였습니다!

2024-04-06 07:28 UTC, oht1221 commented on src/main/java/ladder/LadderGame.java
> +public class LadderGame {
말씀해주신대로 `LadderGame` 클래스를 stateless로 만들기 위해서 일단 인스턴스 변수들을 제거해야겠다는 생각을 해서  Players 와 Prize는 생성 시점을 최대한 늦춰서 지역변수로만 사용되도록 수정을 했습니다. 그런데 사다리 객체는 사다리 상태를 표시해주는 시점에 한 번 생성 하고, 후에 다시 게임 실행 시점에 재사용을 해야해서 어딘가 저장할 곳 없이는 불가능 하다는 결론에 이르렀습니다... 그래서 생각 해보다가 예전에 들었던 ThreadLocal이라는 것을 쓰면 인스턴스에 선언된 변수라도 같은 쓰레드에서만 공유하니까 괜찮지 않을까? 해서 사용해보았습니다. 완전히 Ladder 저장 변수를 없애는 방법은 아직 생각이 안나서 일단 이렇게 구현을 마무리 했습니다 ㅠ

2024-04-06 13:18 UTC, oht1221 commented
안녕하세요 한솔님! 3단계 두 번째 리뷰 요청드립니다 :) 코멘트로 남겨주신 부분들을 반영하고, 전체적으로 테스트 메서드들을 보강하였습니다! 그리고 이동하는 책임은 Player에게 있는 것이 더 타당해 보여서 Ladder에서 Player로 옮겼습니다!

2024-04-07 12:14 UTC, catsbi approved these changes
홍택님 피드백 반영 잘 해주셨어요 ㅎㅎ 테스트코드도 꼼꼼하게 작성해주셨네요 👍 
ThreadLocal 쓰신 부분도 인상깊게봤습니다.  사용 후 remove()로 클리어 해주시는부분도 💯 

그럼 다음 미션으로 넘어가시죠 머지하도록 하겠습니다!

2024-04-07 12:14 UTC, catsbi commented on src/main/java/ladder/Main.java
> +  private static List<String> csvParser(final String text) {
지금은 문제가 없습니다. 나중에~ 여기서 좀 더 심화할 때 고민해보면 좋을 것 같아 코멘트 남겨드리는데, 
입력값에 대한 분리나 공백제거등도 컨트롤러에서 할만한 역할로는 적절하지 않습니다. 공백제거와 문자열 분리역시 테스트 대상이기도 하기 때문이죠. ArgumentResolver와 책임사슬패턴을 고민해보면 좋을 것 같아요.

2024-04-07 12:14 UTC, catsbi commented on src/main/java/ladder/domain/Ladder.java
> +    }
Stream API를 활용하거나 함수로 분리해줘도 좋을 것 같네요!
```suggestion
    boolean hasInvalidRow = rows.anyMathch( ... );
    if(hasINvalidRow) { ... }
```

2024-04-07 12:14 UTC, catsbi commented on src/main/java/ladder/domain/Player.java
> +  }
다음 미션에서는 이 위치정보 역시 일급 객체로 분리되면 좋을 것 같네요!

2024-04-07 12:14 UTC, catsbi commented on src/main/java/ladder/service/LadderGameService.java
> +            .collect(Collectors.toList()));
매개변수 입력 위치에 다른 함수 호출이나 로직을 작성해서 반환값을 전달하는 방식은 코드의 가독성측면이나, 디버깅 측면에서 비권장드립니다. 그래서 기본적으로는 권장드리지는 않아요 ㅎㅎ

2024-04-07 12:14 UTC, catsbi commented on src/main/java/ladder/service/LadderGameService.java
> +    }
Stream API를 활용해보면 어떨까요?

2024-04-07 12:14 UTC, merged

2024-04-10 12:23 UTC, oht1221 commented on src/main/java/ladder/domain/Ladder.java
> +    }
메서드로 분리하였습니다 :)

2024-04-10 12:29 UTC, oht1221 commented on src/main/java/ladder/service/LadderGameService.java
> +    }
Players는 일급 객체로 만들어놓은 상태라, 만약 Stream API를 사용한다면 일급컬렉션에서 콜렉션 객체를 꺼낸 후에 적용이 가능할 것 같은데요, 혹시 그 방식을 말씀하시는 걸까요?

2024-04-10 12:30 UTC, oht1221 commented on src/main/java/ladder/Main.java
> +  private static List<String> csvParser(final String text) {
`ArgumentResolver`, 책임 사슬패턴 한 번 찾아서 공부 해보겠습니다!

2024-04-10 12:31 UTC, oht1221 commented on src/main/java/ladder/domain/Player.java
> +  }
네 4 단계에서 위치 정보를 따로 분리하였습니다 :)