🚀 2단계 - 사다리(생성)
next-step/java-ladder pull request #2110
Opened 2024-04-05 03:39 UTC by kimsunghyun1995

안녕하세요 2단계 PR 합니다.

요구사항에 stream을 적극 사용하라고 나와있는데, 무언가 사용할 곳이 없는 느낌이네요,,

resultView 구현하는 것도 어렵네요

2024-04-05 11:17 UTC, wooobo requested changes
안녕하세요 성현님!

2단계 잘 진행해주셨어요~
코멘트 남겨 놓았어요,
확인 후 재요청 부탁드려요~

그럼 즐거운 금요일 저녁되세요~

2024-04-05 11:17 UTC, wooobo commented on src/main/java/nextstep/ladder/ResultView.java
> +            line.getPoints().forEach(point -> {
view 입장에서 `Point`객체까지 알게하고 싶지 않네요 🤔 

```suggestion
            line.pointsToBoolean().forEach(point(Boolean 타입) -> {
```

가공해서 리턴해주는건 어떨까요?

- 규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

어쩌면 게터를 사용하지 말라는 많은 이유중 하나는, 
무조건 값을 내보내기 보다는 원하는 메시지를 받고 그에 대한 값을 패키징해서 보내주라는 것일수도 있겠네요 🤔

2024-04-05 14:50 UTC, kimsunghyun1995 commented on src/main/java/nextstep/optional/User.java
> +	private static boolean isAgeOver30Under45(User user) {
수정사항 변경시 메소드 명도 변경해야겠네요,,
좀 더 제너럴하게 메소드명 수정하겠습니다!

2024-04-06 01:44 UTC, wooobo requested changes
안녕하세요 성현님!

피드백에 대해 고민해주셔서 감사합니다~
코멘트 확인 부탁드려요~

벚꽃이 피었네요~
즐거운 주말 되세요~

2024-04-06 01:44 UTC, wooobo commented on src/main/java/nextstep/ladder/view/ResultView.java
> +            }
```suggestion
            if (point) {
                printLine();
            } else {
                printGap();
            }
```
for-if 2뎁스군요.
로직의 행동을 표현해보아요.

2024-04-06 01:44 UTC, wooobo commented on src/main/java/nextstep/ladder/domain/LadderBoard.java
> +    public LadderBoard(int countOfHeight, int countOfPerson) {
```suggestion
    public LadderBoard(int 행, int 열) {
```

`LadderBoard`의 입장에서 너무 과한 개념이 들어간 이름들 아닌가요?
`LadderBoard`내부에서는 어떻게 사용하나요?

복잡한 의미를 내포하고 있는 의미는 우리의 머릿속을 복잡하게 만들지 않을까요?
어쩌면 외부에서의 이름을 객체에게 계속 강요하고 전파하고 있는거 아닌가요?

2024-04-06 01:44 UTC, wooobo commented on src/main/java/nextstep/ladder/domain/Line.java
> +            points.add(new Point(() -> isBeforeDrawLine(prevIndex)));
```suggestion
            boolean finalCurrentPoint = isCurrentPoint;
            Point currentPoint = new Point(() -> isBeforeDrawLine(finalCurrentPoint));
            ...
```

`i-1`같은 표현은 복잡한것 같아요.
이전의 상태를 기억하는 형태는 어때요.
결국 원하는것은 이전의 bool아닌가요?

2024-04-06 01:44 UTC, wooobo commented on src/main/java/nextstep/ladder/domain/Line.java
> +        if (foundOverLab)
```suggestion
        if (isFoundOverLab())
```

복잡한 스트림 구조를 의미있는 이름과 함께 `단일책임`,`순수함수` 형태로 표현하면 어떨까요?

2024-04-06 01:44 UTC, wooobo commented on src/main/java/nextstep/ladder/domain/UserNames.java
> +        if(stringNames.stream().anyMatch(name -> name.length() > 5))
어쩌면 구현하신 코드는 컴퓨터적인 언어아닐까요?
코드는 인간의 언어를 표현하는 것일까요 컴퓨터적인 표현을 하는것일까요?

```suggestion
        if(is_초과글자있어?(stringNames))
```

우리가 사용하는 말로 표현하면 어떠한 장점이 있을까요?

2024-04-06 01:44 UTC, wooobo commented on src/main/java/nextstep/ladder/view/InputView.java
> +		Scanner scanner = new Scanner(System.in);
매번 `Scanner`를 생성할 필요가 있을까요? 자원의 낭비 아닌가요?
재활용할수 없을까요?

2024-04-06 01:44 UTC, wooobo commented on src/test/java/nextstep/ladder/LineTest.java
> +        Line line = new Line(List.of(new Point(false),new Point(true),new Point(false)));
```suggestion
        Line line = new Line(List.of(false,true,false));
```

생성자를 다양하게 사용할수 없을까요?

2024-04-06 01:44 UTC, wooobo commented on src/test/java/nextstep/ladder/LineTest.java
> +        assertThat(line.pointToBoolean().get(1)).isEqualTo(true);
값을 꺼내야하나요?
정말 궁금한것은 무엇인가요?

```suggestion
        assertThat(line.pointToBoolean()).containsExactly(...);
```

객체를 단순한 자료구조로 바라보기 보다는 어떠한 상태를 주체적으로 관리하는 객체로 생각해보아요.

```suggestion
        assertThat(line.findPoint(1)).isEqualTo(true);
```

`pointToBoolean` 가 궁금한것인가요, 위치에 따른 상태가 궁금한것인가요?

2024-04-06 01:44 UTC, wooobo commented on src/test/java/nextstep/ladder/PointTest.java
> +		assertThat(point.isActive()).isEqualTo(false);
```suggestion
		assertThat(point.isActive()).isFalse();
```

직관적으로 표현해보아요.

`False 이거와 같아?` vs `False야?` 🤔

2024-04-07 10:05 UTC, kimsunghyun1995 commented on src/main/java/nextstep/ladder/domain/Line.java
> +        if (foundOverLab)
위처럼 변경하면, 해당 함수가 단일책임을 갖는다는 건 이해했습니다!
근데 순수함수 형태로 표현한다는게 잘 이해가 안가는데, 자세히 설명해주실 수 있을까요?

2024-04-07 10:10 UTC, kimsunghyun1995 commented on src/main/java/nextstep/ladder/domain/UserNames.java
> +        if(stringNames.stream().anyMatch(name -> name.length() > 5))
음.. 우리가 사용하는 말로 표현하면, 코드가독성이 좋아질 것 같습니다!

또한, 메서드 구현내용을 볼 필요없이, 메소드명으로만 유추가능하겠네요

2024-04-07 10:22 UTC, kimsunghyun1995 commented on src/test/java/nextstep/ladder/LineTest.java
> +        Line line = new Line(List.of(new Point(false),new Point(true),new Point(false)));
이전에 `List<Bollean> points` 매개변수를 가지는 생성자를 만들었을 때, 제네릭 오버로딩 문제로 따로 만들 수 없었네요,,
다른 방법이 있을까요?

2024-04-07 10:25 UTC, kimsunghyun1995 commented on src/test/java/nextstep/ladder/LineTest.java
> +        assertThat(line.pointToBoolean().get(1)).isEqualTo(true);
해당 테스트는 라인이 제대로 생성됐는지 확인하려는 목적입니다.
`containsExactly` 사용이 맞는 것 같습니다!

2024-04-07 10:28 UTC, kimsunghyun1995 commented on src/main/java/nextstep/ladder/domain/LadderBoard.java
> +    public LadderBoard(int countOfHeight, int countOfPerson) {
음.. 생각해보지 못한 내용이네요

말씀해주신대로 내부에서 사용하는 목적에 따라 네이밍을 하는 것이 좋은 것 같습니다!

2024-04-07 14:22 UTC, wooobo approved these changes
안녕하세요 성현님!

2단계 수고많으셨습니다!
`merge`진행하겠습니다!

그럼 다음 단계도 기대하겠습니다~

2024-04-07 14:22 UTC, wooobo commented on src/main/java/nextstep/ladder/domain/UserNames.java
> +    public int getUserCount() {
일급콜렉션은 하나의 리스트를 가지는 객체일텐데, `size()`라고 해도 충분하지 않을까요?

저는 그냥 일급콜렉션은 여러값을 관리하는 책임을 가지는 객체라고 해서 특별한 내부로직이 있지 않으면 size라고 하는편입니다.


```
ex)
List<Boolean> result = new ArrayList<>();
result.size();
```
`result.getSize()` 이상하지 않나요? 우리가 만든 일급콜렉션이라고 한다고 뭐가 다른걸까요?

2024-04-07 14:22 UTC, wooobo commented on src/main/java/nextstep/ladder/view/InputView.java
> +        System.out.println("참여할 사람 이름을 입력하세요. (이름은 쉼표(,)로 구분하세요)");
`NAME_DELIMITER` 값이 변경되면 혼란스러울것 같아요 😂 
우리가 만든 프로그램을 시간이 지나서도 변경에 용이하게 할 수 있는 부분이 없을지 고민해보아요~

2024-04-07 14:22 UTC, wooobo commented on src/test/java/nextstep/ladder/PointTest.java
> +    @DisplayName("라인 그리기 생성 성공 테스트")
`라인 그리기 생성 성공 테스트` 설명이 `PointTest`에서 사용하기 어색하지 않아요?

2024-04-07 14:22 UTC, merged