Step4 - 사다리(리팩터링)
next-step/java-ladder pull request #2126
Opened 2024-04-08 13:02 UTC by namhyeop

안녕하세요 용주님
마지막 과제 리팩토링 작업 진행해서 PR 올립니다!

이전 Step3에서 주신 피드백들 반영 + 인터페이스화 작업 진행했습니다.
궁금한점이나 이해안가시는 코드들 피드백 부탁드려요 😄

2024-04-09 00:10 UTC, testrace requested changes
안녕하세요 남협님 😃 
몇 가지 코멘트 남겨두었습니다.
확인해 주시고 다시 리뷰 요청 부탁드려요

2024-04-09 00:10 UTC, testrace commented on src/main/java/nextstep/ladder/domain/result/Results.java
> +    }
정적 팩토리 메서드로만 생성한다면 생성자는 private으로 변경하면 어떨까요?

2024-04-09 00:10 UTC, testrace commented on src/main/java/nextstep/ladder/domain/result/LadderResult/LadderResult.java
> +public interface LadderResult {
거의 모든 클래스를 인터페이스로 만들어 주셨네요
책임주도 설계를 의도하고 리팩토링 하신건지 궁금합니다 🤔 
추가로 In-Out 방식으로 TDD를 도전해 보라는 요구사항이 있는데요.
이 부분은 커밋 로그로는 확인이 어려웠어요. 
아직 안해보셨다면 도전해 보시고 그 흔적으로 커밋 로그로 남겨보시면 어떨까요?
해 보셨다면 Out-In, In-Out 차이에 따라 어떤 변경이 있었는지(혹은 없었는지) 의견을 남겨주시면 좋을 것 같아요

2024-04-09 09:10 UTC, namhyeop commented on src/main/java/nextstep/ladder/domain/ladderConnectOrder/LadderConnectOrder.java
> +package nextstep.ladder.domain.ladderConnectOrder;
코드 컨벤션 확인하고 수정해두겠습니다!

2024-04-09 09:10 UTC, namhyeop commented on src/main/java/nextstep/ladder/domain/lines/Lines.java
> +    public Lines(int height, List<LadderConnectOrder> randomLadderConnectOrders) {
이 부분 피드백 반영해놓겠습니다!

2024-04-09 09:52 UTC, namhyeop commented on src/main/java/nextstep/ladder/domain/lines/direction/Direction.java
> +    int move(int currentIndex);
이 부분은 제 상상력(?)이 반영되어 있는 부분인데요
사다리의 이동이 꼭 한 칸만 증가하는거는 아닐 수 있을꺼 같아서 분리해봤습니다

2024-04-09 09:53 UTC, namhyeop commented on src/main/java/nextstep/ladder/domain/lines/direction/impl/MoveDirection.java
> +package nextstep.ladder.domain.lines.direction.impl;
개발자가 인터페의스의 구현체를 선택할 때 가독성이 올라갈거 같습니다.
혹시 다른 장점이 있다면 피드백 부탁드려요!

2024-04-09 09:53 UTC, namhyeop commented on src/main/java/nextstep/ladder/domain/result/Results.java
> +    }
이 부분 피드백 반영해놓겠습니다

2024-04-09 10:01 UTC, namhyeop commented on src/main/java/nextstep/ladder/domain/result/LadderResult/LadderResult.java
> +public interface LadderResult {
책임주도 설계 기준으로 리팩토링을 진행해봤습니다.

In-Out 방식으로 TDD를 도전하는건 Step3에서 구조를 바꾸면서 이미 진행을 해서 추가적으로 작업을 하지는 않았어요
개인적으로 Out-In 방식은 알고리즘 문제를 푸는것과 같이 구현에만 집중되어 코드라인수를 짧게 구현을 할 수 있었던 장점이 있엇던거 같아요. 

하지만 Step3의 용주님 피드백중에 TDD로 도전을 해보시는게 어떻냐고 해서 객체 구조를 다시 잡고, 테스트 하기 어려부분을 분리하여  In-Out 방식으로 진행하려고 하니 기존의 코드들에 대한 가독성과 이해가 힘들었던것 같습니다.

사실상 제가 레거시 코드를 만들고 리팩토링을 한건데 매우 많은 시간을 소모했었네요.
하지만 위와 같이 In-Out 방식으로 리팩토링을 진행했더니 인터페이스를 추출할 때는 굉장히 빠르게 진행했던것 같습니다.
실제 서비스하는 코드는 아니라 테스트 코드들을 통해 안정성을 느낀다는것을 백프로 느끼지는 못하지만 테스트코드들이 있기에 앞으로의 리팩토링이 어렵지는 않을것 같아요

2024-04-10 04:00 UTC, testrace approved these changes
안녕하세요 남협님 😃 
피드백 반영 잘해주셨네요 👍 
사다리 미션은 여기서 마무리하겠습니다
다음 미션도 화이팅입니다 🔥

2024-04-10 04:01 UTC, merged