4단계 - 사다리(리팩터링)
next-step/java-ladder pull request #2131
Opened 2024-04-10 13:05 UTC by oht1221

- 사다리 최소 단위를 Sides라는 객체로 수정
- Sides는 점 사다리 교차점에서 좌, 우에 선이 있는지를 판단하는 객체

2024-04-11 11:36 UTC, catsbi requested changes
홍택님 4단계 리팩터링 미션 진행하시느라 고생하셨습니다 👍 
그런데 현재 개발 부분들이 TDD로 작성되었는지 파악하기에는 커밋이 하나뿐이라 확인이 힘든 문제가 있습니다, 또한 현재 실행시 예외가 발생하고 있는데 확인이 필요해보이네요!. 

그리고 현재 service영역에 대한 테스트와 플레이어 일급 컬렉션의 iterator 테스트 등이 부족한 것 같아요. 확인 후 다시 리뷰요청 부탁드려요!.

2024-04-11 11:36 UTC, catsbi commented on src/main/java/ladder/domain/Coordinates.java
> +  private final Integer y;
Wrapper타입은 명확한 이유가 있는게 아니라면 Primitive타입 사용으로 바꿔주세요! 객체 생성비용측면이나, 의도치않은 오토박싱/언박싱 문제도 있습니다.

2024-04-11 11:36 UTC, catsbi commented on src/main/java/ladder/domain/Coordinates.java
> +    cache[y][x] = this;
생성자에서 캐시에 추가하는건 적절한 책임으로 보이지는 않아요. 차라리 정적 팩토리 함수(of)에서 객체 생성 후 캐시추가 및 반환하는식으로 하는게 어떨까요?

2024-04-11 11:36 UTC, catsbi commented on src/main/java/ladder/domain/Direction.java
> +}
Direction이 이동 방향으로의 정보를 가지고 있다면 Coordinates에서 right, left와 같은 각각의 함수가 필요 없지 않을까요? 

```suggestion
public enum Direction {
  LEFT(Coordinates.of(-1,0))
  
  ...
  
  public Coordinates move(Coordinates target) {
      return target.move(this.coordinates);
  }
}
```

2024-04-11 11:36 UTC, catsbi commented on src/main/java/ladder/service/LadderGameService.java
> +      Coordinates lastPosition = player.move(ladder);
지금 실행시 다음과 같이 에러가 발생하고 있습니다. 확인 부탁드려요 ㅎ
![image](https://github.com/next-step/java-ladder/assets/43158866/4cb76be0-8341-4332-a454-06c0cb0d7322)

2024-04-11 11:36 UTC, catsbi commented on src/main/java/ladder/rowgenerator/RowGeneratorRandom.java
rowReducer, rowCombiner 함수는 사용하지 않는 것으로 보이는데 사용하지 않는 함수는 제거해주시면 좋을 것 같습니다!

2024-04-14 03:12 UTC, oht1221 commented on src/main/java/ladder/domain/Coordinates.java
> +    cache[y][x] = this;
아 말씀해주신대로, 생성자에 객체 초기화 외 추가 로직을 포함시키는건 적절하지 않은 것 같네요. 팩터리 메서드의 역할로 옮겼습니다!

2024-04-14 03:13 UTC, oht1221 commented on src/main/java/ladder/domain/Coordinates.java
> +  private final Integer y;
전체적으로 불필요한 Wrapper 타입들을 원시타입으로 수정하였습니다 ;)

2024-04-14 04:51 UTC, oht1221 commented on src/main/java/ladder/service/LadderGameService.java
> +      Coordinates lastPosition = player.move(ladder);
`Coordinates` 의 캐시 크기를 10x10으로 고정시켜 두고 캐싱해서 생긴 문제였습니다. 캐시 구조를 변경하여 수정했습니다. 리뷰 감사합니다!

2024-04-14 04:52 UTC, oht1221 commented on src/main/java/ladder/rowgenerator/RowGeneratorRandom.java
불필요한 메서드 제거하였습니다!

2024-04-14 05:58 UTC, oht1221 commented on src/main/java/ladder/domain/Direction.java
> +}
말씀해주신대로, Direction enum 객체에 추가하였습니다. :) 동시에 `Coordinates`가 가지고 있던 `downRight`과 같은 이동 로직들은 제거하였습니다. `right()` 메서드는 이동에서는 사용되지 않고 `Point` 의 `next` 팩터리 메서드에서 사용되어서 남겨두었습니다 :)

2024-04-14 15:16 UTC, catsbi approved these changes
홍택님 4단계 미션 피드백까지 반영 잘 해주셨어요. 소소한 피드백 추가적으로 몇 개 남겨드렸으니 이건 따로 고민해보면 좋을 것 같습니다. 

끝까지 피드백 반영하시느라 고생많으셨고, 포기안하셔서 저도 좋았습니다 💯 
그럼 사다리 미션은 여기서 마무리 짓도록 하겠습니다 고생하셨습니다!

2024-04-14 15:16 UTC, catsbi commented on src/test/java/ladder/domain/PlayerIteratorTest.java
> +public class PlayerIteratorTest {
테스트에 함수명은 자바 컨벤션을 맞춰주는게 일관성측면이나 가독성측면에서 도움이 될 꺼에요. 그리고 테스트가 지금은 많아야 2자리수이기에 문제가 없지만 세자리수로 많아질수록 하나하나의 테스트를 확인하기 힘듭니다. 그래서 DisplayName같은 애노테이션의 설명이나 함수명이 중요해집니다. 이런 경우를 위해 어떤 테스트인지에 대한 설명이 좀 더 추가되면 좋을 것 같아요

2024-04-14 15:16 UTC, catsbi commented on src/test/java/ladder/service/LadderGameServiceTest.java
> +  );
픽스쳐가 재사용될 수 있을 것 같다면, 픽스쳐 클래스를 분리해서 관리하시는것도 좋습니다 ㅎㅎ

2024-04-14 15:16 UTC, catsbi commented on src/main/java/ladder/service/LadderGameService.java
>    private final ThreadLocal<Ladder> threadLocal = new ThreadLocal<>();
스레드로컬을 잘 활용하는건 좋습니다!. 그런데 사실 서비스영역은 상태를 관리하지 않는게 클린아키텍처적으로 볼 때 권장됩니다. 
그래서 추상화된 LadderGameRepository를 만들고 이를 인프라 레이어에서 구현체로 연결시키는걸 권장드려요. 
그럼 ThreadLocal을 쓰던 InMemory를 쓰던 Jdbc나 JPA를 쓰던 아무 문제가 없고 서비스계층은 행위에만 집중할 수 있으니까요 ㅎㅎ

2024-04-14 15:16 UTC, merged