🚀 3단계 - 사다리(게임 실행)
next-step/java-ladder pull request #2149
Opened 2024-04-15 17:33 UTC by jioome

자세한 리뷰 감사합니다! 이번 리뷰도 잘 부탁드립니다~~

2024-04-16 14:05 UTC, kyucumber requested changes
사다리 게임 실행 잘 구현해주셨네요.

간단한 몇가지 코멘트 남겨두었으니 참고 부탁드립니다.

2024-04-16 14:05 UTC, kyucumber commented on src/main/java/nextstep/ladder/domain/Line.java
> +		if (leftBridge.isBridge()) {
중요한 부분은 아니나 if를 두번 사용해서 객체지향 생활 체조 원칙의 else를 사용하지 않는다를 위반하고 있네요.

If를 두번 쓰는 것은 else를 쓰는 것과 다르지 않습니다.

메서드 추출 등을 통해 개선해볼 수 있을 것 같아요.

2024-04-16 14:05 UTC, kyucumber commented on src/main/java/nextstep/ladder/domain/Line.java
> +		if (getBridge(bridges.size() - 1).isBridge()) {
left, right와 다르게 변수로 추출되지 않아서 의도가 잘 드러나지 않는 것 같아요. 이 부분도 메서드를 추출해 getBridge(bridges.size() - 1)이 어떤 것을 나타내는지 의도를 드러낼 수 있을 것 같네요.

2024-04-16 14:05 UTC, kyucumber commented on src/main/java/nextstep/ladder/domain/Line.java
> +		if (index >= 0 && index < bridges.size()) {
이 조건이 의미하는건 무엇일까요? 메서드를 통해 의도를 드러내면 어떨까요?

2024-04-17 13:34 UTC, jioome commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +		while (row != lines.size()){
버그가 발생할 수 있겠군요..! 다른 조건으로 변경해보겠습니다~

2024-04-17 13:42 UTC, jioome commented on src/main/java/nextstep/ladder/domain/Line.java
> +		if (leftBridge.isBridge()) {
감사합니다! 객체지향 생활 체조 원칙에 맞게 변경해보겠습니다~

2024-04-17 13:45 UTC, jioome commented on src/main/java/nextstep/ladder/domain/Line.java
> +		if (index >= 0 && index < bridges.size()) {
메소드 이름으로 어떤 역할을 하고 있는지 한눈에 알 수 있도록 신경써서 지어야겠네요! 감사합니다~

2024-04-17 14:05 UTC, jioome commented on src/main/java/nextstep/ladder/domain/Line.java
> +		if (leftBridge.isBridge()) {
새로 커밋한 내역처럼 if 문이 있는 코드를 각각 메서드 추출하는 것이 좋다고 이해했는데 
수정한 부분 확인 부탁드립니다!!~

2024-04-17 14:51 UTC, kyucumber commented on src/main/java/nextstep/ladder/domain/Line.java
> +		if (index >= 0 && index < bridges.size()) {
그리 중요한 부분은 아니지만 의도와 다른 부분이 있는 것 같아 코멘트 남깁니다. 저는 getBridge 메서드의 이름을 변경하는게 아니라     
`index >= 0 && index < bridges.size()` 조건이 어떤 것을 의미하는지 메서드로 추출되면 어떨까 해서 말씀드렸어요.

2024-04-17 14:52 UTC, kyucumber approved these changes
남긴 코멘트 중 의도가 잘못 전달된 부분이 있는 것 같아 답변 남겨두었습니다. 확인 부탁드려요.

잘 구현하셔서 다음 단계 진행을 위해 머지하도록 할게요.

2024-04-17 14:52 UTC, merged