사다리(게임실행)기능을 구현했습니다.
next-step/java-ladder pull request #2166
Opened 2024-04-29 14:17 UTC by yuus95

## 작업 내용
- 사다리 게임 기능 구현

## 질문
move 테스트코드가 전반적으로 부족함 느낌이 들었습니다.. 우선 당일 작업 내용으로 추가적인 피드백을 받은 뒤 다시한번 테스트코드를 작성해보면 어떨까 싶어서...
금일내로 작업한 내용을 우선적으로 리뷰요청드립니다!

2024-04-30 00:04 UTC, javajigi requested changes
일단 구현하고 빠르게 피드백 요청하는 모습 보기 좋네요. 💯 
이에 저도 빠르게 객체의 역할과 책임에 대한 피드백 남겨봤어요.
제가 생각했을 때도 객체의 역할과 책임에 의문이 드는 부분이 좀 있네요.
테스트와 더불어 한번 고민해 보면 좋겠네요

2024-04-30 00:04 UTC, javajigi commented on src/main/java/nextstep/LadderGame.java
> +        Map<String, String> participantStringMap = ladderResult.mappingPrize(prizeList);
이 메서드는 사다리 타기의 핵심 로직을 실행한 결과만을 받아 결과를 출력하는 로직만 가지는 것은 어떨까?
핵심 로직을 담당하는 Ladder에 메시지를 보내고 결과를 얻는 로직은 main이 가지면 어떨까?

2024-04-30 00:04 UTC, javajigi commented on src/main/java/nextstep/domain/LadderResult.java
> +    private int move(Line line, Integer position) {
클래스 이름은 사다리 실행 결과를 저장하는 객체로 보이는데 실제 사다리 실행하는 로직을 가지고 있다.
사다리 실행은 Line과 Line 목록을 가지는 Ladder가 실행하는 것은 어떨까?
이렇게 실행한 결과 저장을 LadderResult가 담당한다.

2024-04-30 00:04 UTC, javajigi commented on src/test/java/nextstep/domain/LadderTest.java
> +    void createLadderResult() {
단위 테스트 단위가 너무 크지 않을까?
사다리 왼쪽 이동, 오른쪽 이동, 이동 없음과 같은 작은 단위의 단위 테스트부터 어떻게 할 것인지에 대해 고민하고 그에 따른 객체 설계를 도전해 보면 어떨까?

2024-05-01 03:06 UTC, yuus95 commented on src/test/java/nextstep/domain/LadderTest.java
> +    void createLadderResult() {
Participant 객체에 `Position` 객체를 만들어서 참가자의 상태를 내부에서 변경할 수 있도록 수정했습니다!

2024-05-01 03:37 UTC, yuus95 commented on src/main/java/nextstep/LadderGame.java
>  public class LadderGame {
InputView 에서는 입력만 받을 수 있게, 
outView 에서는 출력만 할 수 있도록 수정했습니다.

2024-05-01 03:38 UTC, yuus95 commented on src/main/java/nextstep/LadderGame.java
> +        Map<String, String> participantStringMap = ladderResult.mappingPrize(prizeList);
핵심로직을 사다리 내부에서 내부객체에 전달방식으로 수정하였고, 
결과 객체에는 움직인 결과값만 가질 수 있도록 수정했습니다!

2024-05-01 03:38 UTC, yuus95 commented on src/main/java/nextstep/domain/LadderResult.java
> +    private int move(Line line, Integer position) {
실행로직을 Ladder 내부로 이동했습니다!

2024-05-01 03:39 UTC, yuus95 commented
리뷰해주셔서 감사합니다!! 
피드백을 받고 다시 생각해보니 움직임 자체는 참여자 내부에 포함해도 될 것 같아서 
Position이라는 객체를 이용하여 다시 리팩토링 했습니다. 확인부탁드립니다!

2024-05-01 05:09 UTC, javajigi approved these changes
피드백 반영 잘 했네요. 💯 
4단계는 추가 리팩터링 도전인데요.
추가 리팩터링을 위한 피드백과 강의 영상 참고해 리팩터링 도전하거나, 인터페이스 기반으로 개발하는 경험도 해보면 어떨까요?

2024-05-01 05:09 UTC, javajigi commented on src/main/java/nextstep/OutView.java
> +    private static final Scanner scanner = new Scanner(System.in);
```suggestion
    private static final Scanner scanner = new Scanner(System.in);
    private LadderResult ladderResult;
```

상수를 먼저 구현하는 것이 관례

2024-05-01 05:09 UTC, javajigi commented on src/main/java/nextstep/OutView.java
> +    public OutView(LadderResult ladderResult) {
ladderResult을 인스턴스 변수로 가지기 보다 클래스 메서드(static)의 인자로 구현해도 되지 않을까?

2024-05-01 05:09 UTC, javajigi commented on src/main/java/nextstep/domain/Ladder.java
> +        participants.move(lines);
```suggestion
    private int getTarget(int position) {
        int target = position;
        for (Line line : lines) {
            System.out.println("current target : " + target);
            target = line.move(target);
        }
        return target;
    }
```

지금 코드는 participants을 중심으로 move()를 구현하며 lines를 전달하고 있다.
반대로 line.move()를 호출하면서 현재 위치 값을 전달하는 방식으로 구현하는 것은 어떨까?

2024-05-01 05:09 UTC, javajigi commented on src/main/java/nextstep/LadderGame.java
> +    public static void main(String[] args) {
사다리 타기의 전체 흐름을 다음과 같은 구조로 구현해 보는 것은 어떨까?
main()은 MVC에서 Controller의 역할로 가능한 가볍게 구현해야 한다.
Controller 내에는 로직은 최대한 배제하고 Model과 View 사이의 연결 역할만 하도록 구현한다.

```java
public static void main(String[] args) throws Exception {
    Players players = InputView.createPlayers();
    Rewards rewards = InputView.createRewards();

    Ladder ladder = LadderFactory.createLadder(players.countOfPeople(), InputView.getHeight());
    OutputView.printLadder(players, ladder, rewards);

    MatchingResult matchingResult = ladder.play();
    LadderResult result = matchingResult.map(players, rewards);

    OutputView.printResult(result);
}
```

MatchingResult는 Map<Integer, Integer>에 대한 일급콜렉션 객체이다.
Map의 key는 시작 위치, value는 사다리를 실행한 결과 위치이다.

LadderResult는 위치 값만 가지고 있는 MatchingResult의 값을 이름과 결과로 매핑한 결과를 가지는 일급콜렉션 객체이다.

반드시 위와 같은 구조로 개발하지 않아도 된다.
단, 위 코드 힌트를 참고해 개선할 부분이 있으면 개선해 본다.

2024-05-01 05:09 UTC, merged