Step2 - 사다리(생성)
next-step/java-ladder pull request #2186
Opened 2024-10-19 12:16 UTC by kimho314

- 사다리(생성) 로직 구현하였습니다.

2024-10-20 05:03 UTC, testrace requested changes
안녕하세요 호섭님 😃 
2단계 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었습니다.
확인해 주시고 다시 리뷰 요청해 주세요.

2024-10-20 05:03 UTC, testrace commented on src/main/java/nextstep/ladder/model/Player.java
> +            throw new IllegalArgumentException("name is too long");
매직 넘버는 상수로 치환해서 의미를 드러내면 좋을 것 같아요.
그리고 for, if 문에 공백 [컨벤션](https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace)이 안맞는 코드가 많이 있는 것 같아요.
예외메시지도 상세하게 알려주시면 좋을 것 같아요.

2024-10-20 05:03 UTC, testrace commented on src/main/java/nextstep/ladder/model/RandomLineGenerator.java
> +        Random random = new Random();
상수로 선언해서 재활용하면 어떨까요?

2024-10-20 05:03 UTC, testrace commented on src/main/java/nextstep/ladder/view/ResultView.java
> +    public static void printLadder(Ladder ladder, List<Player> players) {
이름 출력과 사다리 출력도 나눠보면 어떨까요?

2024-10-20 05:03 UTC, testrace commented on src/test/java/nextstep/ladder/LadderGameTest.java
> +        final List<String> testNames = new ArrayList<>(List.of("pobi", "honux", "crong", "jk"));
프로덕션 코드와 다르게 테스트에서는 지역 변수에 final 키워드가 있네요.
개인적으로 일관성이 조금 떨어진다는 느낌인데요.
final 키워드를 적용하는 기준이 있으신지 궁금합니다.

2024-10-20 05:03 UTC, testrace commented on src/test/java/nextstep/ladder/LadderGameTest.java
> +        Ladder ladder = ladderGame.run(lineGenerator);
생성 테스트는 `new` 키워드로 인스턴스화 하는 과정을 테스트할 것이라 생각했는데
실제 테스트는 run 메서드를 대상으로 하고 있네요.
생성과 실행은 다른 행위라고 생각하는데요. 테스트를 분리하면 어떨까요?

2024-10-20 05:03 UTC, testrace commented on src/test/java/nextstep/ladder/LadderGameTest.java
> +            System.out.println(line);
테스트에서도 불필요한 코드는 제거해 주세요.

2024-10-20 05:03 UTC, testrace commented on src/test/java/nextstep/ladder/LadderTest.java
> +        Assertions.assertThat(lines.get(0).getPoints()).hasSize(countOfPlayers - 1);
플레이어 수, 높이, MockLineGenerator 를 알고 있으니 어떤 사다리가 그려질지 충분히 예상할 수 있을거라 생각해요.
내부의 값을 꺼내가며 비교하기 보다 예상되는 Ladder 객체를 생성해서 객체끼리 비교하면 어떨까요?

2024-10-20 11:42 UTC, kimho314 commented
안녕하세요 리뷰어님.
남겨주신 피드백 반영해서 재리뷰 드립니다.

2024-10-21 05:44 UTC, testrace requested changes
안녕하세요 호섭님 😃 
피드백 반영 잘해주셨네요 👍 
조금만 더 개선하고 넘어가면 좋을 것 같아 코멘트 남겼습니다.
확인해 주시고 다시 리뷰 요청해 주세요.

2024-10-21 05:44 UTC, testrace commented on src/main/java/nextstep/ladder/model/Ladder.java
> +    public Ladder(List<Line> lines, int height) {
LadderGame에서처럼 Ladder에서도 height 변수는 활용처가 없는 것으로 보이는데요
제거하면 어떨까요?

2024-10-21 05:44 UTC, testrace commented on src/main/java/nextstep/ladder/model/LadderGame.java
> +    public Ladder run(int height, LineGenerator lineGenerator) {
사다리를 실행한다는 건 어떤 의미인지 감이 잘 안오는데요.
사다리를 타고 내려가는 것인가요, 사다리를 그리는 것인가요?
테스트 코드를 보면 잘 그려졌는지 검증하는 것 같아요. 잘 그려졌는지 의도한 것이라면 메서드명도 그에 맞게 변경하면 어떨까요?

2024-10-21 05:44 UTC, testrace commented on src/main/java/nextstep/ladder/model/Line.java
> +    }
필드의 타입과 동일한 주 생성자를 만들고, 모든 부 생성자가 주 생성자를 호출해 중복을 제거해 보시면 좋을 것 같아요.

2024-10-21 05:44 UTC, testrace commented on src/main/java/nextstep/ladder/model/PlayerGroup.java
> +    }
일급 컬렉션을 추가해 주셨네요
인스턴스 변수는 캡슐화를 위한 접근제한자도 없고, 단위 테스트가 존재 하지 않다보니 객체의 필요성을 알기가 어렵네요.
모든 public 메서드에 대해 단위 테스트를 추가해 보시면 좋을 것 같아요.

2024-10-21 05:44 UTC, testrace commented on src/main/java/nextstep/ladder/model/Point.java
> +    private LineGenerator lineGenerator;
위 코멘트와 동일하게 단위 테스트를 추가해 주시면 좋을 것 같아요.
lineGenerator 는 next 메서드에서만 사용되니 메서드의 인자로 받는 것을 고려해 보셔도 좋을 것 같아요.

2024-10-21 05:44 UTC, testrace commented on src/test/java/nextstep/ladder/LineTest.java
>          System.out.println(points);
불필요한 코드는 제거해 주세요

2024-10-21 12:12 UTC, kimho314 commented
### 질문사항
안녕하세요 리뷰어님.
```
public Line(int countOfPlayers, LineGenerator lineGenerator) {
        this.lineGenerator = lineGenerator;
        IntStream.range(0, countOfPlayers - 1)
                .forEach(it -> this.points.add(makeLine(it)));
    }
```
위 코드도 주 생성자 호출할 수 있는 코드로 개선하고 싶은데 좋은 방법이 안떠오르네요. 다른 방법이 있을지 여쭤봅니다.

2024-10-21 12:54 UTC, testrace approved these changes
피드백 반영 잘해주셨네요 👍 
질문에 대한 답변과 몇 가지 고민해 보시면 좋을 것 같아 코멘트 남겨두었습니다.
확인해 주시고 다음 단계 진행해 주세요!

2024-10-21 12:54 UTC, testrace commented on src/main/java/nextstep/ladder/model/Point.java
> +        this.value = !hasPreviousLine && currentLine;
이전 값을 받아 다음 값을 자신의 필드에게 할당하는 것도 좋지만,
Point 객체를 불변객체로 만들어 자신의 값에 따라 다음 값을 생성해서 리턴하는 방법도 고려해 보시면 좋을 것 같아요
```suggestion
    public Point next(...) {
        return new Point(...);
```

2024-10-21 12:54 UTC, testrace commented on src/test/java/nextstep/ladder/LadderGameTest.java
>      @DisplayName("ladder game 실행 테스트")
메서드명이 변경되었으니 DisplayName도 맞춰서 변경하시면 좋을 것 같아요

2024-10-21 12:54 UTC, testrace commented on src/main/java/nextstep/ladder/model/Line.java
> +        this.points = points;
points 인자에 `List.of(new Point(true), new Point(true), new Point(true))` 를 전달한다면 정상적으로 생성되고 있어요.
겹치지 않는 가로선을 가져야하는 책임이 있으니 인스턴수 변수 할당 시점에 유효성을 검증하면 어떨까요?

2024-10-21 12:54 UTC, testrace commented on src/main/java/nextstep/ladder/model/Line.java
>                  .forEach(it -> this.points.add(makeLine(it)));
>주 생성자 호출할 수 있는 코드로 개선하고 싶은데 좋은 방법이 안떠오르네요. 다른 방법이 있을지 여쭤봅니다.

현재 구조에선 정적 팩토리 메서드를 적용해 보시면 좋을 것 같아요
lineGenerator 도 해당 생성자에서만 필요하니 인스턴스 변수로 할당하지 않아도 될 것 같아요.

2024-10-21 12:54 UTC, merged