Step3 - 사다리 실행 부분
next-step/java-ladder pull request #2196
Opened 2024-10-21 06:21 UTC by gyeongjae-ham

# 질문내용
Line 클래스의 findNextPoint 메소드를 더 깔끔하게 해보고 싶은데 생각이 굳어져서 지금 저 방향성밖에 안보입니다ㅜ 어떤 식으로 개선해볼 수 있을까요?

2024-10-21 11:09 UTC, neojjc2 commented
#tag @neojjc2

2024-10-21 11:50 UTC, neojjc2 commented on README.md
> +- [x] 사다리 게임이 실행하면, 참가자별로 결과를 가진다
요구사항 정리 좋습니다 👍

2024-10-21 11:50 UTC, neojjc2 commented on src/main/java/ladder/InputResult.java
> +public class InputResult {
`InputResult` 객체 생성 좋습니다 👍

2024-10-21 11:50 UTC, neojjc2 commented on src/main/java/ladder/Ladder.java
> +    int runPerPerson(int startPoint) {
```suggestion
    private int runPerPerson(int startPoint) {
```
요구사항 구현 깔끔하게 해주셨네요 💯

2024-10-21 11:50 UTC, neojjc2 commented on src/main/java/ladder/Line.java
> +    }
고민하신 부분인 것 같은데, 저 역시 이 부분은 코드 읽기가 좀 어려운 면이 있었습니다 😄 
일단 `checkHorizon`이 직관 적이지 않은 것 같습니다. 양 방향으로 봤을 때 다음 (`Next`)로 갈지 혹은 이전 으로 갈지 (`Prev`)에 대한 `goNextOrPrev`같은 네이밍이면 좀 더 직관적일 것 같습니다. 그리고 `1, 0`도 매직넘버이어서 1이 앞으로 가는건지 `0`이 앞으로 가는건지 계속 코드를 확인해야 하는 어려움도 있었습니다. 
이 부분은 정적 상수로 추출되면 좀 더 가독성을 확보 할 수 있을 것 같습니다 🙏 

`-checkHorizon(startPoint - 1); `이런 표현들이 약간 어렵긴 합니다만
지금 구조에서는 `True`/`False`만 가지고 판단해야 하기 때문에 이 정도면 그래도 최선이라 생각합니다 😄 

차라리 `findHorizon`을 `hasHorizon`으로 네이밍을 변경하고 코드를 풀어쓰는 것도 하나의 방법이 될 수 있을 것 같습니다. 
```java
private static final int GO_NEXT = 1;
private static final int GO_PREV = 0;

..(중략)..
int previousPoint = startPoint - 1;
if (hasHorizon(previousPoint)) {
    return points.get(previousPoint) ? GO_NEXT : GO_PREV;
}

```

2024-10-21 11:50 UTC, neojjc2 commented on src/main/java/ladder/Main.java
> +        inputResult.validSize(players.size());
이 부분은 `InputResult`가 생성되는 시점에서 검증되도록 하시는건 어떨까요?? 😄 

이렇게 필수 검증에 대한 `method`를 제공하는 형식이면 객체를 사용하는 쪽에서 호출하지 않는다면, 누락되어
검증이 누락될 가능성이 커지는 구조가 됩니다. 
`InputView.inputResult`가 `InputResult`를 생성하는 역할까지 가져가는게 아니라 
사용자에게 입력 받는 정도까지만 하게 하시고`InputResult`는 `Main`에서 생성하되 
생상자에서 `validSize`가 같이 검증되는 구조가 되면 더 좋을 것 같습니다. 

```java
String inputResults = InputView.inputResult(); // 아니면 String[]까지는 InputView가 가져가도 좋다고 생각합니다 :-) 
InputResult inputResult = InputResult.perPlayers(inputResults, players.size());
```

2024-10-21 11:50 UTC, neojjc2 commented on src/main/java/ladder/Main.java
> +        }
객체들에 대한 역할과 책임을 잘 부여해주셨으니 이 부분에 대한 검증도 추가 되면 더 좋을 것 같습니다 🙇 
<img width="372" alt="image" src="https://github.com/user-attachments/assets/10b99aad-d7ac-459d-9a28-d776c725f8d6">

2024-10-21 11:50 UTC, neojjc2 commented on src/main/java/ladder/view/OutputView.java
> +    private static boolean checkAll(String resultInput) {
추가적으로 이 부분은 과도한 `method` 추출로 보여서 리뷰 의견 드렸는데
다행이(?) 사용되지 않고 있는 코드 인것 같습니다 😄

2024-10-21 11:53 UTC, neojjc2 commented
> # 질문내용
> Line 클래스의 findNextPoint 메소드를 더 깔끔하게 해보고 싶은데 생각이 굳어져서 지금 저 방향성밖에 안보입니다ㅜ 어떤 식으로 개선해볼 수 있을까요?

@gyeongjae-ham 경재님, 
지금 구조에서는 이정도면 충분한 것 같습니다 😄 
리뷰 코멘트 의견 드렸습니다만, 가독성 확보를 위해 매직넘버추출하고 네이밍 수정 정도 밖에 없을 것 같아요
왜냐하면 `Line`의 여부를 `true`/`false`로 판단하기 때문에` if (true or false)` 과 같은 구조가 계속 될 수 밖에 없어서
이미 최선의 고민을 해주신 것 같습니다 🙇 
마지막 단계 하시면서 다른 구조를 가지고 어떻게 표현해야 할지 연습해보시고 비교해 가시면서
차이점을 알아가시면 읽기 쉽고 유지보수가 간결한 구조에 대해서 좀 더 감이 오실 꺼라 생각되네요 🙇

2024-10-21 11:56 UTC, neojjc2 requested changes
안녕하세요 경재님 🙇 

3단계 구현 잘 해주셨습니다.
이전 단계에서도 이미 사다리를 잘 구현 해주셨어서
큰 수정 없이 잘 해내실꺼라 생각했는데,
역시나 잘 해주셨네요 👍 

소소한 의견 드렸습니다. 
재 리뷰 요청 드린 이유는, 
문의주신 코드 가독성 부분과, 검증에 있어서 조금만 보완되면 좋을 것 같아서
그 부분 개선 요청 드리고자 합니다.

보시고 조금 더 고민 해주시면 감사하겠습니다 🙇 

그럼 재 리뷰 요청 기다리고 있겠습니다 🙏

2024-10-22 00:26 UTC, gyeongjae-ham commented on src/main/java/ladder/Line.java
> +    }
넵 네이밍때문에 가독성이 더 떨어지는 부분이 있네요 감사합니다!

2024-10-22 00:47 UTC, gyeongjae-ham commented on src/main/java/ladder/view/OutputView.java
> +    private static boolean checkAll(String resultInput) {
어...짜고나서 안쓰는걸 안지웠나 봅니다 삭제하겠습니다!

2024-10-22 00:47 UTC, gyeongjae-ham commented on src/main/java/ladder/Main.java
> +        }
넵!!

2024-10-22 00:48 UTC, gyeongjae-ham commented on src/main/java/ladder/Main.java
> +        inputResult.validSize(players.size());
음 inputview에서 한번에 하려고 하다보니 지저분해져서 참고해서 수정했습니다

2024-10-22 09:15 UTC, neojjc2 approved these changes
안녕하세요 경재님 🙇 

개선사항 잘 반영해주셨네요 😄 
충분히 완성도가 올라가고 의도도 잘 반영해주신 것 같습니다 🙏 

마지막 단계 진행하시면, 기존 구조와의 어떤 점이 다른지,
어떤 부분이 장단점인지 더 잘 이해하실 수 있을 것 같네요 😄 

이만 `merge` 하겠습니다.
수고하셨습니다 🙇

2024-10-22 09:15 UTC, neojjc2 commented on src/main/java/ladder/InputResult.java
> +    }
꼼꼼한 검증으로 완성도를 높여 주셨습니다 💯

2024-10-22 09:15 UTC, neojjc2 commented on src/main/java/ladder/Line.java
> +        return GO_PREV;
이정도면 최선이신 것 같습니다 👍

2024-10-22 09:15 UTC, neojjc2 commented on src/main/java/ladder/Players.java
> +
💯 💯 💯 💯 💯

2024-10-22 09:16 UTC, merged