🚀 2단계 - 사다리(생성) 구현 및 리뷰요청
next-step/java-ladder pull request #2230
Opened 2024-10-28 03:34 UTC by joonkb

안녕하세요, 리뷰어님! 😄

로또 마무리와 수강신청 미션을 동시에 진행하느라 이번 미션이 꽤 늦어진 것 같습니다. 😅

특히 이번 사다리 구현에서는 랜덤하게 사다리를 생성하는 부분과 출력하는 데에 많은 시간을 소요된 것 같습니다. ㅎㅎ
마치 알고리즘 문제를 푸는 것처럼 꽤 어려웠던 것 같습니다.

힌트 부분을 참고하려 했지만, "라인"이 가로선을 의미하는지 세로선을 의미하는지 잘 이해되지 않아 구현 방식을 떠올리기 어려웠습니다. 그래서 제 방식대로 구현해보았는데, 더 나은 아이디어가 있다면 알려주시면 정말 감사하겠습니다.

구현 과정에서 사다리를 생성하고 출력하는 부분에서 코드의 깊이가 깊어지고 복잡해진 것 같습니다.
너무 많은 시간이 소요되는 것 같아 우선 리뷰를 받고 하나씩 개선해 나가고자 합니다.

이번에도 많은 리뷰 부탁드립니다! 🙇

감사합니다!

2024-10-29 02:57 UTC, joonkb commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +    public Ladder(Line... lines) {
해당 생성자는 테스트 코드 작성 시 간단하게 객체를 초기화하기 위해 사용하였는데, 테스트 코드에서만 사용하는 생성자를 만드는 것은 지양하는편이 좋을까요?

```
public class LadderPrinterTest {

    @Test
    @DisplayName("사다리가 주어졌을 때, 정상적인 문자열로 반환하는지 테스트한다. |-----|")
    void createLadderPrinter() {
        Line line = new Line(Arrays.asList(Boolean.TRUE, Boolean.TRUE));
        Ladder ladder = new Ladder(line);
        LadderPrinter printer = new LadderPrinter(ladder);
        Assertions.assertThat(printer.printLadder()).isEqualTo("|-----|\n");
    }
}
```

2024-10-29 03:27 UTC, joonkb commented on src/main/java/nextstep/ladder/domain/LadderGenerator.java
> +    private int participantCount;
상태를 가지지 않는다고 하면,  메서드를 구성할때 static 으로 구현하는 것이 좋은 방법일까요?

2024-10-29 14:01 UTC, shared-moon requested changes
병준님 안녕하세요!
2단계 미션 잘 진행 해 주셨네요 :)
코멘트를 좀 남겨두었는데, 이번에 같이 살펴보고 넘어가면 좋을 것 같아요!
확인 후 리뷰 재요청 부탁드려요 ~

2024-10-29 14:01 UTC, shared-moon commented on src/main/java/nextstep/ladder/view/ResultView.java
> +    public static void printLadderLine(List<Boolean> line) {
요거 ResultView가 사다리 결과를 계산하는 로직을 가지고 있는 것 같아요! Ladder를 받아서 사다리를 출력하는거랑, 결과를 받아서 결과 출력하는 부분이 나누어져야 할 것 같습니다!

2024-10-29 14:01 UTC, shared-moon commented
어라 제 브라우저가 뭔가 이상이 있었나보네요..! 분명히 리뷰 남겼던거같은데 펜딩상태로 남아있어서 다시 적어서 보냈는데 중복 리뷰를 달아버렸군요..!

2024-10-29 14:51 UTC, shared-moon commented on src/main/java/nextstep/ladder/domain/LadderGenerator.java
> +    private int participantCount;
LadderGenerator는 가지고 있는 책임이 유틸클래스로 만들어도 충분할 것 같아서 이번 미션에서라는 저라면 유틸클래스로 만들었을 것 같긴 합니다!
근데 스프링을 사용해서 실제 구현을 할 때는 비즈니스 로직에 영향을 주는 코드가 유틸클래스로 만들어져있으면 테스트를 작성하기가 어려워서 그냥 일반 클래스로 만들고 주입받아서 쓰도록 하고 있어요!

2024-10-29 16:12 UTC, joonkb commented
안녕하세요, 리뷰어님! 😄

left와 right 속성을 가진 Point라는 객체를 사용하여 구현하니, 이전보다 코드가 훨씬 깔끔해진 것 같습니다.

이런 생각을 왜 하지 못했는지 아쉽네요...ㅎ 그럼에도 불구하고, 여전히 depth를 줄이지 못한 부분이 있어서 어떤 방식으로 개선할 수 있을지 궁금합니다!

이번에도 많은 리뷰 부탁드립니다! 🙇

감사합니다!

2024-10-30 13:33 UTC, shared-moon approved these changes
병준님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
코멘트를 좀 남겨 뒀는데, 다음 미션 진행 하면서 살펴봐도 좋을 것 같아요!
이번 미션은 머지 하도록 하겠습니다.
고생 많으셨습니다!

2024-10-30 13:33 UTC, shared-moon commented on src/main/java/nextstep/ladder/domain/LadderGenerator.java
> +                randomLine.putBridgeAtPosition(cnt);
Line을 만들 때 Point의 컬렉션을 만들어서 보내주는건 어떨까요 ?
put 보다는 이전 Point의 right 값을 left로 받아 Point를 생성할 수 있게 하면 좀 수월하게 만들 수 있지 않을까 싶습니다..!

2024-10-30 13:34 UTC, merged