2단계 - 사다리(생성)
next-step/java-ladder pull request #2264
Opened 2024-11-05 22:40 UTC by mitsui3point

안녕하세요 리뷰어님,

작성을 하다 삭제를 했다 반복하다보니 리뷰요청이 늦어졌습니다.

요구사항에는 없었지만
이런 고민이 있긴 했는데요,

아래와 같은 사다리도 사다리게임이 진행되기는 할거 같기는 한데,
```
pobi cron honu pob2
    |----|    |----|
    |----|    |----|
    |----|    |----|
    |----|    |----|
            ^
         이 부분 오픈되어있음
```
요구사항에는 이런 상황에서 사다리 한 line 을 재생성한다 등의 요구사항이 없어서 로직에서 추가를 하려다가 제거하였습니다.

저런 사다리도 생성하면 동작하기 때문에 예외상황이 아닌걸로 판단했는데 맞는건지 의문이 듭니다.

그리고 일단 도메인에서 사다리에 필요한 데이터는 생성하는것까진 괜찮은데,
지금 구현을 빠르게 하려다 보니까 도메인에 string 을 렌더링하는 로직이 추가가 되었습니다...
이런 렌더링 메서드를 도메인이 갖고, 렌더링의 책임을 갖는게 맞는건지가 의문이 듭니다..

이번리뷰도 잘부탁드리겠습니다.🙇

2024-11-06 15:14 UTC, testrace requested changes
안녕하세요 윤호님 😃 
2단계 구현 잘해주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청해 주세요.

2024-11-06 15:14 UTC, testrace commented on src/main/java/ladder/domain/Line.java
> +        return IntStream.range(START_INCLUSIVE, names.size())
>그리고 일단 도메인에서 사다리에 필요한 데이터는 생성하는것까진 괜찮은데,
지금 구현을 빠르게 하려다 보니까 도메인에 string 을 렌더링하는 로직이 추가가 되었습니다...
이런 렌더링 메서드를 도메인이 갖고, 렌더링의 책임을 갖는게 맞는건지가 의문이 듭니다..

ui와 관련된 책임은 모두 ui영역으로 이동하면 좋을 것 같아요

2024-11-06 15:14 UTC, testrace commented on src/main/java/ladder/domain/util/SplitUtil.java
> +    public static final String DELIMITER = ",";
유틸은 도메인 객체로 보기가 어렵습니다.
콤마 기호로 구분하는 책임은 ui의 책임으로 이동하면 어떨까요?
유틸 클래스가 꼭 필요할까요?

2024-11-06 15:14 UTC, testrace commented on src/main/java/ladder/view/ResultView.java
> +    private final Ladder ladder;
ui 영역은 입/출력에 대한 책임을 가지고 있으니 도메인 객체를 상태로 가질 필요는 없을 것 같아요.
필요한 메서드에서만 인자로 받으면 어떨까요?

2024-11-06 15:14 UTC, testrace commented on src/test/java/ladder/domain/LineTest.java
> +            String actual = line.toLineString(players);
출력하는 시점이 아니라 생성하는 시점에 검증하면 어떨까요?

2024-11-06 15:14 UTC, testrace commented on src/test/java/ladder/domain/LineTest.java
> +    }
테스트에 대한 설명이 없으니 무엇을 검증하고자 하는지 파악하기 쉽지 않은데요
구체적인 내용과 함께 테스트의 의도를 드러내면 어떨까요?
테스트 코드는 기능을 검증하는 것과 더불어 객체의 역할이 무엇인지 어떻게 사용해야 하는지 명시한 문서라고 생각해 보시면 좋을 것 같아요.
모든 테스트에 DisplayName을 추가해 테스트의 의도를 명확하게 드러내 보시면 좋을 것 같아요

2024-11-06 16:27 UTC, mitsui3point commented on src/main/java/ladder/domain/Line.java
> +    }
이해했습니다.
부 생성자에는 겹치지 않는 로직을 작성해두었는데 정작 주생성자에 검증로직이 없었네요
이부분 작성하고나서 뭔가 PR 드릴때 어떤부분이 빠져있다는 생각이 들었었는데 정확하게 짚어주신것 같습니다.

감사드립니다.🙇

질문사항에 대해서도 답변주신것 잘 이해했습니다. 감사합니다.

수정사항 반영해두겠습니다😅

2024-11-06 18:26 UTC, mitsui3point commented on src/main/java/ladder/domain/Name.java
> +        if (name.length() > 5) {
아하 놓쳤던 부분이네요
수정사항 반영해두겠습니다😅

2024-11-06 18:29 UTC, mitsui3point commented on src/main/java/ladder/domain/Players.java
> +    public static final int DEFAULT_MAX_NAME_LENGTH = 5;
상수가 모호한 부분에 존재하네요..
수정사항 반영해두겠습니다😅

2024-11-06 18:32 UTC, mitsui3point commented on src/main/java/ladder/domain/util/RandomLineGenerator.java
> +        return Math.random() > BOUNDARY;
말씀하신 방향이 더 명시적이네요.!😀
수정사항 반영해두겠습니다😅

2024-11-06 18:45 UTC, mitsui3point commented on src/main/java/ladder/domain/util/LineGenerator.java
> +    Boolean generate();
박싱된 기본 타입보다는 기본 타입을 사용하라

원시값
1. stack 영역 저장, 값만 비교
2. null 불가
3. boxing 이슈 없음

래핑객체
1. heap 영역 저장 참조를 비교
2. null 가능하므로 예기치않은 NPE 발생
3. auto boxing 으로 boxing unboxing 이 일어날때마다 성능저하 이슈발생 
등..

많은 부분에서 래핑객체 타입의 위험성이 많이 있는거 같습니다.

코멘트 주신 덕에 얕게 이해했던 것들이 명확해진 것 같습니다.
제네릭처럼 래핑객체가 필요한 상황도 아닌데 불필요하게 리턴타입을 래핑객체를 사용했네요

수정사항 반영해두겠습니다😅

2024-11-06 19:06 UTC, mitsui3point commented on src/main/java/ladder/view/ResultView.java
> +    private final Ladder ladder;
ResultView 가 인스턴스 변수를 가지면 도메인 상태를 갖게 되니 
도메인의 책임을 갖게 되겠네요..😨
수정사항 반영해두겠습니다😅

2024-11-06 19:54 UTC, mitsui3point commented on src/main/java/ladder/domain/Line.java
> +        return IntStream.range(START_INCLUSIVE, names.size())
급하게 구현하다보니 객체 책임에 대해서 고려를 많이 안한듯한 구현을 한것 같습니다😨

ResultView 에 ui 렌더링을 하도록 메소드를 이동하였습니다.
수정사항 반영해두겠습니다😅

2024-11-06 19:56 UTC, mitsui3point commented on src/main/java/ladder/domain/Players.java
> +    public static final int DEFAULT_MAX_NAME_LENGTH = 5;
Players 가 길이제약을 갖고 있는게 어색하네요..😨

수정사항 반영해두겠습니다😅

2024-11-06 20:00 UTC, mitsui3point commented on src/main/java/ladder/domain/util/SplitUtil.java
> +    public static final String DELIMITER = ",";
유틸을 도메인에 넣어두었었네요..😨

간단한 역할이고, 쓰이는 곳도 한곳밖에 없다보니
말씀하신대로 꼭 필요하지 않은것 같습니다.
유틸 클래스는 삭제하였습니다😅

수정사항 반영해두겠습니다😅

2024-11-06 20:02 UTC, mitsui3point commented on src/test/java/ladder/domain/LineTest.java
> +            String actual = line.toLineString(players);
해당 로직은 UI 쪽으로 이관하였습니다😀

2024-11-07 16:11 UTC, mitsui3point commented on src/main/java/ladder/domain/Line.java
> +            return horizontal;
말씀해주신대로 Point 정적 팩토리 메서드 first 와 next(), last() 메소드로 point 를 체이닝하여 추가하였고,
해당 부분은 Point 로 대체하였습니다😅

2024-11-07 16:12 UTC, mitsui3point commented on src/test/java/ladder/domain/LineTest.java
> +    }
수정사항 반영해두겠었습니다😅

2024-11-09 00:22 UTC, testrace approved these changes
안녕하세요 윤호님 😃 
피드백 반영 잘해주셨네요 👍 
소소하게 코멘트 남겨두었는데 확인해 주시고 다음 단계 진행해 주세요.

2024-11-09 00:22 UTC, testrace commented on src/main/java/ladder/domain/Ladder.java
> +import ladder.domain.util.CrossGenerator;
util 이라는 이름은 너무 광범위하니 generator 같은 이름은 어떠신가요?

2024-11-09 00:22 UTC, testrace commented on src/main/java/ladder/domain/util/RandomCrossGenerator.java
> +        return new Random().nextBoolean();
Random 객체는 상수로 선언해 재활용해도 좋을 것 같아요

2024-11-09 00:22 UTC, testrace commented on src/main/java/ladder/view/ResultView.java
> +    public static final String LINE_BREAK = "\n";
JDK 에서 제공하는 개행 문자열을 사용해 보셔도 좋을 것 같아요
```suggestion
    public static final String LINE_BREAK = System.lineSeparator();
```

2024-11-09 00:22 UTC, testrace commented on src/main/java/ladder/view/ResultView.java
> +    private static String toFormattedHorizontal(int index, int length, List<Point> points) {
글자수에 따라 가로선의 길이를 정하지 않고 실행 예시에 따라 고정된 가로선을 출력하면 어떨까요?
<img width="382" alt="image" src="https://github.com/user-attachments/assets/53fe4ca5-dff8-49ee-9cc3-ea21159ea3ca">

2024-11-09 00:22 UTC, testrace commented on src/test/java/ladder/domain/PointTest.java
> +                .isInstanceOf(PointException.class)
내부 구현이 변경되어 first 메서드에서 예외가 발생해도 이 테스트는 통과하게 됩니다.
테스트 대상이 되는 메서드만 인자로 전달하면 어떨까요?
```suggestion
        assertThatThrownBy(() -> point.next(true))
                .isInstanceOf(PointException.class)
```

2024-11-09 00:22 UTC, merged

2024-11-13 05:24 UTC, mitsui3point commented
리뷰기간이 지났는데도 불구하고 리뷰남겨주셔서 감사드립니다.

리뷰해주신 내용들 반영해서 step3 다시 진행해보겠습니다.

2024-11-13 05:24 UTC, mitsui3point commented on src/main/java/ladder/domain/Ladder.java
> +import ladder.domain.util.CrossGenerator;
패키지명을 보니 util 이라는 이름은 광범위하고 모호한것 같습니다.
수정사항 반영해두겠습니다😅

2024-11-13 05:28 UTC, mitsui3point commented on src/main/java/ladder/view/ResultView.java
> +    private static String toFormattedHorizontal(int index, int length, List<Point> points) {
제가 구현시에 요구사항을 잘못 이해한 것 같습니다.

말씀하신대로 예시에 따라 고정된 가로선을 출력하는게 가시성도 있어보입니다.

수정사항 반영해두겠습니다😅

2024-11-13 05:28 UTC, mitsui3point commented on src/main/java/ladder/view/ResultView.java
> +    public static final String LINE_BREAK = "\n";
기본 제공해주는 상수가 있었군요..😨

수정사항 반영해두겠습니다😅

2024-11-13 05:28 UTC, mitsui3point commented on src/main/java/ladder/domain/util/RandomCrossGenerator.java
> +        return new Random().nextBoolean();
생성은 한번만 해도 nextBoolean() 호출할수 있는데, 매번 하게끔 되어있었네요.

수정사항 반영해두겠습니다😅

2024-11-13 05:40 UTC, mitsui3point commented on src/test/java/ladder/domain/PointTest.java
> +                .isInstanceOf(PointException.class)
언급하신대로 테스트 타깃은 next 메서드의 오류를 재현하는것인데, first 가 감싸져있었네요

언급하신게  테스트 이것 하나이지만,
다시 생각해보니 이 테스트만 해당되는게 아닌것 같습니다.

수정사항 반영해두겠습니다😅

2024-11-14 12:28 UTC, mitsui3point commented on src/main/java/ladder/domain/Player.java
> +public class Player {
다음 라운드에서 play 진행시에 필요할것 같아 남겨두었는데요,

TODO 리스트를 작성하다보니 불필요한것 같아 삭제하였습니다.

step3 반영때 적용하겠습니다😅