4단계 - 사다리(리팩터링)
next-step/java-ladder pull request #2269
Opened 2024-11-06 15:40 UTC by hanhub-ux

리뷰어님, 안녕하세요~!! 
바쁘신 와중에 빠른 피드백 감사드립니다. 

마지막 리팩터링 단계에서 사다리 실행 부분에 대해 더 간소화 할 수 있는 부분을 찾다가 
 - 기존 : 게임 실행 시 이전 Dot의 값을 파라미터로 전달하여 이동step을 구하도록 하였는데 
 - 변경 후 : 사다리 생성 시 이전 Dot의 값을 갖고 Dot객체를 생성하도록 변경(피드백 때 리뷰어님께서 한번 말씀 해주신 부분)

위 와 같이 변경을 하니 Line -> getLineIndex 이 기능이 많이 간소화 되긴 했습니다.

혹시 위 내용 외에 또 적용해 볼만 내용이 있다면 의견 부탁드립니다. 

마지막까지 리뷰해주시느라 수고가 많으십니다. 
감사합니다.

2024-11-07 01:04 UTC, csh0034 requested changes
4단계 진행도 잘 해주셨네요 😄 
몇가지 고민해볼 사항 남겨두었는데
확인 부탁드려요!

2024-11-07 01:04 UTC, csh0034 commented on src/main/java/ladder/domain/Dot.java
>      private static int ONE = 1;
클래스 구성요소 순서는 하단과 같습니다.

1. 상수
2. 인스턴스 변수
3. 생성자
4. 인스턴스 메서드

이때 접근 제어자 순서가 높은 경우 더 위에 나타납니다. (public 이 private 보단 위에 선언)

순서를 맞춰보시면 좋을것 같아요.
추가로 상수의 경우 변하지 않는 값이므로 `static final` 로 선언하는것이 일반적이므로
적용해보시면 좋을것 같습니다.

2024-11-07 08:47 UTC, hanhub-ux commented
리뷰어님 안녕하세요~
의견 주신대로 반영을 해보니 점점 깔끔한 구조가 되어 가고 있는거 같습니다. 

정적팩토리 메서드 & nextDot 기능을 구현하고 나니 외부에서 생성자를 호출할 일은 없어 private으로 변경 하였습니다. 
추가로 Dot 객체에 맴버변수 index를 추가 하였습니다. index를 알고 있으면 바로 다음 이동할 index 알수 있습니다. 

감사합니다.

2024-11-08 00:51 UTC, csh0034 approved these changes
리뷰 적용 잘 해주셨네요 👍 
마지막 단계는 이만 머지하도록 할게요.
그동안 수고 많으셨습니다 😄

2024-11-08 00:51 UTC, merged