Step2 - 사다리(생성)
next-step/java-ladder pull request #553
Opened 2020-08-24 02:04 UTC by yongdae

Step2 진행하였습니다.
리뷰 부탁드립니다. 😄 

Step1 단계에서 피드백 주신 사항 반영하고
Step2 미션 진행하였습니다.

Step2는 고민하는 부분이 이전 미션들과 달라서 어렵네요.
😢😢

2020-08-24 12:44 UTC, gale34 commented on src/main/java/nextstep/mission/Ladder.java
> +    private int height;
height는 다시 안쓰는 변수 같은데 남겨두신 이유가 있을까요?

2020-08-24 12:46 UTC, gale34 commented on src/main/java/nextstep/mission/Ladder.java
> +                Objects.equals(participants, ladder.participants);
이 객체에는
participants, height, lines, cursor가 있는데,
participants, height만 같으면 논리적 동치성을 가진다고 생각하신건가요?

2020-08-24 12:48 UTC, gale34 commented on src/main/java/nextstep/mission/Participant.java
> +            throw new IllegalArgumentException("사용자 이름 길이는 5를 초과할 수 없습니다.");
if 문에 단 한줄만 있어도 중괄호를 사용해주세요! :)
https://google.github.io/styleguide/javaguide.html#s4.3-one-statement-per-line
> Braces are used with if, else, for, do and while statements, even when the body is empty or contains only a single statement.

2020-08-24 12:50 UTC, gale34 commented on src/main/java/nextstep/mission/Line.java
> +    }
반복되는 생성 로직은 통합시켜주는게 좋아보입니다:)
```suggestion
    public Line(List<Boolean> points) {
        validate(points);
        this.points = points;
    }

    public Line(int size) {
        this(createPoints(size));
    }
```

2020-08-24 12:52 UTC, gale34 commented on src/main/java/nextstep/mission/Line.java
> +    }
이건 개인마다 다를 수 있긴 한데,
상대적으로 덜 중요한, Object 재정의 메소드의 경우는 클래스 맨 밑에 위치하고, 중요한 도메인 로직을 위쪽에 배치하는건 어떨까요? :)

2020-08-24 12:53 UTC, gale34 commented on src/main/java/nextstep/mission/Line.java
> +    }
도메인 로직와 출력용 코드는 분리시켜주세요:)

2020-08-24 12:54 UTC, gale34 commented on src/main/java/nextstep/mission/Line.java
> +                        throw new IllegalArgumentException("선은 겹칠수 없습니다.");
depth를 줄이기 위해서, 가독성을 높이기 위해서 메소드로 분리하는건 어떨까요?

2020-08-24 12:56 UTC, gale34 commented on src/main/java/nextstep/mission/Line.java
> +                });
반복문이 반복되는 느낌이 드는 코드입니다.
다음 point의 값을 랜덤으로 반환하는 메소드나 클래스를 만들어보는 건 어떨까요?
알고리즘적인 접근이 아니라 객체지향적인 접근이 필요합니다!:)

hint. 겹치지 않기 위해서는 현재 point값을 인자로 이용하면 될 것 같습니다 :)

2020-08-24 12:58 UTC, gale34 commented on src/main/java/nextstep/mission/Main.java
> +        System.out.println("실행 결과");
view 관련 코드는 따로 다른 클래스에서 다루는게 좋을 것 같습니다 :)
Main 메소드에서는 컨트롤러의 역할만 하도록 해주세요!

2020-08-24 12:58 UTC, gale34 commented on src/main/java/nextstep/mission/Main.java
> +        }
view 관련 코드는 따로 다른 클래스에서 다루는게 좋을 것 같습니다 :)
Main 메소드에서는 컨트롤러의 역할만 하도록 해주세요!

2020-08-24 12:59 UTC, gale34 commented on src/main/java/nextstep/mission/Ladder.java
> +    private int cursor;
cursor 변수는 어떤 역할을 하나요?
객체 차원에서의 상태값이라기 보단, 외부에서 이용하는 index 값의 성격인 것 같습니다.
Ladder라는 객체의 **역할과 책임**에 어울리는 값인지 다시 한번 생각해보세요!

2020-08-24 13:02 UTC, gale34 commented on src/test/java/nextstep/mission/LadderTest.java
> +        ));
이 테스트 코드는 객체의 동등성을 검증하는 것 말곤 더 의미가 없을 것 같네요..!
물론 동등성을 테스트하는 단위 테스트코드도 좋지만,
make 라는 테스트 메소드 이름이므로, 차라리 아래처럼 정상적으로 만들어진다는 코드는 어떨까요?
`assertThatCode(() -> Ladder.make(PARTICIPANTS, HEIGHT)).doesNotThrowAnyException();`

2020-08-24 13:04 UTC, gale34 commented on src/test/java/nextstep/mission/ParticipantTest.java
> +        assertThatThrownBy(() -> new Participant("123456"));
어떤 Exception을 던지는지까지 확인하면 좋을 것 같습니다 :)

2020-08-24 13:04 UTC, gale34 commented on src/test/java/nextstep/mission/LineTest.java
> +        assertThatThrownBy(() -> new Line(Arrays.asList(true, true, true, false)));
어떤 Exception을 발생하는 지까지 확인하면 좋을 것 같습니다:)

2020-08-24 13:07 UTC, gale34 requested changes
미션 진행하느라 고생하셨습니다!
사다리 미션부터는 이전보다 더욱 객체를 구분하기가 어려워집니다...많은 고민을 해보세요!
어려우실 수 있지만! 알고리즘적인 접근보다는 객체 지향적인 접근을 하셔야 더 깔끔한 코드를 만드실 수 있을겁니다 :)
객체 구조와 관련된, 그리고 기타 코멘트들을 달았습니다.
참고해서 반영해주시고, 질문있으시면 언제든지 DM 주세요!

2020-08-25 09:59 UTC, yongdae commented on src/main/java/nextstep/mission/Ladder.java
> +    private int height;
코드를 정리하지 않아 남아있는 코드입니다.
수정하겠습니다!

2020-08-25 10:04 UTC, yongdae commented on src/main/java/nextstep/mission/Ladder.java
> +                Objects.equals(participants, ladder.participants);
위와 같이 코드를 정리하지 않아 남아있는 코드입니다. 수정하겠습니다!

다만 동치성에대해서는 어떻게해야할지 판단이 잘 안서네요.

앞에서 Car와 같은 동치를 비교 할 수 있는 값이 있을땐 그 값을 기준으로하면 되는데
Ladder는 참여자 말고는 동치로 쓸수 있는 값이... 잘 모르겠습니다.

이런 부분은 어떻게 수정하면 좋은지 의견부탁드립니다.

2020-08-25 10:06 UTC, yongdae commented on src/main/java/nextstep/mission/Participant.java
> +            throw new IllegalArgumentException("사용자 이름 길이는 5를 초과할 수 없습니다.");
수정하겠습니다.

2020-08-25 10:09 UTC, yongdae commented on src/main/java/nextstep/mission/Line.java
> +    }
오 이건 몰랐던 방식이네요. 감사합니다!!

2020-08-25 10:15 UTC, yongdae commented on src/main/java/nextstep/mission/Line.java
> +    }
수정하겠습니다.

개인적으로 중요 도메인 로직을 아래쪽에 배치하는 편입니다.

로직적인 부분은 수정할 일이 빈번하게 발생하다보니 눈에 약간 거슬린다고해야하나...?
이야기해주시는데는 이유가 있다고 생각하니 그 이유를 고민해보겠습니다.

2020-08-25 10:24 UTC, yongdae commented on src/main/java/nextstep/mission/Line.java
> +    }
네 수정하겠습니다.

2020-08-25 10:28 UTC, yongdae commented on src/main/java/nextstep/mission/Line.java
> +                        throw new IllegalArgumentException("선은 겹칠수 없습니다.");
분리하겠습니다!

2020-08-25 11:08 UTC, yongdae commented on src/main/java/nextstep/mission/Line.java
> +                });
넵 수정하겠습니다.

2020-08-25 11:08 UTC, yongdae commented on src/main/java/nextstep/mission/Main.java
> +        }
네 수정하겠습니다.

2020-08-25 11:39 UTC, yongdae commented on src/main/java/nextstep/mission/Ladder.java
> +    private int cursor;
리뷰해주시는 분 마다 역활과 책임의 범주가 달라서 어느게 맞는것인지
헷갈리네요;;;

수정하겠습니다.

2020-08-25 11:41 UTC, yongdae commented on src/test/java/nextstep/mission/LadderTest.java
> +        ));
이 코드가 훨씬 좋아보이네요. 감사합니다!!!

2020-08-25 12:04 UTC, yongdae commented on src/test/java/nextstep/mission/ParticipantTest.java
> +        assertThatThrownBy(() -> new Participant("123456"));
수정하겠습니다.

2020-08-25 12:04 UTC, yongdae commented on src/test/java/nextstep/mission/LineTest.java
> +        assertThatThrownBy(() -> new Line(Arrays.asList(true, true, true, false)));
수정하겠습니다.

2020-08-26 00:13 UTC, gale34 commented on src/main/java/nextstep/mission/Ladder.java
> +                Objects.equals(participants, ladder.participants);
어떻게 구현하냐에 따라, 그리고 개발자에 따라 정하기 나름일 것 같은데요.
제 생각엔 같은 Ladder 객체라면, participants와 lines가 같으면 동치가 된다고 생각합니다:)

2020-08-26 00:14 UTC, gale34 commented on src/main/java/nextstep/mission/Line.java
> +    }
아하! 그렇군요 :) 명확한 본인만의 기준이 있으시다면 그대로 사용하셔도 됩니다!

2020-08-26 00:29 UTC, gale34 commented on src/main/java/nextstep/mission/Ladder.java
> +    private int cursor;
앞서 다른 리뷰어분들이 어떤 말씀을 해주셨는지 살짝 찾아봤는데요:) 비슷한 방향으로 피드백을 해주신 것 같습니다.
cursor 변수는 외부 객체에서 어느 line까지 조회했는지 파악할 수 있는 기준이 될 것 같은데요. 정말로 필요하다면, 해당 외부 객체에서 cursor 변수를 사용하는게 어울리는 역할이라고 생각합니다.
그렇게 되면 hasNext(int cursor) 형식으로 인자가 추가되겠죠.
**해당 인덱스값이 line 바운더리를 넘어가는 지**는 Ladder가 관리할 수 있지만, **마지막으로 조회한 line의 index를 관리**는 지금 Ladder에서는 어울리지 않는 것 같습니다.
만약 Ladder의 getLine()를 동시에 호출하는 두 객체가 있다면 어떻게 될까요? cursor를 내부 인스턴스 변수로 관리한다면, 두 객체 모두 원하는 getLine() 결과를 얻지 못하게 되는 구조라 생각합니다:)

yongdae님은 벌써 세번째 리뷰어를 만나시게 된 셈인데요:) 리뷰어들마다 약간씩의 견해차이가 있을 수 있습니다. 그럴 때는 질문도 하시고, 왜 이런 피드백을 달았는 지 이유를 생각해보시면서 본인만의 해답을 찾아가시길 바라겠습니다!
화이팅입니다 :)

2020-08-26 00:32 UTC, gale34 commented on src/main/java/nextstep/mission/Ladder.java
> +            return null;
if 문 한줄이라도 중괄호를 사용해주세요 :)
https://github.com/next-step/java-ladder/pull/553#discussion_r475573785

2020-08-26 00:33 UTC, gale34 commented on src/main/java/nextstep/mission/LadderReader.java
> +public class LadderReader {
잘 만들어주신 것 같네요 👍 
따지고 보면, 비즈니스 로직에 필요하다기보단, View 클래스에 필요한 기능이므로 분리시킨 구조가 좋아보입니다 :)

2020-08-26 00:36 UTC, gale34 commented on src/main/java/nextstep/mission/Line.java
> +class RandomPoint {
다른 클래스 파일로 분리하는건 어떨까요? :)
아래 블로그를 한번 읽어보세요!
https://jinseongsoft.tistory.com/225

2020-08-26 00:38 UTC, gale34 commented on src/main/java/nextstep/mission/Line.java
> +    public static List<Boolean> createPoints(int size) {
private 으로 바꿔도 될 것 같습니다 :)
만약 이 메소드 테스트가 필요하다면 생성자에서 이 메소드를 호출하니까, 다양한 테스트 케이스로 생성자를 테스트하면  간접적으로 이 메소드를 테스트하게 될 것 같네요:)

2020-08-26 00:41 UTC, gale34 commented on src/main/java/nextstep/mission/Line.java
> +        return store;
이 클래스는 객체가 아니라 유틸리티 클래스처럼 만들어도 될 것 같은데 어떻게 생각하시나요?:)

2020-08-26 00:45 UTC, gale34 commented on src/main/java/nextstep/mission/Ladder.java
> +    private List<Line> lines;
다음 단계에선 일급컬렉션 사용을 고려해보세요:)

2020-08-26 00:46 UTC, gale34 approved these changes
피드백 반영하느라 고생하셨습니다!
이전 피드백 몇개에 답글도 달아두었고, 코멘트도 드렸으니 참고해주세요:)
다음 단계 진행하시면서 반영해주시면 되겠습니다
머지할게요!

2020-08-26 00:47 UTC, merged

2020-08-26 10:45 UTC, yongdae commented on src/main/java/nextstep/mission/Line.java
> +class RandomPoint {
네 감사합니다!

2020-08-26 10:45 UTC, yongdae commented on src/main/java/nextstep/mission/Ladder.java
> +            return null;
죄송합니다;

2020-08-26 10:55 UTC, yongdae commented on src/main/java/nextstep/mission/Line.java
> +    public static List<Boolean> createPoints(int size) {
수정했습니다!