2단계 - 사다리(생성)
next-step/java-ladder pull request #556
Opened 2020-08-24 13:58 UTC by pcspapa

2단계 - 사다리(생성) 

리뷰 요청 드립니다.

매 번 미션을 수행하면서 고민되는 것이 어떻게 어디까지 해야 하는 부분입니다.
잘 되었는지 모르겠네요.

수고하세요.

2020-08-24 17:08 UTC, parkeeseul requested changes
사다리 아주 예쁘게 그려주셨네요! 👍 

몇가지 코멘트 남겨보았습니다.
확인해보시고 리뷰요청 부탁드려요! 😄

2020-08-24 17:08 UTC, parkeeseul commented on src/test/java/nextstep/ladder/LadderGeneratorTest.java
> +public class LadderGeneratorTest {
중복코드가 발생하고 있네요! 한번 중복을 제거 해보는 것도 좋을거 같아요 ! 😄

2020-08-25 09:49 UTC, pcspapa commented on src/main/java/nextstep/ladder/ViewInput.java
> +  public Players ready() {
이 부분은 UI-Controller 사이의 DTO 개념으로 사용.
클래스 이름은 좀 변경이 필요할 것 같습니다.

2020-08-25 09:58 UTC, pcspapa commented on src/main/java/nextstep/ladder/LadderGenerator.java
> +    for (int i = 0; i < players.getLadderHeight(); i++) {
DTO 에서 get 을 어떻게 수정해서 사용할 수 있나요?
알려주세요.

2020-08-25 10:04 UTC, pcspapa commented on src/main/java/nextstep/ladder/ViewOutput.java
> +        .forEach(horizon -> System.out.printf("%4s%s%n","", horizon));
ㅎㅎ 미션이 스트림을 사용해라가 있어서..
생각없이 사용했네요.

2020-08-25 11:28 UTC, parkeeseul commented on src/main/java/nextstep/ladder/ViewInput.java
> +  public Players ready() {
아하 Players가 DTO의 개념이였군요! 😄 
필수 사항은 아니지만 DTO 라면 생성할 때 방어적 복사를 위해 필드를 final로 해줘도 좋을거 같아요!
또한 정적 팩토리 메소드 명도 한번 고민해보시면 좋을거 같아요! 

https://sun-22.tistory.com/84

2020-08-25 15:03 UTC, parkeeseul approved these changes
구조 아주 잘 변경해주셨네요! 👍 

몇가지 간단한 코멘트 남겨보았습니다!
확인 해보시고 다음 단계에서 함께 반영 부탁드려요!
고생하셨습니다 !

2020-08-25 15:04 UTC, merged

2020-08-26 10:41 UTC, pcspapa commented on src/main/java/nextstep/ladder/ui/LadderRenderer.java
> +  static String center(String text) {
이 부분은 추후 Util 로 바뀔 가능성이 있어서. 
물론 이번 미션에서는 가능성이 없지만요.