[Step02] 사다리(생성) pr입니다.
next-step/java-ladder pull request #563
Opened 2020-08-26 01:49 UTC by samkko

안녕하세요 :)
사다리(생성) pr입니다.

2020-08-26 11:47 UTC, wheejuni requested changes
2단계 과제 진행하시느라 수고 많으셨습니다. 👍 💯 
인라인 코멘트를 통해 개선 의견과 함께 질문 몇 개를 드렸습니다.
확인해주시고 추가 질문은 언제든지 남겨주세요. 감사합니다!

2020-08-26 11:47 UTC, wheejuni commented on src/main/java/com/hskim/ladder/LadderApplication.java
> +        ladderResultView.printLines(ladder.getAllPoints());
`main` 메소드에 담기엔 조금 방대한 로직인 것 같네요. 
저도 잘 감이 안 오긴 합니다만...;; 아래 원칙에 따라 조금만 리팩토링 시도해 보시겠어요? 

- `main` 에게 모든 역할 맡기지 말고, 게임 전체의 라이프사이클을 관리할 클래스를 설계해 본다. 
    - 게임 관리 클래스는 Input/Output view와 사다리의 상태값을 갖는다. 
    - `main` 에서는 해당 게임 관리 클래스의 객체를 만들고, 실행하는 역할만 갖는다.

2020-08-26 11:47 UTC, wheejuni commented on src/main/java/com/hskim/ladder/model/Ladder.java
> +    }
_참고 과제_ `Builder` pattern의 적용을 시도해 보시겠어요?

2020-08-26 11:47 UTC, wheejuni commented on src/main/java/com/hskim/ladder/model/Ladder.java
> +                .collect(Collectors.toList());
`Lines` 클래스에게 직접 `List<LadderPoint>` 를 리턴하는 책임을 부여한다면,
조금 더 깔끔한 코드가 가능해질 것 같네요. 의미상으로도 그게 맞을 것 같구요.

2020-08-26 11:47 UTC, wheejuni commented on src/main/java/com/hskim/ladder/model/LadderLineIterator.java
> +    }
두 생성자가 의미상으로 어떤 차이점을 가지나요? 
`counter` 가 다른 숫자를 가져야 할 필요가 있나요?

2020-08-26 11:47 UTC, wheejuni commented on src/main/java/com/hskim/ladder/model/LadderPoint.java
> +    }
`toString` 은 어떤 의도로 사용되나요? 
아마 생각해보건대 콘솔 프린트를 위한 문자열을 만드는데 사용할 것 같습니다. 
그러나 `enum` 은 `java.lang.Object` 와 구분되고, `toString` 의 본래 목적대로 이 메소드가 설계되진 않은 것 같습니다. 
각 이넘 케이스가 특정 문자열을 표출할 니즈가 있다면, 저라면 `private String caption` 과 같은 필드를 선언하고, 
필드에 값을 적절히 부여한 다음, 이 필드에 대한 getter를 구현할 것 같습니다. 
그렇게 하면 각 enum이 표시해야 할 문자열을 표시할 수 있을 것 같아요.

2020-08-26 11:47 UTC, wheejuni commented on src/main/java/com/hskim/ladder/model/LadderUsers.java
> +    private List<User> users;
`final` 이 붙어있으면 더 좋을 것 같습니다!

2020-08-26 11:47 UTC, wheejuni commented on src/main/java/com/hskim/ladder/model/UserName.java
> +public class UserName {
좋은 시도입니다. 👍 
그러나 과도한 클래스 분리일 수도 있겠다는 생각은 듭니다. 
우선 지금 이 클래스가 담고 있는 상수 필드들은, 이 클래스가 관리하는 것도 나쁜 방향은 아니지만 `view` 성 클래스들이나, 심지어 프로젝트 전역에서 사용되는 [상수 클래스](https://stackoverflow.com/questions/479565/how-do-you-define-a-class-of-constants-in-java) 로 관리해도 괜찮겠다는 생각은 듭니다. 

지금 이 클래스가 갖고 있는 책임이 이름 문자열의 보관과, 이름 문자열을 생성할 때의 유효성 검증이므로,
이런 역할은 과감히 `User` 에게 맡기고 이 클래스는 삭제해도 되겠다는 생각이 드는데요, 
혹시 이 클래스를 설계하실 때의 설계 의도를 공유해주시면 더 나은 피드백이 가능할 수도 있겠네요.

2020-08-26 12:08 UTC, samkko commented on src/main/java/com/hskim/ladder/LadderApplication.java
> +        ladderResultView.printLines(ladder.getAllPoints());
넵 말씀해주신 대로 리팩토링 시도해보겠습니다 🤔

2020-08-26 12:10 UTC, samkko commented on src/main/java/com/hskim/ladder/model/Ladder.java
> +    }
넵 생성자의 인자의 갯수가 다소 많으니 빌더 패턴을 적용해보는것도 좋아보이네요! 수정해보겠습니다. :)

2020-08-26 12:11 UTC, samkko commented on src/main/java/com/hskim/ladder/model/Ladder.java
> +                .collect(Collectors.toList());
구현하면서도 Line -> Lines -> Ladder로 이어지는 인자전달에서 어떻게 전달해야 좋을지 많이 고민했던 부분이였는데
피드백 감사합니다 :) 말씀해주신것 참고해서 다시 생각해보고 수정하겠습니다!

2020-08-26 12:17 UTC, samkko commented on src/main/java/com/hskim/ladder/model/LadderLineIterator.java
> +    }
![image](https://user-images.githubusercontent.com/28282811/91302328-42a52b00-e7e1-11ea-8a1a-05fde1b7cfee.png)
TC에서 사용하기 위해 만들었던 생성자 입니다.
counter를 값으로 받는 생성자를 만들지 않으면 
isOnLastIndex()를 테스트 하기 위해 next()함수를 여러번 호출하는 코드가 만들어 질것이라고 생각이 되어서요!
혹시 다른 좋은 방법이 있다면 다시한번 피드백 부탁드립니다. 🙇

2020-08-26 12:20 UTC, samkko commented on src/main/java/com/hskim/ladder/model/LadderUsers.java
> +    private List<User> users;
넵 :) users필드에 값이 재할당될 일이 현 요구사항에서는 없어보이네요. 다른 곳도 다시한번 생각해 보겠습니다. 감사합니다.

2020-08-26 12:22 UTC, samkko commented on src/main/java/com/hskim/ladder/model/UserName.java
> +public class UserName {
저번 강의에서 과하다 싶을정도로 클래스를 분리해보라고 말씀해주셨던게 생각나서 최대한 나눠보았던 클래스입니다.
한번 연습해 보았으니 수정해보도록 하겠습니다. 상수 클래스로 관리하는 방식은 처음 보는 방식이네요!
링크 주신 글 읽어보고 고민해보겠습니다. 감사합니다 :)

2020-08-26 12:59 UTC, samkko commented on src/main/java/com/hskim/ladder/model/LadderPoint.java
> +    }
enum이 출력해야할 문자를 가지는것에 대해, 이전 미션에서도 고민한적이 있는데
저는 출력해야할 문자열은 View가 책임을 가져야 한다고 생각했습니다. 
예를 들어 콘솔출력외에 웹출력에 대한 요구사항이 추가되고, 동일 enum 요소에 대해 콘솔과 웹에서 다른 출력을 원한다면
도메인(LadderPoint)가 수정되어야 하는데 이러한 구조보다는 View가 담당하는게 좋다고 생각합니다. 
enum이 java.lang.Object와는 구분된다는 사실은 처음 알았네요! 
![image](https://user-images.githubusercontent.com/28282811/91306229-3754fe00-e7e7-11ea-9d20-612f5ba655c8.png)
말씀해주신 대로 toString이라는 메소드명은 좋지 못한것 같습니다.
좀 더 명확히 의도를 표현할 수 있는 메소드명으로 수정해보도록 할게요 :)
혹시 다른 의견이 있으시다면 다시 피드백 부탁드려요!

2020-08-27 02:58 UTC, samkko commented on src/main/java/com/hskim/ladder/model/UserName.java
> +public class UserName {
UserName클래스의 역할 -> User에게 맡기는것에 대해선 저도 휘준님과 생각이 같아 리팩토링 진행하였습니다. :) 
그런데 상수클래스로 관리하는 방법에 대해서는 첨부해주신 링크 읽고 고민해보았는데, 저는 아래의 답변에 조금 더  공감이되었습니다. 🤔 
해당 상수와 가장 관련이있는 클래스에 상수를 두게되면 다른 클래스에서 해당 상수를 사용할때에도
클래스명.상수 로 사용하게 되니 읽을때에도 더 좋지 않을까 하는 생각입니다.
![image](https://user-images.githubusercontent.com/28282811/91378457-6dcc6080-e85b-11ea-87e9-72da1c81d579.png)
휘준님이 생각하시는 상수 클래스로 관리했을때의 장점은 무엇인가요?
의견 공유해주시면 앞으로 설계할때 생각의 폭이 넓어질것 같습니다. :)

2020-08-27 07:32 UTC, samkko commented
피드백 반영하여 수정해보았습니다.
위에 말씀해주신 내용에 추가로 질문 남겨두었습니다! 
함께 확인부탁드려요 :) 감사합니다. 🙇

2020-08-28 13:19 UTC, wheejuni commented on src/main/java/com/hskim/ladder/model/UserName.java
> +public class UserName {
우선 첨부해주신 스크린샷 기준으로 생각하면, 3번은 저도 반대합니다. 별로 좋은 방법이 아닙니다. 
그러나 제가 느끼기에는 콘솔 출력을 위한 문자열은 _콘솔 출력이 실제 일어나는 클래스_ 에서 관리하는게 더 직관적이라고 생각되기는 합니다. 
그리고 콘솔 입/출력만을 위한 상수들의 경우 묶어서 상수 클래스로 보관하는 것도 의미있다 생각하고요.
그래서 쉽게 말씀드리면 비슷한 특성을 갖고 비슷한 용처를 갖는 상수의 경우 묶어도 된다는게 제 생각입니다. 
지금 상황은 조금은 애매하긴 하네요. ㅎㅎ

2020-08-28 13:22 UTC, wheejuni approved these changes
피드백 반영해주셔서 감사하고, 리뷰가 다소 늦어져 죄송합니다.
직접 연구하고 고민하시면서 정성들여 작성하신 댓글 모두 잘 읽어 보았습니다. 💯 
제 생각도 조심스레 남겨드렸는데 확인해 주시고요.
이번 단계에서의 충분한 학습과 경험이 일어난 것 같아 일단 merge 하겠습니다.
3단계에서도 같이 즐겁게 코딩해 보시죠~

2020-08-28 13:22 UTC, wheejuni commented on src/main/java/com/hskim/ladder/model/Ladder.java
> +    public static class LadderBuilder {
👍

2020-08-28 13:22 UTC, wheejuni commented on src/main/java/com/hskim/ladder/model/User.java
> +    private static final String EXCEED_NAME_LENGTH_LIMIT = "유저 이름은 " + NAME_LENGTH_LIMIT + "자를 초과할 수 없습니다.";
상수 문자열에서 문자열에 대한 연산이 일어나지 않았으면 좋겠는데요. 
어떤 의도로 이렇게 구현하셨는지는 충분히 이해합니다. 👍 💯

2020-08-28 13:22 UTC, merged

2020-08-31 04:36 UTC, samkko commented on src/main/java/com/hskim/ladder/model/User.java
> +    private static final String EXCEED_NAME_LENGTH_LIMIT = "유저 이름은 " + NAME_LENGTH_LIMIT + "자를 초과할 수 없습니다.";
말씀해주신 내용 알아보겠습니다 :) 감사합니다!