3단계 - 사다리(게임 실행)
next-step/java-ladder pull request #572
Opened 2020-08-28 11:43 UTC by sefide

안녕하세요 리뷰어님 :)
3단계 - 사다리(게임 실행) 구현 완료했습니다.

사다리 게임 결과를 내는 기능이 추가되면서 
참가자의 정보를 담는 Participant 클래스와 참가자별 결과 정보를 가지는 LadderGameResult 클래스를 생성하였습니다. 
또한 지난 리뷰에서 코멘트해주셨던 내용도 반영해보았습니다.

리뷰 부탁드리겠습니다.
감사합니다 !

2020-08-29 02:58 UTC, seogi89 requested changes
기능구현 잘해주셨어요 👍 
세세한 커밋 메세지는 정말 코드 읽기를 편하게 해주는것 같아요 💯 
전체적으로도 잘 읽히는 코드인 것 같습니다.

사소한 팁 몇가지와 객체 관계에 대한 질문 남겨놓았으니 확인 후에 리펙토링 진행해주세요.

건강 유의하시고 즐거운 주말 되시길 바라요.

2020-08-29 02:58 UTC, seogi89 commented on src/main/java/ladder/LadderGameController.java
> +        for (int i = 0; i < 3; i++) {
최대 3번만 확인한 조건은 왜 추가하셨을까요 ? 🤔

2020-08-29 02:58 UTC, seogi89 commented on src/main/java/ladder/LadderGameController.java
> +        LadderResult ladderResult = LadderResult.of(participants, InputView.scanLadderResult());
reward 같은 의미가 더 적합하지 않을까요?
LadderGameResult  와 어떤 차이가 있을지 오랫동안 고민하게 되는 변수명인 것 같아요.

2020-08-29 02:58 UTC, seogi89 commented on src/main/java/ladder/domain/Ladder.java
> +                .collect(Collectors.toList());
```     
        Stream.generate(() -> Line.create(participant, lineGenerator))
                .limit(ladderHeight)
                .collect(collectingAndThen(toList(), Ladder::new));
```

이렇게 쓰는게 의미 전달상더 명확할 것 같아요.

2020-08-29 02:58 UTC, seogi89 commented on src/main/java/ladder/domain/LadderResult.java
> +    }
public 으로 외부에 제공하는 생성 메소드들의 형태를 다르게 한 이유가 있을까요?
하나는 생성자방식 하나는 정적팩토리메소드로 두신 이유가궁금합니다.

참가자의 숫자와 보상의 숫자가 같음을 확인하는 책임을 누가 가지고 있어야 할지 고민이 되네요 🤔

2020-08-29 02:58 UTC, seogi89 commented on src/main/java/ladder/domain/Name.java
> +public class Name {
극단적인 객체 분리 👍 
연습과정에서는 충분한 도움이 되리라 생각합니다!

2020-08-29 02:58 UTC, seogi89 commented on src/main/java/ladder/domain/Name.java
> +        Name name1 = (Name) o;
자동 완성을 이용하셨겠지만, 일반적으로 that을 많이 사용하는 것 같아요.

2020-08-29 02:58 UTC, seogi89 commented on src/main/java/ladder/domain/Participant.java
> +    }
생성자를 생략하신것은 의도하신바가 있으실까요 ?

2020-08-29 02:58 UTC, seogi89 commented on src/main/java/ladder/domain/Participant.java
> +        ladder.getLines()
getter 를 사용하지 않고
ladder 에게 시작 index 를 넘겨주면 도착 index 를 받는 방식이 좀더 객체 지향적일 것 같아요.
calculateOrder 에 대한 책임도 Ladder 가 가져 갈 수 있을 것 같구요.

2020-08-29 02:58 UTC, seogi89 commented on src/main/java/ladder/domain/Participants.java
> +                .collect(Collectors.toList());
stream 에서 index를 쉽고 이쁘게 사용할 수 없는 부분은 아쉬운 것 같아요 🤔 
지금과 같이 index 가 필요한 경우에 for 와 stream 중 어떤것이 가독성이 좋다고 생각하시나요.

2020-08-29 02:58 UTC, seogi89 commented on src/main/java/ladder/exception/LadderExceptionMessage.java
> +public final class LadderExceptionMessage {
👍

2020-08-29 02:58 UTC, seogi89 commented on src/test/java/ladder/domain/LadderResultTest.java
> +    @MethodSource("makeGetResultByData")
👍

2020-08-29 06:06 UTC, sefide commented on src/main/java/ladder/LadderGameController.java
> +        for (int i = 0; i < 3; i++) {
요구사항에 질문 횟수에 대한 조건이 따로 없고 실행결과 예시에서는 2번 확인하는걸로 보여서 2번 이상의 질문을 하면 되겠구나 생각하여 추가하였습니다.

2020-08-29 06:09 UTC, sefide commented on src/main/java/ladder/LadderGameController.java
> +        LadderResult ladderResult = LadderResult.of(participants, InputView.scanLadderResult());
넵 맞아요 실행 결과라는 표현에 맞춰서 짓다보니 결과적으로 게임의 결과(LadderGameResult)와 헷갈리는 네이밍을 헷네요 ! 
재석님께서 말씀해주신 Reward가 훨씬 적합한 것 같습니다 ! 감사합니다 👍

2020-08-29 06:25 UTC, sefide commented on src/main/java/ladder/domain/Ladder.java
> +                .collect(Collectors.toList());
오 람다를 이용해 스트림 요소를 만드는건 iterate와 똑같지만 iterate는 초기값을 지정해준다는 점에서 차이가 있군용
generate를 이용한게 확실히 더 명확하게 보이네요. 좋은 팁 배우고 갑니다 🙏

2020-08-29 07:22 UTC, sefide commented on src/main/java/ladder/domain/LadderResult.java
> +    }
가변인자를 받는 생성자는 테스트용으로 생성했는데요 ~
지난 포비님 강의에서 테스트를 위한 생성자를 만드시는 것을 보고 그 부분을 따라하면서 공부했는데 정적팩토리 메소드를 생성하고 나서 제거하지 않고 그대로 두었네요..! 단순히 생성만 해주는 테스트용 생성자라 생각해 참가자의 숫자와 보상의 숫자가 같음을 확인하는 유효성 검증은 따로 넣지 않았습니다. 
정적팩토리메소드(of)가 실제 비즈니스 로직에서 LadderReward를 생성하는데 사용되는데, 테스트용으로 만들어둔 생성자가 실제 로직에서 사용되면 유효성 검증이 안된 인스턴스가 생성될 수 있는 위험이 있을 것 같아요.
음 이렇게 테스트용으로 구현해둔 생성자는.. 테스트후 제거하는게 좋을지, 주석을 남기는게 나을지 고민이 되는데요. 
재석님이라면 이런 상황에서 어떤 방향으로 진행하실지 궁금합니다 !

2020-08-29 07:27 UTC, sefide commented on src/main/java/ladder/domain/Name.java
> +        Name name1 = (Name) o;
넵 that이라는 변수명이 더 명확히 보이겠네요. 
수정해보겠습니다 :)

2020-08-29 07:32 UTC, sefide commented on src/main/java/ladder/domain/Participant.java
> +    }
어떤 생성자를 말씀하시는건가요 ~?

2020-08-29 07:39 UTC, sefide commented on src/main/java/ladder/domain/Participant.java
> +        ladder.getLines()
오 넵 ! 사실 foreach를 사용해서 result값을 처리하는게 좋지 않은 방법이라 알고 있어 고민을 했지만.. 좋은 방법이 떠오르지 않아 마음에 걸렸던 부분입니다 😓 재석님의 말씀에 힌트를 얻어 고민해보고 수정해보겠습니다 ! 감사합니다 !

2020-08-29 07:40 UTC, seogi89 commented on src/main/java/ladder/domain/Participant.java
> +    }
읔 어제 오늘 실수가 많군요 ㅜㅜ 접근 제어자 입니다.

2020-08-29 07:46 UTC, sefide commented on src/main/java/ladder/domain/Participants.java
> +                .collect(Collectors.toList());
음 지금의 코드에서는 index을 사용하고 있어 단순한 반복문은 아니지만 index 값이 어떻게 사용되는지 명확히 보이지 않는 것 같아요. 
for문에서는 index를 활용해 Participant를 생성한다는게 좀 더 명확하게 보이지 않을까요 ? 

이번 과제가 Stream 연습이 목적이라는 생각에 과용을 한 것 같습니다ㅜㅜ!

2020-08-29 08:48 UTC, sefide commented on src/main/java/ladder/domain/Participant.java
> +    }
아하 괜찮습니다 :)
두 메소드가 같은 패키지의 Participants 내에서만 사용 가능하도록 막아야한다는 생각에 제거했는데요 ~
생각해보니 setter나 생성자와 같이 상태값을 변화시키는 메소드가 아니라서, 그럴 필요가 없을 것 같네요..!

2020-08-29 09:21 UTC, sefide commented
리뷰어님 코멘트 달아주신 내용 반영했습니다. 
생각이 부족했던 부분들을 잡 집어내주셔서 리뷰 내용을 반영하면서 새롭게 배운 부분도 있고 좋은 팁도 얻어갑니다.
감사합니다 !

그럼 재리뷰 부탁드립니다 :)

2020-08-29 10:04 UTC, seogi89 commented on src/main/java/ladder/domain/LadderResult.java
> +    }
테스트를 위한 인터페이스를 최대한 지양하고 있기는 하지만, 쉬운길로 가고싶은 욕심을 항상 버리기가 어려운 것 같습니다.
개인적으로는 프러덕션 코드에서 사용되지 않는 코드는 남기지 않는 편입니다.

2020-08-29 10:13 UTC, seogi89 approved these changes
빠르게 피드백 반영해주셨네요 :) 
코드가 워낙 구조가 잘 잡혀 있어 변경에 쉽게 대처가 가능 한것 같아요 👍 

조금 더 책임을 분산 시킬 수 있을 만한 고민 거리를 코멘트로 남겨 놓았으니, 다음 단계에서 고민해보아요.

고생하셨습니다

2020-08-29 10:13 UTC, seogi89 commented on src/main/java/ladder/LadderGameController.java
> +        for (int i = 0; i < 3; i++) {
참여자수가 가변적이니 다른 종료 조건을 잡을 수 있는게 더 좋을 것 같아요
all 이 입력되면 종료된다거나 하는 조건은 어떤가요 ?

2020-08-29 10:13 UTC, seogi89 commented on src/main/java/ladder/view/InputView.java
> +    private static final String LADDER_REWARD_MESSAGE = "\n실행 결과를 입력하세요. (결과는 쉼표(,)로 구분하세요)";
쉽게 놓칠 수 있는 부분까지 👍

2020-08-29 10:13 UTC, seogi89 commented on src/main/java/ladder/domain/Line.java
> +
return points.move(index):

point 스스로 이동할 수 있지 않을까요 ?

2020-08-29 10:13 UTC, merged

2020-08-30 03:46 UTC, sefide commented on src/main/java/ladder/domain/Line.java
> +
오 넵넵 Point에서 값을 꺼내서 확인하는것보다 Point에게 이동 명령을 내리는게 더 객체지향적이겠네요 !
다음 스텝에서 반영해보겠습니다 :)