Step2 - 사다리(생성)
next-step/java-ladder pull request #589
Opened 2020-09-02 14:09 UTC by LimHanGyeol

안녕하세요. Step2 리뷰 요청드립니다 .. !

사다리게임에 대해 게임 방식 파악이 오래걸려 문의드린 시간에 비해 PR이 늦었네요 .. !
게임 로직 파악이 미숙하다보니 TDD 사이클로 진행하지 못했습니다.
미비점이 있을 수 있다고 생각들어요.

피드백 주시면 반영하겠습니다 ! 잘 부탁드립니다 !
태풍 조심하세요 ,, !

2020-09-03 13:18 UTC, wheejuni requested changes
2단계 진행해 주시느라 수고 정말 많으셨습니다! 💯 👍 
간단한 구조개선사항 제안과 리팩토링 거리들 몇 개 짚어 드립니다. 
한번 진행해보시고, 추가 질문이 있다면 언제든지 알려주세요.

2020-09-03 13:18 UTC, wheejuni commented on src/main/java/nextstep/ladder/domain/LadderAutoGenerator.java
> +    }
지금 이 메소드의 쓰임새를 보면...
`right()` 여부를 판단하게끔 호출된 다음에, 실제 라인의 생성은 다른 클래스들의 생성자나 스태틱 팩토리 메소드들에서 이뤄지고 있는데요, 이 로직 구성이 직관적이도 않을 뿐더러, `LadderGenerator` 라는 이 인터페이스의 이름과도 조금 맞지 않는 부분이 있는 것 같습니다.

이 클래스가 갖는 로직을 좀 더 넓혀서 여기서 `List<Line>` 을 리턴하도록 구성하면 어떨까 제안해 봅니다.

2020-09-03 13:18 UTC, wheejuni commented on src/main/java/nextstep/ladder/domain/Line.java
> +import static nextstep.ladder.domain.Point.*;
객체의 생성을 담당하는 역할을 하는 메소드를 `static import` 하시는 경우, 
이 메소드가 어떤 도메인/클래스에 종속되는지 몰라 코드 파악에 조금 어려움을 겪는 경우가 생깁니다. 
코딩 량이 아주 약간 늘어납니다만, 그래도 차라리 `Point.first()` 와 같이 사용하시는 것을 추천드리고 싶어요.

2020-09-03 13:18 UTC, wheejuni commented on src/main/java/nextstep/ladder/domain/User.java
> +    }
1. 이 메소드가 `public` 이여야 하나요?
2. 메소드명의 직관성을 조금 더 더해주시기를 권해드립니다! `.getUserName()` 보다는 단순한 기능을 수행하고 있는 것 같네요.

2020-09-03 14:15 UTC, LimHanGyeol commented on src/main/java/nextstep/ladder/domain/LadderAutoGenerator.java
> +    }
음 이부분에 대해서 쉽게 와닿지 않는데 한번 더 설명 부탁드려도 될까요 ??

2020-09-04 12:37 UTC, LimHanGyeol commented on src/main/java/nextstep/ladder/domain/User.java
> +    }
해당 메소드 네이밍을 "splitByUserName"로 변경했습니다.
public으로 한 이유는 테스트 코드로 인해 하게되었는데,
User생성 책임을 분리하기위해 UserGenerator 클래스를 추가하고, 해당 메소드는 그대로 유지하게 되었습니다.

2020-09-04 12:37 UTC, LimHanGyeol commented on src/main/java/nextstep/ladder/domain/Line.java
> +import static nextstep.ladder.domain.Point.*;
반영했씁니다 !!

2020-09-04 12:39 UTC, LimHanGyeol commented on src/main/java/nextstep/ladder/domain/LadderAutoGenerator.java
> +    }
위의 피드백과 함께 생각하여 말하면,
이 부분에 대해서는 책임부여와 네이밍이 부족했다고 생각이 듭니다.

변경한 내용은 LadderLineGenerator 클래스는 LadderLine에 흩어져있던 생성 책임을 분리하여 부여했습니다.
그리고 기존 구현되어있던 Generator 클래스들은 클래스명을 변경하여 책임을 분명하게 하였습니다.

생성자 매개변수로는 인터페이스 타입을 받게하여 테스트 코드에서는 임의로 포인트 값을 주었고,
프로덕션 코드에서는 랜덤생성을 주입하여 랜덤한 사다리 라인 만들기가 되도록 의도하여 변경했습니다.

휘준님의 의도에 맞게 이해하고 구현했을까요 ??

2020-09-05 01:37 UTC, wheejuni approved these changes
피드백 반영하시느라 수고 많으셨어요. 👍 💯 
3단계에서도 좋은 코드 기대하겠습니다. 감사합니다!

2020-09-05 01:37 UTC, wheejuni commented on src/main/java/nextstep/ladder/domain/RightPointStrategy.java
> +public interface RightPointStrategy {
👍

2020-09-05 01:37 UTC, merged

2020-09-05 01:37 UTC, wheejuni commented
코멘트에 대한 답변은 따로 달아드리겠습니다.

2020-09-05 01:38 UTC, wheejuni commented on src/main/java/nextstep/ladder/domain/LadderAutoGenerator.java
> +    }
좋습니다. 👍 💯 
제 의도와는 살짝 다른 부분이 있지만, 지금 구현해주신 방향도 충분히 직관적이라는 생각이 듭니다. 
`LadderLineGenerator` 를 분리하신 것도 좋은 시도입니다.