Step03 - 사다리(게임 실행) PR입니다.
next-step/java-ladder pull request #608
Opened 2020-09-06 11:07 UTC by misudev

안녕하세요 리뷰어님!

사다리타기 step03- 사다리(게임 실행) PR 입니다.

매번 좋은 리뷰 감사합니다 😃 

이번 리뷰도 잘 부탁드립니다~!

2020-09-06 12:36 UTC, sah3122 requested changes
요구사항 구현을 잘해주셨네요. 👍 
몇가지 피드백 남겨드렸는데 확인 부탁드립니다 😄 
막히는 부분이 있거나 고민되는 부분이 있으면 편하게 DM 주시면 됩니다. !

2020-09-06 12:36 UTC, sah3122 commented on src/main/java/ladder/LadderApplication.java
> +        if (ALL_USER_QUERY_STRING.equals(resultUserName)) {
loop를 돌려서 `all `이 입력되기 전까지 사다리 게임을 계속 진행해볼수 있을까요 :)

2020-09-06 12:36 UTC, sah3122 commented on src/main/java/ladder/LadderApplication.java
> +        LadderResult ladderResult = ladderGame.makeLadderResult(prizes);
사다리 타기의 결과값을 생성하지 않고 요청이 들어오는 순간 마다 탐색하는 구조로 변경해볼수 있을까요 ?

2020-09-06 12:36 UTC, sah3122 commented on src/main/java/ladder/model/Line.java
> +    private void validateLine(List<Boolean> steps) {
사용하지 않는 메소드는 삭제하는것이 어떨까요 ?

2020-09-06 12:36 UTC, sah3122 commented on src/main/java/ladder/model/Line.java
> +    public void processLine(Users users) {
사다리 타기를 진행하면서 Users 객체의 값이 변경되고 있네요. 
Line이라는 클래스는 사다리 가로 한줄을 의미하는 클래스입니다. 
사다리 가로 한줄에서 Users에 대한 정보를 알고 있을 필요가 있을까요 ? 
Line이 가지고 있는 step 객체를 활용해서 사다리 타기를 진행 해보는것을 권장 드려요.
많은 고민이 되실수도 있는데 혼자 해결하기 힘들다면 편하게 DM 주세요 :)

2020-09-08 19:53 UTC, misudev commented on src/main/java/ladder/model/Line.java
> +    public void processLine(Users users) {
넵 ㅠㅠ 이번 스텝 진행하면서 제일 고민했던 부분이에요.
말씀해주신대로 한 Line이 Users 정보를 알고, Users의 값이 변경되는 건 잘못된 방향 같네요 😭
고민해보고 수정하도록 하겠습니다 :)

2020-09-08 20:36 UTC, misudev commented
안녕하세요 동철님! 많이 늦었습니다 ㅠㅠ 
코멘트 주신 것을 바탕으로 다시 고민하여 수정해보았습니다.
수정 사항은 다음과 같습니다~!

- LadderResult를 제거하고, 요청이 들어올 때마다 게임을 실행하도록 수정했습니다.
- Line이 Users를 받아 변경하던 기존 로직에서 위치(index)를 받고, 이동할 위치를 반환하도록 수정했습니다.
- 실행 결과 출력 시 'all'을 받을 때까지 반복하도록 했습니다.

하다보니 controller의 역할이 커진것 같아 고민되네요.. 🤔
다시 한번 리뷰 부탁드립니다 🙏

2020-09-09 13:47 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다. 👍 
사다리 객체가 자율적으로 행동할 수 있게 된것 같아요 😄 
간단한 피드백 몇가지 남겨두었으니 확인 부탁드려요. 
다음 미션을 진행하면서는 부족한 테스트 코드도 반드시 작성해보세요 !

2020-09-09 13:47 UTC, sah3122 commented on src/main/java/ladder/LadderApplication.java
> +            if (ALL_USER_QUERY_STRING.equals(resultUserName)) {
들여쓰기는 1까지만 허용해주세요 :)

2020-09-09 13:47 UTC, sah3122 commented on src/main/java/ladder/model/Line.java
> +    private boolean hasBeforeStep(int position) {
라인 한줄을 생성하는 시점에서 
첫번째, 마지막 Step은 왼쪽으로 갈수 없고, 오른쪽으로 갈수 없는 특별한 규칙이 존재하니 구분지어보는것도 좋을것 같아요 :)

2020-09-09 13:47 UTC, sah3122 commented on src/main/java/ladder/model/Line.java
> +            return pointIndex + 1;
```suggestion
            return moveRight();
```
와 같이 의미를 부여할수 있을것 같습니다 :)

2020-09-09 13:47 UTC, sah3122 commented on src/main/java/ladder/model/Lines.java
> +        return pointIndex;
마지막 위치값만 전달 하는 구조 좋네요 👍 
사다리가 자율적으로 사다리 타기 게임을 진행할 수 있게된것 같아요

2020-09-09 13:47 UTC, sah3122 commented on src/main/java/ladder/LadderApplication.java
> +        int height = InputView.getHeight();
InputView 의 호출을 줄여볼수 있을것 같아요 😄 
Dto 역할을 하는 객체를 만들어보세요 !

2020-09-09 13:47 UTC, sah3122 commented on src/main/java/ladder/model/Line.java
>          }
`!hasBeforeStep(i) && generateStrategy.generate();`와 같은 코드도 가독성을 위해 generateStep() 과 같이 포장해보는것도 좋을것 같아요 !

2020-09-09 13:47 UTC, sah3122 commented on src/main/java/ladder/model/Line.java
> +    public int movePoint(int pointIndex) {
리팩토링을 진행하면서 방향을 가진 Step객체를 만들어 조건문을 줄여보도록 하세요 !

2020-09-09 13:47 UTC, sah3122 commented on src/main/java/ladder/model/Ladder.java
> +    protected int rideLadder(int userPoint) {
테스트 코드가 필요해보여요.

2020-09-09 13:47 UTC, sah3122 commented on src/main/java/ladder/model/Lines.java
> +    public int processLines(int pointIndex) {
테스트 코드가 필요해 보여요 !

2020-09-09 13:47 UTC, merged

2020-09-11 14:27 UTC, misudev commented on src/main/java/ladder/model/Line.java
> +            return pointIndex + 1;
네 ㅎㅎ 훨씬 명확하네요👍

2020-09-11 14:33 UTC, misudev commented on src/main/java/ladder/model/Ladder.java
> +    protected int rideLadder(int userPoint) {
네 😭 테스트 코드가 미비했네요 :( 다음 스텝때 추가하도록 하겠습니다~!

2020-09-11 14:35 UTC, misudev commented on src/main/java/ladder/model/Line.java
>          }
네ㅎㅎ 그럼 더 읽기좋은 코드가 되겠네요!