Step2
next-step/java-ladder pull request #612
Opened 2020-09-06 13:15 UTC by skid901

안녕하세요, 이슬 님.

코드리뷰 요청드립니다.

잘 부탁드립니다. ^^7

2020-09-07 01:59 UTC, parkeeseul requested changes
미션 잘 진행해주셨습니다! 👍 

그런데 테스트 코드가 존재하지 않네요 😢 
몇가지 소소한 코멘트 남겨보았으니 한번 확인 부탁드리고
테스트 코드도 추가 부탁드려요! 😄

2020-09-07 07:50 UTC, skid901 commented
안녕하세요, 이슬 님.

리뷰 해주신 내용을 바탕으로 코드를 수정하고, 테스트 코드를 추가해 보았습니다.

다시 코드리뷰 요청드립니다.

감사합니다. ^^7

2020-09-07 14:16 UTC, parkeeseul requested changes
테스트 코드 잘 작성해주셨네요! 👍 

몇가지 추가 코멘트 남겨보았으니 
한번 확인 해보시고 다시 한번 리뷰요청 부탁드릴게요! 😄 

비가 계속 오네요 😢  조금 쳐질수도 있지만 화이팅 입니다! 🔥

2020-09-07 23:12 UTC, skid901 commented
안녕하세요, 이슬 님.

코드를 상세하게 리뷰 해주셔서 감사합니다.

말씀해주신 대로 `entity` 클래스 내부에 팩토리 메소드를 구현함으로써, 클래스 간 역할을 분명하게 분리할 수 있었던 것 같습니다.

그 외에 다른 사항들도 반영하여 리팩토링을 진행했습니다. 다시 한번 코드리뷰 요청드립니다.

감사합니다. ^^7

2020-09-08 13:18 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
잘 반영해주셔서 따로 코멘트 남길게 없었습니다! 😄 

다음 미션 진행해주세요!  
화이팅 입니다! 🔥

2020-09-08 13:19 UTC, merged