3단계 - 사다리(게임 실행)
next-step/java-ladder pull request #615
Opened 2020-09-06 16:06 UTC by ap-jylee

3단계를 하면서 main 메소드가 많이 복잡해졌습니다. all 분기처리를 딱히 할 곳이 없어서 그대로 진행하였습니다.
또한 이번에 새롭게 track 이라는 객체를 도입했는데요. 
기존의 line 을 횡단선(가로선)으로 사용하고 track 을 세로선으로 사용했습니다.
새로운 객체가 추가되면서 로직이 복잡해지기도 하고 간소화되기도 하였는데요. 피드백 부탁 드립니다.

2020-09-07 07:34 UTC, ohtaeg requested changes
리뷰가 늦어 죄송합니다 🙏 
현재 게임이 원할하게 진행이 되질 않으니 확인 부탁드릴게요!
추가로 구현해주신 부분에 대해 피드백을 드렸으니 확인 부탁드리겠습니다!

피드백 반영 후 재요청 주세요!

2020-09-07 07:34 UTC, ohtaeg commented on src/main/java/nextstep/domain/Tracks.java
> +    }
다음과 같이 변경한다면 메서드의 기능이 명확해질 것 같아요.
```suggestion
    public boolean isFirstTrack(int trackNumber) {
        return findTrack(new Track(trackNumber)).isSameTrackNumber(FIRST_TRACK_NUMBER);
    }
    
    public boolean isLastTrack(int trackNumber) {
        return findTrack(new Track(trackNumber)).isSameTrackNumber(tracks.size() - 1);
    }

    private Target findTrack(Track searchTarget) {
        return tracks.stream()
                  .filter(searchTarget::equals)
                  .findAny()
                  .orElseThrow(IllegalArgumentException::new);
    }
```

2020-09-07 07:34 UTC, ohtaeg commented on src/main/java/nextstep/app/LadderGameApp.java
> +    private static LadderResult getLadderResult(Participants participants, LadderResults ladderResults, LadderGameManager ladderGameManager, String personForResult) {
현재 많은 파라미터를 던지고 있습니다! 파라미터 갯수를 줄여주세요 :)

2020-09-07 07:34 UTC, ohtaeg commented on src/test/java/nextstep/domain/LinesTest.java
> +public class LinesTest {
모든 테스트가 실패하고 있으니 확인해주세요 :)

2020-09-07 07:34 UTC, ohtaeg commented on src/main/java/nextstep/domain/LadderResults.java
> +    private final List<LadderResult> ladderResults;
사다리의 결과를 List로 관리해도 좋지만 어떤 참가자가 어떤 결과를 갖고 있는지 관리하도록 변경이 되면 더 좋을 것 같은데 어떻게 생각하시나요 :) ?

2020-09-07 07:34 UTC, ohtaeg commented on src/main/java/nextstep/app/LadderGameApp.java
> +        LadderResult ladderResult = getLadderResult(participants, ladderResults, ladderGameManager, personForResult);
LadderResults를 알고있다면 LadderResult는 LadderResults를 통해 알 수 있다고 생각해요!

2020-09-07 07:36 UTC, ohtaeg commented on src/main/java/nextstep/domain/LineValidator.java
> +    }
Validator가 추가가 될때마다 내부 클래스가 생성되는 구조 일까요 :) ?
요구사항이 변경되어 많은 모델이 생길 경우 그만큼 Validator가 생길 것이고, 내부 클래스가 생성되는 구조가
적절한지에 대해서도 고민해보시면 좋을 것 같습니다 :)

2020-09-07 08:27 UTC, ap-jylee commented on src/main/java/nextstep/domain/LadderGameConfig.java
> +}
앗.. 이거 두군데서 사용해서 공통으로 뺀건데 각각 하는게 더 나은걸까요?

2020-09-07 08:29 UTC, ap-jylee commented on src/main/java/nextstep/app/LadderGameApp.java
> +        LadderResult ladderResult = getLadderResult(participants, ladderResults, ladderGameManager, personForResult);
그럼 전체 결과를 미리 가져오고 all 인경우 그대로 리턴, 아니면 뽑아서 리턴 이런식으로 하는게 좋을까요?

2020-09-07 08:36 UTC, ohtaeg commented on src/main/java/nextstep/domain/LadderGameConfig.java
> +}
해당 상수를 하나의 객체가 갖고 있다면 좋을 것 같아요!
어떤 객체가 갖고 있는게 적절할지 한번 고민해보아요 :)

2020-09-07 08:37 UTC, ohtaeg commented on src/main/java/nextstep/app/LadderGameApp.java
> +        LadderResult ladderResult = getLadderResult(participants, ladderResults, ladderGameManager, personForResult);
말씀해주신대로 한다면 LadderResult는 외부에 노출될 필요가 없을 것 같아요 👍

2020-09-09 08:29 UTC, ap-jylee commented on src/main/java/nextstep/app/LadderGameApp.java
> +    }
personFactory 는 person 객체만 사용하려고 했었는데요..! 래핑해서 리턴해주면 더 편리할 것 같긴 합니다.

2020-09-09 08:30 UTC, ap-jylee commented on src/main/java/nextstep/app/LadderGameApp.java
> +    }
이건 라임을 맞추기 위해..

2020-09-09 09:39 UTC, ap-jylee commented on src/main/java/nextstep/app/LadderGameApp.java
> +    private static LadderResult getLadderResult(Participants participants, LadderResults ladderResults, LadderGameManager ladderGameManager, String personForResult) {
이 부분 처리가 조금 애매하네요.. 뭔가 합치고 싶어도 3개 이상 인스턴스 변수를 가지면 안되서.. ㅠㅠ

2020-09-10 07:53 UTC, ohtaeg approved these changes
리뷰가 늦어 죄송합니다 🙏 
피드백 반영을 잘해주셨어요 👍 
몇가지의 피드백을 드렸는데 다음 미션을 진행해주시면서 같이 반영해주세요!
다음 미션이 리팩토링인 만큼 리팩토링이 필요해보이는 부분을 찾아 적용해주시면 좋을 것 같아요!
이만 머지하겠습니다 :)

2020-09-10 07:53 UTC, ohtaeg commented on src/main/java/nextstep/app/LadderGameApp.java
> +        LadderResults ladderResults = LadderResultFactory.createLadderResults(InputView.receiveLadderResults());
사다리 결과 입력시, 참여하는 플레이어 수와 같은지 체크해주시면 좋을 것 같아요 :)
![image](https://user-images.githubusercontent.com/20432323/92694522-24633180-f382-11ea-812e-9e3e784da595.png)

2020-09-10 07:53 UTC, ohtaeg commented on src/main/java/nextstep/app/LadderGameApp.java
>              return;
결과값을 한번만 입력하면 종료가 되네요 :)
"all"이 입력되기 전까지 결과를 계속 출력해주시도록 해주실 수 있을까요 :) ?

2020-09-10 07:53 UTC, ohtaeg commented on src/main/java/nextstep/app/LadderGameApp.java
> +                })
해당 로직을 LadderExecutionResults 내부에서 수행하는것에 대해 어떻게 생각하시나요 :) ?

2020-09-10 07:53 UTC, ohtaeg commented on src/main/java/nextstep/domain/ladder/LadderExecutionResult.java
> +}
해당 객체는 인스턴스 변수를 갖고 있는것 외에 특별한 로직이 없기에 불필요한 Wrapping이라고 생각이 되어
삭제해도 무방할것 같아요. 삭제함에 있어서 주영님의 의견은 어떠한지 궁금하네요 :)

2020-09-10 07:53 UTC, ohtaeg commented on src/main/java/nextstep/domain/ladder/LadderExecutionResults.java
> +    private final Map<String, LadderExecutionResult> ladderExecutionResult;
실행 결과를 Map<String, LadderExecutionResult>가 아닌 Map<Person, LadderResult>로 가지면 어떨까요 :) ?
해당 코멘트와 같이 고민해보면 좋을 것 같아요!

2020-09-10 07:53 UTC, ohtaeg commented on src/test/java/nextstep/domain/TracksTest.java
> +import nextstep.domain.track.Tracks;
findTrack() 테스트 코드도 추가해주세요!

2020-09-10 07:53 UTC, ohtaeg commented on src/test/java/nextstep/domain/LinesTest.java
> +import nextstep.domain.line.Lines;
`@ParameterizedTest`를 이용하여 테스트 코드의 중복을 제거해보면 어떨까요 :) ?

2020-09-10 07:53 UTC, ohtaeg commented on src/main/java/nextstep/domain/ladder/LadderExecutionResults.java
> +public class LadderExecutionResults {
해당 객체의 테스트 코드를 추가해주세요!

2020-09-10 07:53 UTC, ohtaeg commented on src/main/java/nextstep/domain/ladder/LadderGameManager.java
>  public class LadderGameManager {
해당 객체의 테스트 코드를 추가해주세요!

2020-09-10 07:54 UTC, merged

2020-09-10 07:57 UTC, ap-jylee commented on src/main/java/nextstep/domain/ladder/LadderExecutionResult.java
> +}
저 두객체를 하나로 묶기위해서 만들었는데요..! 로직 변경하면서 고려해보겠습니다.

2020-09-10 07:57 UTC, ap-jylee commented on src/main/java/nextstep/domain/ladder/LadderExecutionResults.java
> +    private final Map<String, LadderExecutionResult> ladderExecutionResult;
네 이부분 수정하면서 LadderExecutionResult 고민해보겠습니다.

2020-09-10 08:25 UTC, ohtaeg commented on src/main/java/nextstep/domain/ladder/LadderExecutionResult.java
> +}
개인적으로 Wrapping하는 이유중 하나는 상태와 행위를 한곳에서 관리하는 장점이 있다고 생각합니다!
상태를 관리하고 그에 대한 행위가 없다면 Wrapping해야할지 고민해볼 필요가 있는 것 같아요 :)

2020-09-10 08:28 UTC, ap-jylee commented on src/main/java/nextstep/domain/ladder/LadderExecutionResult.java
> +}
아 그럼 person 과 ladderResult 정보를 같이 리턴할때는 어떤식으로 해야하는게 좋을까요?

2020-09-10 08:34 UTC, ohtaeg commented on src/main/java/nextstep/domain/ladder/LadderExecutionResult.java
> +}
Map<Person, LadderResult>로 관리하게 된다면 해당 Map을 통해 정보를 같이 리턴할 수 있다고 생각이 됩니다 :)

2020-09-10 08:36 UTC, ap-jylee commented on src/main/java/nextstep/domain/ladder/LadderExecutionResult.java
> +}
아 넵 이경우는 그렇게 리턴하면 될 것 같습니다..!

2020-09-13 12:34 UTC, ap-jylee commented on src/main/java/nextstep/domain/ladder/LadderExecutionResults.java
> +public class LadderExecutionResults {
이 부분은 결과를 담는 객체라 딱히 테스트할 게 없을 것 같습니다..!