Step2 리뷰요청드립니다!
next-step/java-ladder pull request #621
Opened 2020-09-07 17:30 UTC by oakkim

안녕하세용, 스텝 2 리뷰 요청드립니당

감사합니다!

2020-09-08 07:58 UTC, ohtaeg requested changes
기능 구현을 잘해주셨습니다 👍 객체를 잘 분리해주셨어요!
몇가지의 고민거리를 드렸는데 고민해보시고 리팩토링하면 좋은 경험이 될 것 같아 
Request changes 하였습니다!

피드백 반영 후 재요청 주시면 감사하겠습니다 :)
함께 의논할 것이 있거나 궁금한 점 있으시면 슬랙으로 DM 또는 코멘트를 남겨주세요!

2020-09-08 07:58 UTC, ohtaeg commented on src/main/java/cc/oakk/ladder/model/Ladder.java
> +    private final List<MutableLine> lines;
Line 관계를 상속으로 구현 해주신 이유가 있을까요 :) ?
개인적으로 상속을 사용하면 중복되는 내용을 상당수 제거할 수 있고, 코드 대부분을 재사용할 수 있는 장점이 있지만 상속은 코드 재사용이 아니라 `타입 계층을 구조화`하기 위해 사용하는 방법이라고 생각해요.

현재 구조는 SOLID의 `LSP 원칙`을 위반한다고 생각합니다.
LSP 원칙은 **자식 클래스는 최소한 자신의 부모 클래스에서 가능한 행위는 수행할 수 있어야 합니다.**
즉 부모 클래스와 자식 클래스 사이의 행위가 일관성이 있어야 한다는 의미인데요.
서브 타입(자식 클래스) 은 언제나 자신의 기반타입(부모 클래스) 으로 교체 할 수 있어야 된다고 생각하기에
현재 MutableLine 구현체를 부모인 Line 타입으로 변경되더라도 별 문제없이 수행되어야 한다고 생각해요!

대용님의 의견을 공유해주시면 감사하겠습니다 😄

2020-09-08 07:58 UTC, ohtaeg commented on src/main/java/cc/oakk/ladder/model/Ladder.java
> +                .collect(Collectors.toList());
```suggestion
    public List<Line> getLines() {
        return lines.stream()
                    .collect(Collectors.toList());
```

2020-09-08 07:58 UTC, ohtaeg commented on src/main/java/cc/oakk/ladder/model/line/MutableConnection.java
> +}
MutableConnection과 Connection을 하나로 합쳐도 괜찮다고 생각되는데 어떻게 생각하시나요 :) ?

2020-09-08 07:58 UTC, ohtaeg commented on src/main/java/cc/oakk/ladder/model/line/MutableLine.java
> +        boolean rightConnected = index != width() - 2 && connections.get(index + 1).get();
해당 비교문들을 가독성을 위해 메서드로 분리하면 좋을 것 같아요!

2020-09-08 07:58 UTC, ohtaeg commented on src/test/java/cc/oakk/ladder/model/size/LadderSizeTest.java
> +        assertThatIllegalArgumentException().isThrownBy(() -> new LadderSize(10, Integer.MIN_VALUE));
중복되는 테스트 코드를 `@MethodSource` 이용하여 리팩토링 해보면 어떨까요?

2020-09-08 07:58 UTC, ohtaeg commented on src/test/java/cc/oakk/ladder/model/line/LineTest.java
> +    }
`@ParameterizedTest`를 이용해보면 좋을 것 같아요 :)

2020-09-08 08:59 UTC, oakkim commented on src/main/java/cc/oakk/ladder/view/printer/StringPrinter.java
> +}
`StringPrinter`는 `Printer`에서 문자열로 출력하는 경우가 많아서 번거로움을 줄일려고 만든 클래스입니다. 그리고 `StringPrinter`에서 `Printer<String>`을 받는 이유는 해당 문자열이 콘솔에 출력될지, 웹에 출력될지를 모르기 때문입니다._[1]_

`StandardPrinter`는 `Printer<String>`의 단순 구현체 입니다._[2]_ 조금 용도가 다르다고 생각하는데요. 제 생각에는 그대로 둬도 괜찮지 않을까? 싶습니다.

_[1]: 이러면 `InputView`나 `ResultView`도 `Printer<String>`을 가지도록 만들었어야했네요.
[2]: 생각해보니 얘도 impl 패키지에 들어가야겠네요._

2020-09-08 09:03 UTC, ohtaeg commented on src/main/java/cc/oakk/ladder/view/printer/StringPrinter.java
> +}
의견 공유해주셔서 감사합니다. 말씀해주신대로 [1], [2]에 맞게 리팩토링이 된다면 좋을 것 같아요 :)

2020-09-08 09:04 UTC, oakkim commented on src/main/java/cc/oakk/ladder/model/Person.java
> +public class Person implements Printable<Person> {
`Printer`랑 각 도메인들이 의존하는 부분이 좀 저도 어떻게 해야할지 고민하고 있던 부분인데요. 

차라리 저런 방식을 버리고, 컨트롤러에서 도메인의 값을 하나하나 빼줘서 뷰에 넘겨줘야하나 싶습니다. 뭔가 이것도 성치않은 그림인 듯해서 어떤 방식이 좋을지 좀 더 힌트라도 주실수 있으실까여?

2020-09-08 09:05 UTC, oakkim commented on src/main/java/cc/oakk/ladder/model/size/LadderSize.java
> +public class LadderSize {
아 저도 그 생각을 했긴 했는 데, 이걸 펼칠려고 보니 클래스 필드가 3개 이상이 되어버려서 일딴 유지 했었습니다. 저는 펼칠 수 있다면 펼치는 게 좋다고 생각합니다.

2020-09-08 09:08 UTC, ohtaeg commented on src/main/java/cc/oakk/ladder/model/Person.java
> +public class Person implements Printable<Person> {
View에 데이터를 전달하는 방법은 여러가지가 존재하게 되는데요!
개인적으로는 DTO를 이용하는 편입니다!

1. 도메인 그대로 노출
2. DTO 사용
3. 읽기전용 인터페이스를 만들어 추상화의 의존하도록 구현
4. 등등..

도메인 모델을 데이터 뷰에 노출하는 방법에 관해선 다음 링크를 참고하시면 좋을 것 같아요 :)
[도메인 모델을 데이터 뷰에 노출하는 방법에 관하여](https://javacan.tistory.com/entry/methods-about-exporting-domain-object-to-view)

각 방법마다 장단점은 있으니 이 부분은 트레이드 오프하여 편하신 방법을 사용하시면 될 것 같아요 😄

2020-09-08 09:11 UTC, ohtaeg commented on src/main/java/cc/oakk/ladder/model/size/LadderSize.java
> +public class LadderSize {
Ladder 객체가 높이와 넓이를 꼭 인스턴스 변수로 가질 필요가 있는지 고민해보아요 :)

2020-09-08 10:43 UTC, oakkim commented on src/main/java/cc/oakk/ladder/model/size/LadderSize.java
> +public class LadderSize {
어,,, 그러네요 ㅋㅋㅋㅋ 수정하겠습니당

2020-09-08 10:47 UTC, oakkim commented on src/main/java/cc/oakk/ladder/model/Ladder.java
> +    private final List<MutableLine> lines;
> 위에 언급한 두 가지 문제는 메서드 재정의 때문에 발생한 것입니다. 기존 메서드를 재정의하는 대신 새 메서드로 만들어 넣으면 계승해도 괜찮을 거라 생각할 수도 있습니다. 그런 확장법이 좀 더 안전한 것은 사실이나, 위험성이 완전히 사라지는 것은 아닙니다. 새 릴리스에 추가된 상위 클래스 메서드가 재수 없게도 하위 클래스에 정의한 메서드와 같은 시그니처인데 반환값 자료형만 다를 경우, 여러분이 만든 하위 클래스는 더이상 컴파일 되지 않을 것이며, 반환값 자료형까지도 같은 경우에는 앞서 설명한 두 가지 문제가 일어나기 시작할 것입니다. 게다가, 새로운 상위 클래스 메서드의 일반 규약이 기존 하위 클래스 메서드와 맞을지 알 수 없다는 문제도 있습니다. 하위 클래스에 메서드를 추가할 당시에 만들어진 규약이 아니기 때문입니다.

출처: https://12bme.tistory.com/191 [길은 가면, 뒤에 있다.]

말씀하신 부분 중 *LSP 원칙은 자식 클래스는 최소한 자신의 부모 클래스에서 가능한 행위는 수행할 수 있어야 합니다.* 는 만족하는 거 같은데 라는 생각이 들었습니다. 근데 해당 게시물을 찾아보고 이런 식이 어떤 위험성을 가지는지 확실히 이해되어서 공유드립니다.

2020-09-08 10:49 UTC, oakkim commented on src/main/java/cc/oakk/ladder/model/Ladder.java
> +    private final List<MutableLine> lines;
LSP에 관한 글은 아니지만 비슷한 맥락인듯 싶어서 확인차 공유드립니다. 혹시 좀 다른 뜻이였다면 알려주세요!

2020-09-08 12:36 UTC, ohtaeg commented on src/main/java/cc/oakk/ladder/model/Ladder.java
> +    private final List<MutableLine> lines;
언급해주신 내용이 비슷한 맥락이네요 👍 해당 글은 상속의 단점을 설명해주고 극복하고자 구성 방식을 설명해주고 있는 좋은 글인 것 같아요!

MutableLine이 Line을 상속받고 있는데 어떠한 이유로 상속관계를 가지게 되었는지 고민해보면 좋을 것 같아요!
코드 재사용을 위한 상속 혹은 비슷한 의미의 맥락을 가지고 있기에 계층 구조를 구성하셨다면 상속 구조를 고민해볼 필요가 있습니다. 물론 상속은 부모 클래스의 코드를 재사용 하기 위함도 있지만 객체지향에서 상속의 진정한 목적은 
자식 클래스와 부모 클래스를 동일한 개념적인 범주로 묶어 is - a 관계를 만들어 확장하기 위해 사용한다고 생각합니다.

2020-09-08 12:42 UTC, oakkim commented on src/main/java/cc/oakk/ladder/model/Ladder.java
> +    private final List<MutableLine> lines;
기존에 Printer에 객체를 넘겨줄 때 수정할 수 없도록 만들고 싶어서 Mutable / Immutable 처럼 `MutableLine` / `(Immutable)Line` 으로 만들었습니다. Mutable~ 이라는 형의 객체를 가지고 있을 때만 수정 가능한거지요. 안드로이드에서 LiveData / MutableLiveData 에서 힌트를 얻어 만들어보고 싶었습니다.

하지만 이게 여러 사람들끼리 작업할 때 위험한 부분이 있는 것 같네요. 말씀하신 대로 DTO로 따로 빼내는게 좋을 것 같네요.

2020-09-08 16:27 UTC, oakkim commented
말씀하신 부분 수정 후 다시 리뷰 요청드립니다!

2020-09-09 07:03 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨습니다 👍 
추가로 몇개의 피드백을 드렸는데 확인해주시고 다음 미션을 진행하시면서 반영해주세요!
다음 미션도 화이팅입니다 :)

2020-09-09 07:12 UTC, merged