Step03
next-step/java-ladder pull request #688
Opened 2020-11-26 08:39 UTC by eyabc

안녕하세요 이번미션은 하면서 많이 어려웠던 것 같아요! 이번에도 잘 부탁드립니다 😀

2020-11-26 20:42 UTC, ohtaeg requested changes
안녕하세요 은영님! 3단계도 구현을 잘해주셨습니다 👍
전체적으로 설계도 잘해주셨고 테스트도 꼼꼼하게 잘 작성해주셨습니다 👍 

마지막 미션을 진행하시기전에 몇 개의 피드백을 드렸는데,
피드백 확인 후 반영해주시면 감사하겠습니다 😄 
추가로 주셨던 질문에 대해서도 코멘트를 드렸는데 확인해주세요 ㅎㅎ

미션 마무리가 얼마 남지 않았네요!! 화이팅입니다 🔥

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/controller/Main.java
> +        while(!target.equals("all")) {
저는 사용자의 입력값을 절대로 믿지 않는 비관적인(?) 입장이기에 입력값인 target이 언제든지 null로 들어올 수 있다는 의심을 항상 하고있습니다 ㅎㅎ
그렇기에 target.equals()를 하게 되면 null 참조로 인해 NPE 가 발생할 수도 있다고 생각해요!
다음과 같이 변경하면 좋을 것 같아요 :)

```suggestion
        String target = InputView.readNamesOfParticipant();
        while (!"all".equals(target)) {
```

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/domain/Matcher.java
> +public class Matcher {
해당 객체의 책임은 무엇으로 정의하셨나요 :) ?

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/domain/Matcher.java
> +        Integer indexOfMatched = matchedTable.indexOf(indexOfName);
전체적으로 Integer를 많이 사용해주셨네요!
해당 피드백을 참고하시면 좋을 것 같아요!
https://github.com/next-step/java-ladder/pull/683#discussion_r530412275

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/domain/Name.java
> +}
클린코드 책 내용중 다음과 같은 말이 있는데요!
> 위에서 아래로 코드 읽기:내려가기 규칙
코드는 위에서 아래로 이야기처럼 읽혀야 좋다.
함수 추상화 부분이 한번에 한단계씩 낮아지는 것이 가장 이상적이다.(내려가기 규칙)

해당 validateProhibitName() 메서드를 맨 아래에 위치해주신 이유가 있으신가요 :) ?
잘 작성된 신문 기사를 보면 크게 요약된 내용에서 점차 흐름대로 상세 내용이 나오는데요!
위에 인용된 말처럼 메소드 호출 흐름 순서에 맞게 순서를 조정해주시면 어떨까요?

2020-11-26 20:42 UTC, ohtaeg commented on src/test/java/step03/domain/NamesTest.java
> +    void test_indexOf_invalid() {
해당 테스트가 실패하고 있습니다 ㅎㅎ

2020-11-26 20:42 UTC, ohtaeg commented on src/test/java/step03/domain/ParticipantsTest.java
> +    void test_constructor_of(String names) {
해당 메서드도 실패가 있네요 😭

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/domain/Ladder.java
> +    public List<List<Boolean>> getLadder() {
List\<Step\>이 아닌 List\<List\<Boolean\>\> 으로 반환해주시는 이유가 있을까요 :) ?

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/controller/Main.java
> +    public static void main(String[] args) {
게임이 진행이 되질 않고 있네요 😭  
확인 부탁드릴께요! :)

![image](https://user-images.githubusercontent.com/20432323/100388959-67729e00-306f-11eb-9380-2c68d3b827d4.png)

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/domain/Ladder.java
> +    private final List<Integer> resultTable;
사다리 결과를 객체로 분리해보면 어떤 장점이 있을까요 ~ ?

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/domain/Ladder.java
> +                .forEach(index -> {
이 부분 또한 중첩 포문과 다름이 없다고 생각해요!
중첩 포문을 제거해볼 수 있을까요 ? 😄

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/domain/Ladder.java
> +                    if (!points.get(index)) return;
if 문의 내부가 한 문장일 경우에도 중괄호로 둘러싸는게 컨벤션이오니 다음 링크를 통해 참고하시면 좋을 것 같아요 :) 구글 자바 가이드 문서를 참고하시면 좋을 것 같아요 😄 
```
4.1.1 Braces are used where optional
Braces are used with if, else, for, do and while statements, even when the body is empty or contains only a single statement
```
https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/domain/Matcher.java
> +                throw new NotMatchedCountException();
```suggestion
            if (!count1.equals(count2)) {
                throw new NotMatchedCountException();
            }     
```

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/domain/Names.java
> +    }
해당 피드백과 같은 내용입니다 :)

2020-11-26 20:42 UTC, ohtaeg commented on src/main/java/step03/view/ResultView.java
> +public class ResultView {
출력 View가 깔끔하네요 👍

2020-11-26 20:42 UTC, ohtaeg commented on src/test/java/step03/domain/StepTest.java
> +public class StepTest {
전체적으로 꼼꼼한 테스트 👍

2020-11-26 20:42 UTC, ohtaeg commented on step03.md
> +다음에는 기능을 정의할 때 테스트 케이스 DisplayName 에 다가 정의하는 것이 어떨까 생각하고 있습니다.
DisplayName 의 목적은 테스트 클래스 또는 테스트 방법에 대한 값이나 설명을 선언하는 데 사용되는것이 목적이기에 기능 정의는 DisplayName 이 아닌 별도로 정의해주시면 어떨까 합니다..!!

2020-11-26 20:42 UTC, ohtaeg commented on step03.md
> +## 힌트
> 사다리 결과를 도출하는 과정에 필요한 로직이 저와 많이 다른 것 같아 혼란스럽네요. 
어떻게 하면 좋을지 태경님께서도 의견을 주시면 4단계 미션시작하기 전에 고민을 해결하는데 도움이 됐으면 좋겠습니다!!

개인적으로 포비의 힌트에 맞게 변경하지 않아도 된다고 생각합니다.
힌트는 힌트일뿐이라고 생각하며, 구현에 정답은 없다고 생각해요!
현재 은영님께서 설계를 잘해주셔서 지금 이 설계를 유지해주셔도 좋을 것 같아요 😃 👍 

나중에 여유가 있으시다면 포비의 힌트에 맞게 변경해보시는 것도 좋은 경험이 될 것 같아요!

2020-11-27 05:45 UTC, eyabc commented on src/main/java/step02/view/ResultView.java
> +                    printLine(step);
맞습니다! 제가 꼼꼼하게 보지 못했네요 🙏

2020-11-27 05:54 UTC, eyabc commented on src/main/java/step03/controller/Main.java
> +                .namesOfResult(namesOfResult);
빌터 패턴을 사용한 이유는 다음과 같습니다. 

Matcher 라는 클래스는, 사용자목록과 결과목록을 매핑해주는 역할을 부여했습니다. 
이 역할을 하기 위해서 Participants, NamesOfResult, MappedTable 이 세 객체가 멤버 변수로 필요로 합니다.
그리고 매핑하기 위해서는 각각의 객체가 가지는 List 의 size 가 같은지 검사를 하는 기능도 필요로 했습니다. 

하지만 UI 상 view 에서, 순차적인 입력을 받고 있고, 입력을 받을 때 마다 유효성을 검사해야 된다고 생각하여 
Matcher 객체를 만들기 위해 빌더 를 구성하였습니다. 

빌더 패턴으로 생각하는 기능을 만들 수 있을 거라 사용을 했을 뿐, 그 이상으로 잘 알지는 못합니다
그래서 `build()가 되기까지 term이 존재하여 구성 과정에서 일관성이 없는 상태에서 사용될 수 있다는 단점` 
말씀해주신 설명이 제 코드에서 어떤 취약점이 될 수있는지 더 알려주실 수 있나요?

2020-11-27 06:15 UTC, eyabc commented on src/main/java/step03/controller/Main.java
> +        while(!target.equals("all")) {
8c686f7
그런 상황이 있을수도 있군요! 꿀팁 감사합니다

2020-11-27 06:17 UTC, eyabc commented on src/main/java/step03/domain/Matcher.java
> +public class Matcher {
Matcher 라는 클래스는, 사용자목록과 결과목록을 매핑해주는 역할을 부여했습니다.
이 역할을 하기 위해서 Participants, NamesOfResult, MappedTable 이 세 객체가 멤버 변수로 필요로 합니다.
그리고 매핑하기 위해서는 각각의 객체가 가지는 List 의 size 가 같은지 검사를 하는 기능도 필요로 했습니다.

하지만 UI 상 view 에서, 순차적인 입력을 받고 있고, 입력을 받을 때 마다 유효성을 검사해야 된다고 생각하여
Matcher 객체를 만들기 위해 빌더 를 구성하였습니다.

그리고 외부에서는 getResultByParticipant 를 통해 참여자를 입력받아 참여자의 결과를 리턴받거나 
getResults 를 통해 모든 참여자와 매핑되는 사다리 타기 결과를 map 으로 리턴받을 수 있습니다

2020-11-27 06:20 UTC, eyabc commented on src/main/java/step03/domain/Matcher.java
> +        Integer indexOfMatched = matchedTable.indexOf(indexOfName);
저번 피드백을 이제야 읽어 보네요 좋은 자료 감사합니다!

2020-11-27 06:26 UTC, eyabc commented on src/main/java/step03/domain/Name.java
> +}
넵! 가장 아래에 위치해 있는 이유는, 다른 이유는 없고 테스트 코드를 작성하고 인텔리제이를 통해 메서드를 자동생성해주는 기능을 사용하게 되면 클래스의 가장 아래에 생성이 되더라고요. 테스트 코드의 순서를 항상 생성자를 먼저 정의를 했기 때문에 Override 된 equals 나 hashcode 과 같은 메서드가 항상 위에 위치해 있어서, 매번 마다 새로운 테스트 코드를 작성할 때 마다 위로 올려 주었었는데요. 
매 번 번거로운 것 같아요. validateProhibitName 은 가장 최근에 추가한 메서드 인데, 깜박하고 올리지 않았네요 ㅠㅠ

2020-11-27 06:47 UTC, eyabc commented on src/main/java/step03/domain/Ladder.java
> +    public List<List<Boolean>> getLadder() {
getLadder 호출 한번으로,
 Deep 하게 출력에 필요한 모든 primitive 를 사용할 수 있는 기대감을 생각 했었는데요, 
저도 만들면서 좀 이상하다고 생각은 했는데, 태경 님이 질문하신 이유와 비슷할 것 같습니다! 
태경님의 생각을 말씀해 주시면 감사하겠습니다!

2020-11-27 06:49 UTC, eyabc commented on src/main/java/step03/controller/Main.java
> +    public static void main(String[] args) {
실행 결과 입력의 조건의 경우 
참여할 사람의 숫자와 같아야 하기 때문에 
실행 결과도 , 로 구분하여 4개가 들어가야 하며 

참여자가 1명일 경우 사다리 게임을 할 수 없다고 생각하여 최소 2명을 입력받는 것으로 하였습니다!

2020-11-27 06:53 UTC, eyabc commented on src/main/java/step03/domain/Ladder.java
> +    private final List<Integer> resultTable;
이번에 하면서 분리를 하지 않았습니다. 
resultTable 은 단지 participants 와 namesOfResult 를 매핑하는 인덱스만 하기 때문에 래핑을 할 필요가 있을까? 
사실 해보아야 진짜 알 수 있을텐데 이번 미션 에서는 귀찮아서 해보지 않았습니다 ㅎㅎ 
다음 미션4 을 하면서 꼭 해보고 느낀점을 써보겠습니다!

2020-11-27 07:06 UTC, eyabc commented on src/main/java/step03/domain/Ladder.java
> +                .forEach(index -> {
e329aa9 분리해보았습니다!

2020-11-27 15:13 UTC, ohtaeg commented on src/main/java/step03/controller/Main.java
> +                .namesOfResult(namesOfResult);
Matcher가 사용자와 결과를 매핑해주는 역할을 하는군요! 의견 공유 해주셔서 감사합니다 👍 

> build()가 되기까지 term이 존재하여 구성 과정에서 일관성이 없는 상태에서 사용될 수 있다는 단점
말씀해주신 설명이 제 코드에서 어떤 취약점이 될 수있는지 더 알려주실 수 있나요?

해당 리뷰를 드렸던 계기가 팀 내에서 멀티쓰레드 환경에서 빌더 패턴을 쓴 객체를 공유할때
완성되지 않은 객체를 이용한적 있어서 예외가 발생한 적이 있었습니다 ㅎㅎ;
빌더 패턴의 단점이라고 하면 .build()를 호출하는순간 객체 생성이 완료되는 구조이기에 완성되지 않은
객체를 누군가 사용할 수 있다는 점인 것 같아요! 그렇기에 해당 리뷰를 드리면서 
build()가 되기까지 term이 존재하여 구성 과정에서 일관성이 없는 상태에서 사용될 수 있다는 단점라고 말씀은 드리긴 했는데 다시 생각해보니, 미션과 실무의 환경이 다른데 오버했던 리뷰가 아니였을까 생각이 드네요 🙏

2020-11-27 15:20 UTC, ohtaeg commented on src/main/java/step03/domain/Matcher.java
> +public class Matcher {
의견을 공유해주셔서 감사합니다!
Matcher 라는 네이밍이 많은 뜻으로 해석할 수 있기에 확실한 책임을 유추하기 힘들어서 여쭤봤었던 리뷰였습니다 :)
잘 도출해주신 것 같아요 👍

2020-11-27 15:22 UTC, ohtaeg commented on src/main/java/step03/domain/Ladder.java
> +    public List<List<Boolean>> getLadder() {
해당 Ladder 객체를 은영님이 아닌 다른 사람이 사용했을 경우  List\<List\<Boolean\>\> 라는 반환값은
어떤 값을 뜻하지는지 혼동이 될 것 같습니다!

2020-11-27 15:42 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨어요 👍 
설계가 잘되어 있어서 큰 변경없이 이번 미션도 마무리가 되신 것 같네요 😄 
소소한 코멘트를 남겨드렸는데 확인해주시고 다음 미션을 진행해주세요!

벌써 마지막 미션이네요!! 마지막 미션은 리팩토링인데,
포비의 힌트를 이용하여 리팩토링해보셔도 좋을 것 같고
현재 구조에서 getter를 통해 값을 갖고오고 있는 부분들을 리팩토링해보시면 좋은 경험이 될 것 같습니다!

마지막도 화이팅입니다 🔥

2020-11-27 15:42 UTC, ohtaeg commented on src/main/java/step03/controller/Main.java
> +        int countOfSteps = InputView.readCountOfSteps();
전체적으로 primitive으로 변경해주셨네요 👍

2020-11-27 15:42 UTC, ohtaeg commented on src/main/java/step03/domain/Name.java
> +        return name + "";
```suggestion
        return name;
```

2020-11-27 15:42 UTC, ohtaeg commented on src/main/java/step03/domain/Matcher.java
> +        for(int i = 0; i < participants.size(); i++) {
```suggestion
        for (int i = 0; i < participants.size(); i++) {
```

2020-11-27 15:42 UTC, ohtaeg commented on src/main/java/step03/domain/Ladder.java
> +        if (!hasLine) return;
```suggestion
        for (int index = 0; index < points.size(); index++) {
            swapIndex(table, index, points.get(index));
        }
    }

    private static void swapIndex(List<Integer> table, int index, boolean hasLine) {
        if (!hasLine) {
            return;
        }
```

2020-11-27 15:42 UTC, ohtaeg commented on src/main/java/step03/domain/Ladder.java
> +    public List<List<Boolean>> getLadder() {
해당 Ladder 객체를 은영님이 아닌 동료가 사용할 경우 List\<List\<Boolean\>\> 라는 반환값은
어떤 값을 의미하는지 헷갈릴 것 같아요 😄

2020-11-27 15:42 UTC, ohtaeg commented on src/main/java/step03/controller/Main.java
> +    public static void main(String[] args) {
앗 제가 잘못 입력한 케이스였네요 ㅠㅠ 새벽에 리뷰드리다보니 죄송합니다 🙏

2020-11-27 15:44 UTC, merged

2020-11-29 07:43 UTC, eyabc commented on src/main/java/step03/controller/Main.java
> +                .namesOfResult(namesOfResult);
아니요 좋은 경험 공유해 주셔서 감사합니다! 자바 초보이다 보니 이것 저것 궁금한 것이 많은데 미션을 하면서 빌더 패턴에 대해서 더 공부해 보는 계기가 될 것 같아요!

2020-11-29 07:46 UTC, eyabc commented on src/main/java/step03/domain/Matcher.java
> +public class Matcher {
뭐라고 지어야 될지 모르겠어서 Matcher 를 사용을 했었는데.. 포괄적인 단어라 다른 사람이 봤을 때 잘 알기 어려운 단어가 맞는 것 같아요 ㅎㅎ