3단계 - 사다리(게임 실행)
next-step/java-ladder pull request #689
Opened 2020-11-27 00:26 UTC by siyoon210

rebase 없이 작업을 해서 커밋로그에 2단계 내역도 포함된 것 같습니다 😢  참고해주세요!

2020-11-27 07:50 UTC, vagabond95 requested changes
각 클래스를 책임에 맞게 적절히 잘 분리하려는 노력하셨던 흔적이 많이 보였던 코드였습니다 ㅎㅎ

구조적으로는 크게 피드백을 드릴 부분이 없어 좀 더 생각해볼만한 내용에 대하여 몇가지 코멘트 달았는데요,
검토해보시고 좀 더 같이 논의해보면 좋을 것 같습니다 :)

2020-11-27 07:50 UTC, vagabond95 commented on src/main/java/nextstep/ladder/domain/Line.java
> +    public int getNextIndexOf(int currIndex) {
파라미터 이름으로 축약어 사용은 최대한 지양하는 것이 어떨까요~?
축약어는 서로가 공통으로 지켜지는 약속/ 배경지식을 소유하고 있을 때 온전히 이해가 가능한데 보통 나의 코드를 보는 다른사람은 블랙박스라고 생각하고 최대한 정보를 온전히 드러내는게 좋다고 생각되어서요!

2020-11-27 07:50 UTC, vagabond95 commented on src/main/java/nextstep/ladder/domain/Results.java
> +    private Results(List<String> value, Participants participants) {
NumberOfParticipants 값을 넘겨주는 것은 어떨까요~?

각 도메인의 세부 구현에 최대한 종속되지 않고 필요한 데이터만 넘기게 되면 각 클래스간 의존성을 한층 더 줄여나갈 수 있을 것 같습니다 :)

2020-11-27 07:50 UTC, vagabond95 commented on src/main/java/nextstep/ladder/domain/Results.java
> +public class Results {
Results 라는 이름은 ExecutionResults 의 상위 개념으로 오해할 수 도 있을 것 같아요. 좀 더 정보를 드러내볼 수 있을까요~?

2020-11-27 07:50 UTC, vagabond95 commented on src/main/java/nextstep/ladder/view/ConsoleResultView.java
> +        if (executionResults.isAllKeyword(nameOfWantToCheck)) {
allKeyword 에 대한 판단을 view 에서 했을때와 view 외부에서 계층에서 했을 때의 각각의 장단점은 무엇일까요~?

2020-11-28 02:39 UTC, siyoon210 commented on src/main/java/nextstep/ladder/domain/Results.java
> +    private Results(List<String> value, Participants participants) {
그러네요. 굳이 필요없는 도메인에게 의존성을 갖게 되는 문제가 있었군요! :)

2020-11-28 02:39 UTC, siyoon210 commented on src/main/java/nextstep/ladder/domain/Results.java
> +public class Results {
Results에 이름을 ResultCandidate라는 이름으로 변경했습니다. 이름짓기는 정말 어렵네요 ㅠㅠ 혹시 적절했던 사례가 있었으면 얘기해주실수 있나요? :)

2020-11-28 02:41 UTC, siyoon210 commented on src/main/java/nextstep/ladder/view/ConsoleResultView.java
> +        if (executionResults.isAllKeyword(nameOfWantToCheck)) {
고민해보니 입력 키워드와 키워드에 판단은 view에서 해야하는데 도메인이 갖게 된것 같습니다. allKeyword는 입력값을 건내준 ConsoleInputView로 이동시켰습니다.

참석자 이름중에 allKeyword와 같은 이름이 있는지에 대한 유효성검사를 Participants에서 검사했었는데, Keyword를 view가 가지게 되어서 해당 검사는 LadderGame으로 이동시켰습니다. :)

이런 의도로 리뷰를 해주신게 맞을까요? 혹시 더 고민해봐야할 것이 있다면 꼭 얘기해주세요! 감사합니다.

2020-11-28 13:14 UTC, vagabond95 commented on src/main/java/nextstep/ladder/domain/Results.java
> +public class Results {
이름짓기는 저도 매번 고민하고 어려움을 겪는 문제이기에 명쾌한 정답을 드리기는 어려울 것 같습니다. 😭 (정답이 있다고 생각하지도 않구요!)

저같은 경우 클래스/메소드/변수 이름을 지을 때 크게 2가지 관점을 가지고 짓는데요,
1. 애매한 것 보다는 길어지더라도 의도, 목적을 잘 드러내는 것이 낫다.
-> 코드에 대한 context (배경지식)이 없더라도 이름을 봤을 때 내용을 쉽게 유추가 가능한 것이 가장 베스트라고 생각되는데요, 그러한 상황을 겪을때마다 모호한 이름보다는 엄청 길더라도 잘 드러나는 이름이 좀 더 이해가 쉽다고 느껴졌습니다. 또한 이름을 길게 짓다보면 SRP 원칙에 위배되는 케이스를 자연스럽게 알게되어 코드가 분리되는 이점도 있구요!

2. 패키지 혹은 클래스의 목적에 따라 비슷한 추상화 수준의 이름을 짓는다.
-> 각 클래스는 목적에 따라 패키지로 분류하거나 그룹핑할 수 있는데요, 이때 그룹내의 클래스 네이밍은 같은 추상화 수준을 유지하는 이름을 사용하려고 노력하고 있습니다. 위에 코멘트를 남긴사례도 여기에 속한다고 볼 수 있는데요, 도메인 내용상 본질이 비슷한 클래스이므로 Result 라는 이름은 ExecutionResults 이름에 비해 좀 더 상위수준의 클래스로 느껴질 수 있고 그렇게 되면 클래스간의 계층 구조를 파악하는데 혼동을 줄 수 있기 때문입니다!

이러한 생각도 있구나 하고 가볍게 봐주시면 될 것 같습니다 :)

2020-11-28 13:37 UTC, vagabond95 commented on src/main/java/nextstep/ladder/view/ConsoleResultView.java
> +        if (executionResults.isAllKeyword(nameOfWantToCheck)) {
View 의 역할을 어디까지 두느냐에 따라 달라질 것 같은데요! 저는 컨트롤러에서 다루는 것이 적절하다고 생각했었습니다 ㅎㅎ

우선 제가 생각한 각 역할은 다음과 같았습니당

View:
* 이름, 높이, 실행결과를 입력받음
* 사다리를 그림
* 실행결과 (등수) 를 그림

Controller 
* 입력받은 뷰 데이터를 이용하여 도메인을 컨트롤하고, 도메인을 이용하여 뷰에게 그릴 내용을 전달함 (이건 MVC 패턴의 기본 정의네요 ㅎㅎ;)

Model (도메인)
* 사다리 게임을 그리고, 결과를 리턴함

위와 같은 역할이 있을 때
> 개인별 이름을 입력하면 개인별 결과를 출력하고, "all"을 입력하면 전체 참여자의 실행 결과를 출력한다.
라는 요구사항은 Controller 에서 판단하고 수행되는 것이 가장 적절하다고 생각했는데요, 이유는 위 구현을 하기 위해서는 all 이라는 상태를 가지게 되는데 이는 정의한 View / model 의 역할에서는 이루어질 수 없기 때문입니다. 도메인에 직접적으로 속하지는 않는 내용이지만 특정 상태 (all 이거나 참여자 이름) 에 따라 도메인을 이용하여 view 를 이용하여 어떻게 표현해줄지 결정하는 것은 딱 controller 의 역할에 어울린다고 생각했습니다 ㅎㅎ

물론 위 내용에 대하여 반박할 여지가 다음과 같이 존재합니다.
1. all 이라는 상태는 도메인에 속한다고 볼 수 있지 않을까?
-> 사다리 게임의 결과를 담고있는 클래스가 있고 해당 클래스가 all 인지 여부에 따라 결과를 편집하여 리턴해줄 수 있겠죠, 다만 도메인이 다루는 범위가 그만큼 넓어지는 것인데 그 범위의 제한을 어디까지 하느냐가 추후 논점 포인트가 될 것 같아요.

2. all 은 결국 어떻게 표현하는지에 대한 영역이므로 view 에서 다룰 수 있지 않을까?
-> 그렇게 되면 결국 view 는 all 이라는 상태를 알고 있어야하는데, view 가 알고 있어야할 상태의 범위가 어디까지 될 수 있을지가 논점 포인트가 될 수 있을 것 같아요.

시윤님이 작성하신 코드도 의도가 담겨있으므로 결코 틀린 코드라고 생각되지 않습니다! 다만 각각의 접근방식에 따라 트레이드 오프가 있으므로 어떤것이 이점이 있을 지 계속해서 고민해보시면 좋을 것 같아요 ㅎㅎ

2020-11-28 13:40 UTC, vagabond95 approved these changes
리뷰 잘 반영해주셨네요 👍 👍 

질문 주신내용에 대하여 제 생각을 간략히 남겨봤는데요, 좀 더 논의하고 싶은 내용이네 궁금하신 점 있으시면 편하게 남겨주세요!

3단계는 머지하도록 하겠습니다!

2020-11-29 09:30 UTC, merged