2단계 - 사다리(생성)
next-step/java-ladder pull request #695
Opened 2020-11-28 09:14 UTC by BlueCitron

안녕하세요 이번 미션은 조금 어렵네요 😢 
약간 완성이 덜 된 느낌이 있지만 일단 리뷰요청드리겠습니다! 잘부탁드립니다😄

2020-11-30 07:31 UTC, ohtaeg requested changes
안녕하세요 동성님 😄 
사다리 2단계 미션 구현을 잘해주셨습니다. 👍 
몇 개의 고민거리를 드렸는데, 해당 피드백들을 고민해보시면 좋을 것 같아 Request changes 하였습니다!
피드백 반영 후 재요청 주시면 감사하겠습니다 :)

날씨가 많이 추워졌는데 감기 조심하시구 미션도 화이팅입니다 💪

2020-11-30 07:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/Floor.java
> +    private int totalPointCount;
totalPointCount는 Floor가 꼭 가지고 있을 필드인지 고민해보시면 좋을 것 같아요 :)

2020-11-30 07:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/FloorGenerator.java
> +public class FloorGenerator extends Floor {
개인적으로는 상속 구조가 아쉬운 것 같아요 😂
상속의 진정한 목적은 자식 클래스와 부모 클래스를 동일한 개념적인 범주로 묶어 is - a 관계를 만들기 위함입니다. 즉, 상속의 본질은 타입을 확장하는 개념인데, FloorGenerator 는 그러지 못하고 있는 것 같아요!
뿐더러 해당 구조는 `LSP 원칙`에도 위반이 되는 것 같아요!
Floor를 상속 받은 이유를 알려주실 수 있으신가요 :) ?  
상속 구조를 가지지 않도록 변경해보거나 올바른 상속 구조를 가지도록 리팩토링해보시면 좋을 것 같아요!

2020-11-30 07:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/Floor.java
> +public class Floor {
사다리 층을 잘 추상화 해주셨네요 👍

2020-11-30 07:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/Point.java
> +public class Point {
Point 객체 👍

2020-11-30 07:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/view/LadderHeightInputView.java
> +//        return new LadderHeight(height);
주석은 지워주셔도 될 것 같아요 😄

2020-11-30 07:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/view/LadderHeightInputView.java
> +public class LadderHeightInputView extends AbstractView{
```suggestion
public class LadderHeightInputView extends AbstractView {
```

2020-11-30 07:31 UTC, ohtaeg commented on src/test/java/nextstep/ladder/entity/UserTest.java
> +    }
해당 테스트가 실패하고 있네요!
확인해주시면 감사하겠습니다 :)

2020-11-30 07:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/FloorGenerator.java
> +        Optional.ofNullable(target)
링크 연결시 Point 내부에서 nonNull 체크를 해주고 있기 때문에 Optional.ofNullable()를 사용하지 않아도 
괜찮을 것 같아요 :)

2020-11-30 07:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/FloorGenerator.java
> +        return startPoint;
점대점 방식으로 연결되는 군요 👍

2020-11-30 07:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/Floor.java
> +    }
사용하지 않는 메서드는 제거해주세요!

2020-11-30 07:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/Floor.java
> +    protected Floor() {}
디폴트 생성자는 제거해도 좋을 것 같아요 :)
해당 피드백과 같이 고민해보시면 좋을 것 같아요 😄

2020-11-30 07:31 UTC, ohtaeg commented on src/test/java/nextstep/ladder/entity/ladder/FloorTest.java
> +        assertTrue(firstFloor.hasNext());
한 개의 단위 테스트는 한 개의 메서드 루틴을 검사해야하며 독립적이여야 된다고 생각합니다 :)
테스트를 분리해주시면 감사하겠습니다!

또한 Floor 객체의 다른 메서드에 대해서도 테스트를 추가해주시면 감사하겠습니다 !

2020-11-30 07:31 UTC, ohtaeg commented on src/test/java/nextstep/ladder/entity/ladder/LadderTest.java
> +    }
무엇을 위한 테스트인지 코드로만 봐서는 쉽게 파악이 되질 않네요 😭 
사다리가 올바르게 생성 되었는지 입력값과 결과값을 예측하여 테스트를 진행해주시면 감사하겠습니다 :)

2020-11-30 13:43 UTC, BlueCitron commented on src/main/java/nextstep/ladder/entity/ladder/LadderConfiguration.java
> +public class LadderConfiguration {
Ladder.create메서드에 넘겨받을 인자가 LadderHeight, countOfLines, LinkGenerator 이렇게 3개를 쓰려다보니 부담이 되어서 설정값 클래스를 생각했던 것 같습니다😢 
수정해보도록하겠습니다 :)

2020-11-30 13:50 UTC, BlueCitron commented on src/main/java/nextstep/ladder/entity/ladder/FloorGenerator.java
> +public class FloorGenerator extends Floor {
외부에서 new Floor()를 사용하는 것을 막고 오로지 FloorGenerator를 통해서만 생성할 수 있도록 고민하다보니 해당 코드가 나왔던 것 같습니다 😢 
이부분도 개선해보도록하겠습니다 :)

2020-11-30 14:19 UTC, BlueCitron commented on src/main/java/nextstep/ladder/entity/ladder/FloorGenerator.java
> +        Optional.ofNullable(target)
해당 코드를 작성할 때 제가 했던 생각은
1) (물론 그럴일은 없겠지만) Point target이 null이면 target.hasNext가 에러가 날수 있다는 점
2) Optional 문법을 이용한 스트림형식의 문법(개인적으로 이게 깔끔해보여서 😅 )
와 같이 생각했었는데 지금 다시 생각해보면
1) hasNext가 Chaining하면서 Null체크를 하고 있다는 점
2) 장황 + 중복(target.hasNext)
의 문제점이 있는 것 같아보이기도 합니다 😭 

이럴때 어떤게 나은 방법인지 고민이되는데요
이 부분에 대해서 조언 부탁드리겠습니다 🙏 😄

2020-12-01 05:31 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/FloorGenerator.java
> +        Optional.ofNullable(target)
말씀해주신대로 현재 createLinkRecursively() 메서드는
Optional 문법에서 hasNext()를 수행하고 있는데, 아래 부분에서도 중복해서 hasNext()를 수행하고 있는 문제점이 있는 것 같아요. 추가로 재귀로 동작하고 있기 때문에 협업하고 있던 다른분께서 해당 객체를
위임하게되면 분석이 힘들수도 있다고 생각합니다!

개인적으로 우선 재귀를 걷어내는 방식으로 리팩토링을 시작해보시는게 좋을 것 같아요 :)

2020-12-01 05:52 UTC, ohtaeg approved these changes
리뷰가 늦어 죄송합니다 🙏  피드백 반영을 잘해주셨어요! 👍 
소소한 피드백 몇 개를 드렸는데 확인해주시고 다음 미션을 진행하시면서 반영해주시면 감사하겠습니다 :)
4단계는 리팩토링 과정이기 때문에 천천히 점진적으로 고쳐나가시면 좋을 것 같아요!
다음 미션도 기대하겠습니다 :)

2020-12-01 05:52 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/FloorGenerator.java
> +        Optional.ofNullable(target)
말씀해주신대로 현재 createLinkRecursively() 메서드는
Optional 문법에서 hasNext()를 수행하고 있는데, 아래 부분에서도 중복해서 hasNext()를 수행하고 있는 문제점이 있는 것 같아요. 추가로 재귀로 동작하고 있기 때문에 협업하고 있는 다른분께 해당 객체를 위임하게 되면 분석이 힘들수도 있다고 생각합니다!

개인적으로 우선 재귀를 걷어내는 방식으로 리팩토링을 시작해보시는게 좋을 것 같아요 :)
아직 미션이 많이 남았고 4단계 미션은 사다리 리팩토링이기 때문에
미션을 진행하시면서 고민해보시고 리팩토링 해보시면 좋을 것 같습니다 :)

2020-12-01 05:52 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/LadderHeight.java
> +    private final int height;
높이 객체 👍

2020-12-01 05:52 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/LadderLine.java
> +    }
LadderLine을 생성해주신 이유를 알려주실 수 있으신가요 ~ ?
개인적으로는 단순하게 값을 보관하고 값을 비교만 하고 있기에 꼭 필요한 객체인지 의심을 해볼만한 것 같습니다 :)

2020-12-01 05:52 UTC, ohtaeg commented on src/main/java/nextstep/ladder/LadderController.java
> +        return new Users(users);
이 로직을 Users에서 수행하면 어떤 장점이 있을까요 :) ?
```suggestion
        return new Users(UsersInputView.getUserInput());
```

2020-12-01 05:52 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/Users.java
> +                .collect(Collectors.toList());
Collections.unmodifiablelist()를 활용하여 컬렉션을 외부에서 변조를 할 수 없도록 read-only로 리턴하면 좋을 것 같아요 :) 
```suggestion
                .collect(Collectors.collectingAndThen(Collectors.toList(), Collections::unmodifiableList));
```

2020-12-01 05:52 UTC, ohtaeg commented on src/test/java/nextstep/ladder/entity/ladder/LadderTest.java
> +    }
하나의 테스트 메서드에서 여러 테스트를 진행하고 있는 것 같아요!
테스트 메서드로 분리해볼 수 있을까요 :) ?

2020-12-01 05:52 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/RandomLinkGenerator.java
> +        return random.nextInt(BOUND) % 2 == 0;
다음과 같이 변경해도 좋을 것 같아요 :)
```suggestion
        return random.nextBoolean();
```

2020-12-01 05:52 UTC, merged

2020-12-02 13:32 UTC, BlueCitron commented on src/main/java/nextstep/ladder/entity/ladder/LadderLine.java
> +    }
객체지향 생활체조 원칙에서 말하는 
"모든 원시값(primitive type)과 문자열을 포장한다."
에 따라서 의무적으로 생성한 클래스였는데요 😢 사실 저도 만들면서 긴가민가했습니다 😆 
어떤 상황에서 포장해야할지 잘 감이안오는데 이 부분에 대해서 알려주시면 진행하는데 참고하도록 하겠습니다! 😄

2020-12-02 13:36 UTC, BlueCitron commented on src/main/java/nextstep/ladder/LadderController.java
> +        return new Users(users);
제 생각은
생성 로직을 캡슐화하여(응집도 상승) 외부에서 생성로직에 대해 몰라도 된다..?
인데 맞는걸까요? 😯

2020-12-05 21:52 UTC, ohtaeg commented on src/main/java/nextstep/ladder/entity/ladder/LadderLine.java
> +    }
> "모든 원시값(primitive type)과 문자열을 포장한다."

해당 규칙이 의미하는 내용은 단순 primitive type은 아무 의미 없는 스칼라 값으로 사용되곤 합니다.
만약 메서드에 여러개 int 타입을 파라미터로 받는 경우가 존재한다고 가정할 때, 
파라미터 순서를 잘못해서 입력할 경우 컴파일 시점에서는 문법에 오류없이 해석되지만
런타임 시점에서는 사이드 이펙트가 발생할 요지가 있습니다. 

원시값을 포장해서 객체로 다룬다면 아주 사소하더라도 프로그래머에게 그 값이 어떤 값이며, 왜 쓰고 있는지에 대한 정보를 전할 수 있게됩니다!

2020-12-05 21:54 UTC, ohtaeg commented on src/main/java/nextstep/ladder/LadderController.java
> +        return new Users(users);
넵 맞습니다! 생성 책임을 Users 객체에게 위임함으로써 스스로 생성을 할 수 있게되고, 외부에서 생성 로직에 대해 몰라도 되는 장점이 있다고 생각합니다!