2단계 - 사다리(생성)
next-step/java-ladder pull request #700
Opened 2020-11-29 05:52 UTC by devyoon91

사다리 게임 2단계 구현 했습니다

꼼꼼한 리뷰 부탁드리겠습니다 ~ !😁

2020-11-30 04:38 UTC, parkeeseul requested changes
미션 잘 진행해주셨습니다! 👍 

몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다! 😄 
날씨가 많이 추워졌네요! 감기 조심하시고 미션 화이팅 입니다 🔥

2020-11-30 04:38 UTC, parkeeseul commented on README.md
> +## 📍**2단계 - 사다리(생성)**
요구사항 작성 👍

2020-11-30 04:38 UTC, parkeeseul commented on src/main/java/ladder/domain/Line.java
> +        if(index == (points.size()-1)) {
```suggestion
        if (index == (points.size() - 1)) {
```
[java convetion](https://myeonguni.tistory.com/1596)을 확인 해주세요! 😄

2020-12-01 15:42 UTC, parkeeseul requested changes
피드백 잘 반영해주셨네요! 👍 

몇 가지 추가 코멘트 남겨드렸으니 확인 부탁드립니다!
날씨가 많이 춥네요! 건강 유의하시고 화이팅 입니다 !: 🔥

2020-12-02 11:44 UTC, devyoon91 commented on src/main/java/ladder/domain/Users.java
> +    private static final String USER_NAMEs_SEPARATOR = ",";
앗 부끄럽네여 😫

2020-12-02 11:46 UTC, devyoon91 commented on src/main/java/ladder/domain/Users.java
> +        if (userNames == null || userNames.equals(""))
StringUtils의 isBlank 인줄 알았는데 JDK 11 부터 지원되는 메소드 군요.. JDK 8로 진행하고 있어서 몰랐네요 ㅎㅎ;;

2020-12-04 04:09 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨습니다! 👍 

몇 가지 코멘트 남겨드렸으니 확인 해보시고
다음 단계 미션과 함께 반영 부탁드릴게요!! 😄 
다음 단계 진행해주세요! 화이팅! 🔥

2020-12-04 11:55 UTC, merged