Step3
next-step/java-ladder pull request #727
Opened 2020-12-03 13:07 UTC by joswlv

리뷰 잘부탁드립니다.

2020-12-04 09:11 UTC, misudev requested changes
안녕하세요 승완님 ! 🙂
3단계도 깔끔하게 구현 잘 해주셨네요 👍 😀
몇가지 의견 드렸습니다~ 확인하시고 재요청 부탁드려요 🙏

2020-12-04 09:11 UTC, misudev commented on src/test/java/ladder/domain/user/UserTest.java
> +        assertThrows(LadderGameException.class, () -> User.of(given, givenCoordinate));
AssertJ의 Assertions 가 제공하는 메소드를 사용할수도 있습니다 ! 🙂
```java
assertThatThrownBy(() -> User.of(length6, givenCoordinate))
    .isInstanceOf(LadderGameException.class)
    .hasMessage(예외 메시지);
```

2020-12-06 22:44 UTC, joswlv commented on src/main/java/ladder/domain/model/LadderGameInfo.java
>      private final LadderHeight ladderHeight;
DTO용으로 만든 클래스입니다.

2020-12-07 15:32 UTC, misudev approved these changes
피드백 반영 정말 잘해주셨네요 ! 👍 
몇 가지 의견 남겨드렸는데, 다음 단계 진행하면서 고민해주세요 😁
마지막까지 화이팅입니다 !! 🔥

2020-12-07 15:32 UTC, misudev commented on src/main/java/ladder/domain/ladder/Ladder.java
> +        return newPosition;
인자로 User대신, Postion을 받으면 어떨까요?
Ladder객체는 온전히 사다리에 대한 정보만 알면 좋을 것 같아요 🤔

2020-12-07 15:32 UTC, misudev commented on src/main/java/ladder/domain/model/LadderGameInfo.java
>      private final LadderHeight ladderHeight;
변수를 줄일 방법을 고민해주세요 ! 🤔
**규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.**

2020-12-07 15:32 UTC, merged