Step3 사다리(게임실행)
next-step/java-ladder pull request #759
Opened 2020-12-10 08:19 UTC by sehan

### 사다리 게임실행
실행결과를 추가로 입력받고 참여자 개인별 결과와 전체결과를 조회 기능을 추가했습니다.
이전 리뷰에서 우려했던 게임실행 부분은 의외로 잘 풀려서 큰 변경없이 구현 가능했습니다.

### 리팩토링
연속되는 step 체크하는 로직 부분만 분리해서 책임을 위임시켰습니다. (ConsecutivelyStepChecker)

리뷰 요청드립니다. 😄

2020-12-11 14:58 UTC, enemfk777 requested changes
안녕하세요 세환님 🙇‍♂️
리뷰가 늦어져 대단히 죄송합니다 😭
객체지향 생활 체조 원칙을 지켜주시면 더 좋을 것 같은 부분이 있어 관련 피드백을 드렸습니다!
반영 후 다시 PR 부탁드립니다!

2020-12-11 14:58 UTC, enemfk777 commented on src/main/java/ladder/domain/LadderMembers.java
>      private List<String> names;
규칙 3: 모든 원시값과 문자열을 포장한다.
를 적용해서 LadderMember 클래스를 도출해보시는 건 어떨까요 :)
참가자 이름길에 대한 validation도 옮겨갈 수 있고, LadderMember가 스스로의 position을 갖게 할 수 도 있을것 같습니다 😊

2020-12-11 14:58 UTC, enemfk777 commented on src/main/java/ladder/domain/LadderResults.java
> +    private List<String> results;
LadderMembers클래스에서 드렸던 코멘트와 마찬가지로
규칙 3: 모든 원시값과 문자열을 포장한다.
를 적용해서 LadderResult 클래스를 도출해보시는 건 어떨까요 :)
 LadderResult가 스스로의 position을 갖게 할 수 도 있을것 같습니다

2020-12-11 14:58 UTC, enemfk777 commented on src/main/java/ladder/domain/ConsecutivelyStepChecker.java
> +    }
인스턴스화가 불필요해보이는 클래스로 보입니다 :)
멤버 변수를 없애고 유틸성 클래스로 만들어보시는건 어떨까요? 😊

2020-12-14 01:35 UTC, sehan commented on src/main/java/ladder/domain/DefaultLadder.java
> +    private final LadderResults results;
정말 이 규칙은 방심하면 놓치게 되네요 ^^

2020-12-14 01:36 UTC, sehan commented on src/main/java/ladder/domain/LadderMembers.java
>      private List<String> names;
네, 원시값 래핑 해보겠습니다.

2020-12-14 17:06 UTC, enemfk777 approved these changes
안녕하세요 세환님!!
피드백을 반영해주셔서 감사합니다 💯 
다음 스텝은 리팩토링 스텝인데요, 추가로 제공되는 힌트를 통해 TDD 리팩토링을 진행하시면서
아래 조건들이 지켜졌는지 같이 살펴보시면 좋을 것같습니다 😊
1.  [객체 지향 생활 체조 원칙](https://edu.nextstep.camp/s/MNii0Puk/ls/gWde8rTq)을 어긴 부분은 없는지 
2.  메서드의 인자 수는 2개 이하를 유지하고 3개 이상인 부분이 있다면 리팩토링이 가능할지

이번 PR에 드린 피드백들도 다음 스텝에서 같이 반영 부탁드립니다!🙇‍♂️
그럼 이만 Merge하겠습니다!! 🎉

2020-12-14 17:06 UTC, enemfk777 commented on src/main/java/ladder/domain/DefaultLadder.java
> +    }
Print에 관련된 로직은 OutputView에서 수행하는 것이 도메인 클래스와 view의 직접적인 결합을 피할 수 있고,
출력 기능의 응집도를 높일 수 있는 방향 일 것 같습니다 😊

2020-12-14 17:06 UTC, merged