Step2
next-step/java-ladder pull request #767
Opened 2020-12-11 01:17 UTC by hoonick91

아... 이런 실수를 하다니 😢 

리뷰 재요청 드립니다.

2020-12-11 01:56 UTC, yongdae requested changes
종훈님 2단계를 열심히 진행해주셨네요. 👍👍

진행해주신 내용에대해 몇 가지 의견을 남겨놓았습니다.
확인하시고 다시 리뷰 요청 부탁드리겠습니다. 😄

수고하셨습니다.🙇

2020-12-11 01:56 UTC, yongdae commented on README.md
> +## 요구사항 정리
미션 진행 전에 요구사항을 정리해보는 것은 어떨까요?

요구사항을 단순히 나열해보는 것만으로도
무엇을 어떻게 구현해볼지 고민해볼 수 있을 것 같아요!

2020-12-11 01:56 UTC, yongdae commented on src/main/java/ladder/common/ErrorMessage.java
> +public class ErrorMessage {
ErrorMessage를 따로 분리하신 이유가 있으신가요? 🤔

2020-12-11 01:56 UTC, yongdae commented on src/main/java/ladder/domain/Ladder.java
> +    public Ladder(Participants participants, LadderHeight ladderHeight) {
Participants를 사용하지 않고 구현해보는 것은 어떨까요?

LadderGame은 참가자들을 알아야 할 수 있지만
Ladder는 참가자들을 몰라도 되지않을까요? :)

2020-12-11 01:56 UTC, yongdae commented on src/main/java/ladder/domain/LadderLine.java
> +    private final List<Boolean> value;
변수명을 바꿔보면 어떨까요?

코드를 읽을 때 value는 단수형으로 읽히다보니
단일 값을 가질거라고 예측하기 쉬울 것 같아요.
복수형의 의미를 분명하게 주어서 바꾸면 좋을 것 같아요. 😄

2020-12-11 01:56 UTC, yongdae commented on src/main/java/nextstep/fp/Lambda.java
>      }
이전 단계 피드백 반영해주셨네요. 👍👍

2020-12-11 01:56 UTC, yongdae commented on src/test/java/ladder/domain/LadderLineTest.java
> +class LadderLineTest {
<img width="651" alt="Screen Shot 2020-12-11 at 10 40 53 AM" src="https://user-images.githubusercontent.com/4317804/101850578-5c565c80-3b9d-11eb-9d1b-a0c7f4812c7c.png">
이 요구사항에 해당하는 테스트를 추가해보면 어떨까요? :)

2020-12-11 01:56 UTC, yongdae commented on src/test/java/ladder/domain/ParticipantsTest.java
> +class ParticipantsTest {
<img width="436" alt="Screen Shot 2020-12-11 at 10 42 08 AM" src="https://user-images.githubusercontent.com/4317804/101850651-8871dd80-3b9d-11eb-8994-cdb7727286c2.png">
이 요구사항에 대한 테스트도 추가하면 좋을 것 같아요 ~ 😄

2020-12-11 01:56 UTC, yongdae commented on src/main/java/ladder/MainSimulator.java
> +        ladderGameController.getLadderGameInformation();
진행해주신 결과가 미션에서 요구하는 결과와 다른 것 같아요. 😭

미션에서 요구하는 결과
<img width="416" alt="Screen Shot 2020-12-11 at 10 46 54 AM" src="https://user-images.githubusercontent.com/4317804/101851052-341b2d80-3b9e-11eb-9106-3c523c9d0757.png">

종훈님 미션 수행 결과
<img width="429" alt="Screen Shot 2020-12-11 at 10 45 43 AM" src="https://user-images.githubusercontent.com/4317804/101851055-354c5a80-3b9e-11eb-9ae6-a882ea54fd2c.png">

자세히 보시면 출력되는 사다리의 모양이 달라요.

2020-12-11 14:43 UTC, hoonick91 commented on src/main/java/ladder/common/ErrorMessage.java
> +public class ErrorMessage {
한 군데서 관리하는게 편해서 습관적으로 분리했는데, 중복되는 ErrorMessage가 없어서 domain에 포함시켜도 될 것 같네요 😄 

감사합니다.

2020-12-12 14:28 UTC, hoonick91 commented on src/main/java/ladder/MainSimulator.java
> +        ladderGameController.getLadderGameInformation();
안녕하세요 용대님
먼저, 리뷰 정말 감사드립니다. 특히나 부족한 테스트에 대해 지적주신 부분 도움이 많이 된것 같습니다. 👍 

질문사항이 있는데, 너무 늦은 시간이라 slack은 죄송해서 comment 남김니다.

**1. 실행결과에서 참가자들의 이름을 출력할때의 규칙이 어떻게 되는지 알 수 있을까요?**
- 제가 구현한 방법은 이름마다 기본적으로 한칸씩 띄고, 5자 미만의 이름은 그 차이만큼 이름 뒤에 간격을 주었습니다.
- 미션에서 요구하는 결과를 보고 추론해보았는데, 기본적으로 이름마다 1칸씩 띄고, 5자 미만의 이름은 그 차이만큼 이름 뒤에다가 간격을 준 것 같은데 jk만 앞에 간격이 들어가 있습니다. 혹시 2글자 이하이면, 간격을 앞에다 주는 규칙이 있는지 궁금합니다...

**2. 출력되는 사다리의 어떤 모양이 다른지 설명 부탁드립니다.**
- 앞의 간격을 안 준 모양인지 혹은, 사다리 라인(|-----|)의 모양이 다른지 문의 드립니다.

2020-12-13 04:16 UTC, yongdae commented on src/main/java/ladder/MainSimulator.java
> +        ladderGameController.getLadderGameInformation();
1. 이름이 출력되는 규칙의 경우는 요구 사항에 기재되어 있지는 않지만 출력되는 내용을 보면
    참가자의 이름 중 마지막 글자(5글자 기준)가 사다리 시작 지점에 맞추어 출력이 됩니다. 😄
<img width="177" alt="Screen Shot 2020-12-13 at 1 11 01 PM" src="https://user-images.githubusercontent.com/4317804/102002932-bcd3ce00-3d44-11eb-891b-ac54eec59f13.png">

2. 출력되는 사다리의 모양이 다른 부분은 앞서 1번에서 이야기드린 내용과 중복되는 부분인데
종훈님이 이야기 해주신 것처럼 "앞의 간격을 안 준 모양"이 다릅니다.
결과물 출력시 사다리 시작(|) 지점이 참가자 이름의 마지막 지점입니다. :)

2020-12-13 11:38 UTC, yongdae approved these changes
안녕하세요. 종훈님~ 😄

피드백을 잘 반영해주셨네요. 👍
설계도 간단하지만 깔끔하게 잘 해주신 것 같아요!!

진행해주신 내용에대해 의견드린 부분이 몇가지 있는데 크게 수정이 필요하지 않다고
생각되어 바로 다음 단계를 진행하시면 될 것 같아요. 😄

다음 단계 진행하시기 전에 의견 드린 부분 확인 부탁드리겠습니다.
그럼 다음 단계로 바로 가시죠!!

수고하셨습니다. 🙇

2020-12-13 11:38 UTC, yongdae commented on src/main/java/ladder/domain/Ladder.java
> +    public Ladder(int participantCount, LadderHeight ladderHeight) {
participantCount 대신에 다른 이름을 써보는 것은 어떨까요? 🤔

피드백을 통해 잘 수정해주신 것 같아요. 👍 
한번 더 고민해보면 인자 이름이 참가자라는 의미를 가지는
참가자 수(participantCount) 보다 사다리 크기(sizeOfLadeder)를 사용하면
의미적으로 participant에 종속되지 않을 수 있을 것 같아요. :)

2020-12-13 11:38 UTC, yongdae commented on src/main/java/ladder/domain/LadderLine.java
> +        int ladderLength = participantsCount * 2 - 1;
participantsCount 값에 * 2를 하는 방법밖에 없는걸까요?

크게 문제가 되는 부분이라고 생각되지는 않지만
다르게 말하면 곱하기(*) 를 하지 않고도 할 수 있는 방법도 있을 것 같아요. 🤔

2020-12-13 11:38 UTC, yongdae commented on src/main/java/ladder/domain/RandomLadderGenerateStrategy.java
> +public class RandomLadderGenerateStrategy implements LadderGenerateStrategy {
LadderGenerateStrategy을 사용하지 않고 해보는 것은 어떠신가요?

LadderGenerateStrategy는 전략 패턴을 사용하기 위한 부분이라고 판단되는데
전략 패턴은 Context에 따라 상황에 적절한 비지니스를 부여하기 위해 활용하는 패턴이라고 생각해요.
전략 패턴이 가진 의미를 생각해보면 여기서 필요한가에대해 한번 생각해봐도 좋을 것 같아요. 😄

2020-12-13 11:39 UTC, merged

2020-12-14 06:04 UTC, hoonick91 commented on src/main/java/ladder/domain/RandomLadderGenerateStrategy.java
> +public class RandomLadderGenerateStrategy implements LadderGenerateStrategy {
랜덤으로 사다리를 만드는데, test가 용이하지 않아 전략패턴을 사용했습니다. 

레이싱 경주에서 전략패턴을 이용해서 Test를 했었는데, 혹시 다른 방법이 있을까요?? 😭

2020-12-15 12:52 UTC, yongdae commented on src/main/java/ladder/domain/RandomLadderGenerateStrategy.java
> +public class RandomLadderGenerateStrategy implements LadderGenerateStrategy {
"test가 용이하지 않아 전략패턴을 사용" 이라고 이야기 해주셨는데
전략 패턴을 사용함으로써 test가 용이해진 부분이 있을까요??
지금 테스트에서 LadderGenerateStrategy를 사용함으로써  test가 용이해진 부분은 잘 모르겠어요. :)

연속으로 line이 있는 경우를 예외로 만들어 테스트해보는 것은 어떨까요?
2단계에서 요구했던 "사다리 타기가 정상적으로 동작하려면 라인이 겹치지 않도록 해야 한다."
이 부분을 만족시킬 수 있을 것 같아요~

2020-12-16 03:40 UTC, hoonick91 commented on src/main/java/ladder/domain/RandomLadderGenerateStrategy.java
> +public class RandomLadderGenerateStrategy implements LadderGenerateStrategy {
네 전략 패턴을 사용하는게 아니라 람다를 사용해서 테스트 하도록 수정했습니다.

피드백 감사합니다 👍 👍