[4단계 - 사다리(리팩토링)]
next-step/java-ladder pull request #779
Opened 2020-12-15 06:04 UTC by dbeod2

안녕하세요! 드디어 4단계입니다.
기존꺼에 hint받아서 추가로 수정하였는데 이렇게 하는게 맞나 싶지만 일단 제출해보겠습니다!
사다리 게임하면서 ㅠ.ㅠ 정신없이 실수를 많이했는데 항상 꼼꼼히 봐주셔서 감사합니다.
이번단계도 잘 부탁드리겠습니다🙇‍♀️

2020-12-16 12:35 UTC, parkeeseul requested changes
리팩토링 열심히 진행해주셨네요! 
힌트를 적절히 참고해서 진행해주신 점 좋았습니다 👍 

몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다! 😄 
사다리 미션 끝이 보이네요 화이팅 ! 🔥

2020-12-16 12:39 UTC, dbeod2 commented on src/test/java/ladder/step3_renewal/domain/LadderLineTest.java
> +    }
사다리 이동에 대한 테스트입니다. 
말씀주신대로 결과값테스트로 수정해보겠습니다  :)

2020-12-16 12:40 UTC, dbeod2 commented on src/main/java/step3_renewal/domain/Direction.java
> +            return of(this.right, FALSE);
direction클래스에서 고정 된 값으로 false를 사용하고 있어서 import static 선언해 사용하기 위해 박싱된 타입을 선택해서 사용했습니다.

2020-12-16 12:48 UTC, dbeod2 commented on src/main/java/step3_renewal/domain/Ladder.java
> +                        .mapToObj(i -> LadderLine.init(participants.size(), new LadderRandomGenerator()))
넵 코드 수정하다가 랜덤 요소가 또 ㅠㅠ 인자값으로 전달받겠습니다.

2020-12-16 12:50 UTC, dbeod2 commented on src/test/java/ladder/step3_renewal/domain/DirectionTest.java
> +    }
이 테스트는 다음 랜덤값에 대한 확인 테스트 입니다 point메서드중 next메서드에 현재값이 true인경우 false로 값을 주입해주는 부분이 있어서요! 고민해보고 다시작성해보겠습니다~

2020-12-17 16:15 UTC, parkeeseul requested changes
피드백 열심히 반영해주셨네요! 👍 

몇 가지 추가 코멘트 남겨드렸으니 확인 부탁드립니다!
마지막 까지 화이팅 입니다 ! 🔥

2020-12-17 22:41 UTC, dbeod2 commented on src/main/java/step3_renewal/domain/LadderLine.java
> +        List<Point> points = new ArrayList<>();
넵, 고려해보겠습니다 ~ :)

2020-12-17 23:23 UTC, dbeod2 commented on src/main/java/step3_renewal/domain/Ladder.java
> +    public static Ladder of(int maxHeight, Participants participants, LadderRandomGenerator ladderRandomGenerator) {
엇! ㅜㅜ... LadderGenertor을 만들고 사용한다는게 ;; ㅎㅎ 수정하겠습니다.

2020-12-17 23:26 UTC, dbeod2 commented on src/main/java/step3_renewal/domain/LadderLine.java
> +        Point point = Point.first(new LadderRandomGenerator().nextLine());
인자값으로 전달 받아할 것 같아요 ㅎ.ㅎ

2020-12-17 23:30 UTC, dbeod2 commented on src/main/java/step3_renewal/view/OutputUi.java
> +        IntStream.range(0, line.getPoints().size())
넵 , 위와 같이 코드를 작성하면 결합도 낮아질 것 같고, point의 getter메서드를 직접호출하지 않아도 되네요 ㅎ!

2020-12-18 14:32 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
잘 반영해주셔서 이만 머지 하도록 하겠습니다! 🎉 

그동안 많은 피드백 반영해주시느라 정말 고생많으셨습니다!
유라님께 조금이나마 도움이 될 수 었었다면 좋겠네요 😄 
정말 고생 많으셨고 앞으로 남은 미션도 꼭 완주 하셔서 많은 인사이트들 얻어가시길 바라겠습니다!
응원하겠습니다! 화이팅!

2020-12-18 14:32 UTC, merged