Step2 사다리 타기 생성
next-step/java-ladder pull request #802
Opened 2021-01-17 22:22 UTC by deviscreen

2021-01-18 23:23 UTC, javajigi requested changes
객체 설계 측면에서는 설계를 잘 했는데요.
구현 측면에서 소소하게 개선해봤으면 하는 부분들이 있네요.
그리 큰 수정이 필요한 부분들은 아니니 쉽게 반영할 수 있을 겁니다.

2021-01-18 23:23 UTC, javajigi commented on src/main/java/ladder/domain/Ladder.java
> +    public Ladder(){}
기본 생성자 없이 구현할 수 있지 않을까?

2021-01-18 23:23 UTC, javajigi commented on src/main/java/ladder/domain/Ladder.java
> +    private List<Line> lines;
인스턴스 변수에 중복이 있다.
lines.size() == hieght와 같다.
인스턴스 변수의 수를 최소화한다.

2021-01-18 23:23 UTC, javajigi commented on src/main/java/ladder/domain/Ladder.java
> +    protected List<Name> participateNames(String names) {
`private static`으로 구현해도 되지 않을까?

2021-01-18 23:23 UTC, javajigi commented on src/main/java/ladder/domain/Ladder.java
> +        List<Name> collect = Arrays.stream(strings)
local 변수에 저장하지 않고 바로 return하는 것은 어떨까?

2021-01-18 23:23 UTC, javajigi commented on src/main/java/ladder/domain/Ladder.java
> +        List<Line> generatedLine = Stream.generate(() -> new Line(countOfName))
IntStream으로 구현해 본다

2021-01-18 23:23 UTC, javajigi commented on src/main/java/ladder/domain/Ladder.java
> +        return new ArrayList<>(this.lines);
새로운 ArrayList를 생성하기보다 Collections.unmodifiableList()로 반환하는 것은 어떨까?

2021-01-18 23:23 UTC, javajigi commented on src/main/java/ladder/domain/Line.java
> +    private int columnSize;
`private final`로 구현한다.

2021-01-19 13:52 UTC, deviscreen commented on src/main/java/ladder/domain/Ladder.java
> +    protected List<Name> participateNames(String names) {
private로 변경하면  participateNames 메서드를 테스트 하지 못해서 protected로 구현을 했습니다. private로 변경을 하는 이유가 생성자로 만들어지면서 participateNames 메서드를 사용하고 있기 때문에 private로 구현을 해도된다라는 말씀이신가요??🧐

2021-01-19 23:47 UTC, javajigi commented on src/main/java/ladder/domain/Ladder.java
> +    protected List<Name> participateNames(String names) {
테스트를 위해 private으로 구현하기 힘들다면 객체 설계에 개선할 부분을 찾을 수 있는 힌트라 생각해요.
어떻게 개선하면 좋을지 고민해 보면 어떨까요?

2021-01-20 00:39 UTC, javajigi approved these changes
피드백 반영하느라 수고했네요. 👍 
단, 제가 `새로운 ArrayList를 생성하기보다 Collections.unmodifiableList()로 반환하는 것은 어떨까?` 피드백을 했는데요. 피드백 반영을 피드백을 준 부분에 대해서만 반영했는데요. 다른 부분에도 ArrayList를 사용하는 부분이 있는데 같이 반영해 보면 좋겠어요.
단순히 피드백만 반영해서는 의미가 없고, 이 같은 피드백을 준 이유와 자신이 지금까지 잘못생각하고 있던 습관이 있다면 바꾸려는 노력을 할 때 실력이 향상되리라 생각해요. 단순 피드백만 반영하는 것은 아닌지 생각해 보는 시간이 되면 좋겠네요.

2021-01-20 00:39 UTC, merged

2021-01-20 04:01 UTC, deviscreen commented
> 피드백 반영하느라 수고했네요. 👍 
> 
> 단, 제가 `새로운 ArrayList를 생성하기보다 Collections.unmodifiableList()로 반환하는 것은 어떨까?` 피드백을 했는데요. 피드백 반영을 피드백을 준 부분에 대해서만 반영했는데요. 다른 부분에도 ArrayList를 사용하는 부분이 있는데 같이 반영해 보면 좋겠어요.
> 
> 단순히 피드백만 반영해서는 의미가 없고, 이 같은 피드백을 준 이유와 자신이 지금까지 잘못생각하고 있던 습관이 있다면 바꾸려는 노력을 할 때 실력이 향상되리라 생각해요. 단순 피드백만 반영하는 것은 아닌지 생각해 보는 시간이 되면 좋겠네요.

네 알겠습니다 . 감사합니다