Step2 ladder 리뷰 요청드립니다.
next-step/java-ladder pull request #811
Opened 2021-03-21 09:39 UTC by dhdydtn91

로또에 비해 사다리가 상당히 어렵네요

우선 최대한 객체별로 책임을 나눠 구현해 보았습니다.

또 True ,false에 따라 사다리를 그려줘야하는데 이 부분이 if문이 많아진다 생각해서 Ladder enum클래스로 

바꿔서 구현해보았습니다.

2021-03-21 11:50 UTC, JunilHwang requested changes
안녕하세요 용수님! Stream과 관련된 미션인데 Stream을 거의 사용하질 않으셨네요 ㅠㅠ
최대한 적극적으로 사용해보면 좋을 것 같습니다!

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Line.java
> +            throw new IllegalArgumentException("가로라인은 두번 연속 나올 수 없습니다.");
Custom Exception을 만들어주면 어떨까요?

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Line.java
> +        }
stream을 사용해보면 어떨까요?

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Line.java
> +        }
Stream을 사용해보면 어떨까요?

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Line.java
> +        }
Optional을 이용해보면 어떨까요?

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Line.java
> +    }
이 부분은 전략 객체로 만들어주면 어떨까요?

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Line.java
> +    }
마찬가지로 전략으로 분리시키면 좋을 것 같아요!

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Line.java
> +    }
```suggestion
    public LineDto toDto() {
        return new LineDto(line);
    }
```
이런 이름이 더 어울릴 것 같아요!

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Lines.java
> +        this.lines = lines;
Stream을 사용해보세요!

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Name.java
> +public class Name {
Name보단 PlayerName으로 지어주면 좋을 것 같습니다!

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Name.java
> +                .orElseThrow(() -> new IllegalArgumentException("플레이어 이름은 5글자를 초과할 수 없습니다."));
- 매직넘버는 상수로 만들어서 사용해주세요
- CustomException으로 만들면 좋을 것 같아요!

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Players.java
> +    private static final int ZERO = 0;
상수와 일반 멤버 변수는 개행으로 구분해주면 좋을 것 같습니다!

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Players.java
> +        this.playerList = playerList;
```suggestion
        this(playerList);
```
이렇게 표현할 수 있습니다!

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Players.java
> +        return players;
이 부분도 스트림으로 사용할 수 있지 않을까요?

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Players.java
> +        }
CustomException으로 만들어보세요~

2021-03-21 11:50 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Players.java
> +        return maxLength;
이 부분도 Stream을 사용해보세요!

2021-03-23 11:53 UTC, dhdydtn91 commented
피드백 반영하여 리팩토링 했습니다. 

  - 리팩토링 내용 -
  
1. 전략 객체로 분리
2. for문 stream으로 리팩토링
3. 커스텀 Exception 생성
4. View 로직 리팩토링

2021-03-23 13:30 UTC, JunilHwang approved these changes
안녕하세요 용수님! 피드백 반영 잘 해주셨네요 👍 
Step2는 여기서 마무리 하겠습니다!
이 외에도 몇 가지 리뷰 남겼으니 다음 스텝 진행하실 때 참고하시면 좋을 것 같아요 😄

2021-03-23 13:30 UTC, JunilHwang commented on src/main/java/laddarGame/domain/LadderCreateStrategy.java
> +    }
아예 싱글톤 객체로 만들어줘도 좋을 것 같습니다!

2021-03-23 13:30 UTC, JunilHwang commented on src/main/java/laddarGame/domain/LadderCreateStrategy.java
> +public class LadderCreateStrategy implements CreateStrategy {
전략 분리 👍

2021-03-23 13:30 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Line.java
> +        LadderCreateStrategy conditional = LadderCreateStrategy.of();
전략은 게임 클래스에서 만든 후에 주입을 해주는 방식은 어떨까요?

2021-03-23 13:30 UTC, JunilHwang commented on src/main/java/laddarGame/domain/Lines.java
> +                .mapToObj(index -> new Line(playerCount))
```suggestion
        return Stream.generate(() -> new Line(playerCount))
                .limit(ladderHeight)
```
이렇게 표현하는 방법도 있습니다!

2021-03-23 13:30 UTC, JunilHwang commented on src/main/java/laddarGame/view/Ladder.java
> +    private final String drawPoint;
drawPoint는 View에서 관리를 해줘야하지 않을까요?

2021-03-23 13:30 UTC, JunilHwang commented on src/main/java/laddarGame/view/Ladder.java
> +    }
메소드와 변수명이 같아서 첫 글자를 대문자로 해주신것 같아요!
더 어울리는 메소드 명이 있지 않을까요?

2021-03-23 13:30 UTC, JunilHwang commented on src/main/java/laddarGame/view/Ladder.java
> +public enum Ladder {
Ladder보단 Direction 이라는 이름이 더 좋을 것 같아요!

2021-03-23 13:30 UTC, merged