Step2리뷰요청드립니다.
next-step/java-ladder pull request #870
Opened 2021-04-08 10:37 UTC by cptbong

안녕하세요.
며칠을 계속 고민하다가... 혼자 좀 잘 안풀리는거 같아 리뷰요청드립니다.
전에 로또단계에서도 그랬던거 같은데, 좀 요구사항분석을 제대로 못하는거같네요 ㅜ
일단 이렇게 구현하는게 맞나싶으면서도 해봤습니다.

2021-04-08 10:44 UTC, neojjc2 commented
#tag @neojjc2

2021-04-08 13:37 UTC, neojjc2 requested changes
안녕하세요 일균님 😄 

2단계 구현 잘해주셨습니다 😄 

저도 개인적으로 미션 진행하면서 사다리가 가장 어려웠는데요, 
일단 사다리를 어떻게 그리는지 아예 방식을 몰랐어서
사다리 생성 하는 알고리즘이나 이런 부분 부터 알아보고 이해하느라 
많은 시간이 걸렸었습니다 😄 

차근 차근 하시다 보면 금방 또 하게 되실겁니다
너무 조급하게 생각하지 마시고 하나씩 하나씩 개선해 나가다 보면
어느새 마지막 단계에 계실거라 생각됩니다 😄 🔥 

몇 가지 의견 드렸습니다 
해당 내용 보시고 개선하시는데 도움 되셨으면 좋겠습니다 🔋 

궁금하신 내용이나 고민 있으시면 언제든 코멘트 남겨주시거나 DM 주세요 ✋ 😄 

그럼 재 리뷰 요청 부탁 드리겠습니다 🙇

2021-04-08 13:37 UTC, neojjc2 commented on src/main/java/nextstep/OnlineLadder.java
> +        Random rand = new Random();
`method`가 호출 될 때마다 
매번 초기화가 되는 부분입니다 
이 부분도 `private final static` 으로 상수 처리하면 좋을 것 같습니다 😄

2021-04-08 13:37 UTC, neojjc2 commented on src/main/java/nextstep/OnlineLadder.java
> +        Coordinate coordinate = new Coordinate(name, coordinates.size()+1, 0);
매직넘버가 추출 되어 상수화 되면 가독성 측면에서 더 개선해 볼 수 있을 것 같습니다 😄 🙇

2021-04-08 13:37 UTC, neojjc2 commented on src/main/java/nextstep/view/ConsoleView.java
> +public interface ConsoleView {
`ConsoleView `좋네요 👍

2021-04-08 13:37 UTC, neojjc2 commented on src/main/java/nextstep/view/ResultView.java
> +    public void print(OnlineLadder ladder) {
사다리를 생성과 동시에 출력을 하는 부분이 섞여 있는 것 같습니다 😄 
이렇게 되면 출력할 때 얼마든지 사다리를 변경할 수가 있습니다 😨 

차라리 사다리를 생성하는 부분은 `Ladder`에 위임하시고 출력을 위한 결과만 반환하고 
그 반환된 객체 혹은 `DTO`만 가지고 출력하도록 개선해보시는건 어떨까요??

이 부분 검토 부탁 드립니다 🙇

2021-04-08 13:37 UTC, neojjc2 commented on src/main/java/nextstep/view/ResultView.java
> +        for(int i = 0; i < ladder.heights().size(); i++) {
아래 규칙 다시한번 떠올리시고 개선 고민 부탁 드리겠습니다 😄 

> * 메소드를 작은 단위로 잘 분리했는가?(인덴트를 1로 잘 유지했는가? 포함)
> * else 예약어를 쓰지 않았는가?

2021-04-08 13:37 UTC, neojjc2 commented on src/main/java/nextstep/view/ResultView.java
> +        for (String name : names) {
`Ladder`에 참가자를 추가하는 역할을 출력에서 하고 있습니다 😄 
이 부분도 `Ladder`의 역할과 책임으로 보는게 더 자연스러울 것 같습니다 
출력 부분에서 얼마든지 참가자를 변경 할 수 있으니까요 😅 

이 부분도 개선 검토 부탁 드립니다 🙇

2021-04-08 13:37 UTC, neojjc2 commented on src/main/java/nextstep/view/ResultView.java
> +        for (int i = 0; i < this.ladderCount; i++) {
일균님이 개발이 끝나서 서비스가 진행되고 있는 사다리 게임에 
새로운 개발자가 왔습니다 😄 

그리고 
`LadderGameClient`에서 사다리를 한번 더 출력해보고 싶어서 아래와 같이 코드를 추가했습니다 
당연히 `printAll `일테니 한번 더 출력하고 싶으면 한번 더 호출하면 되겠지 하구요 😄  
```
OnlineLadder ladder = new OnlineLadder(ladderCount);
resultView.printAll(ladder, names);
resultView.printAll(ladder, names); // 한번 더 출력하고 싶어서 추가한 부분
```

그리고 실행하면 아래와 같이 에러가 발생을 합니다 😭 
![image](https://user-images.githubusercontent.com/68527004/114034495-31fd7d00-98b9-11eb-9d17-fb3e183b4f20.png)

예가 약간 억지스러운 면이 있을 수도 있긴 합니다만 😄 
저야 어떤 요구사항을 구현하신지 전체를 다 알고 
일균님 코드 전체를 봤기 때문에 어느 부분이 문제인지 알 수 있지만 

만약 이 코드를 처음 보시는 분이라면 아마 위와 같은 에러를 보시고 
원인을 찾기 위해 고군분투 하실 수 도 있습니다 😄 

`Model `과 `View`가 좀 더 명확히 분리 되면 좋을 것 같습니다 😄 
이 부분도 확인 부탁 드립니다 🙇

2021-04-08 13:37 UTC, neojjc2 commented on src/main/java/nextstep/LadderGameClient.java
> +        String namesString = inputView.inputQuestion("참여할 사람 이름을 입력하세요. (이름은 쉼표(,)로 구분하세요)");
요구사항 다시한번 확인 부탁 드리겠습니다 😄 
> 사다리 게임에 참여하는 사람에 이름을 최대5글자까지 부여할 수 있다. 사다리를 출력할 때 사람 이름도 같이 출력한다.

![image](https://user-images.githubusercontent.com/68527004/114035492-1ba3f100-98ba-11eb-8ba6-a6a6bfa74ae9.png)

2021-04-08 13:37 UTC, neojjc2 commented on src/main/java/nextstep/LadderGameClient.java
> +        String ladderCountString = inputView.inputQuestion("최대 사다리 높이는 몇 개인가요?");
참여자 제한이 따로 있지는 않았던 것 같습니다 😄 
이 부분도 확인 한번 부탁 드리겠습니다 🙇 

![image](https://user-images.githubusercontent.com/68527004/114035708-53129d80-98ba-11eb-8534-f8f11b434f1b.png)

2021-04-08 13:37 UTC, neojjc2 commented on src/main/java/nextstep/LadderGameClient.java
> +        resultView.printAll(ladder, names);
출력 부분도 다시한번 확인 부탁 드립니다 😄 

참가자가 3명인데 사다리 시작점이 4개 이네요 😅 

![image](https://user-images.githubusercontent.com/68527004/114035932-8b19e080-98ba-11eb-858a-f8ce33727e79.png)

2021-04-11 06:36 UTC, cptbong commented on src/main/java/nextstep/OnlineLadder.java
> +    protected final List<Coordinate> coordinates;
없습니다. ㅜ private으로 했다가 수정중에 뭐 바꾼거같네요.

2021-04-11 11:53 UTC, cptbong commented
@neojjc2  안녕하세요. 다시 작성해서 리뷰요청드렸습니다.
여쭤볼게 몇가지 있는데요.
1.  제가 작성한 Line.java의 lineString메서드(69라인)이  복잡한데, 이걸 람다로 변경할 수 있을까요? 좀 고민해보고 검색해봐도 답이 안나와서 여쭤봤어요.
2. index문제인데요. 하다가 뭔가 저만의 소설이 시작되고, 머릿속으로 상상을 하다가... **어? 클린코드면 이해하기 쉽고 해야하는데, 그럼 사다리높이도 숫자그대로 해야하는거아냐?** 라는 생각으로... 뭔가 반복문의 시작값은 1이되어야하고, 최대값은 <가 아닌 <=로 되야하지 않나? 싶었는데, 그건 아니겠죠?;;
3. 사다리를...
일단 랜덤boolean으로 그리는데, 해당 라인에 체크되는게 없으면 Random nextInt로 하나만 그렸습니다.
해당라인을 모두 그렸으면, 윗 라인의 그려진녀석을 참고해서 하나만 그리도록 했는데요.
이게... 아니겠죠? 😭

2021-04-12 05:20 UTC, neojjc2 requested changes
안녕하세요 일균님 😄 

몇 가지 추가의견 드렸습니다 🙇 
DM 으로도 말씀 드렸지만 😅 

먼저 기능이 잘 동작 되도록 구현하신 다음 
리팩토링 하는 방식으로 접근해보시는 것도 하나의 방법일 것 같습니다 🙇 

그럼 다시한번 리뷰 요청 부탁 드리겠습니다 🙇

2021-04-12 05:20 UTC, neojjc2 commented on src/main/java/nextstep/model/Line.java
> +    public void mark() {
`mark()`의 반환타입을 `boolean` 형으로 개선해보시는건 어떨까요??
Exception을 발생시키게 되면 호출하는 쪽에서 `Exception`을 반드시 처리해야 합니다 
게다가 `IllegalArgumentException`은 `RuntimeException`이어서 호출하는 쪽에서 
이 부분의 코드를 보지 않으면 모를 수도 있습니다 

그럼 예측하지 않은 상황에서 `Exception`이 발생하기 때문에 
강제로 프로그램이 종료되는 크리티컬한 (?) 상황이 올 수도 있습니다 😄 

`mark()`를 호출한 쪽에서 `true`이면 잘 마킹이 됐구나 하고 `false`면 마킹이 되지 않았구나 
정도면 충분할 것 같습니다 😄 

이 부분도 검토 부탁 드리겠습니다 😄

2021-04-12 05:20 UTC, neojjc2 commented on src/main/java/nextstep/model/Lines.java
> +            this.lines.get(targetVertical).mark();
위에서 의견드린 것 처럼 개선해주신다면
여기서 불필요하게 `catch`할 필요가 없을 것 같습니다 😄 

`Exception`에 대해서 도움 되실만한 내용 공유 드립니다 🙇 
> https://cheese10yun.github.io/checked-exception/

2021-04-12 05:20 UTC, neojjc2 commented on src/main/java/nextstep/model/Players.java
> +        Optional<String> first = Arrays.stream(names)
```suggestion
        Arrays.stream(names).anyMatch(s -> s.length() > 5);
```
`anyMatch`를 한번 활용해보시는건 어떠실까요?? 🤔

2021-04-14 12:29 UTC, cptbong commented
안녕하세요.
여쭤볼게 있습니다. 제가 작성한 코드에서 Points클래스의 47라인에
markBottom메서드가 있습니다.
이걸 전에 슬랙 DM으로 여쭤봤을때는 **쪼개면되겠네요**. 라고 자신있게 말했는데, 뭔가 이런 인덱스를 왔다갔다 하고, 루프중에 continue도 사용하는... 더러운 냄새가 무지 나지만 어찌 건들지? 라는 생각이 드네요 ㅜ
단순히 extract method야 가능하지만, 그렇다고 악취가 없지는 않을거 같은데... 뭔가 힌트 없을까요? @@

2021-04-14 15:34 UTC, neojjc2 approved these changes
안녕하세요 일균님 🙇 

정말 여러번 요청을 드렸는데도 잘 이렇게 소화해주셔서 너무 감사합니다 💯 👍 

고민도 많이 해주셨고, 그 덕에 어느정도 구조가 잡힌 것 같습니다 😄 
추가 고민에 대한 질문을 주셨는데, 아직까지 너무 사다리를 그리는 데만 
집중이 되어계신거 같습니다 😅 

이 부분은 다음단계 진행하시면서 같이 고민해보시죠!!

일단 merge 하겠습니다 🙇

2021-04-14 15:38 UTC, neojjc2 commented
> markBottom메서드가 있습니다.
이걸 전에 슬랙 DM으로 여쭤봤을때는 쪼개면되겠네요. 라고 자신있게 말했는데, 뭔가 이런 인덱스를 왔다갔다 하고, 루프중에 continue도 사용하는... 더러운 냄새가 무지 나지만 어찌 건들지? 라는 생각이 드네요 ㅜ
단순히 extract method야 가능하지만, 그렇다고 악취가 없지는 않을거 같은데... 뭔가 힌트 없을까요? @@

일단 사다리를 생성하시는데 너무 집중이 되셔서 그런거 같습니다 😄 
먼저 출력을 위해 필요한 부분과 출력과 관여된 부분을 ResultView로 옮기시고
사다리 게임을 실행할 수 있는 부분까지 고려해보시면 
자연스럽게 더 분리가 될 것 같습니다 😄 

좋은데요?? 👍 

다음단계 진행하시면 자연스럽게 더 정리가 될 것 같습니다 🔥 
화이팅 입니다 🔋

2021-04-14 15:38 UTC, merged