[사다리타기 - Step2] 코드리뷰 요청 드립니다!
next-step/java-ladder pull request #895
Opened 2021-04-11 14:16 UTC by juniqlim

준일님, 안녕하세요! 
코드리뷰 요청드립니다.

2021-04-12 07:29 UTC, JunilHwang requested changes
안녕하세요 준규님! Step2 구현 잘 해주셨습니다 👍 
Stream 관련 미션인 만큼 Stream을 조금 더 적극적으로 사용해보면 어떨까요?
이 외에도 몇 가지 리뷰 남겼으니 확인 후 다시 피드백 요청 부탁드립니다. 🙇‍♂️

2021-04-12 07:29 UTC, JunilHwang commented on src/main/java/nextstep/fp/Lambda.java
> +            .filter(number -> c.test(number))
```suggestion
            .filter(c::test)
```
이렇게 표현할 수 있습니다.

2021-04-12 07:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +            lines.add(Line.from(count, new RandomBooleanStrategy()));
strategy는 외부에서 주입해주는게 어떨까요?

2021-04-12 07:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +        return new Ladder(lines);
Stream 관련 미션인 만큼 Stream을 조금 더 적극적으로 사용해보면 좋을 것 같습니다!

2021-04-12 07:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Line.java
> +        return new Line(points);
앞선 리뷰와 동일합니다.

2021-04-12 07:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Member.java
> +            throw new IllegalArgumentException("참여자 이름은 5글자 이하여야 합니다.");
CustomException을 만들어보면 어떨까요?

2021-04-12 07:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Member.java
> +    public static Member from(String name) {
보통 이럴 땐 of 혹은 valueOf 라는 메소드 이름을 사용합니다!

2021-04-12 07:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Member.java
> +    }
보통 toString은 system.out에서 확인하기 위한 용도로 사용됩니다.
아예 getter를 만들어주면 어떨까요? 혹은 DTO를 만드는 것도 하나의 방법입니다!

2021-04-12 07:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Point.java
> +    }
아예 전략 패턴에 전적으로 위임해주면 어떨까요?

2021-04-12 07:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Point.java
> +    private final BooleanStrategy booleanStrategy;
strategy를 멤버변수로 가지고 있기 보단 매개변수로만 사용해주면 더 좋을 것 같습니다.

2021-04-12 12:39 UTC, juniqlim commented on src/main/java/nextstep/ladder/domain/Member.java
> +    public static Member from(String name) {
제가 정적 팩토리 메소드 사용을 많이 안해봐서, 이펙티브 자바 책에 나와있다고 하는 네이밍을 따라해봤습니다. 
https://it-mesung.tistory.com/184 
from 은 저도 잘 못본 것 같아서 of로 변경하겠습니다!

2021-04-13 01:03 UTC, juniqlim commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +            lines.add(Line.from(count, new RandomBooleanStrategy()));
준일님 조언대로 외부에서 주입하는 것으로 코드를 변경해보았습니다.
외부주입으로 변경했을때 이점이, 외부에 Ladder는 BooleanStrategy가 필요하다고 알리게 된 대신에, 테스트가 좀 더 용이해지는 것 맞을까요? 제가 코드 변경을 제대로 한게 맞는지.. 이점에 대해 아리송 합니다ㅠㅠ

2021-04-13 01:06 UTC, juniqlim commented on src/main/java/nextstep/ladder/domain/Member.java
> +    }
말씀대로 toString은 편향적인 것 같습니다! getter를 만들었습니다.

2021-04-13 01:07 UTC, juniqlim commented on src/main/java/nextstep/ladder/domain/Point.java
> +    }
전략 패턴으로 위임하니 Point 가 더 깔끔해지고 booleanStrategy을 매개변수로 사용할 수 있었습니다.

2021-04-13 01:16 UTC, juniqlim commented
안녕하세요 준일님!  말씀해주신 피드백을 반영해보았습니다.
코드리뷰 부탁드립니다!

추가적인 궁금증이 있어서 
https://github.com/next-step/java-ladder/pull/895#discussion_r612052733
여기 댓글을 달았습니다. 확인을 부탁드립니다. 🙇‍♂️

2021-04-13 02:08 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Ladder.java
> +            lines.add(Line.from(count, new RandomBooleanStrategy()));
넵 맞습니다! 그리고 더 유연하게 관리하는게 가능해집니다 ㅎㅎ

2021-04-13 02:20 UTC, JunilHwang approved these changes
안녕하세요 준규님! 피드백 반영 잘 해주셨네요 👍 
질문에 대한 답변은 해당 코멘트에 남겨놨습니다.
Step2는 여기서 마무리하겠습니다. 바로 다음 스텝 진행해주세요!

2021-04-13 02:20 UTC, merged