[사다리 - 2단계]리뷰 요청드립니다.
next-step/java-ladder pull request #900
Opened 2021-04-12 13:11 UTC by jaystar13

안녕하세요. 용대님
오늘은 비가 주륵주륵 내리네요. 🌧
집에서 미션하기 참 좋은 날입니다.😄

생각보다 시간이 좀 많이 걸린 미션이였습니다.
많이 고민을 하고 그동안 배운걸 되도록 많이 써먹을려고 해봤는데
아직도 많이 부족한거 같네요.

미션을 진행하면서 궁금한 내용에 대해 조언을 부탁드릴려고 합니다.

1. Stream을 의식적으로 사용하도록 노력을 했는데요,
반복을 할 수 있는거라면 무조건 Stream을 사용하는게 좋을까요?
아직 익숙하지 않은 거라 저도 모르게 for문으로 코딩을 하기도 하는데요
간단한 것은 괜찮은 건지? for문과 비교한 Stream의 단점은 없는지 궁금합니다.

2. 설계상의 고민인데요,
A라는 클래스가 B라는 클래스의 멤버 변수 중 일부분을 참조해야 하는 상황이라면,
이 A클래스는 생성자 또는 메서드의 인자로 B클래스 전체를 받는게 좋을지?
아니면 B클래스의 멤버 변수만 인자로 받는게 좋을지 고민입니다.
의미상으로는 당연히 후자쪽의 일부 멤버 변수만 받는게 좋을 거 같은데요
제가 능력히 부족한 탓인지 이렇게 되면 필연적으로 getter(또는 getter비스무리)를 사용하게 되어서
getter사용 지양에 위배가 되어 버리고 마네요.
이건 설계를 고쳐야 하는건지...
혹시 관련해서 도움을 주실 수 있으시면 정말 감사하겠습니다.

많이 부족한 코드이지만 리뷰 부탁드리겠습니다.🙇‍♂️

2021-04-12 15:06 UTC, yongdae commented
안녕하세요. 재성님!
리뷰 요청과 별개로 질의해주신 내용에대해 먼저 답변드립니다. 😄

1. for문과 Stream의 장단점

for문은 문장에도 적혀있든 말 그대로 일종의 구문이고 Stream은 자바에서 제공하는 패키지이기 때문에
같은 선상에서 비교하는 것은 어렵다고 생각합니다.

다만 활용에 있어서의 차이점은 있습니다.

for문은 반복적으로 처리해야하는 작업문을 작성해야 할 때 활용한는 구문이고
Stream은 일련의 일들을 연속적으로 처리 할 때 활용하는 패키지라고 생각하시면 좋습니다.

조금 더 상세히 말하자면 for문은 어떤 형태가 되었든 정말 반복적인 일을 하고 반복적인 일만 할 수 있습니다.

for(int start = 0; start < end; start++) {
    System.out.println(start);
}

Stream 패키지를 활용하면 하나의 연산이 끝나면 연산 결과를 다시 연산 할 수 있습니다.

numbers.stream()
.map(number -> number.getValue()) // int로 치환하는 연산
.sum() // 합산하는 연산

추가로 Stream을 활용하면 연산 내용도 인터페이스로 분리 할 수 있어 비지니스를 분리하는데 용이한 점이 있습니다.

2. getter를 사용하지 않고 객체를 설계하는 방법

이 질문은 리뷰이분들께 가장 많이 받는 질문 중 하나입니다. :)

규칙 4: 한 줄에 점을 하나만 찍는다.
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

주로 위의 2가지 규칙을 적용하게되면 고민하시는 부분인데요
설계 방법에는 여러가지가 있지만 가장 권장드리는 방법은 메세지 전달을 활용한 방법입니다.

코멘트로 설명드리기에는 내용이 많아서
[규칙 4: 한 줄에 점을 하나만 찍는다.](https://7942yongdae.tistory.com/29) 을 기준으로 설명한 링크를 전달드립니다.

2021-04-12 15:36 UTC, yongdae requested changes
안녕하세요. 재성님!! 😄 
커밋 내역만 봐도 많은 고민을 통해 미션을 진행해주셨다는게 느껴집니다. 👍 
수고하셨습니다.

일단 질문해주신 내용은 답변이 너무 길어 [코멘트](https://github.com/next-step/java-ladder/pull/900#issuecomment-817889385)를 통해 답변드리고
진행해주신 내용에대해서도 의견드렸습니다~ :)

리뷰 내용 확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🔥🔥
그리고 언제든 DM을 통해 질문하셔도 괜찮으니 고민이나 의견있으시면 말해주세요!

2021-04-12 15:36 UTC, yongdae commented on README.md
> +## 기능 목록
기능 목록을 정리해주셨네요. 👍

2021-04-12 15:36 UTC, yongdae commented on README.md
> +
게임 결과를 확인하는 기능도 추가해보면 어떨까요?

사다리 게임에서는 게임 결과도 중요한 부분인 것 같아요. :)

2021-04-12 15:36 UTC, yongdae commented on src/main/java/ladder/LadderGameApplication.java
> +            resultView.printOutLineResult();
LadderController만 사용하게 해보면 좋을 것 같아요. :)

사다리 게임이 라이브러리 형태로 제공되서 다른 개발자가 사용한다고하면
LadderController 하나만 사용해서 사다리게임을 할 수 있게 해주는게 좋지 않을까요?

2021-04-12 15:36 UTC, yongdae commented on src/main/java/nextstep/fp/StreamStudy.java
> +                .sorted((w1, w2) -> w2.length() - w1.length())
```suggestion
                .sorted(Comparator.comparingInt(String::length).reversed())
```

이렇게 사용하는 방법도 있어요~

2021-04-12 15:36 UTC, yongdae commented on src/test/java/ladder/LineTest.java
> +        System.out.println(lineResult);
결과를 확인하는 부분이 없어요. 😭 

테스트는 최종적으로 기대하는 결과 값을 통해 검증을 하는데
결과를 확인하는 부분이 없기 때문에 어떤 결과를 예측하고 테스트를 만들었는지 알수가 없어요ㅜ

2021-04-12 15:36 UTC, yongdae commented on src/test/java/ladder/LineTest.java
> +public class LineTest {
테스트를 추가해보면 어떨까요?

1. 게임 결과를 예측하는 테스트

예를 들어 이런 사다리 게임 결과 있다고 했을 때
<img width="111" alt="Screen Shot 2021-04-09 at 11 24 07 PM" src="https://user-images.githubusercontent.com/4317804/114194660-b23fe300-998a-11eb-983d-6b1bb73408e5.png">

1번의 최종 위치는 3
2번의 최종 위치는 1
3번의 최종 위치는 2

와 같은 결과를 확인 할 수 있는 테스트를 작성하면 어떨까요?

2. 연속된 점(가로라인)을 가질 수 없는 것을 확인하는 테스트

이렇게 2개의 테스트를 추가해보면 요구사항을 만족시키는 테스트를 작성 할 수 있어요. 😄

2021-04-12 15:36 UTC, yongdae commented on src/test/java/ladder/PlayersTest.java
> +        assertThat(players.playerPosition(new Player("test4"))).isEqualTo(Position.LAST);
Players와 상관없이 위치 정보를 확인 할 수 있으면 좋을 것 같아요!

예를 들어 Players 말고 Point가 위치 정보를 확인 할 수 있다면 어떨까요?

2021-04-12 15:36 UTC, yongdae commented on src/main/java/ladder/view/ResultView.java
> +        }
[규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.](https://7942yongdae.tistory.com/9?category=987860)

이 규칙을 적용해보면 좋을 것 같아요. :)

2021-04-15 13:30 UTC, jaystar13 commented
안녕하세요.😃

피드백 주신 내용과 DM으로 얘기해 주신 부분 적용해 보았습니다.

아래는 이번 작업 중에 가장 크게 한 고민인데요
도움이 될 수 있는 의견이 있으시다면 감사히 듣겠습니다.

getter를 의식적으로 사용하지 않도록 많이 신경쓰고 있는데요,
결과를 출력하는 view에서는 도저히 getter를 사용하지 않을 수가 없습니다.😭
데이터를 주고 받는 순수 프로퍼티 객체는 getter를 사용해도 된다고 알고 있지만
이번 사다리 게임과 같은 미션에서는 dto 역할도 희미해져 버려서
결국 도메인 클래스에 getter를 추가해 버리고 말았습니다.ㅠ😭

제 능력으론 getter없이는 안되겠다 생각되어서 그랬는데요,
혹시 getter없이도 결과를 출력할 수 있는 좋은 방법이 있을까요?

결과를 보여주는 부분 만드는 것도 많은 고민을 하게 하네요.

항상 꼼꼼한 리뷰 감사드립니다.🙇‍♂️😄

2021-04-15 16:37 UTC, yongdae commented
안녕하세요~ 재성님 😄

view에서 getter와 사용하지 않고 사다리 미션을 진행 할 수 있는 방법에대해서 질문을 주셨는데요.

규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.
이 규칙은 묻지 말고 시켜라 라는 의미를 내포하고 있습니다.

하지만 view가 화면을 그리는 것을 묻지 않고 시키게 된다면 
LineResults 아니면 Line 혹은 Point 이들 중 한 객체에게 그림을 그리라고 시켜야하는데
이는 화면에 대한 책임을 지게되기 때문에 맞지 않은 방법이 됩니다.

즉 이야기하신 것과 같이 DTO 혹은 VO를 사용해서
View를 위한 데이터를 담아 주고받아서 사용하는 방법 말고는 없습니다.

다만 조금 다른 관점에서 이야기한다면 get 이라는 접두사를 사용하지 않는 방법이 있습니다.
일반적으로 get 이라는 접두사는 객체가 가진 private 값을 준다는 의미를 지니지만,
get 접두사를 사용하지 않고 값을 전달해준다면 단순히 private 값을 준다는 의미는 없앨 수 있습니다.

2021-04-15 17:06 UTC, yongdae approved these changes
안녕하세요. 재성님 ~ :)

피드백도 잘 반영해주시고 많은 고민을 해주셨네요. 👍
수고하셨습니다. 😄

진행해주신 내용에는 큰 이견이 없어
2단계는 여기서 merge하도록 하겠습니다 ~

몇 가지 의견이 있어 피드백 드린 부분이 있으니
이 부분은 다음 단계에 같이 반영 부탁드리겠습니다. 🙇

질문은 [코멘트](https://github.com/next-step/java-ladder/pull/900#issuecomment-820570136)를 통해 답변을 드렸습니다!
그럼 다음 리뷰 요청을 기다리고 있겠습니다. 🔥🔥

2021-04-15 17:06 UTC, merged

2021-04-15 22:28 UTC, jaystar13 commented on src/main/java/ladder/domain/Point.java
> +    }
넵 이 부분을 고민하긴 했었는데요,
제가 처음에 설계한 부분중에 하나가
인터페이스를 사용하여 Point를 만들어 보자는 목적이 좀 있었어요.
아직 인터페이스 설계와 사용 경험이 많지 않아서 공부 목적도 있었고
혹시나 그럴일은 없겠지만
나중에 더 좋은 Point그리기 방법으로 변경할 수도 있을 거 같구요. ㅎㅎ

2021-04-15 22:33 UTC, jaystar13 commented on src/main/java/ladder/domain/Line.java
> +    public Line(List<Point> points) {
아마 자동차 레이싱 때 들었던 포비님 강의였던거 같은데요,
제가 기억하기로는

1. 해당 API를 사용하는 개발자를 위해 생성자는 많이 제공해도 무방하다.
2. 테스트를 위한 생성자를 만드는 것도 괜찮다.

이런 내용을 들었던 기억이 있어서
적용을 해 보았습니다. :)
너무 오래전(?) 강의라 사실 제 기억이 정확하지 않을수도 있어요.ㅠㅠ

2021-04-17 07:22 UTC, yongdae commented on src/main/java/ladder/domain/Line.java
> +    public Line(List<Point> points) {
포비님이 강의를 통해서 이야기를 하셨다면 크게 문제 되는 부분은 없다고 생각합니다. :)

다만 지금 만드신 구조에서 이 피드백을 반영한다면 개선 될 수 있는 구조가 있어요.
단순히 테스트에서만 사용하기 때문에 코드를 지양해야한다고 이야기 드린 부분은 아니니 반영해보시면 어떨까요?