[사다리타기 - 4단계] 코드 리뷰 요청
next-step/java-ladder pull request #917
Opened 2021-04-15 03:48 UTC by oper912

안녕하세요 리뷰어님!

사다리 마지막단계 코드리뷰 요청드립니다 :smile: :+1:

2021-04-15 12:23 UTC, karian7 requested changes
안녕하세요! 순호님.
지난 PR 의 피드백까지 모두 반영해 주셨습니다. 👍👍

객체간 책임들이 잘 나눠져 있어서 더 개선할 점은 보이지 않습니다. 💯 
다만, 이대로 끝내긴 아쉬워서 이전 단계에서 구현하신 view 쪽 구현을 조금 더 개선해 보면 좋겠습니다.
수정후 다시 요청주시면 마무리 하도록 하겠습니다~

2021-04-15 12:23 UTC, karian7 commented on src/main/java/ladder/view/InputView.java
> +        System.out.println("참여할 사람 이름을 입력하세요. (이름은 쉼표(,)로 구분하세요)");
```suggestion
        System.out.printf("%n실행 결과를 입력하세요. (결과는 쉼표(,)로 구분하세요)%n");
```
intellij 를 사용하신다면 코드 개선에 대한 지원을 받으실 수 있습니다. 😀 
![Capture 2021-04-15 오후 9 19 31](https://user-images.githubusercontent.com/247208/114867900-4816ba80-9e30-11eb-8119-15eddb7c78e1.jpg)

2021-04-16 13:47 UTC, oper912 commented on src/main/java/ladder/domain/ExecutionResultMap.java
> +                                executionResultMap.add(persons.getPerson(index), ladderExecutionResults.getExecutionResult(index)),
감사합니다! 지속적으로 개선할 수 있는 부분 말씀해주셔서 너무 좋았습니다

2021-04-16 14:21 UTC, karian7 approved these changes
안녕하세요! 순호님.
사다리타기 마지막 미션까지 완주하신것 축하드립니다. 🎉 
많은 피드백을 놓치지 않고 검토하고 구현하는데 많은 어려움이 있으셨을것 같습니다. 그만큼 이번 미션에서 스트림과 함수형 프로그래밍에 대해 많은 경험이 되셨길 바랍니다.
마지막 볼링미션도 완수하시길 빌겠습니다. 🎉🎉

2021-04-16 14:21 UTC, karian7 commented on src/main/java/ladder/view/ResultView.java
> +                    System.out.printf(String.format("%n%s%s", ladderLineStringString, ladderLineString));
람다식 내부가 길어지면 적절히 extract method 를 해주면 가독성이 올라갑니다.

2021-04-16 14:21 UTC, karian7 commented on src/main/java/ladder/view/ResultView.java
> +        System.out.printf(String.format("%n%s%n", executionResultString));
```suggestion
        System.out.printf("%n%s%n", executionResultString);
```
이게 맞을것 같습니다. 😀

2021-04-16 14:21 UTC, karian7 commented on src/main/java/ladder/domain/ExecutionResultMap.java
> +    public static ExecutionResultMap of(final Persons persons, final LadderExecutionResults ladderExecutionResults) {
이렇게도 구현할 수 있을것 같습니다. 구현에는 다양한 방법이 있으니 비교하면서 더 나은 방식을 찾아가 봅시다 😀 
```java
    public static ExecutionResultMap of(final Persons persons, final LadderExecutionResults ladderExecutionResults) {
        var result = IntStream.range(0, persons.getCountOfPerson())
                .mapToObj(mapper(persons, ladderExecutionResults)::apply)
                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));

        return new ExecutionResultMap(result);
    }

    private static Function<Integer, Map.Entry<String, String>> mapper(
            Persons persons,
            LadderExecutionResults ladderExecutionResults
    ) {
        return (index) -> new SimpleEntry<>(persons.nameOf(index),
                                            ladderExecutionResults.getExecutionResult(index));
    }
```

2021-04-16 14:21 UTC, merged

2021-04-16 14:43 UTC, karian7 commented on src/main/java/ladder/domain/ExecutionResultMap.java
> +                                executionResultMap.add(persons.getPerson(index), ladderExecutionResults.getExecutionResult(index)),
다른 구현방법에 대해서도 추가해 놓았습니다. 😀 
https://github.com/next-step/java-ladder/pull/917#discussion_r614872727