Step3리뷰요청드립니다.
next-step/java-ladder pull request #945
Opened 2021-04-21 13:52 UTC by cptbong

게임실행을 진행하면서...
보니까 사다리를 잘못 그리고 있었던거 같아요.
|-|-| |
|  | |-|
위처럼 가로로 연속되는게 있었고, 이거를 어찌 처리하나 많이 고민하다가...
_아 애초에 잘못 그렸구나_라고 생각되어 이를 수정하고 다시 진행했습니다.
결국 왼쪽? 오른쪽? 이것만 선택하면 되는거구나... 했는데, 맞죠?
Lines클래스의 start메서드에서 이걸 처리하는데, 지금 제가 봐도 좀 그런데...
이 외에도 문제가 있을까해서 리뷰 요청드립니다.
계속 귀찮게 해드리네요. 😭

2021-04-21 13:53 UTC, neojjc2 commented
#tag @neojjc2

2021-04-22 03:55 UTC, neojjc2 requested changes
안녕하세요 일균님 🙇 

리뷰 많이 기다렸습니다 😄 
3단계 구현 잘해주셨습니다 💯 

이렇게 꾸준히 차근 차근 잘 따라와 주셔서 너무 감사합니다 
한번에 많은 것들을 리팩토링 하려고 하지 마시고 하나씩 하나씩 
법칙을 적용해가면서 개선해나가면 되니 
너무 조급해 하시거나 혹은 미안해 하지 않으셔도 됩니다 (전혀 아무렇지도 않고 오히려 좋습니다 😄 )

너무 많은 의견을 드리면 오히려 혼동을 드릴 수 있을 것 같아서
일단 method 들이 한 번에 한 가지 일만 할 수 있도록 먼저 개선 해보시면 좋을 것 같습니다 🙇 

그에 대한 의견 드렸으니 확인해주시고 
다시 재 리뷰 요청 해주시면 감사하겠습니다 😄 

지치지만 않으시면 됩니다 🔋 
그럼 재 리뷰 요청 기다리고 있겠습니다 🔥

2021-04-22 03:55 UTC, neojjc2 commented on src/main/java/nextstep/LadderGameClient.java
> +        resultView.print(winners[winner]);
요구사항을 보시면 사다리 하단에 결과가 출력 되도록 되어 있습니다 😄 
그리고 `all` 을 입력하면 모든 결과를 볼 수 있는 부분도 추가 되어야 할 것 같습니다 🙇 

확인 한번 부탁 드리겠습니다 🙇

2021-04-22 03:55 UTC, neojjc2 commented on src/main/java/nextstep/model/Lines.java
> +        while (index < this.lines.size()) {
고민 하셨던 부분이네요 😄 
일단 너무 어렵게 생각하지 마시고 `method`로 추출 먼저 부탁 드리겠습니다 😄 
지금 `start`라는 `method`가 하고 있는 일이 너무 많습니다 🤔 

**"하나의 `method`가 하나의 일만 하도록 한다"** 라는 기준만 생각하시고 
여러 개의 세부 `method`로 일단 나누고 호출하도록 하는 것 부터 시작해보시는 건 어떨까요?? 🔥 🔋

2021-04-22 03:55 UTC, neojjc2 commented on src/main/java/nextstep/model/OnlineLadder.java
> +        int playerIndex = this.filter(whoWinner);
예외 처리 좋습니다 👍 

추가적으로 의견 드리자면 `index` 확인이 아닌 `Optional`을 활용해보시는건 어떨까요?? 
`Player`객체를 바로 반환 받을 수도 있을 것 같습니다  😄 

도움 되실만한 내용 공유 드립니다 
> https://www.daleseo.com/java8-optional-after/

2021-04-22 03:55 UTC, neojjc2 commented on src/main/java/nextstep/model/OnlineLadder.java
> +    public int filter(Player playerName) {
이미 일급컬렉션에 `filter`라는 이름이 있으니 `findByPlayerName`이나 `findByPlayer` 등의 
좀 더 가독성 있는 이름이 더 좋을 것 같습니다 😄

2021-04-22 03:55 UTC, neojjc2 commented on src/main/java/nextstep/model/Player.java
> +        this.player = name;
`Players`에 있는 이름의 길이를 검증하는 부분이 여기에 있다면 
객체의 역할과 책임 관점에서 좀 더 분명해질 것 같습니다 😄 

이 부분 개선 검토 부탁 드리겠습니다 🙇

2021-04-22 03:55 UTC, neojjc2 commented on src/main/java/nextstep/model/Players.java
> +    public int filter(Player player) {
자동차 미션 때 해오셨던 
> 메소드를 작은 단위로 잘 분리했는가?(인덴트를 1로 잘 유지했는가? 포함)

법칙을 한번 적용하여 개선 부탁 드립니다 😄

2021-04-25 08:34 UTC, cptbong commented
안녕하세요.

**고민 하셨던 부분이네요 😄
일단 너무 어렵게 생각하지 마시고 method로 추출 먼저 부탁 드리겠습니다 😄
지금 start라는 method가 하고 있는 일이 너무 많습니다 🤔

"하나의 method가 하나의 일만 하도록 한다" 라는 기준만 생각하시고
여러 개의 세부 method로 일단 나누고 호출하도록 하는 것 부터 시작해보시는 건 어떨까요?? 🔥 🔋**

-> 여기가 가장 고민됬었습니다.
처음에는 말씀하신데로 method추출을 하다가... 뭔가 계속 기대한값이 아니라서 확인해보니 메서드에서 shallow copy때문이였구요.
이를 해결하려고, 일단 이너클래스로 안에 Games를 만들었다가 **왜 이너클래스?**라는 생각이 들어 클래스로 추출해서 진행해봤습니다.
명칭이 딱히 떠오르지 않아 Games라고 했는데, 잘 된건지 모르겠네요.

2021-04-26 03:48 UTC, neojjc2 approved these changes
안녕하세요 일균님 🙇 

그래도 요청사항 반영해주시고 많이 고민해주셔서 정말 감사합니다 🙇 
그리고 포기 안하시고 잘 따라와주신 것도 감사드립니다 😄 

그래도 많은 부분 개선이 되셨는데, 
본격 마지막 단계 하실 준비가 되신 것 같습니다 😄 

다음 단계 진행하시면서 
지금 고민하신 부분들을 힌트를 통해 어떻게 개선할 수 있는지
그리고 지금 일균님이 작성하셨던 부분이 어떻게 바뀔 수 있는지에 대해
경험 해보시면 좋을 것 같습니다 🙇 

바로 `merge` 하겠습니다 🙇 
마지막 단계 진행 부탁 드립니다 🔥 🔥 🔥 🔥 🔥

2021-04-26 03:48 UTC, merged