[사다리 게임 - 3단계] 리뷰 요청드립니다.
next-step/java-ladder pull request #953
Opened 2021-04-24 14:44 UTC by dailyworker

안녕하세요 멘토님 

항상 DM으로 물어봐주신 질문에 잘 피드백 해주시고, 이번 DM같은 경우에는 어떻게 보면 제가 제대로 체크를 못했던 부분도 있어서 

번거롭게 해드리는거같아서 무척 죄송스러웠습니다 😭 

이번 단계는 PR전에 DM으로 여러 이야기를 나눈거같아서 구현 상에서 질문 드릴 사항은 몇개 없어보입니다. 

1. `Award` 의 `member` 인원 수 의존성 문제

Award의 개수가 member 인원 수와 같은지 validate 처리를 위하여 생성자에 멤버 수를 받게 처리하였고, 이 때문에 `Controller` 에서 다음과 같이 처리를 하였습니다. 
 
```.java
//ladderController.java
private LadderBoard initPhase() throws IOException {
    Members members = getMembers();
    Award award = getAward(members.size());
    Ladder ladder = getLadder(members);
    return new LadderBoard(ladder, award);
  }

private Award getAward(int size) throws IOException {
    return new InputView().enteredAward(size);
  }

//InputView.java
public Award enteredAward(int size) throws IOException {
    System.out.println("실행 결과를 입력하세요. (결과는 쉼표(,)로 구분하세요)");
    return Award.createPrizes(reader.readLine()
        .split(","), size);
  }
```

위와 같이 의존성이 생기는데 이 부분을 해결할 방법이 있을까요? 

항상 좋은 피드백과 인사이트를 주셔서 감사합니다! 

이번 주도 좋은 주말 보내시기 바랍니다!!

2021-04-25 07:19 UTC, karian7 requested changes
안녕하세요! 수웅님.

고민이 많으셨던만큼 결과가 잘 나온것 같습니다. 👍👍 
본문에 주신 질문은 라인 댓글로 남겼고요, DM 으로 피드백을 나눠서 크게 바꿀만한 부분은 없지만 그낭 넘어가기 아쉬우니 몇가지 추가로 피드백 드렸습니다.ㅎㅎ

검토해주시고 다시 요청해주시면 다음 단계로 넘어가겠습니다~

2021-04-25 07:19 UTC, karian7 commented on src/main/java/nextstep/laddergame/domain/Award.java
> +  private final List<Name> prizes;
결과도 `Name` 으로 추상화 하셨군요. 👌

2021-04-25 07:19 UTC, karian7 commented on src/main/java/nextstep/laddergame/domain/Award.java
> +  public Award(List<Name> prizes, int memberSize) {
> Award 의 member 인원 수 의존성 문제

여기서 `memberSize` 는 prizes 의 갯수를 검증하기 위해 입력받은 값이니 `expectedSize` 정도면 어떨까요?

2021-04-25 07:19 UTC, karian7 commented on src/test/java/nextstep/laddergame/domain/LadderBoardTest.java
> +    assertAll(
👍

2021-04-25 07:19 UTC, karian7 commented on src/main/java/nextstep/laddergame/domain/LadderBoard.java
> +                .prize(index)
`keyMapper` 와 `valueMapper` 를 extract method 해서 가독성을 높여보면 좋겠습니다.

2021-04-25 07:19 UTC, karian7 commented on src/main/java/nextstep/laddergame/LadderController.java
> +        }
2단계 들여쓰기가 생겼네요. 1단계로 낮춰봅시다 😀 
참고로 전체 결과를 `while` 문 안에서 출력하지 않는 방법도 있어요. 😉

2021-04-25 07:19 UTC, karian7 commented on src/main/java/nextstep/laddergame/domain/Award.java
> +        .collect(ArrayList::new, ArrayList::add, ArrayList::addAll);
이부분은 `Collectors.toList()` 를 활용해 봅시다.ㅎㅎ

2021-04-25 10:32 UTC, dailyworker commented on src/main/java/nextstep/laddergame/domain/Award.java
> +        .collect(ArrayList::new, ArrayList::add, ArrayList::addAll);
수정하였습니다!!

2021-04-25 10:33 UTC, dailyworker commented on src/main/java/nextstep/laddergame/LadderController.java
> +        }
지역변수를 활용하여 처리하였습니다!

2021-04-25 10:33 UTC, dailyworker commented on src/main/java/nextstep/laddergame/domain/LadderBoard.java
> +                .prize(index)
좋은 인사이트를 주셔서 감사합니다. 메서드 분리하여 해결하였습니다

2021-04-25 10:33 UTC, dailyworker commented on src/main/java/nextstep/laddergame/domain/Award.java
> +  public Award(List<Name> prizes, int memberSize) {
넵 시그니처 변경하였습니다

2021-04-26 01:07 UTC, karian7 approved these changes
> Award 의 member 인원 수 의존성 문제

위 질문을 저는 `Award` 객체가 `memberSize` 를 의존하지 않으면 좋겠다는 생각이신것으로 이해했어요. 그래서  https://github.com/next-step/java-ladder/pull/953#discussion_r619764343 로 피드백 드렸는데요, 정리하면 `member` 라는 용어를 굳이 `Award` 에서 알 필요가 없으니 해당 객체내에서 의미있는 `expectedSize` 로 rename 하는게 어떤가 하는 의견이었습니다.
그런데 `createPrizes` 같은 메소드는 rename 되어 있지 않아서 혹시 제가 수웅님이 고민하시는 부분을 잘못 캡처한것 아닐까 하는 생각이 드네요. 이부분 확인 부탁드립니다. 😀 

그밖에 이번 단계는 마무리 해도 될 것 같습니다. 다음 단계는 [피드백 동영상](https://edu.nextstep.camp/s/ApJ4Ca71/ls/rtA3Dyuk)을 보시고 리팩토링 하는 과정입니다. 그동안 수웅님이 설계상 고민되었던 부분들을 많이 풀어줄 수 있으리리 기대합니다.
그럼 다음 리뷰에서 만나요~

2021-04-26 01:07 UTC, karian7 commented on src/main/java/nextstep/laddergame/domain/LadderBoard.java
> +            this::prizeName
키와 값이 무엇인지 알게 되었습니다. 👍

2021-04-26 01:07 UTC, merged