사다리 1단계 리뷰 요청합니다.
next-step/java-ladder pull request #956
Opened 2021-04-25 16:07 UTC by nhs0912

생각보다 사다리 출력하는게 너무 힘들었네요 ㅠㅠㅠ

아직 사다리게임 클래스는 구현은 안하고 놔두었습니다. 

리뷰 부탁드려요~

2021-04-26 08:50 UTC, dbeod2 requested changes
안녕하세요! 
본격적으로 사다리 미션을 시작하셨네요! 
수고하셨습니다 👏🏻👏🏻👏🏻

몇가지 고민해보면 좋을 것 같아서 코멘트 남겨두었습니다. 
확인 부탁드립니다. 🙇🏻‍♀️

2021-04-26 08:50 UTC, dbeod2 commented on README.md
> +#Class List
요구사항 정리 💯

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/LadderMain.java
> +        LadderGame ladderGame = new LadderGame(users, ladderHeight);
선언은 되어있는데 사용하지 않고있네용

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Ladder.java
> +public class Ladder {
일급콜렉터를 사용하신 것 같은데..

멤버변수에 대한 접근 제어자가  default인데 이유가 있을까요? 누락하신걸까요?
생성자가 제대로 된 역할을 하지 못하고 있는 것같은데 확인 부탁드립니다!

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/LadderGame.java
> +
사다리 게임 객체는..... 선언만 하시고 제대로 사용되는 부분이 없는 것같은데 확인 부탁드립니다 ㅠ.ㅠ

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Line.java
> +    }
view 코드가 domain에 포함되어있네요! 
프러덕션코드와 ui코드는 분리해주시길바랍니다 :)

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Line.java
> +    private int pointCount = 0;
따로 초기화는 안해주셔도 될 것같습니다!

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/RandomNumber.java
> +    private static final int makableLadderNumber = 4;
상수작성 규칙을 지켜주세요 :)

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/RandomNumber.java
> +        return new Random().nextInt(10);
10을 의미있는 수로 만들어주는게 어떨까요?

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Users.java
> +    public List<User> userList() {
미사용 메서드는 과감하게 제거해주세요!

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Users.java
> +        if (this.userList.stream().map(User::name).distinct().count() != userList.size()) {
값에 대한 검증 잘해주셨습니다.

의견을 드리자면 현재 조건문에 있는 코드가 읽기 어렵네요 .
읽기쉽게 코드를 수정해보시는건 어떠실까요?

this.userList.stream().map(User::name).distinct().count() <- for문안에 if가 들어가 있어서 2depth가 되었네용! 
프로그래밍 요구사항 중 2depth를 넘지 않도록 한다는 요구사항이 있습니다.
확인 부탁드립니다!

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Users.java
> +    public int userCount() {
미사용 코드입니다.
추후 사용을 위해 만들어두신 걸까용? 🤔

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/nextstep/optional/User.java
> +                .filter(age-> age>=MIN_FIND_AGE && age <=MAX_FIND_AGE)
이전 피드백 반영 👍🏻

2021-04-26 08:50 UTC, dbeod2 commented on src/test/java/ladder/domain/LadderTest.java
> +
ladderTest인데 테스트가 부족한 것 같습니다 ㅠ.ㅠ

2021-04-26 08:50 UTC, dbeod2 commented on src/test/java/ladder/domain/LineTest.java
> +        int countOfPerson = 4;
테스트에 대한 검증결과를 확인 할 수가 없네용! 
검증부탁드립니다 : )

2021-04-26 08:50 UTC, dbeod2 commented on src/test/java/ladder/domain/NameTest.java
> +
참여자 테스트 💯💯💯

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Line.java
> +        int resultRandomNumber = randomNumber.randomNumber();
랜덤 데이터가 프러덕션 코드 안으로 들어가게되면 테스트하기 힘들어지는데용! 
어떻게 하면 테스트하기 쉬운 구조가 될 수 있을지 고민해보시면 어떠실까요? 🤔

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Line.java
> +            drawOneLineLadder(i);
ui코드와 domain코드는분리해주시길 바랍니다 :)

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Name.java
> +    private String name;
원시값 포장 👍🏻👍🏻

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Name.java
> +        this.name = name;
값에 대한 유효성 검사는 값을 주입하기 전에 이루어져야 할 것 같습니다.

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Name.java
> +        if (name == null || name.length() <= LIMIT_MIN_LENGTH) {
String타입의 값이 null인 경우 (.)으로 바로 검색하면 값 자체가 null이기 때문에 NullPointerException이 발생하게 됩니다. 

현재 작성해주신 코드상으로는 name이 null일 때, 첫번째 검증에서 name이 null이기 때문에 exception이 발생하며, 
작성해주신 두번째 조건에 대해 검증을 못하게 됩니다. 

정확한 검증을 위해 name에 대한 null체크 먼저 해보시는게 어떠실까요?

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Line.java
> +    private List<Boolean> points = new ArrayList<>();
Boolean과 boolean의 차이는 무엇이며, 박싱타입을 사용하신 이유가 무엇인가용?

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/Line.java
> +        return index % 2 == 0 ? true : false;
return해주시는 값 자체가 boolean값이네용! 
아래처럼 표현이 가능 한 것 같습니다 :) 
```suggestion
       return index % 2 == 0;
```

2021-04-26 08:50 UTC, dbeod2 commented on src/main/java/ladder/domain/User.java
> +public class User {
원시값 포장을 하셨는데  user로 한번 더 감싸주신 이유가 무엇일까요 ?

2021-05-05 05:33 UTC, nhs0912 commented on src/main/java/ladder/domain/Line.java
> +    private List<Boolean> points = new ArrayList<>();
Boolean는 Wrapper class이고 boolean은 Primitive 자료형입니다.  둘의 차이는 Boolean는 null값이 들어갈 수가 있고, boolean은 true, false값만 저장이 가능합니다. null check가 필요하지 않는 경우 boolean을 사용하는 것이 속도측면에서 좋아요! 그리고 여기서는 List<>선언하고서 제네릭 부분에는 ObjectElement가 들어가야하기 때문에 Boolean으로 선언하였습니다 :)

2021-05-05 05:41 UTC, nhs0912 commented on src/main/java/ladder/domain/Name.java
> +        if (name == null || name.length() <= LIMIT_MIN_LENGTH) {
그렇네요! 너무 한꺼번에 검증하려다보니 한가지가 빠지게 되네요! 이러한 검증은 분리하는 것이 더 좋겠네요! ㅋㅋㅋ

2021-05-05 05:42 UTC, nhs0912 commented on src/main/java/ladder/domain/Name.java
> +        this.name = name;
저 둘의 순서가 어떤것이 더 좋을까 고민을 했는데 왜냐하면 값을 먼저 주입하면 따로 파라미터를 안넣어도 되고 그 전에 체크를 하면 파라미터를 만들어야해서요! 
근데 생각해보니 로직상에서는 값 주입전에 하는 것이 더 좋겠네요. 우리가 건물 출입할때도 먼저 출입증 검증부터 하고 들어가니깐요 ㅋㅋㅋ

2021-05-05 05:55 UTC, nhs0912 commented on src/main/java/ladder/domain/Users.java
> +    public int userCount() {
네 추후 사용을 위해서 한건데 이런 코드는 지금 단계에서는 추후에 만드는게 더 좋을거 같네요 ㅋㅋㅋ 삭제 하겠습니다.

2021-05-05 06:19 UTC, nhs0912 commented on src/main/java/ladder/domain/Users.java
> +        if (this.userList.stream().map(User::name).distinct().count() != userList.size()) {
너무 길어가지고 변수로 따로 빼는게 가독성이 더 좋겠네요! 

2 depth인지는 몰랐었네요! ㅋㅋㅋ 따로 변수로 받아가지고 하면 1depth로 처리 가능하겠네요!

2021-07-02 03:44 UTC, nhs0912 commented
안녕하세요! 과정이 끝나가지고  포비님에게 PR보내려고 하는데...유라님에게 갔네요 ㅠㅠㅠ 
어떻게 변경하면 되는지 좀 알아봐야겠네요 ㅠㅠ 

이 과정 덕분에 직장에서 리팩토링을 레거시 시스템에 조금씩 녹이고 있습니다. 직장에서 개발할 것이 많아서 바빴네요 ㅠㅠ 
그래도 포비님에게 약속한대로 끝까지 과정을 끝내보려고 다시 시작해보려고 합니다. 물론 포비님은 모르는 혼자만의 약속이지만 ㅋㅋㅋㅋㅋㅋ 

조금씩 천천히 제대로 끝까지 완주할게요!

2021-07-05 03:39 UTC, javajigi approved these changes
피드백 반영 잘 했네요. 👍 
다음 단계가 사다리 타기 구현의 핵심 기능인 만큼 꼭 도전해 볼 것을 추천합니다.

2021-07-05 03:39 UTC, merged