4단계 - 사다리(리팩토링)
next-step/java-ladder pull request #960
Opened 2021-04-28 10:48 UTC by djoon

안녕하세요 용대님
4단계 리뷰요청 드립니다~

힌트로 주어진 설계보다는 기존 설계에서 좀 바꿔보았습니다.

3단계 이후 텀이 굉장히 길었는데, 제가 했던 설계가 잘 기억나지 않아서... 😢
기존 설계 위에 용대님 피드백을 최대한 반영해가면서 다시 재구성해보았습니다.
(객체에 Nx 접두어가 붙은 건 그런 이유에서... ㅎㅎ;;)

기타 개선해야할점 있으면 의견 부탁드리겠습니다~

2021-04-28 17:47 UTC, yongdae requested changes
안녕하세요. 동준님 :)

이전 단계에서 전달드린 피드백을 잘 반영해주셨네요. 👍 
4단계 힌트도 잘 반영해주셨구요!

진행해주신 내용에 대해 몇가지 의견 남겨놓았습니다~
확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🔥🔥

2021-04-28 17:47 UTC, yongdae commented on src/main/java/nextstep/ladder2/Controller.java
> +        NxPlayers players = new NxPlayers(Arrays.asList(info.get(INPUT_PLAYERS_NAME).split(",")));
`Arrays.asList(info.get(INPUT_PLAYERS_NAME).split(","))`

이 부분을 함수로 분리해보면 좋을 것 같아요. :)

2021-04-28 17:47 UTC, yongdae commented on src/main/java/nextstep/ladder2/Controller.java
> +        NxPrizes prizes = new NxPrizes(Arrays.asList(info.get(INPUT_PRIZES_NAME).split(",")));
`Arrays.asList(info.get(INPUT_PRIZES_NAME).split(","))`

이 부분도요!

2021-04-28 17:47 UTC, yongdae commented on src/main/java/nextstep/ladder2/Controller.java
> +        NxLadder ladder = new NxLadder(Integer.parseInt(info.get(INPUT_LADDER_HEIGHT)),
`Integer.parseInt(info.get(INPUT_LADDER_HEIGHT)`

이 내용도 함수로 정의해보면 어떨까요? 🤔

2021-04-28 17:47 UTC, yongdae commented on src/main/java/nextstep/ladder2/domain/NxBridge.java
> +    private final boolean enabled;
이 부분은 힌트에서 주어진 Direction을 적용해보면 좋을 것 같아요. 😄 

`힌트로 주어진 설계보다는 기존 설계에서 좀 바꿔보았습니다.`
의견 주신 부분은 확인했습니다.

다만 Direction 객체는 사다리 미션에서 중요한 역할을 하는 부분이니 학습을 위해서도
적용해보시는 것을 권장드려요. 😄

2021-04-28 17:47 UTC, yongdae commented on src/main/java/nextstep/ladder2/domain/NxLadder.java
> +    public NxLadder(int height, int countOfPerson, LadderBuilder ladderBuilder) {
이전보다 사다리를 만드는 방법이 간결해지고 읽기도 좋아졌네요. 👍

2021-04-28 17:47 UTC, yongdae commented on src/main/java/nextstep/ladder2/domain/NxLadder.java
> +            updatedIndex = bridge.movePosition(updatedIndex);
방식을 변경해보면 어떨까요? 🤔

```suggestion
            updatedIndex = line.movePosition(updatedIndex);
```

이렇게 코드를 변경해도 동작 할 수 있게 해보면 좋을 것 같아요. :)

2021-04-28 17:47 UTC, yongdae commented on src/main/java/nextstep/ladder2/domain/builder/RandomBuilder.java
> +public class RandomBuilder implements LadderBuilder {
사다리를 만드는 부분을 별도의 인터페이스를 분리해 구현해주셨네요. 👍

2021-04-28 17:47 UTC, yongdae commented on src/main/java/nextstep/ladder2/domain/prize/NxPrizes.java
> +public class NxPrizes {
NxPrizes의 테스트를 만들어보면 어떨까요?

사다리 결과를 확인하는 테스트를 만들 수 있을 것 같아요. :)

2021-05-02 14:56 UTC, djoon commented on src/main/java/nextstep/ladder2/Controller.java
> +        NxPlayers players = new NxPlayers(Arrays.asList(info.get(INPUT_PLAYERS_NAME).split(",")));
InputView에서 처리하도록 변경하였습니다

2021-05-02 14:57 UTC, djoon commented on src/main/java/nextstep/ladder2/Controller.java
> +        NxPrizes prizes = new NxPrizes(Arrays.asList(info.get(INPUT_PRIZES_NAME).split(",")));
이부분도 InputView 메소드에서 처리하도록 변경하였습니다.

2021-05-02 14:57 UTC, djoon commented on src/main/java/nextstep/ladder2/Controller.java
> +        NxLadder ladder = new NxLadder(Integer.parseInt(info.get(INPUT_LADDER_HEIGHT)),
InputView 내에서 처리 하도록 변경했습니다.

2021-05-03 05:54 UTC, djoon commented on src/main/java/nextstep/ladder2/domain/NxBridge.java
> +    private final boolean enabled;
Direction 객체를 반쪽(?)만 적용해보았습니다....

기존 구현에선 RandomBuilder에서 boolean List로 설계도(?)를 그려주고, 그 과정에서 예외 케이스를 걸러주는데

Direction 객체를 적용하면 first(Random().nextBoolean()) -> next() -> ... -> next() -> last() 로만 하면
자동으로 적합한 사다리를 그려줘서

제대로 리팩토링을 한다면, RandomBuilder가 boolean List를 생성할 필요가 없어지겠네요.

그러나, 기존 구현에서 사다리를 그려주는 것도 boolean List를 사용하고 있어서 절충안(?) 성격으로 구현해보았습니다...

2021-05-03 05:55 UTC, djoon commented on src/main/java/nextstep/ladder2/domain/NxLadder.java
> +            updatedIndex = bridge.movePosition(updatedIndex);
관련 내용 반영하였습니다.

2021-05-03 06:15 UTC, djoon commented on src/main/java/nextstep/ladder2/domain/prize/NxPrizes.java
> +public class NxPrizes {
테스트 추가하였습니다.

2021-05-03 11:47 UTC, yongdae approved these changes
안녕하세요. 동준님~ :)

피드백을 잘 반영해주셨네요. 👍 
마지막으로 참고하시면 좋을 것 같아 의견드린 부분 있으니 확인만 부탁드려요~

그럼 이만 여기서 사다리 미션을 마무리해도 좋을 것 같습니다!!
사다리 미션을 완주하시느라 고생 많으셨어요!! 🎉

동준님께 드린 피드백이 조금이나마 도움이 되었으면 하는 바램입니다 :)
그동안 고생 많으셨습니다 🙇

2021-05-03 11:47 UTC, yongdae commented on src/test/java/ladder2/NxLadderTest.java
> +        ResultView.printLadderResult(controller.convertToLadderViewDto(ladder.getLines()), 4);
Controller의 convertToLadderViewDto 함수를 사용하지 않고
미션을 수행 할 수 있으면 좋을 것 같네요. :)

2021-05-03 11:47 UTC, yongdae commented on src/main/java/nextstep/ladder2/Controller.java
> +        }
ResultView가 가지고 있는 static 키워드를 사용하지 않고 해보셔도 좋을 것 같습니다~

2021-05-03 11:47 UTC, yongdae commented on src/main/java/nextstep/ladder2/domain/NxBridge.java
> +    }
여기서 사용하는 1 이라는 값도 상수로 치환해서
이름에 의미를 주어 사용하면 좋을 것 같아요. :)

2021-05-03 11:48 UTC, merged