2단계 - 사다리(생성)
next-step/java-ladder pull request #984
Opened 2021-08-03 13:58 UTC by Hyune-c

스트림과 람다는 어느정도 익숙하게 쓴 것 같은데, 아직 FP 는 어떻게 써야되는지 잘 안보입니다.

많은 피드백 부탁드립니다.

2021-08-03 14:03 UTC, Hyune-c commented on src/main/java/nextstep/ladder/controller/LadderGameController.java
> +        ResultView.printLadders(lines);
처음의 의도는 `ResultView 로 Dto 를 만들어 넘기자` 였습니다.
PlayerNames 는 쉽게 했는데, Ladder 는 잘 안되었습니다.

Lines 안에 Line 이 있고, 그 안에 List<Boolean> 이 있는 형태이기 때문에 LinesDto 를 만들고 그 안에 LineDto 를 만들면 가능한 것 같지만, 뭔가 지저분하게 되는 것 같아서 피드백을 받고 싶어 현 상태를 유지했습니다.

2021-08-03 14:03 UTC, Hyune-c commented on src/main/java/nextstep/ladder/view/InputView.java
> +    };
요구 사항에는 없지만 FP 를 접목해볼겸 입력 편의 메소드를 만들었습니다.
애플리케이션을 실행시키고 입력 값이 없이 엔터를 치면 디폴트로 5명의 사용자와 10개 높이의 사다리를 만듭니다.

2021-08-03 14:03 UTC, Hyune-c commented on src/main/java/nextstep/ladder/view/ResultView.java
> +    }
지금 짠 코드에서 이 부분이 제일 맘에 안들지만, 뾰족한 개선법을 찾지 못했습니다..

2021-08-03 15:08 UTC, JunilHwang requested changes
안녕하세요 병현님! 사다리 생성 미션 잘 진행해주셨네요 👍 
일단 DTO는  병현님이 말씀하신 것 처럼 `List<List<Boolean>>` 형태로 변환해서 넘겨주면 좋을 것 같아요! 귀찮더라도 필요한 과정이라고 생각합니다 ㅎㅎ

그리고 미션을 진행하다보면 결국 세로줄이 아닌 가로줄로 만들어야 하는데..
이왕 하는 김에 이번 단계에서 해보면 어떨까요?

2021-08-03 15:08 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/LineExistsGenerator.java
> +}
strategy로 만들어주면 테스트할 때 용이하지 않을까요?

2021-08-03 15:08 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Lines.java
> +        return lines;
여기도 stream을 사용해주면 어떨까요?

2021-08-03 15:08 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Lines.java
> +        return lines;
`return new Lines(height, lines);`을 반환할 수 있도록 해주면 좋을 것 같아요!

2021-08-03 15:08 UTC, JunilHwang commented on src/main/java/nextstep/ladder/view/InputView.java
> +    };
순간 java가 아니라 js인줄 알았네요 ㅎㅎ
학습을 위한 시도 같아서 좋습니다 👍

2021-08-03 15:08 UTC, JunilHwang commented on src/main/java/nextstep/ladder/view/InputView.java
> +    }
앞선 리뷰처럼 List로 변환하지 말고 Domain에 그대로 넘겨주세요! 
`"pobi,honux,crong,jk,hyune"` 이러한 형태의 input도 Domain에서 수용할 수 있도록 만들면 좋을 것 같아요.

2021-08-03 15:08 UTC, JunilHwang commented on src/main/java/nextstep/ladder/view/ResultView.java
> +            }).collect(Collectors.joining(LINE_DELIMITER)) + LINE_DELIMITER;
```suggestion
            .map(e -> e ? LINE_FLAG : LINE_BLANK)
            .collect(Collectors.joining(LINE_DELIMITER)) +
            LINE_DELIMITER;
```
이럴땐 삼항연산자를 사용해도 괜찮을 것 같습니다.
혹은 아예 메소드로 분리하는 방법도 있어요!

2021-08-03 15:22 UTC, Hyune-c commented on src/main/java/nextstep/ladder/view/ResultView.java
> +            }).collect(Collectors.joining(LINE_DELIMITER)) + LINE_DELIMITER;
네 저도 실무라면 삼항 연산자를 썻을 것 같은데, 이전 리뷰에서 삼항 연산자도 else 라고 하셔서 사용을 안했네요 ㅠ

2021-08-03 15:45 UTC, Hyune-c commented on src/main/java/nextstep/ladder/domain/LineExistsGenerator.java
> +}
전체 로직을 바꾸면서 같이 해보겠습니다.

2021-08-03 15:45 UTC, Hyune-c commented on src/main/java/nextstep/ladder/domain/Lines.java
> +        return lines;
전체 로직을 바꾸면서 같이 해보겠습니다.

2021-08-03 16:55 UTC, Hyune-c commented on src/main/java/nextstep/ladder/domain/Line.java
> +    }
이 부분도 stream 으로 개선하고 싶은데 방법이 떠오르지 않습니다.

- 모든 Line 은 false 를 가지고 시작합니다. (초기값)
- 다음 lineExists 여부는 prevLineExists 와 관계가 있습니다.
    - stream 은 index 가 존재하지 않고 현재의 element 만 관여할 수 있기에 prevLineExists 를 알 수 없습니다.

2021-08-04 01:15 UTC, Hyune-c commented
>그리고 미션을 진행하다보면 결국 세로줄이 아닌 가로줄로 만들어야 하는데..
이왕 하는 김에 이번 단계에서 해보면 어떨까요?

대공사가 될 줄 알았는데 생각보다 빨리 처리했네요.
결과적으로 코드가 더 간결해진 것 같습니다.

2021-08-04 11:40 UTC, Hyune-c commented on src/main/java/nextstep/ladder/domain/LineExistsGenerator.java
> +}
> 이 클래스에도 FP 를 적용할 수 있을까요?

지금까지 공부했던 전략 패턴에서는 항상 추상 클래스를 사용하는 것만 봤었습니다.
근데 코드를 검수하면서 이 클래스를 다시 보니 Function<Boolean, Boolean> 으로 개선할 수 있을 것같다는 생각이 들었습니다.

만약 그렇게 구현을 바꾼다면, Random 은 어디에 두어야 할까요? Util 로 빼야 될까요?
또는 지금의 상태 그대로 괜찮은 걸까요?

2021-08-04 11:40 UTC, Hyune-c commented on src/main/java/nextstep/ladder/view/InputView.java
> +        (string.isEmpty()) ? "10" : string;
조금 더 개선해 봤습니다.

그런데 이렇게 만들고나니, 그냥 각 input 메소드 안에 로직을 그대로 넣는 것과 다름이 없어보이는데요. 
(익명 클래스 or 그냥 절차지향적으로 구현)

혹시 리뷰어님이라면 이런 `입력 보조 기능` 을 어떻게 구현하실 것 같나요?

2021-08-04 13:29 UTC, JunilHwang approved these changes
안녕하세요 병현님! 피드백 반영 잘 해주셨네요 👍 
이번 단계는 여기서 마무리하겠습니다.
몇 가지 피드백 남겼으니 다음 단계 진행하실 때 참고해주시면 좋을 것 같아요!
질문에 대한 답변도 해당 코멘트에 남겨놨습니다.

2021-08-04 13:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Line.java
> +    private final LineExistsGenerator lineExistsGenerator;
generator를 멤버변수로 가지고 있기 보단 메소드를 실행할 때 주입하여 사용하는 방식은 어떨까요?

2021-08-04 13:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Line.java
> +            exists.add(lineExistsGenerator.generate(exists.get(i - 1)));
지금 보니 lineExistsGenerator 자체가 이 부분 이외에서는 사용되지 않는 것 같아요!

2021-08-04 13:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Line.java
> +    }
여긴 억지로 Stream으로 만들 순 있으나, 지금 처럼 유지하는게 더 효율적일 것 같아요!

2021-08-04 13:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Line.java
> +    }
일단 힌트를 드리자면, reduce를 사용하는 방법이 있답니다.

2021-08-04 13:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/LineExistsGenerator.java
> +}
음.. 저의 경우에는 전략 객체를 항상 interface로 관리했는데 반대네요 ㅎㅎ
Random의 경우 Random이 필요한 전략객체 내부에서 관리해주면 어떨까요?
일단 전신이 되는 기본 Generator에 있는게 무척 부자연스러워보이네요

2021-08-04 13:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/domain/Lines.java
> +        return new Lines(lines);
```suggestion
        return Stream.generate(Line.of(playerCount))
                .limit(height)
                .collect(collectingAndThen(toList(), Lines::new));
```
이렇게 표현할 수 있답니다!

2021-08-04 13:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/view/InputView.java
> +        (string.isEmpty()) ? "10" : string;
음.. 꼭 필요한 경우가 아니라면 그냥 테스트 코드로 대체하는게 적합할 것 같아요 ㅎㅎ
어플리케이션 레이어에 이런 코드가 있는건 사실 적합하지 않아서요

2021-08-04 13:29 UTC, JunilHwang commented on src/main/java/nextstep/ladder/view/InputView.java
> +    }
input을 통해 List를 만들어내기 보단, 
domain에서 `"pobi,honux,crong,jk,hyune"` 이러한 문자열을 받아서 처리할 수 있도록 만들어주면 어떨까요?

이런걸 `다형성` 이라고 한답니다!

2021-08-04 13:34 UTC, merged

2021-08-04 13:54 UTC, Hyune-c commented on src/main/java/nextstep/ladder/domain/LineExistsGenerator.java
> +}
맞습니다.
Random 객체가 모든 Generator 에 있을 필요가 없으니 구현체에 있는게 더 나은 설계 이겠네요.
다음 버전에 개선해보겠습니다.

2021-08-04 13:56 UTC, Hyune-c commented on src/main/java/nextstep/ladder/domain/Lines.java
> +        return new Lines(lines);
for 문을 IntStream 으로 바꿀떄마다 긴가민가 했던 부분인데 더 좋은 방법이 있었군요.

감사합니다!