4단계 - 사다리(리팩토링)
next-step/java-ladder pull request #996
Opened 2021-08-08 17:01 UTC by bingbingpa

안녕하세요. 리뷰어님!
4단계 리뷰 요청드립니다. 

리팩토링이라서 금방 끝날줄 알았는데 피드백 영상이 제가 구현했던것들이랑 다른 부분들이 많아서
결국 지우고 다시 시작을 했습니다.
여러가지로 생각해볼 거리들도 많아서 시간이 조금 오래 걸렸습니다.

2021-08-09 13:50 UTC, jaeyeonling requested changes
사다리 리팩토링을 깔끔하게 잘 해주셨습니다 👍 
소소한 코멘트 남겨두었으니 확인 부탁드릴게요!

2021-08-09 13:50 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/ladder/LadderLine.java
> +    public static LadderLine of(int sizeOfPerson) {
정적 팩토리를 사용하는 경우 생성자의 접근제어자를 private로 해주는 것이 관례인데요
왜 이러한 관례가 생겼는지 고민해보아요

2021-08-09 13:50 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/player/Players.java
> +    public int findByName(String name) {
```suggestion
    public int findPositionByName(String name) {
```

메서드의 기능이 변경되며 네이밍도 같이 변경해주면 좋을 것 같아요 :)

2021-08-09 13:50 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/ladder/Direction.java
> +        return next(generate());
랜덤한 요소가 내부에 존재한다면 해당 메서드의 테스트를 하기 힘들어지는데요!
테스트가 가능한 구조로 만들 수 있는 방법에 대해 고민해보아요 :)

2021-08-09 14:01 UTC, bingbingpa commented on src/main/java/nextstep/ladder/ladder/LadderLine.java
> +    public static LadderLine of(int sizeOfPerson) {
원래는 private 로 했다가 테스트를 위해서 public 으로 열었는데요. 그것보다 테스트를 위한 팩토리 메소드를 하나 더 추가 하는게 좋을까요?

2021-08-09 14:04 UTC, bingbingpa commented on src/main/java/nextstep/ladder/ladder/Direction.java
> +        return next(generate());
피드백 강의를 보고 바꿔보았는데요. production 에서 사용할 public next() 와 테스트를 위한 next(boolean nextCurrent) 가 있어서 테스트에는 무리가 없었던 것 같은데 테스트를 위한 메소드를 제거하는게 좋을까요?

2021-08-09 15:00 UTC, jaeyeonling reviewed
질문의 답변 남겨두었으니 확인 부탁드릴게요~

2021-08-09 15:00 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/ladder/Direction.java
> +        return next(generate());
public next() 와 next(boolean nextCurrent) 를 나눔으로써 Direction의 테스트는 할 수 있지만, public next() 메서드 자체의 테스트는 불가능하다고 보시면 될 것 같습니다 :)

2021-08-09 15:00 UTC, jaeyeonling commented on src/main/java/nextstep/ladder/ladder/LadderLine.java
> +    public static LadderLine of(int sizeOfPerson) {
단순 생성을 담당하는 역할이라면 팩토리 메서드를 추가하는 것이 더욱 좋아보이네요 😄

2021-08-09 15:02 UTC, bingbingpa commented on src/main/java/nextstep/ladder/ladder/Direction.java
> +        return next(generate());
늦은 시간에 답변 해주셔서 감사합니다. 답변 참고해서 수정해보겠습니다!

2021-08-10 12:45 UTC, jaeyeonling approved these changes
마지막까지 미션 잘 진행해주셨습니다 👍 
수 많은 코멘트 반영하시느라 고생 많으셨어요 😄 
해당 요청은 머지하도록 하겠습니다 마지막 미션도 화이팅입니다!!

2021-08-10 12:45 UTC, merged